### ISSUE TITLE
Teamspeak linux plugin

### ISSUE THREAD

**Issue by famfo** [IDI-Systems/acre2#1005]
Recently I switched to Linux and now acre is not working with my teamspeak anymore because the plugin is a dll and not a so. Because I am not able to find the teamspeak in the scource code it would be great if someone could make one.

**Comment by BrettMayson** [comment]
Duplicate of #653

**Comment by TheMagnetar** [comment]
Duplicate. Closing. Besides, the team speak code has nothing to do. The source code of the plugin is in the repository.

**Comment by famfo** [comment]
First of all sorry did't see the first one, second of all where is the code for the teamspeak plugin.

**Comment by jonpas** [comment]
https://github.com/IDI-Systems/acre2/tree/master/extensions/src/ACRE2TS
