### ISSUE TITLE
Radio range to high for all but 343 on default

### ISSUE THREAD

**Issue by StoneLabs** [IDI-Systems/acre2#1006]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373 (stable) (latest)`
- **CBA:** `3.15.1.200418 (latest)`
- **ACRE2:** `2.7.4.1027 (workshop) (latest)`

- [X] Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!

**Description:**
[Reddit thread for reference](https://www.reddit.com/r/arma/comments/i6jmws/acre2_radio_range_too_high_bug_or_working_as/)

> According to https://acre2.idi-systems.com/wiki/user/basic-concepts. The range of the 148 and the 152 should be 5-7 km on ideal conditions. The 77 should be around 3-5 km.
> 
> Now we have the problem that all radios expect the AN/PRC-343 can without any problem transmit from bottom left of Altis to top right. That's about 20 km if I'm not mistaken. (Both ends on sea level, so there are a lot of mountains in between). The signal loss is only about -50dBm (acquired using acre_sys_signal_showSignalHint = true; ACRE_SIGNAL_DEBUGGING = 1;)
> 
> This seems odd to me. Is that a bug? Or is the wiki outdated? Some incorrect usage on our ends maybe? (CBA settings are on default with LOS Multipath and Terrain loss 1.0).

Any help would be greatly appreciated!

**Steps to reproduce:**
1. Spawn 2 players
2. Teleport one to top right corner of altis (sea level)
3. Teleport the other to lower left corner (sea level)
4. Use PRC 148 or 152 and transmit (also tested with 77 and SEM52)
5. Have nice and crisp -50dBm signal

**Expected behavior:**
Far less than -50dBm i'd guess? Need confirmation on this. Expecting no signal (<120?dBm) on that distance.

**Where did the issue occur?**
Multiplayer
Default CBA settings. (Multipath with terrain loss 1.0 as well as Stanley-Rice)

**Log Files:**
-> See comment below.

**Additional context:**
- [X] Tested with different hosts and different players

**Screenshots:**
-> See comment below.

**Comment by jonpas** [comment]
You don't happen to be running Arma 32-bit?

**Comment by StoneLabs** [comment]
I did some more testing. I'm running arma3_64 with just CBA and ACRE2. So 64-bit.

**Screenshot of the situation with signal strength hints:**
![test](https://user-images.githubusercontent.com/19885942/89763165-41da7c80-daf2-11ea-91e7-0f829c216168.png)

**The scenario used with nothing but 2 players and some radio triggers to teleport them around.**
[Radio%20Test.Altis.zip](https://github.com/IDI-Systems/acre2/files/5049682/Radio.20Test.Altis.zip)

**Acre_dll.log file. This one might be a little weird because there was nobody to test with rn. So i just ran two instances of arma and teamspeak. Dont know how this affects the logs. (Issue is confirmed with real mp though; not just 2 instances)**
[acre_dll.log](https://github.com/IDI-Systems/acre2/files/5049697/acre_dll.log)

**Arma .rpt log file from the sender instance. (Right window in screenshot)**
[arma3_x64_2020-08-10_10-05-13.rpt.txt](https://github.com/IDI-Systems/acre2/files/5049704/arma3_x64_2020-08-10_10-05-13.rpt.txt)

**Arma .rpt log file from the receiver instance. (left window in screenshot)**
[Arma3_x64_2020-08-10_09-54-20.rpt.txt](https://github.com/IDI-Systems/acre2/files/5049715/Arma3_x64_2020-08-10_09-54-20.rpt.txt)

If you need any more information, please let me know.

**Comment by StoneLabs** [comment]
Update: The issue does not appear in development build 2.7.4.1032.

**Comment by jonpas** [comment]
Closing as fixed in dev-build.
