### ISSUE TITLE
Move Basic Mission Setup Module to CBA Settings

### ISSUE THREAD

**Issue by EinfachJul** [IDI-Systems/acre2#1012]
**Is your enhancement related to a problem?**
CBA Settings seem to be a more modern approach compared to a module. Also, CBA Settings can easier be scripted than a module.

**Solution you'd like:**
Move the modules settings to a CBA Settings tab

**Comment by Freddo3000** [comment]
I'd think that the basic mission setup acts like sort of a preset for template missions. Having it set in CBA settings might conflict with other scripted approaches to that.

**Comment by jonpas** [comment]
That module is basically a simple preset, if anything we would get rid of it and replace with a simple API call, but that would break backwards compatibility for no real gain.
