### ISSUE TITLE
Loading ACRE breaks ACE's blood volume icon

### ISSUE THREAD

**Issue by aradiel** [IDI-Systems/acre2#1021]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98 Profiling` 
- **CBA:** `3.15.1 stable`
- **ACE3** `3.13.4 stable`
- **ACRE2:** `2.7.4.1027 stable`

**Description:**
Loading ACRE seems to break the new ACE3 medical feedback icon that shows when the player has a low blood level. It's supposed to show up in the upper left corner of the stance indicator after a certain threshold of blood loss, but something in ACRE breaks it.

**Steps to reproduce:**
- Go to into any mission with the icon enabled
- Wound yourself to start bleeding
- Wait until the medical status change into "Lost a lot of blood"

**Expected behavior:**
After the "Lost a loot of blood" threshold, a blood droplet icon should appear in the stance indicator and dynamically adapt to your blood level and bleeding status.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- RPT: [gist](https://gist.github.com/aradiel/664f7b818a76a0b3d183230796588ad6)
- ACRE log: [gist](https://gist.github.com/aradiel/9d07db682703bfdfa5f6a6d6df2279c8)

**Additional context:**
I theorized that perhaps the presence antenna direction indicator was the culprit, but even with no radios it still didn't show up

**Comment by jonpas** [comment]
Cause: https://github.com/IDI-Systems/acre2/blob/baabb7cb43b8be4c6a0fcf171089151710bc4cad/addons/sys_gui/RscInGameUI.hpp#L8-L12
