### ISSUE TITLE
API - `setPTTDelay` wrong use of isEqualType

### ISSUE THREAD

**Issue by ansin11** [IDI-Systems/acre2#1024]
https://github.com/IDI-Systems/acre2/blob/2cc989bf1fd16dd50571d4225c7f87ff751b484f/addons/api/fnc_setPTTDelay.sqf#L22
The function will always exit with false on this line because a number is compared to a String.
Correct use of [isEqualType](https://community.bistudio.com/wiki/isEqualType) would be `if (!( _delay isEqualType 0)) exitWith { false };`.

**Comment by jonpas** [comment]
Nice find. Do you want to open a PR?

**Comment by ansin11** [comment]
I'll leave it to you to push the fix.
