### ISSUE TITLE
API - `setPTTDelay` unreachable statement

### ISSUE THREAD

**Issue by ansin11** [IDI-Systems/acre2#1028]
https://github.com/IDI-Systems/acre2/blob/3309f1a8c5b554d88289d178b540b5cc25368cab/addons/api/fnc_setPTTDelay.sqf#L18-L22
My previous approach (#1024) to an issue with line 22 was too narrow-minded (my apologies) - and we all failed to realize that the statement can never be reached:
- If `_delay` is a number, nothing happens.
- If `_delay` is not a number, [params](https://community.bistudio.com/wiki/params) shows an error message and replaces `_delay` with the specified default value 0 - which is a number - before line 22 is reached.

As such, `_delay isEqualType 0` always returns true in line 22 and the statement is never actually used for anything - line 22 can be omitted entirely.

I'll leave it to someone else to push this.

**Comment by jonpas** [comment]
Fixed by #1033.
