### ISSUE TITLE
Some players cannot communicate with each other after the mission has started

### ISSUE THREAD

**Issue by VulturARG** [IDI-Systems/acre2#1029]
**Mods (complete and add to the following information):**
@ACE - Legacy Medical Module
@ADV - ACE Medical (only for ace³ versions until 3.12.6)
@Anizay
@ArgA
@cba_a3
@cup_terrains_core
@cup_terrains_cwa
@cup_terrains_maps
@Distrikt 41 - Ruegen
@Em_Buildings
@FAA Fuerzas Armadas Argentinas
@Project OPFOR
@rhsafrf
@rhsgref
@rhsusaf
@Vcom AI V3.4.0
@Virolahti - Valtatie 7"
@ACRE2

- **Arma 3: 1.98.146373 [stable]
- **CBA:** `3.15.1.200418` [stable]
- **ACRE2:** `2.7.0.1034` [stable]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

Server settings
C:\armaserver\arma3server_x64.exe "-mod=@ACE - Legacy Medical Module;@ADV - ACE Medical (only for ace³ versions until 3.12.6);@Anizay;@ArgA;@cba_a3;@cup_terrains_core;@cup_terrains_cwa;@cup_terrains_maps;@Distrikt 41 - Ruegen;@Em_Buildings;@FAA Fuerzas Armadas Argentinas;@Project OPFOR;@rhsafrf;@rhsgref;@rhsusaf;@Vcom AI V3.4.0;@Virolahti - Valtatie 7" -noSound -world=empty "\"-cfg=C:\armaserver\basic.cfg\"" "\"-profiles=C:\armaprofiles\VCOM-ACE_Legacy_Medical_Module\"" -port=2302 -serverMod=@extDB3 -filePatching -config=configs\Servidor-Oficial-Clan-ArgA-VCOM-ACE-Legacy-WebPanel-0Headless

**Description:**
During the course of several cooperative missions, some players stop listening to each other or one listens to the other and the other does not listen to the first. Both by radio or by direct communication. Last time with 44 players

**Steps to reproduce:**
Start a mission, play for at least half an hour and problems start to appear.

**Expected behavior:**
Have normal communication between players

**Where did the issue occur?**
- Dedicated Multiplayer Coop.

**Log Files:**
[https://aeroroca.com.ar/varios/ACRE/arma3server_x64_2020-10-01_13-32-52_ACRE.rpt](url)

- The only acre_dll.log that I found in server was from 2020-03-21. The mission was 2020-10-01

ACRE setting are in cba_settings_userconfig.pbo file.
[https://aeroroca.com.ar/varios/ACRE/cba_settings.sqf](url)

**Additional context:**
Using force acre_sys_signal_signalModel = 1; in config alwaws star in LOS Multipath instead LOS Simple

**Screenshots:**
No Screenshots

**Comment by VulturARG** [comment]
nobody? 

(⌣́_⌣̀)

**Comment by TheMagnetar** [comment]
You are probably initializing the  radios incorrectly.  The best point to discuss these issues is our slack (link in the front page of the github). Avoid Vanilla Arsenal or assigning radios with an ID at mission creation.

**Comment by jonpas** [comment]
> Vanilla Arsenal

Should work just fine, we have support/compatibility for it (as well as ACE Arsenal).

**Comment by jonpas** [comment]
You are on ACRE2 `2.7.0.1034`, that version is known to have problems, update to the latest 2.8.0.

**Comment by VulturARG** [comment]
> You are probably initializing the radios incorrectly. The best point to discuss these issues is our slack (link in the front page of the github). Avoid Vanilla Arsenal or assigning radios with an ID at mission creation.

Thanks for your answer. I asked about other problem in slack before write this. Nobody awnser me.

      ¯ \ _(´°°｀)_ / ¯

**Comment by VulturARG** [comment]
> You are on ACRE2 `2.7.0.1034`, that version is known to have problems, update to the latest 2.8.0.

Thanks for answering me. We have already downgraded to the latest version and are testing if we have a recurrence of the problem.
Anyway, looking at the issues, it is seen that the problem that the players do not hear each other after a while is a common problem that has not been solved completely despite the successive version changes.

**Comment by jonpas** [comment]
You downgraded or upgraded? You should be on 2.8.0, sadly all older logs or information is not particularly useful. Upload a mission where we can reproduce that (ideally with just CBA, ACE, ACRE) or at least see your code.

**Comment by VulturARG** [comment]
I upgraded to stable version (from steam) and change to Longley-Rice model. We could not take the risk that the problem continues in our missions. The radio 152 cover all map, but this is "less worse" than we can`t talk between us.
i don't know if the problem persist

**Comment by jonpas** [comment]
We sadly can't help as we currently can't reproduce the issue. If you get across it again, re-open the issue.
