### ISSUE TITLE
Ideas for ACRE

### ISSUE THREAD

**Issue by CubelightCodes** [IDI-Systems/acre2#1032]
Dear ACRE i am very happy with your project, and would like to request some ideas for the future.

- Add Batteries to Radios and a way of loading them maybe, so that the Watt settings really affect something
- SATCOM for 117F and 152, as they work in real life it would be cool to have a working SATCOM mode that works not on LOS but can range way further -> maybe with the option of the mission builder to enable or disable it
- Encryption modes for all Radios -> For now  only the AN/PRC-148 can be encrypted which makes it unfair in PvP Scenarios, it would be great if every Radio could be encrypted
- Russian or Chinese Radios
- Speakers for every Radio (Where they exist in reality)
- Electronic Warfare Systems to deny or weaken communication -> So that SINCGARS and HAVE QUICK have an effect
- Placeable stationary Radios for command posts
- Make signals more noisy especially on further ranges, so that the squelch really has an effect
- Allow to mute yourself in Teamspeak. Not everybody has a hardware mute option, and if something happens in real life at theirs, every player hears it

Would be very cool, if you'd enhance the ACRE Project further, we really prefer it over its concurrence

**Comment by jonpas** [comment]
If we would have infinite time, that would all already be done. :smile: 

Most of the things are big features that we do not see feasible in ACRE2, but maybe in the next iteration of ACRE. I will touch on a few.

> Encryption for all radios

Not all radios we have feature encryption in their real counterparts. If someone adds another feasible one that does, absolutely.

> Speakers for every radio

Yeah, someone just has to do it. Maybe a blocker was that not all radio UIs are fledged out like 148 or 152, but this could also be done through the ACE Interact menu (especially with help of #1038). Open a new issue if you want to see that.

---

What I would pull out from ACRE2 specifically at this point in time (and would urge you to open new issues for):
- Allow to mute yourself in Teamspeak
- Speakers for every Radio (Where they exist in reality)

I will close this large wish list, as we cannot track all of those things here. For relevant things, open new issues (anyone).
