### ISSUE TITLE
Loss of signal when I switch hearing sides for the 152

### ISSUE THREAD

**Issue by ranger604** [IDI-Systems/acre2#1039]
**Mods (complete and add to the following information):**
- **Arma 3: 2.00.146773
- **CBA: 3.15.1
- **ACRE2: 2.8.0
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
When using the AN/PRC-152 if I change hearing sides to left or right I lose all signals and cannot hear any communications. It only workings when hearing from both sides. 
**Steps to reproduce:**
Self interact, try to set hearing side for the AN/PRC-152 left or right, loss of signal.

**Expected behavior:**
Would like to be able to set hearing side.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer /  Virtual Arsenal

**Log Files:**
Start perimeters were set to -nologs

**Additional context:**
none
**Screenshots:**
N/A

**Comment by jonpas** [comment]
> Start perimeters were set to -nologs

Logs are useful, don't use that parameter. It could have very valuable information, which we will need to diagnose it.

However, if it's not an Arma issue it could be your stereo setup issue, make sure all of that is working properly with other applications.

**Comment by ranger604** [comment]
Thanks for the quick response.  I am gonna turn that off now and try to get some logs. I have not issues on any other applications.

**Comment by ranger604** [comment]
[acre_dll.log](https://github.com/IDI-Systems/acre2/files/5533986/acre_dll.log)

**Comment by jonpas** [comment]
Sorry for late reply, we would need the game log as well (.rpt).

And ANY other information you can provide about your audio setup.

**Comment by jonpas** [comment]
No further information to debug. Likely hardware / 3D audio emulation issue.
