### ISSUE TITLE
GS/GSM disconnect issue on dedicated server

### ISSUE THREAD

**Issue by Tirpitz93** [IDI-Systems/acre2#1040]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00` Stable
- **CBA:** `3.15.1` Steam workshop
- **ACRE2:** `2.8.0` Steam workshop
- **ACE:** `3.13.4` Steam workshop
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
Cannot disconnect from GS/GSM when on dedicated server. works fine on local/3DEN.

**Steps to reproduce:**

- Take AN/PRC-77
- move to GSA, connect
- try to disconnect
- no notification for disconnect, unable to connect to same or different antenna

**Expected behavior:**
After disconnecting I would expect to get a notification and be able to connect to other antenna/reconnect

**Where did the issue occur?**
- Dedicated 
- Not apparent on EDEN- singleplayer or EDEN-multiplayer

**Log Files:**
- Server: https://pastebin.com/58Y1M6Q8
- Client: https://pastebin.com/QqxtJEy5
- Acre_Dll: https://pastebin.com/sGv7v8PH

**Additional context:**
Same behavior displayed with TS connected.

**Screenshots:**
https://www.youtube.com/watch?v=svcRs4hzO3Y

**Comment by jonpas** [comment]
I believe I've experienced that myself a few weeks ago.

**Comment by Tirpitz93** [comment]
Could it be something to do with the locality of the execution of disconnect functions?

**Comment by jonpas** [comment]
`EFUNC(sys_radio,getRadioObject)` in [disconnectServer](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_gsa/fnc_disconnectServer.sqf#L40) returns `any` because the [hash `acre_sys_server_objectIdRelationTable`](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_radio/fnc_getRadioObject.sqf#L21) doesn't exist on the server.

**Comment by PabstMirror** [comment]
getRadioObject fix is easy
```
// On a dedicated server objectIdRelationTable will not be available
if (isDedicated) exitWith { 
    if (HASH_HASKEY(EGVAR(sys_server,masterIdTable), _class)) then {
        _ret = (HASH_GET(EGVAR(sys_server,masterIdTable), _class) select 0);
    };
    _ret
};
```
but it also seems like `acre_sys_data_fnc_dataEvent` won't work when called on a dedicated server because `_processQueue` never runs

probably best to just immediately send data instead of running another PFEH for this one case

**Comment by jonpas** [comment]
I was thinking it would just be easier to send the player object from the client, or whoever is getting disconnected. I didn't look deep enough into the automatic disconnect (PFH) code though.

**Comment by PabstMirror** [comment]
If a player disconnects we'll need to be able to detect and then send a data event,
so I think it has to happen on the server

**Comment by jonpas** [comment]
There has to be something that changed this, because it used to work at least on the original release. It could be that we just didn't handle disconnects properly before.

**Comment by PabstMirror** [comment]
As far as I can tell
gsa calls "setData" event happens on server
https://github.com/IDI-Systems/acre2/blob/master/addons/sys_data/fnc_handleSetData.sqf#L86
has always written to `GVAR(eventQueue)`
and that only gets read from
https://github.com/IDI-Systems/acre2/blob/master/addons/sys_data/fnc__processQueue.sqf
which only runs on clients

so calls to `acre_sys_gsa_fnc_getConnectedGsa` would never work, when running on a dedicated server

**Comment by PabstMirror** [comment]
Tested ACRE 2.7.0 on dedicated
Player call to `["ACRE_PRC148_ID_1"] call acre_sys_gsa_fnc_getConnectedGsa = <NULL-object>`
