### ISSUE TITLE
Add civilian/marine band radios

### ISSUE THREAD

**Issue by Tirpitz93** [IDI-Systems/acre2#1041]
**Solution you'd like:**
Add Civilian radios such as ICOM, Baofeng, Standard horizon, Garmin devices. this could include features such as channel scanning/multi channel monitoring, as well as DSC (digital selective calling) & GPS integration.

**Alternatives you've considered:**
Possible alternative would be a secondary mod with these additional model.

**Comment by jonpas** [comment]
Yes, if time would be infinite!

On a serious note, if you have the models and are willing to integrate them, we would definitely be happy to see that. Time of current developers is limited and new radios from our side are less likely as time moves on. ACRE2 radios are not "just models", you need Arma UI, interactions and high quality renders.

I will close this as it is a general asset request.

**Comment by Tirpitz93** [comment]
> On a serious note, if you have the models and are willing to integrate them, we would definitely be happy to see that. Time of current developers is limited and new radios from our side are less likely as time moves on. ACRE2 radios are not "just models", you need Arma UI, interactions and high quality renders.

I would probably be more suited to implementing the DSC GPS or scanning functionality.
