### ISSUE TITLE
Audio sounding 'glitchy' in high speed aircraft, and how to (probably) fix

### ISSUE THREAD

**Issue by dslyecxi** [IDI-Systems/acre2#1042]
I don't have a video to go with this, but I'd imagine most ACRE users are familiar with how e.g. being in a C-130 with other players has weird audio glitching sounds, like the position of the units isn't where they should be. I'm assuming this is still the case in current ACRE2 builds (ST is a version or so behind currently). 

This is likely a subtle issue caused by the difference between the simulation commands (`getPos`, `getDir`, etc, which are roughly a frame ahead) and the visual commands (`getPosVisual`, `getDirVisual`, etc, which are based on where you actually see the object). 

I see that a few visual commands are used in the codebase, but there are a lot of instances where they aren't, and some of them (for instance, `fnc_processDirectSpeaker.sqf`) seem like situations where using `getPosASL` instead of `getPosASLVisual` , for instance, would cause this kind of issue. 

You can visualize this via placing a jet in the editor and running this once you preview the mission: 
```sqf
test_draw3d_ind = addMissionEventHandler ["Draw3D", {
    private _yourVeh = your_named_vehicle; 
    drawIcon3D ["\a3\ui_f\data\gui\cfg\Hints\icon_text\group_1_ca.paa", [1,.3,.3,1], getPos _yourVeh, 1, 1, 0, "Simulation", 1, 0.020,"RobotoCondensed"];
    drawIcon3D ["\a3\ui_f\data\gui\cfg\Hints\icon_text\group_1_ca.paa", [.3,1,.3,1], getPosVisual _yourVeh, 1, 1, 0, "Visual", 1, 0.020,"RobotoCondensed"];

    drawLine3D [(getPosVisual _yourVeh), (getPosVisual _yourVeh) vectorAdd ((vectorDir _yourVeh) vectorMultiply 50), [1,0,0,1]];
    drawLine3D [(getPosVisual _yourVeh), (getPosVisual _yourVeh) vectorAdd ((vectorDirVisual _yourVeh) vectorMultiply 50), [0,1,0,1]];
}];
```

It looks like this in motion: 
https://gyazo.com/50f55d7d1506c254b2fa2b7d920eec5f

Changing the `getPos`/`getDir` commands that handle player speaking to be visual-based instead would likely fix this particular artifact. It's always happening, but you only really notice it when moving at high speeds.

**Comment by Sniperhid** [comment]
Thanks for the report with a good description.

This is something @Soldia1138 and myself have experimented with a bit in the past and it was a few years back so I may be mis remembering. I think what we currently have was best we could do at the time (although it was only a few evenings of experimentation). I believe the crux was that we use `eyePos` command for the local player position, as this provides a useful position for audio. https://github.com/IDI-Systems/acre2/blob/master/addons/sys_core/fnc_updateSelf.sqf#L30

Unfortunately there isn't currently a visual variant of the `eyePos` command. There is a BI ticket request for `eyePosVisual` which would offer the easiest solution to this issue -> https://feedback.bistudio.com/T123362

An alternative might be try to and calculate a visual `eyePos` using other commands if someone wants to dig into that, I don't think I looked too deeply into that. It should then as you say just be a matter of updating all other references to the visual commands.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/addons/core/functions/fnc_defaultPositionCoordinates.sqf#L33

I use this, works fine and gets you head pos. Its probably a bit more expensive than eyePos though, I counter that with transmitting unit velocity too, and doing custom interpolation on plugin side.

**Comment by dslyecxi** [comment]
If `eyePos` is simulation, wouldn't it be possible to `getPosASL` the player, find out the difference between that and `eyePos`, then apply that offset to the `getPosASLVisual` of the player to have essentially an eyePos that's in visual space?

**Comment by dslyecxi** [comment]
I went ahead and did an override of this for ST, changing both `processDirectSpeaker` and `updateSelf` to use visual commands and the method I described in my prior reply. 

In `updateSelf`, this is the relevant change: 
```sqf
ACRE_LISTENER_POS = (getPosASLVisual acre_player) vectorAdd ((eyePos acre_player) vectorDiff (getPosASL acre_player));
```

`processDirectSpeaker` IIRC was just changing to visual variants of commands. 

I haven't extensively tested it in MP yet, but from the usage I have done, it seems to have significantly improved the sound of audio in fast-moving aircraft.

**Comment by jonpas** [comment]
@dslyecxi Would you want to open a PR? Or maybe upload the diff and one of us can put it in under your name? It can be further tested in dev-builds.

**Comment by veteran29** [comment]
Method suggested by dedmen has same performance (bit surprised here as it uses less commands) and is a lot smoother:

https://user-images.githubusercontent.com/4293906/109048980-fd9e7a80-76d7-11eb-8740-e297e4af6c79.mp4

```sqf
onEachFrame {
    drawIcon3D ["\a3\ui_f\data\gui\cfg\Hints\icon_text\group_1_ca.paa", [1,.3,.3,1], 
        ASLToATL ((getPosASLVisual acre_player) vectorAdd ((eyePos acre_player) vectorDiff (getPosASL acre_player))),
        1, 1, 0, "getPosASLVisual", 1, 0.020,"RobotoCondensed"];

    drawIcon3D ["\a3\ui_f\data\gui\cfg\Hints\icon_text\group_1_ca.paa", [.3,1,.3,1],
        ASLToATL (acre_player modelToWorldVisualWorld (acre_player selectionPosition "pilot")),
        1, 1, 0, "modelToWorldVisualWorld", 1, 0.020,"RobotoCondensed"];    
};
```
```sqf
Result:
0.0018 ms
Cycles:
10000/10000
Code:
(getPosASLVisual acre_player) vectorAdd ((eyePos acre_player) vectorDiff (getPosASL acre_player))

Result:
0.0018 ms
Cycles:
10000/10000
Code:
acre_player modelToWorldVisualWorld (acre_player selectionPosition "pilot")
```
Current implementation:
```sqf
Result:
0.0005 ms
Cycles:
10000/10000
Code:
eyePos acre_player
```

**Comment by PabstMirror** [comment]
First 2.02 multiplayer and I noticed this effect was much more noticeable when on the map screen inside of an aircraft.
I will try to investigate this

**Comment by dslyecxi** [comment]
Sorry, missed the previous question (I guess I don't have github notifying me). I was coming back to say that as of 2.02 it seems worse, and the noted fix doesn't seem to completely address it.

**Comment by PabstMirror** [comment]
```
[{
    systemChat format ["Head diff: %1", ((AGLtoASL (player modelToWorldVisual (player selectionPosition "head"))) vectordistance (eyePos player))];
    _otherGuy = if (q1 == player) then { q2 } else { q1 };
    private _emitterPos = AGLtoASL (_otherGuy modelToWorldVisual (_otherGuy selectionPosition "head"));

    private _projectPos = AGLtoASL positionCameraToWorld [0, 0, 0];
    private _playerDir = (AGLtoASL positionCameraToWorld [0, 0, 1]) vectorDiff _projectPos;
    // !!!!! swap these 2:
    // private _playerPos = eyePos acre_player;  // old
    private _playerPos = acre_player modelToWorldVisualWorld (acre_player selectionPosition "head"); // new

    private _angle = acos (_playerDir vectorCos (_playerPos vectorFromTo _emitterPos));
    private _dist = _playerPos vectorDistance _emitterPos;
    systemChat format ["%1 @ %2", _dist, _angle]; 
}, 0.25, []] call CBA_fnc_addPerFrameHandler;
```
`eyePos` is non-visual, so it's very ahead of what the the other "visual" commands are reporting
for pilot at fast helicopter speeds it was ~5 m offset, for a passenger (non-local vehicle) it was even higher
We would be fine using all `getPos` OR all `visual` commands, but can't mix them. (Non-visual might be better because it's a frame ahead, but I doubt it)

I think all that matters is the position/direction offsets, as that will effect the audio
using `acre_player modelToWorldVisualWorld (acre_player selectionPosition "head")` gave a nearly constant offset and angle for the 2nd systemChat, so I think it will be a solid fix
