### ISSUE TITLE
Sharing radio does not show who picked up the radio

### ISSUE THREAD

**Issue by diwako** [IDI-Systems/acre2#1043]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00.146991 performance`
- **CBA:** `3.15.2`
- **ACRE2:** `2.8.0.1037`
- **ACE3:** `3.13.5.57`

**Description:**
When picking up the radio, the variable name of that unit given in 3den will be used, if the unit returns the radio it says following
![image](https://user-images.githubusercontent.com/8259498/100539208-20cea080-3235-11eb-8419-97d763f487b7.png)

Do note that trying it out in singleplayer only yields the return message, testing it in MP with another person will also yield that pick up message.

**Steps to reproduce:**
- Go to 3den
- Place down 2 units and a game master module
- Give yourself a 117
- Preview
- Set your radio to shareable
- Remote control the other unit
- Pick up the shared radio through ace interaction

**Expected behavior:**
Unit name is being displayed when taking the phone and returning it

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Log Files:**
N/A

**Additional context:**
Happened yesterday in a mission of ours, could reproduce in 3den as well. I believe it is a similar issue that DUI has at the moment that was introduced with A3 2.00

**Comment by jonpas** [comment]
https://github.com/IDI-Systems/acre2/blob/c7d11b16ece89252029da41aeda202f24098246f/addons/sys_external/fnc_stopUsingExternalRadio.sqf#L31-L45

Just uses `name`.

**Comment by diwako** [comment]
Same in dui, `name` is used, if `ACE_name` is not available

https://github.com/diwako/diwako_dui/blob/9c9c9ed63e48893f40265574923da4581ea58ff5/addons/radar/functions/fnc_cacheLoop.sqf#L287

**Comment by jonpas** [comment]
I just tried in a live mission on a dedicated server, both parties get the correct messages. No Eden variables set though.

The only way I can get "Error: No vehicle" is when there is no external user currently. There could be a race condition? Since [`stopUsingRadio`](https://github.com/IDI-Systems/acre2/blob/c7d11b16ece89252029da41aeda202f24098246f/addons/sys_external/fnc_stopUsingExternalRadio.sqf#L25) is called before the notifications?

**Comment by jonpas** [comment]
> There could be a race condition? Since [`stopUsingRadio`](https://github.com/IDI-Systems/acre2/blob/c7d11b16ece89252029da41aeda202f24098246f/addons/sys_external/fnc_stopUsingExternalRadio.sqf#L25) is called before the notifications?

`stopUsingRadio` just stops active transmission, there doesn't seem to be any race condition. Looks like pure `name` bug. @diwako did you figure that one out at DUI?

**Comment by diwako** [comment]
I have not checked into this as of late. Need to check that again once i get some time.

**Comment by jonpas** [comment]
Any info on this from DUI @diwako ? I am inclined to close this and blame `name` command.

**Comment by diwako** [comment]
I would say close and blame `name` I have not yet encountered it again.
