### ISSUE TITLE
Spectator - Vehicle attenuated inside

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#1048]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACRE2:** `2.8.0`

**Description:**
1st person spectator (ACE Spectator or EG Spectator) of a unit inside a vehicle will perform attenuation same as being outside the vehicle, it does not take the unit's attenuation into account.

**Steps to reproduce:**
- Spectate unit inside vehicle
- Select 1st person
- Listen to units in vehicle (spectated and others)

**Expected behavior:**
Hear units inside the vehicle clearly.

**Where did the issue occur?**
- Dedicated

**Log Files:**
/

**Additional context:**
Works for certain seats (FFV only it seems), not for most.

**Screenshots:**
/

**Comment by PabstMirror** [comment]
need to look at findOcclusion and getUnitAttenuate
both are using hardcoded `acre_player`

Should be able to then use `cameraOn` to get the spectated vechicle
