### ISSUE TITLE
acre2 not connected to teamspeak

### ISSUE THREAD

**Issue by Camar0n** [IDI-Systems/acre2#1054]
Download it thought the steam workshop and when I load into a game it say  'ACRE not connected to TeamSpeak'. when I googled the issue the only really information I found was to run steam and TS in administrator however this to didn't work, however I did notice that there is not plugin on TS which other members of my unit noticed, however they downloaded ACRE 2 the same way I did and it works for them. Any help is appreciated.
I'm not really tech savvy so I'm unsure what is wrong

**Comment by osfrance** [comment]
Hi, I had the same issue with TS 3.5.6 - acre2 (steam workshoip) 2.8.0.1037 and arma3 (steam) 2.0.0 

Thanks for help !

**Comment by jonpas** [comment]
Sorry for late answer.

Is ACRE2 plug-in/addon activated in TeamSpeak?

**Comment by osfrance** [comment]
Hi, yes Acre2 is activated
![image](https://user-images.githubusercontent.com/11570186/105721483-eaf02480-5f24-11eb-82f8-8ff6824c5288.png)

I try to lauch Arma3_x64 and teamspeak in admin mode, it's the same issue ...

I precise I use my own TS server in 127.0.0.1 for testing (with antiflood point per tick at 15), but i've tested with a public server and I had the same issue too ...

**Comment by jonpas** [comment]
Upload RPT.

**Comment by Camar0n** [comment]
> Sorry for late answer.
> 
> Is ACRE2 plug-in/addon activated in TeamSpeak?

with help from people in my unit, i was able to find out what was wrong but we are unable to fix it
for some reason it refuses to activate on TS no clue why we have tried a lot to fix this but it didnt work

**Comment by jonpas** [comment]
What is wrong then, if you don't mind sharing?

**Comment by osfrance** [comment]
@jonpas thanks for help, this is my rpt : 

[arma3_rpt.zip](https://github.com/IDI-Systems/acre2/files/5867514/arma3_rpt.zip)

In TS, Arma is always disconnected : 

![image](https://user-images.githubusercontent.com/11570186/105725526-5b00a980-5f29-11eb-8c2a-5f220ad8d526.png)

**Comment by jonpas** [comment]
@osfrance Are you joining any server? All I see is loading intro missions. ACRE will only connect to TeamSpeak if you are in a multiplayer session.

**Comment by osfrance** [comment]
@jonpas Oh I see... I've just create a mission for testing if acre/ts work properly on my computer, but not try in MP...
Sorry for the mistake, I try in MP and acre was connected with TS :-)
Many thanks for help !
