### ISSUE TITLE
Documentation - Complete all function headers

### ISSUE THREAD

**Issue by Soldia1138** [IDI-Systems/acre2#107]
We need to complete all the generic function headers. General format should be already in every function. 

Help is definitely appreciated

**ACE_INTERACT**
PR: 
- [ ] ace_interact\fnc_actionSetMTT.sqf
- [ ] ace_interact\fnc_generateConnectorActions.sqf
- [ ] ace_interact\fnc_generateConnectorList.sqf
- [ ] ace_interact\fnc_generateConnectors.sqf
- [x] ace_interact\fnc_generateRxTxChildrenActions.sqf
- [x] ace_interact\fnc_generateSpatialChildrenActions.sqf
- [x] ace_interact\fnc_radioChildrenActions.sqf
- [ ] ace_interact\fnc_radioListChildrenActions.sqf
- [ ] ace_interact\fnc_radioPTTChildrenActions.sqf

**API**
PR: 
- [x] All Functions

**SYS_ATTENUATE**
PR: 
- [x] All Functions

**SYS_COMPONENTS**
PR: 
- [x] All functions

**SYS_CORE**
PR:  #171 
- [x] All functions

**SYS_DATA**
PR: 
- [ ] sys_data\fnc_acreEvent.sqf
- [ ] sys_data\fnc_addHighPriorityId.sqf
- [ ] sys_data\fnc_assignRadioPreset.sqf
- [ ] sys_data\fnc_clearRadioData.sqf
- [ ] sys_data\fnc_clientHandleJipData.sqf
- [ ] sys_data\fnc_closeGui.sqf
- [ ] sys_data\fnc_createEventMsgId.sqf
- [ ] sys_data\fnc_dataEvent.sqf
- [ ] sys_data\fnc_getPlayerRadioList.sqf
- [ ] sys_data\fnc_getPresetData.sqf
- [ ] sys_data\fnc_getRadioPresetName.sqf
- [ ] sys_data\fnc_getRadioState.sqf
- [ ] sys_data\fnc_getRemoteRadioList.sqf
- [ ] sys_data\fnc_getScratchData.sqf
- [ ] sys_data\fnc_guiDataEvent.sqf
- [ ] sys_data\fnc_guiInteractEvent.sqf
- [ ] sys_data\fnc_handleGetData.sqf
- [ ] sys_data\fnc_handleGetRadioState.sqf
- [ ] sys_data\fnc_handleSetChannel.sqf
- [ ] sys_data\fnc_handleSetData.sqf
- [ ] sys_data\fnc_handleSetRadioState.sqf
- [ ] sys_data\fnc_handleSetRadioStateEvent.sqf
- [ ] sys_data\fnc_interactEvent.sqf
- [ ] sys_data\fnc_isRadioInitialized.sqf
- [ ] sys_data\fnc_noApiFunction.sqf
- [ ] sys_data\fnc_noApiSystemFunction.sqf
- [ ] sys_data\fnc_onDataChangeEvent.sqf
- [ ] sys_data\fnc_openGui.sqf
- [ ] sys_data\fnc_physicalEvent.sqf
- [ ] sys_data\fnc_processRadioEvent.sqf
- [ ] sys_data\fnc_processSysEvent.sqf
- [ ] sys_data\fnc_registerRadioPreset.sqf
- [ ] sys_data\fnc_removeHighPriorityId.sqf
- [ ] sys_data\fnc_sendDataEvent.sqf
- [ ] sys_data\fnc_serverHandleJip.sqf
- [ ] sys_data\fnc_serverPropDataEvent.sqf
- [ ] sys_data\fnc_setScratchData.sqf
- [ ] sys_data\fnc_sortRadioList.sqf
- [ ] sys_data\fnc_stateEvent.sqf
- [ ] sys_data\fnc_syncData.sqf
- [ ] sys_data\fnc_transEvent.sqf
- [ ] sys_data\fnc__processQueue.sqf

**SYS_EXTERNAL**
PR: 
- [x] All functions.

**SYS_GUI**
PR: 
- [ ] sys_gui\fnc_closeInventory.sqf
- [ ] sys_gui\fnc_closeVolumeControl.sqf
- [ ] sys_gui\fnc_handleContextMenu.sqf
- [x] sys_gui\fnc_handleTake.sqf
- [ ] sys_gui\fnc_inventoryListMouseDown.sqf
- [ ] sys_gui\fnc_inventoryListMouseUp.sqf
- [x] sys_gui\fnc_inventoryMonitorPFH.sqf
- [x] sys_gui\fnc_onInventoryAction.sqf
- [ ] sys_gui\fnc_onInventoryRadioDoubleClick.sqf
- [ ] sys_gui\fnc_onInventoryRadioSelected.sqf
- [ ] sys_gui\fnc_onVolumeControlAdjust.sqf
- [ ] sys_gui\fnc_onVolumeControlKeyPress.sqf
- [ ] sys_gui\fnc_onVolumeControlKeyPressUp.sqf
- [ ] sys_gui\fnc_onVolumeControlSliderChanged.sqf
- [x] sys_gui\fnc_openInventory.sqf
- [ ] sys_gui\fnc_openVolumeControl.sqf
- [ ] sys_gui\fnc_setVolumeSliderColor.sqf
- [x] sys_gui\fnc_uniqueArray.sqf
- [x] sys_gui\fnc_updateVehicleInfo.sqf

**SYS_INTERCOM**
PR: 
- [x] All functions.

**SYS_IO**
PR: 
- [ ] sys_io\fnc_ping.sqf
- [ ] sys_io\fnc_restartServer.sqf
- [ ] sys_io\fnc_sendMessage.sqf
- [ ] sys_io\fnc_server.sqf
- [ ] sys_io\fnc_serverReadLoop.sqf
- [ ] sys_io\fnc_serverRunning.sqf
- [ ] sys_io\fnc_startServer.sqf
- [ ] sys_io\fnc_stopServer.sqf

**SYS_LIST**
PR: 
- [ ] sys_list\fnc_cycleRadios.sqf
- [ ] sys_list\fnc_displayHint.sqf
- [ ] sys_list\fnc__showHintBox.sqf

**SYS_MODES**
PR: #108 
PR: #199 
- [x] All Functions

**SYS_PRC117F**
PR: 
- [ ] sys_prc117f\fnc_closeGui.sqf
- [ ] sys_prc117f\fnc_formatChannelValue.sqf
- [ ] sys_prc117f\fnc_initializeRadio.sqf
- [ ] sys_prc117f\fnc_openGui.sqf
- [ ] sys_prc117f\fnc_preset_information.sqf
- [ ] sys_prc117f\fnc_render.sqf
- [ ] sys_prc117f\farris_menus\Loading.sqf
- [ ] sys_prc117f\farris_menus\Main.sqf
- [ ] sys_prc117f\farris_menus\MODE.sqf
- [ ] sys_prc117f\farris_menus\OPT.sqf
- [ ] sys_prc117f\farris_menus\PGM.sqf
- [ ] sys_prc117f\farris_menus\SQ.sqf
- [ ] sys_prc117f\menus\fnc_callButtonFunctor.sqf
- [ ] sys_prc117f\menus\fnc_callCompleteFunctor.sqf
- [ ] sys_prc117f\menus\fnc_callEntryFunctor.sqf
- [ ] sys_prc117f\menus\fnc_callRenderFunctor.sqf
- [ ] sys_prc117f\menus\fnc_callSingleActionCompleteFunctor.sqf
- [ ] sys_prc117f\menus\fnc_changeMenu.sqf
- [ ] sys_prc117f\menus\fnc_changeMode.sqf
- [ ] sys_prc117f\menus\fnc_changeValueAck.sqf
- [ ] sys_prc117f\menus\fnc_clearDisplay.sqf
- [ ] sys_prc117f\menus\fnc_createMenu.sqf
- [ ] sys_prc117f\menus\fnc_defaultButtonPress.sqf
- [ ] sys_prc117f\menus\fnc_delayFunction.sqf
- [ ] sys_prc117f\menus\fnc_drawCursor.sqf
- [ ] sys_prc117f\menus\fnc_dynamicCall.sqf
- [ ] sys_prc117f\menus\fnc_formatText.sqf
- [ ] sys_prc117f\menus\fnc_onButtonPress.sqf
- [ ] sys_prc117f\menus\fnc_renderMenu.sqf
- [ ] sys_prc117f\menus\fnc_renderText.sqf
- [ ] sys_prc117f\menus\fnc_setRowText.sqf
- [ ] sys_prc117f\menus\fnc_timerFunction.sqf
- [ ] sys_prc117f\menus\fnc_toggleButtonPressDown.sqf
- [ ] sys_prc117f\menus\fnc_toggleButtonPressUp.sqf
- [ ] sys_prc117f\menus\fnc_toggleIcon.sqf
- [ ] sys_prc117f\menus\types\ActionSeries.sqf
- [ ] sys_prc117f\menus\types\Alphanumeric.sqf
- [ ] sys_prc117f\menus\types\ChangeValueAck.sqf
- [ ] sys_prc117f\menus\types\Display.sqf
- [ ] sys_prc117f\menus\types\Frequency.sqf
- [ ] sys_prc117f\menus\types\List.sqf
- [ ] sys_prc117f\menus\types\Loading.sqf
- [ ] sys_prc117f\menus\types\Number.sqf
- [ ] sys_prc117f\menus\types\Selection.sqf
- [ ] sys_prc117f\menus\types\Static.sqf
- [ ] sys_prc117f\radio\fnc_getChannelData.sqf
- [ ] sys_prc117f\radio\fnc_getChannelDataInternal.sqf
- [ ] sys_prc117f\radio\fnc_getChannelDescription.sqf
- [ ] sys_prc117f\radio\fnc_getCurrentChannel.sqf
- [ ] sys_prc117f\radio\fnc_getCurrentChannelData.sqf
- [ ] sys_prc117f\radio\fnc_getDefaultState.sqf
- [ ] sys_prc117f\radio\fnc_getExternalAudioPosition.sqf
- [ ] sys_prc117f\radio\fnc_getListInfo.sqf
- [ ] sys_prc117f\radio\fnc_getOnOffState.sqf
- [ ] sys_prc117f\radio\fnc_getSpatial.sqf
- [ ] sys_prc117f\radio\fnc_getState.sqf
- [ ] sys_prc117f\radio\fnc_getStates.sqf
- [ ] sys_prc117f\radio\fnc_getVolume.sqf
- [ ] sys_prc117f\radio\fnc_handleBeginTransmission.sqf
- [ ] sys_prc117f\radio\fnc_handleEndTransmission.sqf
- [ ] sys_prc117f\radio\fnc_handleMultipleTransmissions.sqf
- [ ] sys_prc117f\radio\fnc_handlePTTDown.sqf
- [ ] sys_prc117f\radio\fnc_handlePTTUp.sqf
- [ ] sys_prc117f\radio\fnc_handleSignalData.sqf
- [ ] sys_prc117f\radio\fnc_isExternalAudio.sqf
- [ ] sys_prc117f\radio\fnc_setChannelData.sqf
- [ ] sys_prc117f\radio\fnc_setChannelDataOperational.sqf
- [ ] sys_prc117f\radio\fnc_setCurrentChannel.sqf
- [ ] sys_prc117f\radio\fnc_setOnOffState.sqf
- [ ] sys_prc117f\radio\fnc_setSpatial.sqf
- [ ] sys_prc117f\radio\fnc_setState.sqf
- [ ] sys_prc117f\radio\fnc_setVolume.sqf

**SYS_PRC148**
PR: 
- [ ] sys_prc148\fnc_closeGui.sqf
- [ ] sys_prc148\fnc_initializeRadio.sqf
- [ ] sys_prc148\fnc_openGui.sqf
- [ ] sys_prc148\fnc_preset_information.sqf
- [ ] sys_prc148\fnc_render.sqf
- [ ] sys_prc148\menus\fnc_addAnimation.sqf
- [ ] sys_prc148\menus\fnc_changeState.sqf
- [ ] sys_prc148\menus\fnc_defaultButtonHandler.sqf
- [ ] sys_prc148\menus\fnc_delayFunction.sqf
- [ ] sys_prc148\menus\fnc_displayLine.sqf
- [ ] sys_prc148\menus\fnc_frequencyToString.sqf
- [ ] sys_prc148\menus\fnc_handleEscButton.sqf
- [ ] sys_prc148\menus\fnc_handleMenuButtonEnter.sqf
- [ ] sys_prc148\menus\fnc_handleMenuDirButton.sqf
- [ ] sys_prc148\menus\fnc_handleModeButton.sqf
- [ ] sys_prc148\menus\fnc_highlightText.sqf
- [ ] sys_prc148\menus\fnc_menuMoveCursor.sqf
- [ ] sys_prc148\menus\fnc_onButtonPress.sqf
- [ ] sys_prc148\menus\fnc_onChannelKnobPress.sqf
- [ ] sys_prc148\menus\fnc_onVolumeKnobPress.sqf
- [ ] sys_prc148\menus\fnc_PFH.sqf
- [ ] sys_prc148\menus\fnc_removeAnimation.sqf
- [ ] sys_prc148\menus\fnc_setCursor.sqf
- [ ] sys_prc148\menus\fnc_setText.sqf
- [ ] sys_prc148\menus\fnc_showIcon.sqf
- [ ] sys_prc148\menus\fnc_showMenu.sqf
- [ ] sys_prc148\menus\fnc_startFlashText.sqf
- [ ] sys_prc148\menus\fnc_stringToFrequency.sqf
- [ ] sys_prc148\menus\fnc_toggleButtonPressDown.sqf
- [ ] sys_prc148\menus\fnc_toggleButtonPressUp.sqf
- [ ] sys_prc148\menus\fnc_updateChannelData.sqf
- [ ] sys_prc148\menus\fnc_updateMode.sqf
- [ ] sys_prc148\radio\fnc_getChannelData.sqf
- [ ] sys_prc148\radio\fnc_getChannelDataInternal.sqf
- [ ] sys_prc148\radio\fnc_getChannelDescription.sqf
- [ ] sys_prc148\radio\fnc_getCurrentChannel.sqf
- [ ] sys_prc148\radio\fnc_getCurrentChannelData.sqf
- [ ] sys_prc148\radio\fnc_getDefaultState.sqf
- [ ] sys_prc148\radio\fnc_getExternalAudioPosition.sqf
- [ ] sys_prc148\radio\fnc_getListInfo.sqf
- [ ] sys_prc148\radio\fnc_getOnOffState.sqf
- [ ] sys_prc148\radio\fnc_getSpatial.sqf
- [ ] sys_prc148\radio\fnc_getState.sqf
- [ ] sys_prc148\radio\fnc_getStates.sqf
- [ ] sys_prc148\radio\fnc_getVolume.sqf
- [ ] sys_prc148\radio\fnc_handleBeginTransmission.sqf
- [ ] sys_prc148\radio\fnc_handleEndTransmission.sqf
- [ ] sys_prc148\radio\fnc_handleMultipleTransmissions.sqf
- [ ] sys_prc148\radio\fnc_handlePTTDown.sqf
- [ ] sys_prc148\radio\fnc_handlePTTUp.sqf
- [ ] sys_prc148\radio\fnc_handleSignalData.sqf
- [ ] sys_prc148\radio\fnc_isExternalAudio.sqf
- [ ] sys_prc148\radio\fnc_setChannelData.sqf
- [ ] sys_prc148\radio\fnc_setCurrentChannel.sqf
- [ ] sys_prc148\radio\fnc_setOnOffState.sqf
- [ ] sys_prc148\radio\fnc_setSpatial.sqf
- [ ] sys_prc148\radio\fnc_setState.sqf
- [ ] sys_prc148\radio\fnc_setVolume.sqf
- [ ] sys_prc148\states\AccessDenied.sqf
- [ ] sys_prc148\states\ChannelDisplays.sqf
- [ ] sys_prc148\states\Group.sqf
- [ ] sys_prc148\states\MainDisplays.sqf
- [ ] sys_prc148\states\ModeDisplays.sqf
- [ ] sys_prc148\states\OffDisplay.sqf
- [ ] sys_prc148\states\ProgramDisplays.sqf
- [ ] sys_prc148\states\ProgrammingDisplays.sqf
- [ ] sys_prc148\states\StartUp.sqf

**SYS_PRC152**
PR: 
- [ ] sys_prc152\fnc_closeGui.sqf
- [ ] sys_prc152\fnc_formatChannelValue.sqf
- [ ] sys_prc152\fnc_initializeRadio.sqf
- [ ] sys_prc152\fnc_openGui.sqf
- [ ] sys_prc152\fnc_preset_information.sqf
- [ ] sys_prc152\fnc_render.sqf
- [ ] sys_prc152\farris_menus\Loading.sqf
- [ ] sys_prc152\farris_menus\Main.sqf
- [ ] sys_prc152\farris_menus\OPT.sqf
- [ ] sys_prc152\farris_menus\PGM.sqf
- [ ] sys_prc152\menus\fnc_callButtonFunctor.sqf
- [ ] sys_prc152\menus\fnc_callCompleteFunctor.sqf
- [ ] sys_prc152\menus\fnc_callEntryFunctor.sqf
- [ ] sys_prc152\menus\fnc_callRenderFunctor.sqf
- [ ] sys_prc152\menus\fnc_callSingleActionCompleteFunctor.sqf
- [ ] sys_prc152\menus\fnc_changeMenu.sqf
- [ ] sys_prc152\menus\fnc_changeMode.sqf
- [ ] sys_prc152\menus\fnc_changeValueAck.sqf
- [ ] sys_prc152\menus\fnc_clearDisplay.sqf
- [ ] sys_prc152\menus\fnc_createMenu.sqf
- [ ] sys_prc152\menus\fnc_defaultButtonPress.sqf
- [ ] sys_prc152\menus\fnc_delayFunction.sqf
- [ ] sys_prc152\menus\fnc_drawCursor.sqf
- [ ] sys_prc152\menus\fnc_dynamicCall.sqf
- [ ] sys_prc152\menus\fnc_formatText.sqf
- [ ] sys_prc152\menus\fnc_onButtonPress.sqf
- [ ] sys_prc152\menus\fnc_renderMenu.sqf
- [ ] sys_prc152\menus\fnc_renderText.sqf
- [ ] sys_prc152\menus\fnc_setRowText.sqf
- [ ] sys_prc152\menus\fnc_timerFunction.sqf
- [ ] sys_prc152\menus\fnc_toggleButtonPressDown.sqf
- [ ] sys_prc152\menus\fnc_toggleButtonPressUp.sqf
- [ ] sys_prc152\menus\fnc_toggleIcon.sqf
- [ ] sys_prc152\menus\fnc_verifyIsMenu.sqf
- [ ] sys_prc152\menus\types\ActionSeries.sqf
- [ ] sys_prc152\menus\types\Alphanumeric.sqf
- [ ] sys_prc152\menus\types\ChangeValueAck.sqf
- [ ] sys_prc152\menus\types\Display.sqf
- [ ] sys_prc152\menus\types\Frequency.sqf
- [ ] sys_prc152\menus\types\List.sqf
- [ ] sys_prc152\menus\types\Loading.sqf
- [ ] sys_prc152\menus\types\Number.sqf
- [ ] sys_prc152\menus\types\Selection.sqf
- [ ] sys_prc152\menus\types\Static.sqf
- [ ] sys_prc152\radio\fnc_getChannelData.sqf
- [ ] sys_prc152\radio\fnc_getChannelDataInternal.sqf
- [ ] sys_prc152\radio\fnc_getChannelDescription.sqf
- [ ] sys_prc152\radio\fnc_getCurrentChannel.sqf
- [ ] sys_prc152\radio\fnc_getCurrentChannelData.sqf
- [ ] sys_prc152\radio\fnc_getDefaultState.sqf
- [ ] sys_prc152\radio\fnc_getExternalAudioPosition.sqf
- [ ] sys_prc152\radio\fnc_getListInfo.sqf
- [ ] sys_prc152\radio\fnc_getOnOffState.sqf
- [ ] sys_prc152\radio\fnc_getSpatial.sqf
- [ ] sys_prc152\radio\fnc_getState.sqf
- [ ] sys_prc152\radio\fnc_getStates.sqf
- [ ] sys_prc152\radio\fnc_getVolume.sqf
- [ ] sys_prc152\radio\fnc_handleBeginTransmission.sqf
- [ ] sys_prc152\radio\fnc_handleEndTransmission.sqf
- [ ] sys_prc152\radio\fnc_handleMultipleTransmissions.sqf
- [ ] sys_prc152\radio\fnc_handlePTTDown.sqf
- [ ] sys_prc152\radio\fnc_handlePTTUp.sqf
- [ ] sys_prc152\radio\fnc_handleSignalData.sqf
- [ ] sys_prc152\radio\fnc_isExternalAudio.sqf
- [ ] sys_prc152\radio\fnc_setChannelData.sqf
- [ ] sys_prc152\radio\fnc_setChannelDataOperational.sqf
- [ ] sys_prc152\radio\fnc_setCurrentChannel.sqf
- [ ] sys_prc152\radio\fnc_setOnOffState.sqf
- [ ] sys_prc152\radio\fnc_setSpatial.sqf
- [ ] sys_prc152\radio\fnc_setState.sqf
- [ ] sys_prc152\radio\fnc_setVolume.sqf

**SYS_PRC343**
PR: #110 
- [x] All functions

**SYS_PRC77**
PR: #109 
- [x] All functions

**SYS_RACK**
PR: 
- [x] All functions.

**SYS_RADIO**
PR: #589
- [x] All functions.

**SYS_RPC**
PR: 
- [x] All functions

**SYS_SEM52SL**
PR: 
- [ ] sys_sem52sl\functions\fnc_onAudioSocketPress.sqf
- [ ] sys_sem52sl\functions\fnc_onChannelKnobPress.sqf
- [ ] sys_sem52sl\functions\fnc_onPTTButtonPress.sqf
- [ ] sys_sem52sl\functions\fnc_onVolumeKnobPress.sqf
- [ ] sys_sem52sl\functions\fnc_presetInformation.sqf
- [ ] sys_sem52sl\functions\fnc_render.sqf
- [ ] sys_sem52sl\functions\fnc_renderDisplay.sqf
- [ ] sys_sem52sl\radio\fnc_closeGui.sqf
- [ ] sys_sem52sl\radio\fnc_getChannelData.sqf
- [ ] sys_sem52sl\radio\fnc_getChannelDescription.sqf
- [ ] sys_sem52sl\radio\fnc_getCurrentChannel.sqf
- [ ] sys_sem52sl\radio\fnc_getCurrentChannelData.sqf
- [ ] sys_sem52sl\radio\fnc_getExternalAudioPosition.sqf
- [ ] sys_sem52sl\radio\fnc_getListInfo.sqf
- [ ] sys_sem52sl\radio\fnc_getOnOffState.sqf
- [ ] sys_sem52sl\radio\fnc_getSpatial.sqf
- [ ] sys_sem52sl\radio\fnc_getState.sqf
- [ ] sys_sem52sl\radio\fnc_getStates.sqf
- [ ] sys_sem52sl\radio\fnc_getVolume.sqf
- [ ] sys_sem52sl\radio\fnc_handleBeginTransmission.sqf
- [ ] sys_sem52sl\radio\fnc_handleEndTransmission.sqf
- [ ] sys_sem52sl\radio\fnc_handleMultipleTransmissions.sqf
- [ ] sys_sem52sl\radio\fnc_handlePTTDown.sqf
- [ ] sys_sem52sl\radio\fnc_handlePTTUp.sqf
- [ ] sys_sem52sl\radio\fnc_handleSignalData.sqf
- [ ] sys_sem52sl\radio\fnc_initializeRadio.sqf
- [ ] sys_sem52sl\radio\fnc_isExternalAudio.sqf
- [ ] sys_sem52sl\radio\fnc_openGui.sqf
- [ ] sys_sem52sl\radio\fnc_setChannelData.sqf
- [ ] sys_sem52sl\radio\fnc_setCurrentChannel.sqf
- [ ] sys_sem52sl\radio\fnc_setOnOffState.sqf
- [ ] sys_sem52sl\radio\fnc_setSpatial.sqf
- [ ] sys_sem52sl\radio\fnc_setState.sqf
- [ ] sys_sem52sl\radio\fnc_setVolume.sqf

**SYS_SEM70**
PR: 
- [ ] sys_sem70\functions\fnc_clearDisplay.sqf
- [ ] sys_sem70\functions\fnc_onChannelStepKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onDisplayButtonPress.sqf
- [ ] sys_sem70\functions\fnc_onFunctionKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onkHzKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onMainKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onMemorySlotKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onMHzKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onNetworkKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_onVolumeKnobTurn.sqf
- [ ] sys_sem70\functions\fnc_presetInformation.sqf
- [ ] sys_sem70\functions\fnc_render.sqf
- [ ] sys_sem70\functions\fnc_renderDisplay.sqf
- [ ] sys_sem70\functions\fnc_setNetworkID.sqf
- [ ] sys_sem70\radio\fnc_closeGui.sqf
- [ ] sys_sem70\radio\fnc_getChannelData.sqf
- [ ] sys_sem70\radio\fnc_getChannelDescription.sqf
- [ ] sys_sem70\radio\fnc_getCurrentChannel.sqf
- [ ] sys_sem70\radio\fnc_getCurrentChannelData.sqf
- [ ] sys_sem70\radio\fnc_getExternalAudioPosition.sqf
- [ ] sys_sem70\radio\fnc_getListInfo.sqf
- [ ] sys_sem70\radio\fnc_getOnOffState.sqf
- [ ] sys_sem70\radio\fnc_getSpatial.sqf
- [ ] sys_sem70\radio\fnc_getState.sqf
- [ ] sys_sem70\radio\fnc_getStates.sqf
- [ ] sys_sem70\radio\fnc_getVolume.sqf
- [ ] sys_sem70\radio\fnc_handleBeginTransmission.sqf
- [ ] sys_sem70\radio\fnc_handleEndTransmission.sqf
- [ ] sys_sem70\radio\fnc_handleMultipleTransmissions.sqf
- [ ] sys_sem70\radio\fnc_handlePTTDown.sqf
- [ ] sys_sem70\radio\fnc_handlePTTUp.sqf
- [ ] sys_sem70\radio\fnc_handleSignalData.sqf
- [ ] sys_sem70\radio\fnc_initializeRadio.sqf
- [ ] sys_sem70\radio\fnc_isExternalAudio.sqf
- [ ] sys_sem70\radio\fnc_openGui.sqf
- [ ] sys_sem70\radio\fnc_setChannelData.sqf
- [ ] sys_sem70\radio\fnc_setCurrentChannel.sqf
- [ ] sys_sem70\radio\fnc_setOnOffState.sqf
- [ ] sys_sem70\radio\fnc_setSpatial.sqf
- [ ] sys_sem70\radio\fnc_setState.sqf
- [ ] sys_sem70\radio\fnc_setVolume.sqf

**SYS_SERVER**
PR: 
- [ ] sys_server\fnc_acknowledgeId.sqf
- [ ] sys_server\fnc_checkServerGearDesync.sqf
- [ ] sys_server\fnc_clientGCRadio.sqf
- [ ] sys_server\fnc_cloneRadioData.sqf
- [ ] sys_server\fnc_collect.sqf
- [ ] sys_server\fnc_getRadioId.sqf
- [ ] sys_server\fnc_invalidGarbageCollect.sqf
- [ ] sys_server\fnc_masterIdTracker.sqf
- [ ] sys_server\fnc_onGetRadioId.sqf
- [ ] sys_server\fnc_remoteDebugMsg.sqf
- [ ] sys_server\fnc_setSpectator.sqf
- [ ] sys_server\fnc_updateIdObjects.sqf

**SYS_SIGNAL**
PR: #111 
- [x] All functions

**SYS_SOUNDS**
PR: 
- [x] All functions

**Comment by TheMagnetar** [comment]
I can take care of this. For the moment I will add only the generic header. Another pass would be required in order to document arguments, return values and purpose of the function.

**Comment by Sniperhid** [comment]
As part of the vehicleracks branch/PR I have done this for all of sys_components (as well as fixing various aspects of sys_components) - So ignore that one for now.

Due to the number of files involved it may be best to do this in parts with various pull requests.

**Comment by Soldia1138** [comment]
Cool. We all should participate. I at least try to do the header of a function whenever I come across.

**Comment by Soldia1138** [comment]
@Sniperhid: You are right. I will change my PR. Should do it component wise.

**Comment by jonpas** [comment]
Yep, component wise sounds good. 👍

**Comment by TheMagnetar** [comment]
For the aforementioned functions I am already changing the function name in the example call.

**Edit**: I have all of them renamed except for sys_data

**Comment by Soldia1138** [comment]
So we should merge your PR prior changing anything on those components.

However, will update list whenever a PR is merged. For better overview I added sections on first comment an links to PRs

**Comment by jonpas** [comment]
@TheMagnetar For examples, let's do them without semi-colon at the end, like @Soldia1138 does. I'll add that to the docs page later today.

**Comment by TheMagnetar** [comment]
@jonpas I will modify them.

**Comment by TheMagnetar** [comment]
Updated issue description.

**Comment by TheMagnetar** [comment]
Updated issue description.

**Comment by TheMagnetar** [comment]
Sys_radio component documentation in #589

**Comment by jonpas** [comment]
Realistically, this is not getting finished for ACRE2 at this point anymore.
