### ISSUE TITLE
ACRE a game master

### ISSUE THREAD

**Issue by MJVEVERUSKA** [IDI-Systems/acre2#1075]
I want to report a problem in the editor if I give the zeuse module an error pops up. I only used CBA and ACRE everything worked and when I added the game master. Error. The same on a test server without the game master, but with the setting as a reporter using Zeus again an error. Probably incompatibility with the new ARMA 3 Version: 2.02.

I'm attaching a jpg 
![Výstřižek](https://user-images.githubusercontent.com/65508396/111068948-12964e80-84cb-11eb-8ac4-9fdcb572ebb2.PNG)

**Comment by jonpas** [comment]
As you can see in the error: `task_force_radio_items`, what does this have to do with ACRE? :)

Your mission probably contains references to TFAR.

**Comment by MJVEVERUSKA** [comment]
I created a mission only with cba and acre without the Lord of the Games module and through logging in as a server administrator I connected like zeus vanila and an error popped up.

**Comment by MJVEVERUSKA** [comment]
And when I put the Lord of the Games module in the editor, the error pops up too

**Comment by MJVEVERUSKA** [comment]
So I'm sorry. I fixed it by deleting the arma3.cfg folder from me because I found out that the TFAR was embedded there and is fixed. Everything works as it should. I apologize again.

**Comment by Soldia1138** [comment]
No Problem, glad you could solve your issue.
