### ISSUE TITLE
ACRE Stuttering

### ISSUE THREAD

**Issue by Lao22** [IDI-Systems/acre2#1078]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.x.x` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
When we are in our server sometimes ACRE will cause different players to "Stutter" in direct communication, even though they are clear and fine on the 343, it also seems that they will "stutter" only for certain people while others can hear them fine,  I have tried to recreate the issue. but as the *stutter* doesn't effect me, i cannot. i am now attempting to figure out the difference between me and the people with the issue.

**Expected behaviour:**
Clear direct communication without stutter

**Where did the issue occur?**
- Dedicated

**Comment by jokoho48** [comment]
maybe related to #1042 ?

**Comment by Lao22** [comment]
> maybe related to #1042 ?

i don't think so, communication on the radios is clear and fine, even for the person that is stuttering on direct speech, we can hear them fine on the radio, but in direct speech it's all stuttery and it's not always the same person and some missions we go entire op no issues, then next op 3 or 4 people have issues, to then the next op only 1.

**Comment by jonpas** [comment]
We would need you to fill out the issue template fully, all versions of mods and some log files.

Seeing your TeamSpeak configuration could also help.

**Comment by jonpas** [comment]
No further information provided.
