### ISSUE TITLE
ACRE2 don't switch on TS3 (maybe server-side)

### ISSUE THREAD

**Issue by PolTville** [IDI-Systems/acre2#1081]
**Mods:**
- **Arma 3:** `2.02.174359 STABLE`
- **CBA:** `3.15.3.210310 STABLE`
- **ACRE2:** `2.8.0.1037 STABLE`

**Description:**
ACRE doesn't work when player join the server, the missions start correctly but ACRE2 don't switch or work. But TS3 say "Arma 3 Connected: yes" at all my players.
I tried with differents TS servers, i think problem come server-side, cause i've another A3 server (not on the same dedicated) where ACRE work.

**Expected behavior:**
I start my server, i start my game, i start my ts3 and i join my A3 et TS3 servers. And I'm switched on a channel and i can speak with my mates.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- Server RPT: https://pastebin.com/kLv2p3QK

**Comment by PolTville** [comment]
Vocal works, not the channel switch.

**Comment by jonpas** [comment]
Are you talking about channel switching only? Direct voice and radios work?

Could be your channel names, best if you give us a screenshot of the channels setup. Also make sure you are using the correct password if the channel has one.

**Comment by PolTville** [comment]
I talk about Switching only finally. Direct voice, 3D spatialization, differents level volume and radios work. I tried today.

![1](https://media.discordapp.net/attachments/756567768874090636/828347636314537994/unknown.png)
![2](https://cdn.discordapp.com/attachments/756567768874090636/828348009955065887/unknown.png)
![3](https://cdn.discordapp.com/attachments/756567768874090636/828348068650287135/unknown.png)
![4](https://cdn.discordapp.com/attachments/756567768874090636/828348289467809832/unknown.png)

Sorry my french.

**Comment by jonpas** [comment]
No problem, I understand you.

Does your other server (one that works) have different channel name?

**Comment by PolTville** [comment]
The other server have the same channel. Note: I'm on servers' transition.

I tried with a new channel (named ACRE2, pass 1234), even a new TS3 server and nothing, no switch.

**Comment by PolTville** [comment]
Do you need others informations ? 

Do you have an idea ?

**Comment by jonpas** [comment]
Not at this moment, no.

**Comment by jokoho48** [comment]
@AsimoPaul check that in Advanced the Max Users and Family Max Users is set not Limited (sometimes Inherited is also broken because if the parent is set to Limited it also does not allow entry).

**Comment by PolTville** [comment]
I checked and no limit or something like

**Comment by BifeO** [comment]
We have the same problem in our server (1º BITI). Interesting that we have a separate test server and it doesn't occur on that. The first uses FAST2 (I think) and the second uses FASTER to run it, but that's the only difference that I know of.
But, on both we can't get "Unmute player" work unticked. On any instance, briefing or playing, the module doesn't change. Is that a known issue?

**Comment by saviorsoldier** [comment]
I have the same problem. While I'm testing on my local server it's working but while I'm using my virtual dedicated server it's not switching my channel. All the settings same as @AsimoPaul

**Comment by jonpas** [comment]
This must have something to do with permissions. Maybe moving is restricted enough that even plugin is unable to do it?

**Comment by BifeO** [comment]
Not at all. Two different Arma servers with the same settings have different behaviors over the same TS3 server. I'll look more into it.

**Comment by jonpas** [comment]
@BifeO Are the server names the same? I assume not, so one of them probably correctly finds the TS server, the other doesn't find a matching name.

Regarding "Unmute players", that probably just doesn't do what you think it does. It's just a preventative measure to unmute people when you disable/leave ACRE.

**Comment by BifeO** [comment]
Tested here and it seems to be a server issue. We'll be upgrading the server and resetting it, so I'll let you guys know if anything changes.

Now I get what "Unmute players" does. But I'd like to be able to mute myself ingame, if it's an ACRE feature that causes this unmuting. Thanks!

**Comment by jonpas** [comment]
> Now I get what "Unmute players" does. But I'd like to be able to mute myself ingame, if it's an ACRE feature that causes this unmuting. Thanks!

Set yourself to Away.

**Comment by saviorsoldier** [comment]
Tested TeamSpeak 3 with 2 different server (1 local, 1 dedicated), there is no indication that this problem caused by TS3 "move client" permissions. As @BifeO said, different ARMA 3 servers with same settings have different behaviors over the same TS3 server. I agree with him.

**Comment by saviorsoldier** [comment]
Tested with 2 different server. Each server has own TeamSpeak 3 server inside of it. All the ACRE settings, server OS's and mission files also same. Only latest Steam versions of ACRE 2 & CBA_A3 used.

Server 1 RPT: https://gist.github.com/saviorsoldier/2edcb4c1bdf5563a5f1c3cc49ef3354a
Server 2 RPT: https://gist.github.com/saviorsoldier/6e601b590a2766632841a5cf549643e6

Result is also same, no automatic switch to designated TS3 room. If you can show me how to get acre_dll.log file I can share it too @jonpas

**Comment by jonpas** [comment]
`acre_dll.log` should be in `<Arma 3 installation>/logs` @saviorsoldier.

We don't really log anything regarding channel switch, so this would require some debugging.

> 1 local, 1 dedicated

Which one worked and which didn't?

**Comment by saviorsoldier** [comment]
Local server worked but dedicated not worked. I will send you the acre_dll.log's as soon as I'm able to.

**Comment by HaynesW** [comment]
Please have you guys solved this problem, I have the same problem now and want to find a way to solve it.

**Comment by Nilia119** [comment]
We just had a new Dedicated Server running via TADST and the problem did not appear and i was properly switched. But when i switched to FASTER the problem starts to reappear as well as it was still on our hosted Main Server..
So this got me thinking, which settings are different in the server_config and basic.cfg between TADST and our Normal/Faster Server. I tried a lot for the last 3 hours and i couldn't find a thing, everything i tried did not work. By pure accident i changed the Servername of our Faster Server (which was the same as the hosted Server but not as TADST) from "Test Server der 9. Jägerkompanie" to "Test Server der 9. Jaegerkompanie" and it worked... So it was the "ä" i tried it on our regular Server to and it did work to.
I would assume, you cannot have certain characters in the Server Name for some reason...

**Comment by jonpas** [comment]
There is a separate issue for non-ASCII character support already #579.

**Comment by Nilia119** [comment]
> There is a separate issue for non-ASCII character support already #579.

Interesting, i did a **lot** of research, since switching to ACRE regarding this specific issue. But i never turned anything up and i tested a lot...
I don't mean to be annoying or something but this should be mentioned in the ACRE 2 Wiki https://acre2.idi-systems.com/wiki/user/ts-channel-switching
To Maybe help other who eperience the same Problem (i actually have talked to some other Clans who experiemce the same issue) atleast until it is fixed (if ever). If you want to, i can edit the page by myself and make a pull request.
Thank you in advance.

**Comment by jonpas** [comment]
Sure, pull requests for improved actual documentation are always welcome.

**Comment by jonpas** [comment]
I don't know if this is still a problem, we haven't had any for a while now.

Looking at the server names being used again, and that things were possibly happening on 2 different servers (different OS version, configuration), it might just be that on some setups the non-ASCII character use was converted correctly, while on others it wasn't, thus running into #579.

Please re-open if anyone can reproduce with a simple server/channel name with ASCII-only characters.
