### ISSUE TITLE
Second param for unit specifier does not work for acre_api_fnc_getAllRadiosByType

### ISSUE THREAD

**Issue by mjc4wilton** [IDI-Systems/acre2#1090]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.02`
- **CBA:** `3.15.3`
- **ACRE2:** `2.8.0`

**Description:**

**Steps to reproduce:**
- Equip AN/PRC-152 into inventory.
- Execute `["ACRE_PRC152"] call acre_api_fnc_getAllRadiosByType` in debug console to get expected output
- Execute `["ACRE_PRC152", player] call acre_api_fnc_getAllRadiosByType` in debug console and get the unexpected output `[]`

**Expected behavior:**
When specifying a unit the function returns an array of their radio ID's.

**Where did the issue occur?**
- Tested in single player

**Log Files:**
- Nothing applicable to note

**Comment by jonpas** [comment]
What does `[player] call acre_sys_core_fnc_getGear` give you?

**Comment by mjc4wilton** [comment]
hmm...
Retested this morning and it seems to be working?
Calls to acre_sys_core_fnc_getGear appear to be returning correctly, even when doing it with a remote controlled unit via ACE_player. Might have been something I was doing wrong at 2:30 am and didn't notice. I'll leave it open for a few days while I do some testing to make sure its working before I close this issue

**Comment by jonpas** [comment]
Feel free to just re-open if you manage to reproduce. :)
