### ISSUE TITLE
Questions : Spawn automatically with a radio & No babel active

### ISSUE THREAD

**Issue by nicolas-goyon** [IDI-Systems/acre2#1093]
( I didn't find where i put the question label sorry)

Hi, i have 2 question, first, I have a mission where everyone spawn with the AN/PRC-343 but no-one have it in the arsenal, i did not find anything about it...

The second question is what is the babel system, how its work, and is there a possibility to hide the case "no babel active" ?

**Comment by jonpas** [comment]
You can get most of that information on our wiki: https://acre2.idi-systems.com/

ACRE radios appear in Arsenal just fine, check your configuration (whitelist if you have one).

See wiki on how Babel works. "No babel active" message simply means you are pressing a Babel keybind, but you have Babel disabled.

Feel free to join us on ACE3 Slack #acre2 for further questions like that.
