### ISSUE TITLE
How to change radio? (Not bug)

### ISSUE THREAD

**Issue by Cocaina-Ricky** [IDI-Systems/acre2#1094]
This isn't a bug, but a question.

When I spawn, the default radio I am given is AN/PRC-343 but I want the default to be AN/PRC-152

How can I make this happen, so every unit that joins in the game, gets that specific radio?

**Comment by jonpas** [comment]
You can use the Basic Mission Setup module, but there is currently a bug #574.

Alternatively you can use an API function in `initPlayerLocal.sqf` with the following:
```sqf
["ACRE_PRC152"] call acre_api_fnc_setItemRadioReplacement;
```

**Comment by Cocaina-Ricky** [comment]
This doesn't seem to work at all unfortunately.

**Comment by jonpas** [comment]
What does "not work at all" mean exactly? RPT file, versions you are using, just fill out the issue template.

**Comment by Cocaina-Ricky** [comment]
You gave me a script, I tried it and it completely removed the radio out of my list and didn't replace it with the classname: ACRE_PRC152.

Meaning I have no radio and never received one when spawned in.

RPT doesn't show these errors
But here, i'll link it anyway
https://www.mediafire.com/file/4m1qw029dvohvl3/arma3server_2021-05-03_08-36-05.rpt/file

Version is stable + latest.

**Comment by jonpas** [comment]
It works fine, just tried it.

**Fill out the issue template completely**, you did not mention what server or local host you are running it, what else is in the mission or what mods you are using (specific versions required - try with only CBA+ACRE2 and maybe ACE3).

**Comment by Cocaina-Ricky** [comment]
I really don't wanna type out 52 mod names. It's too long.

I'm using it on a dedi box, public, no localhost.

I'll try it out later and work my way around it. Surprised there's no classnames in-game so I can manually assign the radios to people.

**Comment by jonpas** [comment]
And I don't want to debug an issue that might be entirely on your side without that information. :)

You can assign radios using normal ways, Arsenal, loadout scripts, whatever. This is about replacement of the vanilla radio. You can also get rid of that vanilla radio.

**Comment by Cocaina-Ricky** [comment]
Yeah I understand man. I don't wanna waste your time with that either, I know it's 100% my side. I was just wanting to know how to assign that specific radio.

Understood about vanilla radio as I will remove that.

Unfortunately when I go into Arsenal I don't see the radios there, is there a specific place it goes?

**Comment by jonpas** [comment]
Uniform/Vest/Backpack -> Items.

**Comment by jonpas** [comment]
No further reply.
