### ISSUE TITLE
Radios set to "right ear" do not work 

### ISSUE THREAD

**Issue by mwade-dt** [IDI-Systems/acre2#1095]
When setting the 148 or 152 to us "Right Ear" via the ACE interact menu, neither radio will work. Radios do not squawk, transmit, or play sound. The graphic in the bottom of the screen shows it's activated, but no sounds play.

**Comment by jonpas** [comment]
Could be something with your audio setup, make sure stereo audio works properly outside of Arma.

Also fill out the issue template in full!

**Comment by JamesTheClarke** [comment]
A guy in our unit had the same issue. The reason was he had an Arctis 7 headset that split audio channels and messes up audio inputs when combined with ACRE2's right ear option.

**Comment by jonpas** [comment]
No further reply, re-open if you still experience the issue. This is entirely a device issue, we play all sounds via TeamSpeak's playback system.
