### ISSUE TITLE
SOG COMPAT has no server key

### ISSUE THREAD

**Issue by MadSoloSniper** [IDI-Systems/acre2#1096]
Missed in all the fury to get this out to the workshop.

**Description:**
No server key for the ACRE2 SOG Compat

**Steps to reproduce:**
- Install it
- look for the key
- it's not there

**Expected behavior:**
- Key so we can have Battleye on
- check for proper MODs
- Run a tight server

**Where did the issue occur?**
- Dedicated 

**Log Files:**
NA

**Additional context:**
NA

**Screenshots:**
NA

**Comment by jonpas** [comment]
No, it is there in the main ACRE2 package.
```
    Directory: G:\SteamLib\steamapps\common\Arma 3\!Workshop\@ACRE2\keys


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----       6. 05. 2021     15:18            177 acre_2.9.0.1042.bikey
```
