### ISSUE TITLE
ACRE2 TS3 BUG

### ISSUE THREAD

**Issue by Lazky** [IDI-Systems/acre2#1097]
The ACRE2 is only updated on the Arma 3 but not on the TS3, it gives problems when using it in the game. Answer me if there is progress please

![image](https://user-images.githubusercontent.com/83792917/117379602-05775980-ae95-11eb-89b9-489bbfaafeca.png)

**Comment by jonpas** [comment]
Fill out the template...

**Comment by PabstMirror** [comment]
you and server have different versions
