### ISSUE TITLE
SOG:PF - F-4 Phantom Rack Radios are modern PRC-117Fs rather than PRC-77s

### ISSUE THREAD

**Issue by SyniRon** [IDI-Systems/acre2#1101]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.01.147540`
- **S.O.G. Prairie Fire:** `1.01.006305`
- **CBA:** `3.15.3.210310`
- **ACRE2:** `2.9.0.1042`
- **ACRE2 SOG COMPAT:** `2.9.0.1042`
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
All F-4 Phantom variants have PRC-117Fs as rack radios rather than PRC-77s. The huey helicopters all have 77s as rack radios causing a communication incompatibility and all phantom pilots force to carry 77s in their backpacks to fix it.

**Steps to reproduce:**
- Spawn F-4 of any type in editor
- Start mission as pilot
- Check rack radios

**Expected behavior:**
F-4s should all have PRC-77s by default to allow communication between fixed wing and rotary wing as well as calls from the ground.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer)

**Log Files:**
- https://gist.github.com/peakzero/e24c1ed743783be4e856b51593362fbb
- https://gist.github.com/peakzero/58f60863b12b2102db801d9213dfd949

**Additional context:**
N/A

**Screenshots:**
![2021-05-11_23-37-46](https://user-images.githubusercontent.com/66834451/117915406-37345a00-b2b3-11eb-960f-dd44c0fa3065.png)

**Comment by PabstMirror** [comment]
looks like "vanilla" sog has acre configs for helicopters
```
			class AcreRacks
			{
				class Rack_1
				{
					displayName = "Dashboard";
					shortName = "Dash";
					componentName = "ACRE_VRC64";
					mountedRadio = "ACRE_PRC77";
					allowedPositions[] = {"driver", "commander", "external"};
					disabledPositions[] = {};
					defaultComponents[] = {};
					isRadioRemovable = 0;
					intercom[] = {"none"};
				};
			};
```
but doesn't seem to be anything on the F-4 airplane (`vn_air_f4_base`)

I guess we could add it, but it's awkward having the acre configs being split (helicopters done by them, and air by us)
But I also understand that there are limits to how often they can update

**Comment by SyniRon** [comment]
I was not aware of that fact, that makes sense. I have submitted a bug report to the CDLC tracker as well to see what they say, perhaps they will fix it. 

https://feedback.bistudio.com/T158512
