### ISSUE TITLE
TeamSpeak 3 Win x64 Crashes on ACRE2 Install/Reload

### ISSUE THREAD

**Issue by SnowsongWolf** [IDI-Systems/acre2#1109]
Description:  Windows x64 TeamSpeak 3 crashes when ACRE2 plugin is initially loaded, and when the plugin is reloaded.

Frequency: Always

Steps to reproduce:
1. Install Windows x64 TeamSpeak 3 client.
2. Subscribe to an enable the ACRE2 mod via Steam Workshop.
3. Enable the ACRE2 mod in the Arma 3 Launcher.
4. Launch TeamSpeak 3.
5. Launch Arma 3.
6. Observe that TeamSpeak 3 will crash shortly after the ACRE2 plugin is installed.
7. Relaunch TeamSpeak 3.
8. Observe that the ACRE2 plugin appears enabled.
9. Click the Reload Plugin button for ACRE2.
10. Observe that TeamSpeak 3 will crash immediately.

**Comment by SnowsongWolf** [comment]
This issue does not appear to affect in-game function.  The Plugin is loading correctly after initial install and functions with the Arma 3 ACRE2 mod.

**Comment by jonpas** [comment]
Please fill out the template, with all versions, especially ACRE2 and TeamSpeak versions, any other plugins loaded etc.
