### ISSUE TITLE
PRC 77 channel/knob position cannot be set via acre_api_fnc_setRadioChannel

### ISSUE THREAD

**Issue by diwako** [IDI-Systems/acre2#1111]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147540`
- **CBA:** `3.15.3.210310`
- **ACRE2:** `2.9.0.1042`

**Description:**
When trying to set the channel/frequency/knob position on the PRC 77 via script, it errors out

**Steps to reproduce:**
- create new empty mission
- place down any vanilla unit
- preview
- exec this in debug console
```sqf
[] spawn {
player addBackpack "B_FieldPack_cbr";
player addItem "ACRE_PRC77";
waitUntil {([] call acre_api_fnc_isInitialized)};
if !([player, "ACRE_PRC77"] call acre_api_fnc_hasKindOfRadio) exitWith {
    systemChat "no prc77 radio in inventory";
};
private _radio = ["ACRE_PRC77"] call acre_api_fnc_getRadioByType;
if (isNil "_radio") exitWith {
    systemChat "could not retrieve id'd prc77";
};
[_radio, 2] call acre_api_fnc_setRadioChannel;
};
```

**Expected behavior:**
The frequency of my prc 77 has changed and the frequency knob should be on the second position

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Log Files:**
- none

**Additional context:**
Trying to set the frequency of prc 77s at spawn of the player unit. In my digging I figured the prc 77 need more info than just channel of frequency, such as knob position and some more.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8259498/119631613-5d5c0d00-be10-11eb-9738-3b09ac1fb563.png)

**Comment by PabstMirror** [comment]
`acre_sys_prc77_fnc_setCurrentChannel` expects `_eventData` to be an array of
[mhz knob, khz knob]

we could adjust the api function to take either array or just a single number (and then set khz to 0)
`_eventData params [["_mhz", 0, [0]],["_khz", 0, [0]]]; `

OR map channels to something like `number = mhz * 20 + khz`

OR just say api//channel numbers just don't work for the PRC77 because it has 2 knobs

**Comment by diwako** [comment]
I think most people that are not too familiar with the 77s would just go with the first knob and leave the second one alone.
