### ISSUE TITLE
Save channel selected or Add radio's to arsenal with preset channel

### ISSUE THREAD

**Issue by Jelliebean255** [IDI-Systems/acre2#1112]
**Is your enhancement related to a problem?**
Problem is that when a team member dies they would have to reselect the channel they were on. This causes confusion as players forget to switch back to the required channel for the group. 

**Solution you'd like:**
-Add a feature were the player can save the current radio setup that the have this include ear position, channel and volume. This can either be done by a mouse scroll action or with ACE interaction. Mouse wheel scroll would create a file with the stored setting related to the current mission, role and loadout. Upon respawn file is loaded and applied to the radio's equipped by the player. 

**Alternatives you've considered:**
-As an alternative, add some pre-defined radio with different channels selected into the arsenal. Something like example attached.

**Additional context:**
Biggest problem is the channel selection. 
![Acre Arsenal Setup](https://user-images.githubusercontent.com/83724093/119832052-2106da80-befe-11eb-9982-196ffa09173d.PNG)

**Comment by Soldia1138** [comment]
You could achieve this easily with a combination of EH and API calls (e.g. https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_getCurrentRadioChannelNumber.sqf).

I think this is too specific to be implemented in ACRE itself

**Comment by jonpas** [comment]
This is out of scope, fits better in a mission framework or the mission you need it in.
