### ISSUE TITLE
20 seconds of stutter after changing loadout

### ISSUE THREAD

**Issue by freghar** [IDI-Systems/acre2#1116]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04`
- **CBA:** `3.15.3.210310`
- **ACRE2:** `2.9.0.1042`
- **ACE3:** `3.13.6`

**Description:**
The game stutters once per second some 20 seconds after `setUnitLoadout` using this loadout array (wrapped in a reproducer):
```sqf
[] spawn {
    sleep 3;
    player setUnitLoadout [
        ["arifle_TRG20_F","","","",["30Rnd_556x45_Stanag",30],[],""],
        [],
        [],
        ["U_BG_Guerilla1_1",[["ACRE_PRC343",1]]],
        [],
        [],
        "",
        "",
        [],
        ["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]
    ];
};
```
When executed for the first time, the stutter is only barely noticeable, however when I wait for it to stop (20 seconds) and execute the above again, the stutter is notably more visible the second time around.

What's curious is that the second (or any further) reproducer run can be with an empty loadout (with `["ACRE_PRC343",1]` and `ItemRadioAcreFlagged` removed) and the stutter still happens for the next 20 seconds, .. another repeated attempt results in no stutter. This indicates it might be related to the _previous_ loadout a unit had.

This is reproducible in singleplayer editor preview, the stutter doesn't visibly happen in dedicated MP, **however** when logging `diag_fps` every frame, I can see a statistically significant ~2 FPS dip every ~50 frames on a ~50 FPS server and this happens only during the 20 second window, not before or after. In this case, the reproducer is executed locally on the client.

This is also reproduble only with ACE3, I was unable to get the same stutter when running without ACE3. .. I tried removing `ace_nametags.pbo` and other PBOs that could feasibly affect it, but the problem is more likely the ACE3 compatibility code on ACRE2 side.

**Steps to reproduce:**
1. Set mouse smoothing to maximum in game settings
1. Place down any soldier unit in editor
1. Preview in SP
1. Execute the reproducer above in debug console
1. Wait 30 seconds
1. Execute the reproducer again
1. Start turning around as smoothly as you can
1. After the `sleep 3` finishes, observe 1-second stutter for 20 seconds

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Log Files:**
- [RPT file](https://gist.github.com/freghar/04ee3f91c8c1323a842f92300f9ff738)
  - unfortunately, nothing interesting
- [acre_dll.log](https://gist.github.com/freghar/ee76924d2af1b6c41b91e0ae247b4a20)
  - same here

**Video:**
I've tried to record this with maximum mouse smoothing and at 60 FPS, but it's only barely visible due to recording artifacts:

[![youtube video link here](https://img.youtube.com/vi/OY63Y4DfhiQ/0.jpg)](https://www.youtube.com/watch?v=OY63Y4DfhiQ)

**Comment by jonpas** [comment]
This sounds similar to #1007, but your test cases seem to disagree.

**Comment by jonpas** [comment]
@freghar Do you happen to know if this is still an issue? I haven't been paying much attention to this as changing entire loadout during critical gameplay is not something that really happens at all.

**Comment by jonpas** [comment]
Closing as potentially fixed. If it's still an issue in v2.11 or higher, leave a comment and we will re-open.
