### ISSUE TITLE
Mic randomly cuts out when talking

### ISSUE THREAD

**Issue by Kill3rCat** [IDI-Systems/acre2#1118]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147719'
- **CBA:** `3.15.3`
- **ACRE2:** `2.9.0.1042`
- **ACE3:** `3.13.6`
- **ACE3X:** `3.5.4`
- IFA3
- IFA3-ACRE2 compats
- Camofaces
- CUP Terrains
- Crossroads Bocage terrain
- Drongo's Artillery
- dzn Weapon Holders Carryable
- Enhanced Movement & Rework
- GRAD Trenches
- JSRS
- JSRS IFA3
- L_Suppress
- LAMBS
- Prone Launcher
- RR Immersive Maps
- US General Equipment
- CSA38
- CSA38 ACE compats
- CSA38 IFA3/FOW compats
- KAT Notebook
- Northern Fronts terrains
- Orglandes terrain

**Description:**
One of the members of my unit has an issue that his mic sometimes randomly cuts out mid-sentence when in ACRE. This only happens when in Teamspeak and connected to ACRE2. The issue does not occur when out of ACRE or when using TFAR.

**Steps to reproduce:**
- He gets in ACRE
- Sometime later in the mission, he cuts out while talking, and has to retransmit his sentence

**Expected behavior:**
He is able to transmit without issue.

**Where did the issue occur?**
- Dedicated MP, haven't tested client-hosted because neither of us can host

**Log Files:**
https://gist.github.com/Kill3rCat/058404d8d7f78f501eb2c58d67352199

**Additional context:**
When he cuts out, his icon continues to light up blue in TS, but sound does not come through in-game and the icon above his head doesn't wiggle. He never cuts out while out of ACRE, or while in TFAR. Only ever while in-game, in ACRE. We have spent countless hours testing this, trying to track down the issue, without success. Only the one person has this issue, nobody else. The issue has persisted even after getting a new PC and doing a fresh reinstall of Windows, Arma 3, Teamspeak, ACRE plugin, all mods, etc.

The issue never seems to occur at the start of the mission, though that may simply be by chance, and seems to happen with greater frequency when more people are connected to the server. The issue does not occur when we attend regular weekly events with another community, OFCRA, who use a different TS and game server, as well as using TFAR instead of ACRE2.

**Comment by jonpas** [comment]
Is he using Push-To-Talk or Voice Activation?

**Comment by Kill3rCat** [comment]
> Is he using Push-To-Talk or Voice Activation?

We've tried both, should've mentioned that. Sorry.

**Comment by jonpas** [comment]
Is it always just that one specific player? How is his internet connection to the TS and Arma servers? I suspect there is something else at play here.

**Comment by Kill3rCat** [comment]
> Is it always just that one specific player? How is his internet connection to the TS and Arma servers? I suspect there is something else at play here.

Yes, it only affects this one player. His connection to Arma and TS is fine, the only issues he has are with his ACRE cutting out. It never happens when in TS but out of ACRE, or when in TS and using TFAR. Only when in-game and in-ACRE.

**Comment by Kill3rCat** [comment]
It's definitely an issue with ACRE. He only has the issue when using ACRE and in-game. Any ideas?

**Comment by tbeswick96** [comment]
Maybe related, I've been told I cut out if I'm monologuing and switch into zeus

**Comment by jonpas** [comment]
Issue showing when ACRE is in use does not guarantee ACRE is the cause, it might just be showing the issue.

There is no reason cut-out should happen, maybe there is some action being invoked that cuts voice transmission, maybe a conflict in keybinds? Capturing it on video or being able to reliably reproduce it will help a lot, but that may not be easy to get.

**Comment by Kill3rCat** [comment]
> Issue showing when ACRE is in use does not guarantee ACRE is the cause, it might just be showing the issue.
> 
> There is no reason cut-out should happen, maybe there is some action being invoked that cuts voice transmission, maybe a conflict in keybinds? Capturing it on video or being able to reliably reproduce it will help a lot, but that may not be easy to get.

The issue is unlikely to be a keybinding issue. We tried a lot of things to reproduce the issue. We connected to our game server and connected to ACRE. We then talked for about 30 minutes and did various tests involving continuous transmission (holding down PTT button and giving a mock briefing), as well as interrupted transmission (repeatedly pressing the key, terminating transmission, talking again, terminating, etc.), as well as trying to induce issues by putting obstacles between us, moving around, using smoke and large numbers of AI to induce FPS drops, etc.

The issue seemed to come and go randomly, sometimes not manifesting at all for several minutes, and other times being quite severe. And yet when we reproduced the circumstances in which the issue occurred, we couldn't find any pattern or causal relationship between the issue and any of our testing strategies.  Bear in mind, the user has replaced his headset and his entire PC and the issue has persisted, so it must be an issue somehow with his config/settings, or a networking issue. Could packet loss cause this issue? I wouldn't think so but I could be wrong. And again, the issue doesn't occur out of ACRE.

**Comment by jonpas** [comment]
Hmmm, good info.

One thing I didn't ask yet, does it happen only with using radios, or direct speaking as well? You say TS icon stays lit, is that for him or also everyone else?

**Comment by Kill3rCat** [comment]
Both radios and directly speaking. TS icon remains lit for everyone.

**Comment by jonpas** [comment]
Is there any chance you can try reproduce this on an "empty" mission with only CBA+ACRE2? Then we can maybe find some debug information to help out.

**Comment by Kill3rCat** [comment]
We can try. It was hard enough to repro it using our normal modset.

**Comment by TheRoyalRat** [comment]
I'm also encountering this, although it is with an almost entirely different modset. No solution found on my part.

**Comment by Dizax67** [comment]
same issue

**Comment by jonpas** [comment]
Have never seen this personally, or anyone from the team. Please re-open if it's still encountered and add as much information regarding the setup as you can.
