### ISSUE TITLE
CSLA Compatibility 

### ISSUE THREAD

**Issue by MJVEVERUSKA** [IDI-Systems/acre2#1120]
Hello, it would be possible to make compatibility with the new DLC: csla

      Thank you

**Comment by jonpas** [comment]
We don't have any plans at the moment. ACRE should just work provided they don't have any incompatible features. Signal will be calculated as if it would be terrain flat.

We are open to adding and publishing compatibility package (specifically FakeWRP for terrain) if anyone wishes to contribute it.

**Comment by jonpas** [comment]
This has been released in v2.10.0 with #1156.
