### ISSUE TITLE
"acre_api_fnc_getRadioChannel" always returns 1 for AN/PRC-77

### ISSUE THREAD

**Issue by BulletsBreath** [IDI-Systems/acre2#1121]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04.147719` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.2` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.9.0.1042` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
the function "acre_api_fnc_getRadioChannel" always returns 1, no matter which frequency is applied, for AN/PRC-77

**Steps to reproduce:**
- start arma 3 with CBA, ACE and ACRE2 only
- create a new mission in editor (virtual reality) 
- place a playable unit and equip AN/PRC-77, press play
- use function in debug console: ["ACRE_PRC77_ID_1"] call acre_api_fnc_getRadioChannel 
- See return value: 1
- change frequency to a random value, use function again
- See return value: 1
- repeat

**Expected behavior:**
return value of the function should change, it does for every other radio including SEM52 and SEM70, which also work with frequencies.

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by jonpas** [comment]
AN/PRC-77 only has one channel. Channel in turn has a set frequency. You are not changing the channel, but frequencies. SEM52 and SEM70 have channels you switch between.

There is currently no direct API for getting a frequency, but you can get it through internal variables (not guaranteed to stay the same in future updates):
```sqf
private _txData = ["ACRE_PRC77_ID_1", "getCurrentChannelData"] call acre_sys_data_fnc_dataEvent;
private _currentFreq = _txData getVariable "frequencyTX";
```
