### ISSUE TITLE
Audio ques for incoming and outgoing transmits are mute

### ISSUE THREAD

**Issue by CommyDuck** [IDI-Systems/acre2#1125]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.x.x` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
ACRE2 properly installed, doesn't matter if it's in editor or in server, Audible ques for incoming and outgoing transmits for handheld radios are mute/not there. One guy in our unit of 25 has had the fortune of getting these audio ques. I understand it's a quality of life thing, I'm just trying to help my unit understand what's happenign.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...
- [Answer] Can't say I have anything for this, I just installed and this bug happened

**Expected behavior:**
Expectation was for the audible ques to activate when incoming and outgoing transmits happen. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
- [Answer] All of the above

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the extension log file, which can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Additional context:**
Not that I can say, I tried to unsubscribe and subscribe back to ACRE but I cant uninstall the plug in from TS. Also, TFAR beta was disabled and I've gone as far as to uninstall that, to no success though.

**Screenshots:**
It's an audible issue, sorry.

**Comment by jonpas** [comment]
Did you try troubleshooting steps on our wiki?

**Comment by CommyDuck** [comment]
ngl didn't know you had one, what's the wiki?

**Comment by CommyDuck** [comment]
> Did you try troubleshooting steps on our wiki?

I would like the link, or if the solution is on slack.

**Comment by jonpas** [comment]
https://acre2.idi-systems.com/wiki/user/installation#troubleshooting

**Comment by jonpas** [comment]
Is this still a problem?

**Comment by CommyDuck** [comment]
> Is this still a problem?

I personally had no control over anything to do with the server but no, I managed to fix it by completely getting rid of ACRE and TS from my PC and getting everything back.

**Comment by jonpas** [comment]
That could also be anti-virus software or something similar. Glad you solved it.

**Comment by CommyDuck** [comment]
Thanks for the check in
