### ISSUE TITLE
Hearing radio chatter while unconcious

### ISSUE THREAD

**Issue by Lefrets** [IDI-Systems/acre2#1128]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.04` stable
- **CBA:** `3.15.5.210713` 
- **ACE3:** `3.13.6`
- **ACRE2:** `2.9.0.1042`

**Description:**
Although having the ACE3 unconcious hearing setting set to 0 (not hearing anything while unconciouns) I (and everyone else I play with) am able to hear everyone talk on the radio. I'm not able to hear the others via proximity chat though...

**Steps to reproduce:**
- Go unconcious
- Have somone else talk via radio (tested with AN/PRC-343; AN/PRC-152)
- Hear the other person via radio though not via proximity chat

**Expected behavior:**
Hear nothing at all. 

**Where did the issue occur?**
- Dedicated

**Additional context:**
This issue has alrady occured sometime 2018, and got officially fixed that year.

**Comment by jonpas** [comment]
Should be fixed by #1159 and https://github.com/acemod/ACE3/pull/8659 a while ago.
