### ISSUE TITLE
Can mute others in spectator but not self

### ISSUE THREAD

**Issue by Quailsnap** [IDI-Systems/acre2#1131]
**Is your enhancement related to a problem?**
I have a keybind to mute other spectators in ACRE2, but if I talk they can still hear me while I cannot hear them. Odd behavior and perhaps not by design.

**Solution you'd like:**
Muting others in spectator should also mute them from hearing you.

**Alternatives you've considered:**
N/A

**Additional context:**
ACRE2 preventing any muting in Teamspeak (even adv. local mute still has an odd blip where they can hear me) makes this difficult.

**Comment by jonpas** [comment]
Using Voice Activation I assume?

This isn't necessarily not by design, but expectation that most users use Push-To-Talk, where this can't be a problem as you'd need to press a button to talk anyways.

**Comment by Quailsnap** [comment]
I would argue the expectation that "most users use Push-To-Talk" is unfounded. IIRC TS3 default is not PTT, and of the units I've played with as of late, only one in eight enforces PTT. Many figure they'll be multi-tasking while they talk in Arma, and freeing a finger off of a key means voice activation isn't entirely uncommon.

That said, the pool of people that talk to themselves with the other spectators muted is limited to streamers, so a "fix" may be a pretty low priority.

I still don't understand why ACRE2 forces unmute in general, but the rationales I can imagine don't really apply to Spectator.

**Comment by rautamiekka** [comment]
I read, and I think someone in our group said, that TS has a problem with detecting the keypresses made within 'Arma 3' some times, especially if you had to use 2 separate combos to tell ACRE to activate the radio and TS to allow mic usage, so there's that.

**Comment by jonpas** [comment]
It was recommended to use PTT for a long time, TeamSpeak's voice detection was not good enough generally, there are still problems today. Not an unfounded expectation, just a fact in history of ACRE2.

Open to PRs to address this.

**Comment by Quailsnap** [comment]
> 
> 
> I read, and I think someone in our group said, that TS has a problem with detecting the keypresses made within 'Arma 3' some times, especially if you had to use 2 separate combos to tell ACRE to activate the radio and TS to allow mic usage, so there's that.

Not to wake a dead issue, but I think that's just because that person may be running Arma as a fullscreen application with elevated permissions (as admin) and Teamspeak without (not as admin), which may prevent keybinds from the latter reaching when the former is in focus. Best to run both as admin.



> 
> 
> It was recommended to use PTT for a long time, TeamSpeak's voice detection was not good enough generally, there are still problems today. Not an unfounded expectation, just a fact in history of ACRE2.
> 
> Open to PRs to address this.

A PR to remove the auto-self-unmute functionality, or only run it once when ACRE initializes, should be simple. Would you be open to something that features those?

**Comment by jonpas** [comment]
> A PR to remove the auto-self-unmute functionality, or only run it once when ACRE initializes, should be simple. Would you be open to something that features those?

Absolutely.

**Comment by jonpas** [comment]
Not sure if this is still an active issue since there were some changes in Zeus/Spectator code. But the original issue does not describe what was decided in the end.
