### ISSUE TITLE
Basic radios in Prairie Fire for all team members?

### ISSUE THREAD

**Issue by zacekjakub** [IDI-Systems/acre2#1132]
Normal team members are unable to communicate low-distances.

I want every member to have some basic radio. Is that possible?

Thank you

**Comment by jonpas** [comment]
Tagging @veteran29.

**Comment by veteran29** [comment]
There's no way to do this out of the box without some sort of arsenal/zeus mod.

**Comment by rautamiekka** [comment]
1 of our group's bosses said you need to spawn a box with the radios through Zeus cuz even in ACE Arsenal they aren't visible as of this, but once ACE supports the DLC it might.

**Comment by jonpas** [comment]
As @veteran29 put it, this isn't possible now to do nicely from ACRE2's compatibility side at this time.
