### ISSUE TITLE
Acre radio sounds(Beep) not working

### ISSUE THREAD

**Issue by iRock1** [IDI-Systems/acre2#1133]
Found that the radio sound is not working in our recent missions. Not sure where to look or what to do, not that IT(software) savvy.  Happened for a few players in our unit. Please help.

**Comment by jonpas** [comment]
See our troubleshooting section under installation instructions in our wiki.

**Comment by iRock1** [comment]
Thanks for that. We found this mentioned in the previous issues, and found the fix. It was the b64 not activated on our server. Thanks.

**Comment by iRock1** [comment]
Solved

**Comment by jonpas** [comment]
Lovely! :+1:
