### ISSUE TITLE
Add a radio speaker option

### ISSUE THREAD

**Issue by S0P4** [IDI-Systems/acre2#1134]
Hi, my request is to add a radio speaker mode, that the radio operator can set to other teammates ear the radio if they are nearby.

If u need more context or more explicación let my to know.

**Comment by Drofseh** [comment]
Radios are only given speakers if they have a speaker in real life.

**Comment by S0P4** [comment]
All radios has speakers is the default method u can put a headset. Maybe a particular model don has speakers.

For example, this Is an/prc 152 data sheet, if u look this has a builtin speakers and mic 

https://www.l3harris.com/all-capabilities/falcon-iii-an-prc-152a-wideband-networking-handheld-radio

**Comment by jonpas** [comment]
Headset output is not a speaker.

152 does have a speaker, you can enable it through its menus (just like on the real one), I believe it's under OPT.

**Comment by S0P4** [comment]
Sorry if a dont explain my self well, my english Is not that good, if inplememted, u can add a ace action to enable the speaker to be more prsctical ?

**Comment by jonpas** [comment]
Clear Backblast has a nice guide on using radio speakers on the 152 and 148: https://wiki.clearbackblast.com/guides:acrespeakers

There are no plans to make an ACE Interaction for this, we follow the realistic use of radios as much as possible.
