### ISSUE TITLE
Acre muting TS

### ISSUE THREAD

**Issue by KILLAKAN10** [IDI-Systems/acre2#1160]
**Mods (complete and add to the following information):**
Aaren's Blast Effects
ace		
ACE Compat - RHS AFRF	Steam	
ACE Compat - RHS USAF	
ACE Compat - RHS: GREF	
ACE Compats - RHS Compats	
ACE Interaction Menu Expansion
Ace Medical Assistant [Simple Medical Mod]
ACE Vehicle Medical	
ACRE2	
Advanced Weapon Mounting
CBA_A3	
DynaSound 2	
Enhanced Map Ace Version	
Enhanced Movement	
Enhanced Soundscape	
Gruppe Adler Trenches	
JSRS SOUNDMOD	
JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support	
JSRS SOUNDMOD - RHS GREF Mod Pack Sound Support	
JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support	
RHSAFRF	
RHSGREF	
RHSSAF	
RHSUSAF
Zeus Enhanced	
Zeus Enhanced - ACE3 Compatibility	

**Description:**
#432 in it's entirety, it just started happening mid mission.

**Steps to reproduce:**
1. Get in
2. ????
3. Pain, 400 metres, Front.

**Expected behavior:**
Anything but that.

**Where did the issue occur?**
- Dedicated 

**Log Files:**
- Link to acre_dll.log https://pastebin.com/RUDtaG14
-Link to Server RPT https://pastebin.com/SQtKXyvf
-Link to Client RPT https://pastebin.com/NduUg6NX
**Additional context:**

**Screenshots:**

**Comment by jonpas** [comment]
Provide RPT.

**Comment by KILLAKAN10** [comment]
Sorry, I didn't think it necessary since I didn't crash, I'll get that now and edit the original post.

Wait, did you want the client RPT or Server RPT? 

Ah fuck it have both, that's probably the best solution.

**Comment by jonpas** [comment]
There are a lot of mods and mission scripts, some have errors as seen in the RPT. This is more or less impossible to debug that way I am afraid.

**Comment by KILLAKAN10** [comment]
Shame, any idea how 432 happened?

**Comment by jonpas** [comment]
Sadly not.

**Comment by jonpas** [comment]
Have you had that happen again since this report?

**Comment by KILLAKAN10** [comment]
It would happen regularly, we kinda stopped playing antistasi because between the acre issues and set-up time in-game, not an awful lot would get done at all :p

**Comment by jonpas** [comment]
So this only happened with Antistasi?

**Comment by KILLAKAN10** [comment]
It would happen with other stuff too, like nmd sandbox, but antistasi was generally the only mission played

**Comment by jonpas** [comment]
This is now over a year old with no further information. If you are still experiencing it, maybe ask other users of Antistasi+ACRE or other combinations you found the issue with, see if they are having the same issue first.
