### ISSUE TITLE
Documentation on auto-saving

### ISSUE THREAD

**Issue by Oscar-Geare** [IDI-Systems/acre2#1161]
**Is your enhancement related to a problem?**
In documentation there is mention of an "auto-saving" feature when talking about operational or preset programming for the 152 (https://acre2.idi-systems.com/wiki/radios/an-prc-152#operational-programming) however (I think?) there is no documentation on how to enable this feature. I believe this should enable channel switching on the 152?

**Solution you'd like:**
Documentation on how to use this feature.

**Comment by jonpas** [comment]
In interface of the radio, under "RADIO OPTIONS" menu there should be a "PRESET AUTOSAVE" item that you can set.

You don't need this to enable channel switching. Only if you want to manually program presets directly on the radio and keep them persistent.

**Comment by Oscar-Geare** [comment]
Hey mate, yeah do have that option under OPT > Radio Options, but it says "NO ITEMS IN MENU". How can I proceed from here?

**Comment by Oscar-Geare** [comment]
Hello. Regarding my last question, was there an option or a setting I'm missing? When going into that menu it just tells us there is no items. It doesn't seem like there is an option to actually enable the autosaving?

**Comment by jonpas** [comment]
Then it was probably just never implemented to the end.

**Comment by Oscar-Geare** [comment]
So does this mean there are server side settings that should be set? If so, what should they be?

**Comment by jonpas** [comment]
No, it is simply not implemented.

I checked the code again and I misread it last time, it is just the menu that was preared.

**Comment by Oscar-Geare** [comment]
Ah ok. Thank you for looking into it. Any chance for it to be roadmapped for some time next year?

**Comment by jonpas** [comment]
No, this is a free time project and there are no schedules.

**Comment by Oscar-Geare** [comment]
No problem, understandable. Thanks mate.
