### ISSUE TITLE
Sahara 

### ISSUE THREAD

**Issue by Jedipirateman** [IDI-Systems/acre2#1171]
**Description:**
When starting a mission with ACRE Enabled on the new DLC it comes up with an error and says it was unable to parse the map and it is going to use arcade signals
**Steps to reproduce:**
- Go to Sahara DLC
- Click Play
- See Error

**Expected behavior:**
working ACRE

**Where did the issue occur?**
Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

**Comment by Soldia1138** [comment]
#1169
