### ISSUE TITLE
Radios not working since last ACE update

### ISSUE THREAD

**Issue by Red-Dog-Actual** [IDI-Systems/acre2#1172]
Radios no longer working since last ACE update. Can not transmit or receive. Can not access radio by ACE self interaction. Local voice communication still functions normally.

**Comment by jonpas** [comment]
Fill out the issue template.

**Comment by Kursius** [comment]
@Red-Dog-Actual I faced the same issue, however, removing 'dzn Extended Jamming' worked. Make sure you are not using that mod.
The new ACE update changed how jams work, making the aforementioned mod incompatible with ace, and subsequently breaking ACRE (and TFAR).

**Comment by M-Davies** [comment]
> @Red-Dog-Actual I faced the same issue, however, removing 'dzn Extended Jamming' worked. Make sure you are not using that mod. The new ACE update changed how jams work, making the aforementioned mod incompatible with ace, and subsequently breaking ACRE (and TFAR).

Related issue for that https://github.com/10Dozen/dzn_EJAM/issues/29
