### ISSUE TITLE
Improve Audio Quality of 148/152 Speaker Functionality - INT AUDIO & Radio Speakers

### ISSUE THREAD

**Issue by JamesTheClarke** [IDI-Systems/acre2#1173]
**Is your enhancement related to a problem?**
It's more of a question rather than a specific request/problem: is it possible to improve the audio distortion used for the [148/152 speaker functionality](https://wiki.clearbackblast.com/guides:acrespeakers)? It's a really neat/useful feature, however, it kinda sound a bit more like people around you plugged their headsets directly into your radio rather than a true speaker system. Especially in direct comparion to the same feature in TFAR. Would it be possible to update the audio distortion / sound model used for speakers to make then sound a bit more tinny and "speaker-like". I know that's not a good description of the enhancement but unfortunately I am not an audio-tech guy. :)

**Solution you'd like:**
Pretty much what I described above, if the speaker system could sound a bit more like TFARs speakers or other RL equivalents it would improve the experience a lot.

**Alternatives you've considered:**
Switching to TFAR, but why would I do that when I <3 ACRE2 so much?!

**Additional context:**
Nope, that's pretty much it. Thank you for your time and efforts!

**Comment by PabstMirror** [comment]
I tried just dropping the low-end and I think it does sound a little more like a speakerphone

https://youtu.be/C7B2E_qR6PU?t=1 - Original
https://youtu.be/C7B2E_qR6PU?t=27 - With new low-shelf filter

**Comment by JamesTheClarke** [comment]
@PabstMirror that's exactly the sound I was looking for, kudos! And the song choice was brilliant! :D

If this could make it into the next release version, maybe with a cba option to choose between either sound model (old and new) I'd be over the moon!
