### ISSUE TITLE
acre_api_fnc_removeRackFromVehicle - Doesn't work?

### ISSUE THREAD

**Issue by LegalSmeagol** [IDI-Systems/acre2#1176]
Hi. 

I'm trying to run `[this, "ACRE_VRC103_ID_1"] call acre_api_fnc_removeRackFromVehicle;` inside a vehicle's init but this is having absolutely no effect on the vehicle. I've also tried the wiki example of `[cursorTarget, "ACRE_VRC103_ID_1"] call acre_api_fnc_removeRackFromVehicle;` but still doesn't work.

Seems like a lot of the API is very hit and miss when it comes to functionality. 

Any help welcome on this.

**Comment by jonpas** [comment]
All rack API can only happen post-initialization I believe. `init` will happen before racks are initialized. Try to run it from debug console after they are all setup, and I think it should work.

There is definitely room for improvement, but rack initialization process is not simple.

**Comment by LegalSmeagol** [comment]
I did already try that. The first one I tried was of course in the `init `and then I attempted to run it via the debug console as 'Server'. Not quite sure what the true and false responses are referencing, but when using `ACRE_VRC103_ID_1` I get 'false' returned and when using `ACRE_VRC103` (without ID_1) I get 'true' returned, but neither are changing the racks.

**Comment by Drofseh** [comment]
It's working fine for me.

This is the method I'm using to replace racks on a helicopter for an upcoming mission.
In vehicle init:
```
if (isServer) then {
    [
        {
            private _vehicle = _this select 0;

            [_vehicle, {}] call acre_api_fnc_initVehicleRacks;

            private _vehicleRacks = [_vehicle] call acre_api_fnc_getVehicleRacks;

            for "_i" from (count _vehicleRacks) - 1 to 0 step -1 do {
                [_vehicle, _vehicleRacks select _i] call acre_api_fnc_removeRackFromVehicle;
            };

            [_vehicle, ["ACRE_VRC64", "Radio Set - Alpha", "Set A", false, ["driver","copilot"], [], "ACRE_PRC77", [], ["Intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;
            [_vehicle, ["ACRE_VRC64", "Radio Set - Bravo", "Set B", false, ["driver","copilot"], [], "ACRE_PRC77", [], ["Intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;

            _vehicle setVariable ["Dro_customRacksAdded", true, true];
        },
        [this],
        0.1
    ] call CBA_fnc_waitAndExecute;

    [
        {(_this select 0) getVariable ["Dro_customRacksAdded", false]},
        {[(_this select 0), {}] call acre_api_fnc_initVehicleRacks},
        [this]
    ] call CBA_fnc_waitUntilAndExecute;
};
```

**Comment by Drofseh** [comment]
Actually, depending on when you're running `acre_api_fnc_removeRackFromVehicle`, the racks might not have initialized yet, in which case there appear to be no racks to remove, so you may want to initialize whatever radios are there from config first, and then remove them.

`acre_api_fnc_initVehicleRacks`, `acre_api_fnc_removeRackFromVehicle`, and `acre_api_fnc_addRackToVehicle` all also need to be run on the server, 

I've updated my code to reflect that

**Comment by jonpas** [comment]
If there is any idea on how to make API better while allowing above flexibility, please open an issue with it.
