### ISSUE TITLE
Arma 3 not showing "Acre 2 isn't connected to Teamspeak"

### ISSUE THREAD

**Issue by GucciDoublePluggers** [IDI-Systems/acre2#1178]
Opened a new server via LAN as the host, and played a mission using acre 2. The game got a little laggy so we saved the game, and remade the server. Upon reentering the server, acre 2 was not working. I went to look on the teamspeak to see that it said, "Arma Connected: no." Tried resetting both arma and teamspeak several times, reloaded the server several times, disabled and then reloaded the Acre 2 plugin, and tried running the server without teamspeak to see if the message showing that Acre 2 wasn't connected to teamspeak would pop up. It didn't.

Is there a command I can run in the debug console to show the message?

**Comment by rautamiekka** [comment]
You need to fill the template in full ;)

**Comment by jonpas** [comment]
Fill the issue in full and maybe we can help.

Saving and loading is generally not supported, but if you provide full info, maybe something can be done about it.
