### ISSUE TITLE
No Channel switch in Teamspeak

### ISSUE THREAD

**Issue by Nilia119** [IDI-Systems/acre2#1181]
Hi,
my Unit recently switched from TFAR to ACRE2. Since we switched, the Automated Channel switch in TS3 does not function anymore.
ACRE is working, it is connecting with ArmA 3 and is working "as desired", but all Users have to manually switch to the appropiate Channel (It did work with TFAR). The CBA Settings are set correctly and if i would start a dedicated Server, it does move everybody. Which leads me to think, that this is a Server sided issue.
In the last couple of months i tried a lot, to fix it, but with no result. Maybe anybody of you have any Ideas. (The Server is hosted via HostHavoc).
Attached i have my Server.cfg, if you need more information, don't hesitate to conntact me.
[serverConfig.txt](https://github.com/IDI-Systems/acre2/files/7833057/serverConfig.txt)

Thank you in Advance!

**Comment by Drofseh** [comment]
Please fill out the issue report
```
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.x.x` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the extension log file, which can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.
```

**Comment by saviorsoldier** [comment]
We already have an issue report (#1081) regarding this problem.

**Comment by jonpas** [comment]
Duplicate, please use #1081 for further information.
