### ISSUE TITLE
Acre2 radio channels resetting zeus

### ISSUE THREAD

**Issue by WarhammerActual** [IDI-Systems/acre2#1182]
Hello, wondering if anyone could help me with a problem I am experiencing. I use acre2 and when I go in and out of Zeus my radio channels are reset back to default Channel 1. Has anyone heard of this bug or does anyone know a workaround or fix thank you in advance

**Comment by jonpas** [comment]
Fill out the issue template...

**Comment by WarhammerActual** [comment]
> Fill out the issue template...

Gladly have a link perhaps? Or point me in the correct location? I do not see a "template" anywhere. Thank you

**Comment by WarhammerActual** [comment]
Scratch that , I see it now under bug

**Comment by jonpas** [comment]
Reopen with a filled out template if still a problem.
