### ISSUE TITLE
Why are the keybinds not in the documentation?

### ISSUE THREAD

**Issue by jeremysmitherman** [IDI-Systems/acre2#1183]
**Is your enhancement related to a problem?**
There seems to be no clear place in the documentation showing the default keybinds

**Solution you'd like:**
The keybinds to be in an easily accessible, easy to find place in the docs

**Comment by jonpas** [comment]
> Why are the keybinds not in the documentation?

Defaults are in the game. What is the use case of having them in documentation as well?

**Comment by jeremysmitherman** [comment]
I don't see them in game options, and there's no keybinds in addon options, sorry to ask a dumb question but what am I missing here?

**Comment by jonpas** [comment]
When you are loaded into a mission: `Controls -> Configure Addons -> [dropdown] ACRE2`

**Comment by rautamiekka** [comment]
> I don't see them in game options, and there's no keybinds in addon options, sorry to ask a dumb question but what am I missing here?

Have you missed the mentioned `Controls` menu all this time you owned the game ? Or did you overlook the possibility of ACRE binds in there ? TBF, I've done similar things, so I know what it's like, which ain't helped by the similar menus having same wordings.

**Comment by jonpas** [comment]
Closing as apparently solved.
