### ISSUE TITLE
radios on players not showing up in ace

### ISSUE THREAD

**Issue by malfalcons** [IDI-Systems/acre2#1188]
**Mods (complete and add to the following information):**
- all mods are in the html  found here (https://github.com/malfalcons/arma3-rtp)

**Description:**
I have an issue where personal radios are not coming up at all when they are on a player it doesn't come up with ace or anything  when we open the inventory they are there, and it does it with all the radios even the lr radio that you carry. radios in vics work fine though.  I test it through eden multiplayer and with this code in in obj int in eden and it runs fine but i move it to my dedicated server and it doesn't do anything.
waitUntil { ([] call acre_api_fnc_isInitialized) };
[(["ACRE_PRC152"] call acre_api_fnc_getRadioByType), 2] call acre_api_fnc_setRadioChannel;

**Steps to reproduce:**
i have  provided the mission file  as well (https://github.com/malfalcons/arma3-rtp)
**Expected behavior:**
for the personal radios to come up in ace interact 

**Where did the issue occur?**
- Dedicated 
**Log Files:**
- https://github.com/malfalcons/arma3-rtp

**Comment by jonpas** [comment]
Looks like a mod conflict or something. Please fill out the issue template as specified, with version of Arma being used.

Also test with CBA, ACE and ACRE alone.

```
Suspending not allowed in this context
Error in expression <#line 0 "/idi/acre/addons/api/fnc_isInit>
  Error position: <#line 0 "/idi/acre/addons/api/fnc_isInit>
  Error Generic error in expression
File /idi/acre/addons/api/fnc_isInitialized.sqf..., line 0
Error in expression <;
(acre_sys_radio_radioIsBaseClassCache setVariable [_radio, _isBaseClassRadio])>
  Error position: <setVariable [_radio, _isBaseClassRadio])>
  Error Reserved variable in expression
File /idi/acre/addons/sys_radio/fnc_isBaseClassRadio.sqf..., line 26
Error in expression < };
(acre_sys_radio_radioBaseClassCache setVariable [_radio, _baseClassRadio]);
>
  Error position: <setVariable [_radio, _baseClassRadio]);
>
  Error Reserved variable in expression
File /idi/acre/addons/sys_radio/fnc_getRadioBaseClassname.sqf..., line 27
```

**Comment by malfalcons** [comment]
So it was a mod conflict dzn extended jamming and ace compats for zuse enhanced and rhs was causing the issue i didn't think it could of been a mod since it was working fine when i would host with all of those mods on my comp
