### ISSUE TITLE
Unable to add racks to objects

### ISSUE THREAD

**Issue by Saarine-E** [IDI-Systems/acre2#1195]
**Mods:**
- **Arma 3:** `2.08.149135 profiling branch`
- **CBA:** `3.15.6`
- **ACRE2:** `2.9.1.1045`
- **ACE3:** `3.14.1`

**Description:**
Adding racks and radios to objects seems to no longer function.

**Steps to reproduce:**
1. Go to 3den and place an object, along with a unit to play as.
2. In the objects init field, put in the code that's worked for me before:
`this call acre_api_fnc_initVehicleRacks;
[this, ["ACRE_VRC103", "Upper Dash", "Dash", false, ["external"], [], "ACRE_PRC152", [], ["intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;`
Alternatively, try the code provided [on the documentation](https://acre2.idi-systems.com/wiki/frameworks/vehicle-racks#assigning-racks-mid-mission-or-to-non-enterable-vehicles):
`[this, ["ACRE_VRC103", "Upper Dash", "Dash", false, ["external"], [], "ACRE_PRC117F", [], ["intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;`
3. Test the mission in multiplayer and attempt to interact with the radio rack on the object. There should be no radio interactions available.

**Expected behavior:**
A rack with a mounted radio should appear in the interaction menu and be usable.

**Where did the issue occur?**
- Editor (Multiplayer)

**Additional context:**
The first code has worked for me in the past (though it was 9 months ago), but no longer functioned when I tried to use it now. Other functionality is normal, such as racks on vehicles that have them by default (the Hunter MRAP for example).

**Comment by Drofseh** [comment]
Works fine for me. Be careful where you are executing the functions, they are server only. You will also need to re-initialize the racks after you add them.

Here is an example of code for an objects init field, removing some racks and replacing them with a different type:
```
if (isServer) then {
    [
        {
            private _vehicle = _this select 0;

            [_vehicle, {}] call acre_api_fnc_initVehicleRacks;

            private _vehicleRacks = [_vehicle] call acre_api_fnc_getVehicleRacks;

            for "_i" from (count _vehicleRacks) - 1 to 0 step -1 do {
                [_vehicle, _vehicleRacks select _i] call acre_api_fnc_removeRackFromVehicle;
            };

            [_vehicle, ["ACRE_VRC64", "Radio Set - Alpha", "Set A", false, ["driver","copilot"], [], "ACRE_PRC77", [], ["Intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;
            [_vehicle, ["ACRE_VRC64", "Radio Set - Bravo", "Set B", false, ["driver","copilot"], [], "ACRE_PRC77", [], ["Intercom_1"]], false, {}] call acre_api_fnc_addRackToVehicle;

            _vehicle setVariable ["Dro_customRacksAdded", true, true];
        },
        [this],
        0.1
    ] call CBA_fnc_waitAndExecute;

    [
        {(_this select 0) getVariable ["Dro_customRacksAdded", false]},
        {[(_this select 0), {}] call acre_api_fnc_initVehicleRacks},
        [this]
    ] call CBA_fnc_waitUntilAndExecute;
};
```

**Comment by Saarine-E** [comment]
Ah, allright thanks. So it was just me not knowing how to use scripting. Unfortunate that there aren't really places to ask for help with this stuff, People in general arma scripting communities seem to all use TFAR so they can't help with ACRE specific stuff, and the few that use ACRE never touch it in these kinds of ways.

But yeah, since it was just my ineptitude with code as opposed to an actual bug, I'll close this.

**Comment by Drofseh** [comment]
> Unfortunate that there aren't really places to ask for help with this stuff

Join the ~~[Ace3 Slack](https://slackin.ace3mod.com/)~~ Ace3 Discord, there is a channel dedicated to Acre2 there.

**Comment by jonpas** [comment]
> that use ACRE never touch it in these kinds of ways.

You're just in the wrong place. :D
