### ISSUE TITLE
Is possible to use a table radio not owned by someone ? 

### ISSUE THREAD

**Issue by osfrance** [IDI-Systems/acre2#1196]
Hi, I'd like to know if it's possible to create a new object radio that can be usable without owned by someone ? 

(tipically a Radio AN/PRC-117F on a table that can be used with a headset or a speaker, that can be frequency tuned, mast antenna unpluggable ...)

Thanks for your answer 👍

**Comment by Drofseh** [comment]
Please fill out the issue template next time.

It wouldn't look like a PRC117, but if an object supports Ace interaction then I think you should be able to add a radio rack with external access.
This code in object init should do it, but I haven't tested it.

```
if (isServer) then {
    [
        {
            private _vehicle = _this select 0;

            [_vehicle, ["ACRE_VRC103", "RadioName", "RadioNameShort", false, ["external"], [], "ACRE_PRC117F"], false, {}] call acre_api_fnc_addRackToVehicle;

            _vehicle setVariable ["Dro_customRacksAdded", true, true];
        },
        [this],
        0.1
    ] call CBA_fnc_waitAndExecute;

    [
        {(_this select 0) getVariable ["Dro_customRacksAdded", false]},
        {[(_this select 0), {}] call acre_api_fnc_initVehicleRacks},
        [this]
    ] call CBA_fnc_waitUntilAndExecute;
};
```

**Comment by osfrance** [comment]
No sorry the script don't work, I think the function acre_api_fnc_addRackToVehicle don't work with objects other than vehicles ...

**Comment by Drofseh** [comment]
sorry, in my haste I missed a couple of parameters.

try just `[this, ["ACRE_VRC103", "RadioName", "RadioNameShort", false, ["external"], [], "ACRE_PRC117F", [], []], true, {}] call acre_api_fnc_addRackToVehicle;` in the object init.
I've confirmed that will work

**Comment by osfrance** [comment]
Thanks ! it's work with vehicles, but not with other objects ...

**Comment by Drofseh** [comment]
Pretty much all objects (actual vehicles, buildings, walls, tables, chaires, other props, etc) in Arma are vehicles, as in they are a subclass of CfgVehicles.
What is the object you're trying to add it to?
The object you're using might not support extended event handlers needed for Ace3 and Acre2.

**Comment by osfrance** [comment]
Hi, I've tried with many objects (computer, table...) but it's work only with vehicle... 
What type of object you've used ?

**Comment by TACHarsis** [comment]
I think the issue is solved here?

https://github.com/IDI-Systems/acre2/issues/1195

**Comment by Drofseh** [comment]
> I think the issue is solved here?
> 
> #1195

No, it is not.

**Comment by TACHarsis** [comment]
> > I think the issue is solved here?
> > #1195
> 
> No, it is not.

Not? In the other issue you said it works.
What's different there and here?

**Comment by Drofseh** [comment]
> > > I think the issue is solved here?
> > > #1195
> > 
> > 
> > No, it is not.
> 
> Not? In the other issue you said it works. What's different there and here?

The issue here is that the objects they are trying to add it to don't support it.

**Comment by jonpas** [comment]
More/better API for this could be added, but this issue is not on-topic for that.
