### ISSUE TITLE
DayZ SA support

### ISSUE THREAD

**Issue by KRDucky** [IDI-Systems/acre2#1199]
**Is your feature request related to a problem?**
It would be nice to see DayZ SA support. It is unclear if ACRE2 will work with DayZ SA given the Enfusion engine is being used.

**Comment by jonpas** [comment]
There are no plans at this moment. I don't see it easily happening with ACRE2 as it's an entirely different platform to begin with.

**Comment by PabstMirror** [comment]
IIRC dayzsa doesn't support dll extensions, so it may not be possible
