### ISSUE TITLE
Arma 3 crashing when initializating acre2 in game world.

### ISSUE THREAD

**Issue by Poulern** [IDI-Systems/acre2#120]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACRE2 Version:** `2.3.0.915` (stable)

**Mods:**
- `@CBA_A3`
- `@acre2`

**Description:**
- Attempting to load any scenario will crash the game. Singleplayer, MP, Arsenal. Only place where it doesnt happen is in 3den and 3den arsenal. Seems to be a .dll issue based on the rpt. 

**Steps to reproduce:**
- Load any scenario, any sort of initialization of acre will crash arma 3. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
-  [rpt](https://gist.github.com/Poulern/afc4dde3fcca3119cf1e4d361dff836e) and [extension log](https://gist.github.com/Poulern/2466513717d4ffa8961ed3adcf9bb8be)

**Comment by jonpas** [comment]
No a DLL problem, that message at the end is normal in Arma and not an error. You must have something else going on.

**Comment by Poulern** [comment]
I have no idea what I should do to try to isolate it further. I know the mod is physically loading and i can use TFR and ACE3 just fine without any issues. Ive turned off anything that might block it further(Windows 10 defender), running anything arma 3 and ts as admin. Its happened with different versions of acre2(you can see in the ext log about early october and the same issue is happening then, sadly i dont have any more details about version of acre2 etc.)

**Comment by Sniperhid** [comment]
Have you ever had ACRE2 since 2.2.0.904 load okay?

**Comment by Poulern** [comment]
Never has ACRE2 loaded in any form. Arma 3 wouldn't load in earlier versions unless -world=empty(ofc thats not the case anymore). I've only tried acre2 twice though(since we use TFR but are looking into switching).

**Comment by Sniperhid** [comment]
Well from your acre_dll.log it seems ACRE fails to finish the PBO indexing. Typically acre_dll.log looks something like:
```2016-11-29 23:37:51,613-{INFO }- ACRE Loaded
2016-11-29 23:37:51,618-{INFO }- Generating PBO List
2016-11-29 23:37:55,262-{INFO }- PBO Index complete
2016-11-29 23:37:56,048-{INFO }- Map Loaded
```

In the past we had issues with Tobi EyeX interfering with ACRE2's loading of the pbo index. Are you running Tobi EyeX/any other periphals?

**Comment by Poulern** [comment]
Sorry for late response, yeah this was the issue, you guys should include it in the troubleshooting somewhere because I couldn't find that anywhere on the googles.

**Comment by jonpas** [comment]
It's actually not an ACRE2 issue only, impacts other extensions too.

**Comment by dfr1238** [comment]
my friend fix it by close mouse application,hope is help
