### ISSUE TITLE
Unable to parse map KHE SANH

### ISSUE THREAD

**Issue by BEAST-556** [IDI-Systems/acre2#1200]
Hi

**Mods (complete and add to the following information):**
- **Arma 3:** current stable (steam)
- **CBA:** current stable (steam)
- **ACRE2:** `2.9.1045` current stable (steam)
- **SOG CDLC** current stable (steam)
- **ACE:** current stable (steam)

**Description:**
ACRE error message after starting a mission - unable to parse map on KHE SANH

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Additional context:**
it seems to work fine with the error - as the error said it uses the "arcade" values

**Screenshots:**
https://i.imgur.com/N1RRrPA.png

**Comment by jonpas** [comment]
You need to load the `optionals/@acre_sys_sog` compatibility (also separately published on Workshop).
