### ISSUE TITLE
Possible to use modules via script?

### ISSUE THREAD

**Issue by aebian** [IDI-Systems/acre2#1201]
Hi all, 

This is neither a bug nor an FR, but the docs don't do justice and since the ace3public slack has no channel for acre2 I post here. 
Is it possible to use ACRE2 modules via scripting?

I tried this and it does not work:

```
_acre2Group = createGroup sideLogic;
"acre_api_basicMissionSetup" createUnit [[0,0,0], _acre2Group, "this setVariable ['BIS_fnc_initModules_disableAutoActivation', true, true];this setVariable ['DefaultRadio',"",true];this setVariable ['DefaultRadio_Two',"",true];this setVariable ['DefaultRadio_Three',"",true];this setVariable ['DefaultRadio_Four',"",true];"];
```

Basically what I want is to stop the 343 distribution via scripting. 

Arma 3 Version: Using A3 devbranch

Thanks.

**Comment by Drofseh** [comment]
There is an `#acre2` channel in the ace3public slack, you just have to join it

**Comment by aebian** [comment]
Ah thanks, I missed that.
