### ISSUE TITLE
Conflict with Cytech 

### ISSUE THREAD

**Issue by hawkbat05** [IDI-Systems/acre2#1203]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.08.149102 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.6.211004 stable` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.9.1.1045 stable` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
When the [Cytech Core Assets](http://steamcommunity.com/sharedfiles/filedetails/?id=2764686098) and [Cytech Underground Map](http://steamcommunity.com/sharedfiles/filedetails/?id=2764740492) mods are loaded, ACRE2 radios do not show up in inventories and no player to player audio (direct or radio) is transmitted.

**Steps to reproduce:**
- Load Cytech Core Assets and Cytech Underground
- Start the built-in Altis escape map

**Expected behavior:**
All players will have radios (343 by default) and direct voice and radios will function.

**Actual behavior:**
Only the host will have a radio. All other players will have no radios and can't communicate over voice.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Log Files:**
- [CytechLoaded.rpt](https://gist.github.com/hawkbat05/40a93f246f9ee9e8153fecab10549c9b#file-acre2bugcytechloaded-rpt)
- [CytechUnLoaded.rpt](https://gist.github.com/hawkbat05/40a93f246f9ee9e8153fecab10549c9b/raw/5849fc2d04d2ed27a0fa38653e73cf3b6d93b4b5/ACRE2BugCytechUnloaded.rpt)
- [acre2_plugin.log](https://gist.github.com/hawkbat05/40a93f246f9ee9e8153fecab10549c9b/raw/3ccce75227d0c2034eb9bf1d7ce5fb035af3113f/acre2_plugin.log)

**Additional context:**
Noticed in the client logs that normally we would see:
> 23:08:44 CallExtension loaded: ACRE2Arma (F:\Steam\steamapps\common\Arma 3\!Workshop\@ACRE2\ACRE2Arma_x64.dll) [2.9.1.1045]
> 
> 23:08:44 [ACRE] (sys_io) INFO: Pipe opened.
> 23:08:44 [ACRE] (sys_core) INFO: Loading Map: \A3\map_Altis\Altis.wrp with radio signal code 6
> 23:08:44 [CBA] (xeh) INFO: [20835,214.942,0] PostInit finished.
> 23:08:44 [ACRE] (sys_core) INFO: AI Detection Activated.
> 23:08:44 [ACRE] (sys_signal) INFO: Using radio propagation model: LOS Multipath
> 23:08:44 [ACRE] (sys_data) INFO: Data Sync Requested.
> 23:08:44 [CBA] (versioning) INFO: [20836,215.012,0] VERSIONING_SERVER:cba=3.15.6.211004, acre=2.9.1.1045
> 23:08:44 [ACRE] (sys_data) INFO: Data Sync Received: 0.0507813KB (0.365997s).
> 23:08:44 [ACRE] (sys_data) INFO: Data Processing. 0 pending events, 0 pending data updates.
> 23:08:44 [ACRE] (sys_data) INFO: Data Sync Complete.
> 23:08:46 [ACRE] (sys_core) INFO: Map Load Complete: \A3\map_Altis\Altis.wrp with radio signal code 6
> 23:08:46 [ACRE] (sys_core) INFO: Version information. Plugin: 2.9.1.1045 - Client: 2.9.1.1045 - Server: 2.9.1.1045

With the Cytech mods running the data sync does not complete:
> 23:03:40 CallExtension loaded: ACRE2Arma (F:\Steam\steamapps\common\Arma 3\!Workshop\@ACRE2\ACRE2Arma_x64.dll) [2.9.1.1045]
> 
> 23:03:40 [ACRE] (sys_io) INFO: Pipe opened.
> 23:03:40 [ACRE] (sys_core) INFO: Loading Map: \A3\map_Altis\Altis.wrp with radio signal code 6
> 23:03:40 [CBA] (xeh) INFO: [22793,261.225,0] PostInit finished.
> 23:03:40 [ACRE] (sys_core) INFO: AI Detection Activated.
> 23:03:40 [ACRE] (sys_signal) INFO: Using radio propagation model: LOS Multipath
> 23:03:40 [ACRE] (sys_data) INFO: Data Sync Requested.
> 23:03:44 [ACRE] (sys_core) INFO: Map Load Complete: \A3\map_Altis\Altis.wrp with radio signal code 6

When Cytech is loaded the player hosting the server never sees a log entry for receiving the data sync request. Normally they'd see:
> 23:08:40 [ACRE] (sys_data) INFO: Data Sync for acre_player: myUser [2:57,3] - 0.0400391KB

**Screenshots:**
N/A

**Comment by PabstMirror** [comment]
Something in that mod is wrecking loading times 
and preventing cba postInit from being called until after the mission has started

host client
```
PreInit Starts
// Takes 30 second to load, wtf??
// Have to click continue on map screen
PostInit Starts
T-31sec call addPublicVariableEventHandler
```

client
```
PreInit Starts
PostInit Starts (on the map like normal)
T-25sec acre_sys_data_fnc_syncData - sending pubVar
```

the client sends the pubVar before the server is listening
this is just playing on stratis; Normally it takes my machine ~4 seconds to load

So contact the map makers and tell them to not break CBA

**Comment by hawkbat05** [comment]
Thanks for having a look. I'll reach out to the Cytech mod author(s).

Edit: Adding link to Cytech bug report: [https://steamcommunity.com/workshop/filedetails/discussion/2764686098/3185738591086335381/#c3267935171648961534](https://steamcommunity.com/workshop/filedetails/discussion/2764686098/3185738591086335381/#c3267935171648961534)

**Comment by jonpas** [comment]
I will close this as it's Cytech's fault by breaking CBA.
