### ISSUE TITLE
Individual power adjustments for radios

### ISSUE THREAD

**Issue by Mattifine** [IDI-Systems/acre2#1206]
**Is your feature request related to a problem?**
My Community would like to use the AN/PRC-117F as a unlimited range radio, but still be used the interference and rage calculation features on the short range AN/PRC-152 and AN/PRC-343. This is so that all of our leaders can stay in contact over the entire map but the squad radios still get obstructed by buildings, hills and distance. Like we are fighting in kavala and the SQL is calling for CAS that is positioned at the air field and we can't contact them. IF we use arcade mode there is no point in carrying a LR radio since you can just use a SR.

**Solution you'd like:**
A new addon option that let's you adjust the strenght of individual radio types.

**Alternatives you've considered:**
I can't think of any thing

**Additional context:**
I can't script and don't even get me started on mods (From what I have gathered that can be done with mods). Doing it with scripts would be a problem BC my unit lets people make their own missions and if it is a script if would need to be done every time.

**Comment by rautamiekka** [comment]
If all else fails, you can have the [ground spikes with masts](https://acre2.idi-systems.com/wiki/user/ground-spike-antenna) in places like the airfield, or a high-ground central location that might work as a message relay center (a Player gets messages to pass on), that ppl stay connected to.

^ The tower boosts the output power, and being much taller also helps. The wiki says "to 20W", but I've my suspicions about that. Another is that a vehicle with a rack is used cuz depending on the used infantry radio it doubles or triples the output power; some vehicles even have an empty rack you can mount your radio to if it's some incompatible one.

^ If possible, have the whole 1-piece (or the 2 pieces used to make it) in someone's backpack, it'll make much harder to progress and contact for the squad, though.

**Comment by jonpas** [comment]
Settings for this won't be added, but a [custom signal processing](https://acre2.idi-systems.com/wiki/frameworks/custom-signal-processing) or preset data field `power` can be used.
