### ISSUE TITLE
Add meta.cpp files to optionals

### ISSUE THREAD

**Issue by crazyirish93** [IDI-Systems/acre2#1209]
**Is your enhancement related to a problem?**
Currently, the acre2 optional's published on the steam workshop are missing meta.cpp and mod.cpp. This means that the mods cannot be auto-downloaded through the Arma 3 launcher server browser.

**Solution you'd like:**
Update respective optional mods so they have at least the meta.cpp file.

https://community.bistudio.com/wiki/Arma_3:_meta.cpp

https://steamcommunity.com/sharedfiles/filedetails/?id=2450980898&searchtext=acre2+sog
EXAMPLE:
/// Version of meta.cpp content
protocol = 1;

/// Steam Workshop item id
publishedid = 2450980898;

/// Steam Workshop item name
name = "ACRE2 S.O.G. Prairie Fire Compatibility";

/// Time of last update of the Steam Workshop Item (in .NET Framework time format)
timestamp = 9876432101234567890;

/// Mod hash that is send by the server to the client instead of calculated hash)
hashOverride = 1234567890;

**Comment by jonpas** [comment]
Agreed, pull requests wanted!
