### ISSUE TITLE
SEM 52 - Problem with set Frequency 

### ISSUE THREAD

**Issue by Pictureclass** [IDI-Systems/acre2#121]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.2` (stable )
**ACRE2 Version:** `2.3.0.915` (dev)

**Mods:**
- `@CBA_A3`
- `@acre2`

**Description:**
- Generaly, when we setup a frequency on the SEM52 whitch is not integer ( 49.000) then not everyone on the same frequency can hear everyone (Group of 8 Players).
Our guess is, that its diffrent, how you set the frequence. Example
Players should set the 49.975. The players which go up to 50.000 and go down one step could hear everyone with the workflow. But they cannot hear players which go to 49.000 and go the steps up.

**Where did the issue occur?**
- Dedicated

**Comment by Sniperhid** [comment]
I will look into this!

**Comment by Sniperhid** [comment]
Resolved. Thanks for the report!
