### ISSUE TITLE
Compatibility mod requirements are not well communicated to the end user

### ISSUE THREAD

**Issue by nh-oriki** [IDI-Systems/acre2#1214]
**Is your enhancement related to a problem?**
Yes - Users attempting to use ACRE2 with ArmA 3 CDLC may encounter issues with ACRE that are unclear and difficult to resolve.
Currently, if you launch ArmA with Western Sahara and ACRE2 enabled, you'll get an error on the menu:
`"WARNING: acre requires acre_sys_ws (@compat_ws) at version [2,10,0,1050] (or higher). You have none."`
Trying to google out this error is pretty difficult, and unless you collect that "ws" stands for "Western Sahara", this message can leave the player without any leads to go on. SOG Prairie Fire generates a similar message for its respective compatibility mod.

Compatibility mods are not mentioned on the mod's [Workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=751965892), in the mod's [README](https://github.com/IDI-Systems/acre2/blob/master/README.md), or in the mod's [installation guide](https://acre2.idi-systems.com/wiki/user/installation) in either the main or troubleshooting sections. While they are listed on the ACRE_Team workshop, it's a bit kludgy to get to this page because of how Steam's site is laid out.

**Solution you'd like:**
The mod should make clearer that the CDLC Compatibility mods exist, and troubleshooting information should be added to help players attempting to resolve issues that arise from missing compatibility mods. While getting rid of compatibility mods entirely would be preferable, making clear which ones are available would make things much easier.

If possible, displaying an ingame message or opening the appropriate Workshop page would also be nice additions, but there are simpler changes to point players in the right direction that don't require any code work.

**Alternatives you've considered:**
None - these are primarily quality of life changes that would be reflected in places where the mod is available. ie the Steam Workshop page and the documentation.

**Additional context:**
ACE3 has a similar setup and just stuck a bunch of links to their compat mods at the end of [their workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=463939057).

**Comment by jonpas** [comment]
I've added a "Compatibility" section with a short description and links to the compatibility packages on the Workshop page.

We can add something to our documentation as well, contributions welcome!
