### ISSUE TITLE
Add The Bra (S.O.G) compatibility

### ISSUE THREAD

**Issue by Verstand3n** [IDI-Systems/acre2#1216]
Description:
When starting a mission with ACRE Enabled on the new S.O.G DLC map "The Bra" it comes up with an error and says it was unable to parse the map and it is going to use arcade signals
Steps to reproduce:

- Enable S.O.G DLC, CBA, ACRE2, ACRE2 SOG Compat
- Go to The Bra map
- Click Play
- See Error

Expected behavior:
no error message

Where did the issue occur?
Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

[hope I did not overlook an already existing issue for this]

**Comment by jonpas** [comment]
#1211
