### ISSUE TITLE
Racks in Tank-derived vehicles don't have "use" action

### ISSUE THREAD

**Issue by maxcloutier13** [IDI-Systems/acre2#1222]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10.149954` 
- **CBA:** `3.15.8.220912` 
- **ACRE2:** `2.10.0.1050` 
- **ACE** `3.15.2`

**Description:**
The racks in tank-derived vehicles do not show the "use" action so they are unusable. Affects the racks that are

**Steps to reproduce:**
- I start the game. Open editor->Stratis.
- Spawn an ammo bearer 
- Spawn Empty Badger IFV 
- Get in Driver 
- Ace-Interaction->Rack

**Expected behavior:**
- I can see the rack (VRC-103) and the mounted radio (117F) but there is no option to "use" it. Only option shown is "unmountable". 
- Merkava does the same (which is where my "tank-derived" comment comes from).
- Sanity-check: Spawn a MH6-Littlebird. I see 2 racks (VRC-103) and both mounted with 117F's but in this case I see the option to "use" and even a "use all" on the dash menu.  Works exactly as expected. 
- Sanity-check2: Works fine in a M-ATV so MRAP-derived are good too. I can mount a 152 on the first rack and the 117f in the vrc-103 of rack 2 shows the "use" function and works as expected. 
- 
**Where did the issue occur?**
- Singleplayer/dedicated

**Log Files:**
https://pastebin.com/DY7B84Zn

**Additional context:**
I noticed the problem while trying to edit/customize the rack layout in my clan vehicles. Got frustrated at things not working as expected and ended up trying to remove everything and testing with vanilla vehicles. They all seem to behave the same wrong way. Looking quickly at the class modifications coming from acre's code I don't see an obvious problem with the tank classes, but it's definitely not working as intended for me. 

**Screenshots:**
Missing option in badger
https://postimg.cc/MMQWX4bH
Available option in mh-6
https://postimg.cc/kVZJJ9SL

**Comment by Drofseh** [comment]
Connect to it through the vehicle's intercom.

**Comment by maxcloutier13** [comment]
> Connect to it through the vehicle's intercom. 

With the "work" knob? The documentation is not exactly clear about the relationship between the intercom and the rack/radios beyond the crew/pax comms. The change in behavior is confusing.

**Comment by Drofseh** [comment]
> > Connect to it through the vehicle's intercom.
> 
> With the "work" knob? The documentation is not exactly clear about the relationship between the intercom and the rack/radios beyond the crew/pax comms. The change in behavior is confusing.

Yup with the work knob
https://acre2.idi-systems.com/wiki/user/vehicle-racks#vehicle-intercom

**Comment by maxcloutier13** [comment]
Oooh in the rack page ;o) Thanks.  The intercom page is very scarce in details about that, with no mention of the word "rack" at all. I never really drive but I was trying to streamline the racks in my group's vehicles in preparation for a change in settings that will require the use of long-range radios... I want my less trained infantry to be able to use the LR radio in case of emergency. Guess what I need is to set the work knob on rack A by default... 
Thanks again ;o)
