### ISSUE TITLE
Radios stop working during missions. Individuals 10 meters away cannot hear one another on the radios. 

### ISSUE THREAD

**Issue by GallopingGepard** [IDI-Systems/acre2#1224]
**<html>
<body>

CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
-- | -- | --
Operation TREBUCHET | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=769440155
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
A2 Declassified: Fireteam Zulu | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1659590037
Operation TREBUCHET First Contact | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1572627279
Operation TREBUCHET ACE Compat | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1267657613
ACRE2 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=751965892
ADV ACE-CPR (Pike Edition) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1957746437
19th Fleet Armor Mod | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2047587607
OPCAN 3.0 By Wolf Of Tribute Modding (formerly LM) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2016312756
A2 Declassified: Specialized Ordnance | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1933244792
Ace Medical Assistant [Simple Medical Mod] | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1677267612
BackpackOnChest | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=820924072
Freestyles Crash Landing | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2231150238
No More Aircraft Bouncing | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1770265310
DUI - Squad Radar | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1638341685
ITC Land Systems | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1388192893
Gruppe Adler Trenches | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1224892496
Operation TREBUCHET First Contact ACE Compat | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1572642262
Operation Trebuchet+ | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1763651451
KLPQ Music Radio | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1241545493
Advanced Rappelling - Reworked | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2073987581
M224 60mm Mortar (ACE) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2472780935
Eden Extended Objects | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=882231372
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - Maps | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
CUP Terrains - CWA | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=853743366
Interiors for CUP | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1883956552
Eden Objects | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=686802825
CH View Distance | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=837729515
Em_Buildings | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=671539540
Immersion Cigs | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=753946944
PLP All in One | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1960024802
RnT Trenches - Standalone | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1983487115
3den Enhanced | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=623475643
WMO - Walkable Moving Objects | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=925018569
Arma 3 Non Editor Objects | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1736812763
Enhanced Movement | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
JM's Structures | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1876589191
Phantom hawks vanilla vehicle addons All In One Pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1366067990
GEARSOC - Deluxe Edition | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1299068883
cTab NSWDG Edition | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2511318948
Rested Weapon Movement | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1181731794
VIDDA \| LEGACY VERSION | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1282716647
TAC VESTS | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=779568775
12th Marine Division Assets | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=2350072953
Advanced Urban Rappelling | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=730310357
Advanced Sling Loading | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=615007497
Ladder Tweak | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1803586009
Foe Hammer Helmet | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2745448736
LDF Desert Retexture | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1919803068
Max Women Soldiers | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2480118782
The Carver Findings | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2598549968
G.O.S Al Rayak | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=648172507
G.O.S. N'ziwasogo v2 APEX | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2084904847
Breach | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2820127143
Defoliating Munitions | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2817306300

</body>
</html>**

**Arma 3:** 
Launcher version: 1.5.149879
Game version: 2.10.149954
Branch: main 

**CBA:** `v3.15.8.220912` 

**ACRE2:** `2.10.0.1050 `

**Description:**
During several missions, our unit has experienced complete radio blackouts. A player could be standing next to another player on completely flat ground yet is unable to hear one another. 

**Steps to reproduce:**
40+ players on a dedicated server, playing a scripted mission with 200+ AI. Perform radio checks periodically until issue appears. 

**Expected behavior:**
For the radio system to be clear and readable at realistic distances when terrain interference is not a problem.

**Where did the issue occur?**
October 19th 2022 @21:00 GMT - 24:00 GMT
October 29th 2022 @21:00 GMT - 24:00 GMT
November 5th 2022 @21:00 GMT - 24:00 GMT
November 12th 2022 @21:00 GMT - 23:00 GMT

**Log Files:**
Uploaded to Drive due to length of the text: https://drive.google.com/file/d/1IC3YLqTs7p8tS-a4cM-NCMf_3mWoWl_u/view?usp=share_link

**Additional context:**
Feel free to reach out to us on Discord: 
Unit lead: Schultz#0012
Developer: SerBonsie#0001

**Screenshots:**
Various videos - will link as they become available.

**Comment by mjc4wilton** [comment]
Does your mission file have any calls to `acre_api_fnc_copyPreset` or `acre_api_fnc_setPreset`? Trying to determine if this is related to #1056

**Comment by BSherb** [comment]
Another question is how loadouts are handled, my unit just ran into this problem recently.
If you're saving loadouts per player and reapplying them on respawn, make sure to include acre_api_fnc_filterUnitLoadout to prevent duplicating ID's

If not, feel free to ignore.

**Comment by jonpas** [comment]
No answers to above questions provided, so closing this as we have other issues already open about the same thing with more information.
