### ISSUE TITLE
Multiple Channel Communication with one radio

### ISSUE THREAD

**Issue by rco-titus** [IDI-Systems/acre2#1225]
**Is your feature request related to a problem?**
Not entirely related to a problem. Communication has become a hassle with acre when being in a large team with a lot of counterparts. To keep communication clear we have different channels that everyone operates on. In order to communicate to said counterparts we need to change frequencies or have additional radios to communicate to these sections. which carrying multiple radios becomes a problem given the players inventory.

**Solution you'd like:**
As the radios are supposed to simulate their real world counterparts as per the ACRE2 Documentation, I would like a feature to be added that will allow for communication and monitoring on multiple radio channels, the ability to program which channels are being monitored etc. (Similar to TFAR), as these features are apart of the real world counterparts.

**Alternatives you've considered:**
I have considered using TFAR but it lacks the realism and experience I enjoy with ACRE2, there are a lot more features and better designed features with ACRE that I don't want to sacrifice

**Additional context:**
Reafference with TFAR goes in hand with their ability to utilize the number pad to select different channels and frequencies you are monitoring as well as quickly switching to a given monitored channel and communicating over it.

**Comment by jonpas** [comment]
With a solid command structure and radio network, you should never need more than 2 radios (3 at most). What is your setup that requires more?

If you need to switch channels quickly, there are keybinds available and pre-bound.

> As the radios are supposed to simulate their real world counterparts as per the ACRE2 Documentation, I would like a feature to be added that will allow for communication and monitoring on multiple radio channels ... as these features are apart of the real world counterparts.

No radios currently modelled in ACRE support dual watch or multi-PTT features. It is not possible to use multiple channels at once with them. This is not going to get added to radios that should not have it.

**Comment by rco-titus** [comment]
I believe I have misinterpreted this. I'm referring to the frequency hopping feature. it essentially allows for scanning on the given channels. to speak on them you still have to switch your channel you are transmitting on. This feature is on most radios as well but I'm mainly referring to the 152.

Programming this can be found on [B191716 Communication Equipment](https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B191716%20Communication%20Equipment.pdf) page 51 - 52
This is also listed under [SINCGARS](https://en.wikipedia.org/wiki/SINCGARS)

**Comment by jonpas** [comment]
Frequency hopping is a separate thing, would definitely want.
