### ISSUE TITLE
people cant hear me

### ISSUE THREAD

**Issue by boofhead141** [IDI-Systems/acre2#1229]
when using ARCE 2 mod in Arma 3, im set to yelling and when im talking to people they cant hear me or im very quiet when talking.
is this proble that people have had

**Comment by jonpas** [comment]
Can people hear you normally just on TeamSpeak outside of the game?

Fill out the issue template, we can't help otherwise.

**Comment by boofhead141** [comment]
OUT OF GAME IS FINE ITS ONLY WHEN IM USING ARCE THIS HAPPENS

**Comment by jonpas** [comment]
> Fill out the issue template, we can't help otherwise.

**Comment by boofhead141** [comment]
**Mods (complete and add to the following information):**
- **Arma 3 LATEST
- **CBA: LATEST
- **ACRE2: LATEST

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by rautamiekka** [comment]
> * **Arma 3 LATEST
> * **CBA: LATEST
> * **ACRE2: LATEST

That ain't a valid version number; without the actual ones there's no telling.

**Comment by jonpas** [comment]
>> Fill out the issue template, we can't help otherwise.
