### ISSUE TITLE
Transmit Noise/Squelch not Playing when PTT keyed

### ISSUE THREAD

**Issue by BSherb** [IDI-Systems/acre2#1231]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.10.0.1050` [e.g. 2.0.0 stable, commit hash]
- **ACE3:** `3.15.2`
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
Radio squelch when pressing PTT does not play

**Steps to reproduce:**
- Grab radio(s)
- Activate PTT
- No squelch

**Expected behavior:**
The transmit start/end noise to play
**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer 

**Log Files:**
- [Arma3_x64_2023-02-25_09-04-46.log](https://github.com/IDI-Systems/acre2/files/10831383/Arma3_x64_2023-02-25_09-04-46.log)

- [acre_dll.log](https://github.com/IDI-Systems/acre2/files/10831388/acre_dll.log)

**Additional context:**
None

**Screenshots:**
None

**Comment by jonpas** [comment]
See the [Troubleshooting](https://acre2.idi-systems.com/wiki/user/installation#troubleshooting) on our Installation wiki page, and verify `"b64"` is whitelisted on your server (dedicated or self-hosted) as noted.

You won't hear any sounds being played in Singleplayer as Singleplayer will not connect to TeamSpeak.

**Comment by jonpas** [comment]
Assuming fixed due to inactivity.
