### ISSUE TITLE
Documentation for TeamSpeak and Server Admins

### ISSUE THREAD

**Issue by tsal** [IDI-Systems/acre2#1232]
**Is your feature request related to a problem?**
I find it pretty frustrating that administrator documentation is not front-and-center for something that _has a server-side component_.

**Solution you'd like:**
A clear, concise explanation of configuration needed for the TeamSpeak server (channels? channel names? channel passwords?) or how to change them _externally without needing CBA client interactions in-game_.

**Alternatives you've considered:**
Searching everywhere in your documentation. No mention of server configuration or defaults.

**Additional context:**
This really should be a basic thing.

**Comment by jonpas** [comment]
ACRE2 itself does not have any server-side configuration, it is all using CBA. You can set TeamSpeak properties "externally" using the method described on the CBA Wiki: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#userconfig

Apart from that, the only other "server" configuration is general TeamSpeak Server stuff like increasing Anti-Flood limits.

[Configuration](https://acre2.idi-systems.com/wiki/user/installation#configuration) section of our Installation guide contains references to the CBA Settings System, the export/import and how to apply them. It is definitely preferable to export once and then pick and choose - that way you can get all the variables and can't miss any setting.

Documentation for each setting is included in the CBA Settings System as well, there is no separate documentation on it available on our wiki or outside the game (except the source code of course).

As for defaults, you don't need _any_ server configuration for ACRE2 to just work on your TeamSpeak Server.

---

Is there something else you expected to see? We always welcome pull requests. Documentation is important as well, however ACRE2 does not have a lot of manpower behind it, so sometimes documentation lacks behind the actual functionality.

**Comment by tsal** [comment]
> As for defaults, you don't need any server configuration for ACRE2 to just work on your TeamSpeak Server.

In our case, this simply wasn't true. It wasn't moving users as expected. We switched to another mod and it just worked. I wanted to use ACRE2 because client side was significantly easier, but the server side just didn't work for our server / team speak.

I guess what I was looking for was exporting the configuration once, after the server was already running, since that was the only way I could ever get the CBA to show ACRE2 settings. I was hoping there was a list of the variables in the documentation, because I know where the cba settings file itself goes.

I guess I'll close this. thanks.

**Comment by jonpas** [comment]
> In our case, this simply wasn't true. It wasn't moving users as expected.

Channel Switching is also enabled by default, but the small requirement for it to work with default setup is a matching name between Arma 3 Server and a TeamSpeak channel. This is however an optional feature, and would distract from the core basic installation instructions if it were to be included there. Any contributions to documentation are welcome to improve the visibility of it though, as long as it's not distracting from the minimal needed setup.

> We switched to another mod and it just worked.

I don't see how any system can do channel switching without assuming some default values to work against. I guess you mean TFAR, in which case you likely just had Arma 3 Server and a TeamSpeak channel named in a way that works with its defaults.

> I guess what I was looking for was exporting the configuration once

CBA Settings can be exported, that's the easiest way currently.
