### ISSUE TITLE
Add megaphone feature

### ISSUE THREAD

**Issue by hbeni** [IDI-Systems/acre2#1235]
Hi there,
some time ago we played some police missions. For advanced crowd control missions, it would be nice to have some "megaphone" radio item that basicly behaves like direct speech, but with more range and an appropriate sound effect, and, if possible, more directed (so the amplification only works in some kind of sound cone in the viewed direction).

**Comment by jonpas** [comment]
Duplicate of #970.

**Comment by hbeni** [comment]
Not exactly a duplicate - in #1235 it is about a omnidirectional speaker system.
Here, specifically:
> if possible, more directed (so the amplification only works in some kind of sound cone in the viewed direction).
