### ISSUE TITLE
Audio artifacts in TS channel with high(est) bitrate

### ISSUE THREAD

**Issue by A-tG** [IDI-Systems/acre2#1237]
Game and mods (from workshop) are latest versions at the moment. No ACE.
Teamspeak server version: 3.13.7 on Linux
client: 3.5.6
If ACRE's channel Audio codec is set to Opus Music with Quaility 10 for some clients sound is pitched down + crackling.
My input and output devices are all set to 24bit 48khz. I did not had any problems, but other client with 16 bit 44.1khz "Speakers" heard my voice with mentioned artifacts. No problems with Opus Voice Quality 10

I may add recorded example later.

**Comment by PabstMirror** [comment]
It may be caused because the plugin is getting a stereo mix and is expecting a mono.
(it's basically the same as pitch shifting by half)

fix in part of pr #1105

https://github.com/IDI-Systems/acre2/pull/1105/files#diff-5be897ee5ca93830134dd14c08605294f497f78b974eb3d85ed17063f5b2aeeaR50-R57

**Comment by A-tG** [comment]
It sounds like that 
[acre-opus-music-codec-bug.zip](https://github.com/IDI-Systems/acre2/files/11103255/acre-opus-music-codec-bug.zip)
Quality does not matter, only type of codec

**Comment by jonpas** [comment]
> Quality does not matter, only type of codec

Yeah that makes sense. ACRE should be able to handle high bitrates (at least to level provided by TeamSpeak) without an issues, but different codecs, especially ones added later in TeamSpeak's life, may have issues as we are directly interacting with audio data.
