### ISSUE TITLE
ACRE 2 Left ear audio right ear audio 

### ISSUE THREAD

**Issue by RubMyPeaches** [IDI-Systems/acre2#1239]
So I've used ACRE for years and I'm just now realising that when i set two of the same and or different radios to individual ears both said radios will play through both sides of my headset. 

I've tried deleting the mod and reinstalling but that has proved wrong any idea's

**Comment by jonpas** [comment]
This is usually an issue with hardware or virtual surround systems.

**Comment by jonpas** [comment]
If you still experience this after disabling any virtual surround/3D systems, reopen and fill out the template in full.
