### ISSUE TITLE
Tools - GitHub publish tool errors

### ISSUE THREAD

**Issue by Sniperhid** [IDI-Systems/acre2#124]
The Jenkins build script has some issues/areas for improvement.

- [x] Improve the steam publish script to link to the release tag directly?
Perhaps something like:
 ```"steam_changelog": "Version {major}.{minor}.{patch}.{build} - See changelog on github - https://github.com/IDI-Systems/acre2/releases/v{major}.{minor}.{patch}.{build}"```
- [x] tag_name was not valid - see below
```
Creating Github Release...
{'message': 'Validation Failed', 'documentation_url': 'https://developer.github.com/v3/repos/releases/#create-a-release', 'errors': [{'field': 'tag_name', 'resource': 'Release', 'code': 'custom', 'message': 'tag_name is not a valid tag'}, {'resource': 'Release', 'code': 'custom', 'message': 'Published releases must have a valid tag'}, {'field': 'target_commitish', 'resource': 'Release', 'code': 'invalid'}]}
('Github Publish', 'Failed to Create Release')
Error: Publish failed.
```
- [x] manifest.json for release -> destinations -> github -> branch is `release` should be `release-build`

**Comment by jonpas** [comment]
Has been fixed by branch name fix.
