### ISSUE TITLE
vehicle radio rack modules 

### ISSUE THREAD

**Issue by twidjr** [IDI-Systems/acre2#1243]
**Is your feature request related to a problem?**
yes scripts for adding radio racks to vehicles do not work on dedicated servers 

**Solution you'd like:**
a simple plug-and-play module that will purge all radio racks and give mission makers the ability to easily change all settings for the racks (i.e. radio rack, rack name, abbreviated rack name, seats, underlying radio, and intercom you could just combine radio rack and underlying radio) 

**Alternatives you've considered:**
I have tried to use scripts but I'm not an sqf master and it does not work on multiplayer (dedicated server) also I feel it would help a lot of other people with making ops 

**Additional context:**
I have considered using parameters in the vehicle itself like ace3 settings but I feel modules would be less confusing so you can do 1 module for 1 rack and have multiples for each. (depending on how you set it up you can also sync it to multiple vehicles)

**Comment by jonpas** [comment]
There is a bigger thing with Racks API requiring player to initialize etc. There won't be any modules added though, Eden attributes maybe.
