### ISSUE TITLE
TeamSpeak 3 Beta v3.6.0 incompatible API

### ISSUE THREAD

**Issue by Nilia119** [IDI-Systems/acre2#1247]
A Couple of days ago, Teamspeak pushed an Update (I use the beta Channel of TS3 v. 3.6.0), which lead to ACRE (and TFAR) plugins not working anymore due to a Plugin API Update.
Since this would have a massive impact on all ACRE (and TFAR) Users, I therefore wanted to give you a heads-up.
The Beta Updates will come to the normal TS3 Users rather sooner than later and until to this Update it always worked regardless of beta/stable Client.
As a side note: if you use the beta Channel and run to the same problem, you can "switch" back to the stable branch by manually executing the "update.exe" in your TS3 Install directory.
The Update notes:
https://community.teamspeak.com/t/teamspeak-3-client-3-6-0-beta/40515

**Comment by jonpas** [comment]
> ! Plugin API increased to **26 as workaround** for Qt update incompatibility

Great.

---

We likely just need to add API 26 to [supported matrix](https://github.com/IDI-Systems/acre2/blob/a782449066264b68c5b1e2369d7c35e4cb1f97b1/extensions/src/ACRE2Shared/helpers.cpp#L42). Although we don't have 25 specifically named, either it's backwards compatible with 24, or something did actually break in 26.

EDIT: As I've guessed, they changed minimum version to 26, so it is backwards incompatible by default (our plugin will be though).

**Comment by Nilia119** [comment]
Awesome, if it is that easily fixed!

**Comment by jonpas** [comment]
Yeah, nothing we use has changed so it's easy.

**Comment by DeliciousJaffa** [comment]
3.6.0 is now a stable teamspeak release
