### ISSUE TITLE
GM Compatibility issue

### ISSUE THREAD

**Issue by zbigniewpaczynski** [IDI-Systems/acre2#1250]
Сhange AN / VRC-103 to SEM-90 in the Global Mobilization DLC, because SEM-90, because SEM-90 was really used in leopards and other armored vehicles and helicopters in GM, unlike a VRC-103, which was developed much later.
![image](https://github.com/IDI-Systems/acre2/assets/50900928/0e822a98-da2a-4a7c-8f5e-7483a4156e84)

**Comment by jonpas** [comment]
We do not provide direct support for compatibilities. PRs are however welcome to improve it.
