### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by Cutarrow123** [IDI-Systems/acre2#1254]
Acre 2 Installing 2.11.0.1054 for me 
But its installing 2.10.0.1054 for my freind 

I Have no logs 
He's tried auto install/manually re-install wiped all of his stuff and tried again and nothing will work

**Comment by jonpas** [comment]
Describe your issue in more detail. 2.10.0.1054 doesn't and never existed. Include screenshots.

**Comment by Cutarrow123** [comment]
Hey sorry i can't send screenshots because we fixed the issue he had to
wipe everything to do with, Acre 2, and TS on his computer

but i can personally confirm that it showed  2.10.0.1054 as his plugin
version when he shared his screen and i could not hear him on TS or in game

**Comment by jonpas** [comment]
Roger, in the future, provide as much information as possible when you report an issue.
