### ISSUE TITLE
Altis failed to be Parsed by ACRE

### ISSUE THREAD

**Issue by DREBIN692** [IDI-Systems/acre2#1259]
**Mods:**
- **Arma 3:** Stable
- **CBA:** Stable
- **ACRE2:** Stable
-**ACE3** Stable w/o overpressure pbo
-**CUP** Stable
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
When loading into my mission, there is an orange error box that says
ACRE2 Failed to parse the current map
The Current map was/is Altis

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
There to not be an error
I expected it to work out of the box so to speak

**Where did the issue occur?**
- Dedicated

**RPT**
Rpt file from my game
[Arma3_x64_2023-07-12_04-36-21.txt](https://github.com/IDI-Systems/acre2/files/12025807/Arma3_x64_2023-07-12_04-36-21.txt)
RPT File from the server
[arma3server_x64_2023-07-12_02-45-14.txt](https://github.com/IDI-Systems/acre2/files/12025875/arma3server_x64_2023-07-12_02-45-14.txt)

**Screenshots:** 

![20230712035600_1](https://github.com/IDI-Systems/acre2/assets/122871620/13c40cf4-957a-4d16-b3c9-af52b05aa42c)

**Comment by jonpas** [comment]
RPT is required.

**Comment by DREBIN692** [comment]
wait one

**Comment by DREBIN692** [comment]
there you go

**Comment by DREBIN692** [comment]
RPT has been added

**Comment by jonpas** [comment]
You are using Arcade propagation model, correct?

Can you try switching it to one of the others and seeing if you still get the error?

**Comment by DREBIN692** [comment]
will do, once my game loads, the funny thing is, my buddy who was in the server with me, doesn't get the error, and can hear me on local and the radios, but I can only hear him on local

**Comment by DREBIN692** [comment]
it might be due to an error in installation on my end, I did a full reinstall of ts and acre and let acre move the plugins and it seems to have loaded and initialized according to the teamspeak chat window

**Comment by DREBIN692** [comment]
nah, it still fails to propegate for me

**Comment by jonpas** [comment]
You might have an anti-virus or something blocking loading of the map. Everything else seems to check out.
