### ISSUE TITLE
Vehicle Power Amps

### ISSUE THREAD

**Issue by WelshBanana** [IDI-Systems/acre2#1260]
Add a power amp for when radio's are mounted in a vehicle rack and converted into a VRC, there is a power amp option making the total transmitting wattage 50W. This would make more sense for the current distances achievable by the 117F and would add more value to using vehicle mounted radio's.

**Comment by jonpas** [comment]
AN/VRC-103 already increases 117F's power form 20W to 50 W. Other racks boost their respective radio powers as well. Ref. https://acre2.idi-systems.com/wiki/user/vehicle-racks
