### ISSUE TITLE
Zeus - Exiting remote control while the AI character is inside a vehicle breaks racks and intercom

### ISSUE THREAD

**Issue by RM978** [IDI-Systems/acre2#1267]
**Mods**
- **Arma 3:** `2.12.150779`
- **CBA:** `3.15.8.220912`
- **ACRE2:** `2.11.0.1054`
- **ACE3:** `3.15.2`

**Description:**
Zeus remote control - exiting remote control while the AI character is inside a vehicle causes vehicle rack radios and intercom radios to be bugged for the player character and other remotely controlled AI characters.

**Steps to reproduce:**
1. Spawn a vehicle (I tested both Eden editor and Zeus spawning). I spawned a HEMTT truck just to show that it happens, even if the vehicle used to "activate" the bug doesn't need to have a radio nor intercom.
2. Remote control an AI character (both inside a vehicle or spawned outside).
3. Exit remote control while the AI character you control is inside a vehicle.
4. Enter another vehicle (one with a rack radio or intercom radio) as a player character or another AI character.
5. Try to use rack radio (either select the "use" option in the ACE rack radio menu or select work / monitor A on the intercom panel).
6. On the rack radio / intercom UI, the "DASH R/T" text will briefly turn white...
7. ... and then, in the rack radio scenario: the rack radio UI will disappear and reappear after a second. "DASH" text will be gray, and you won't be able to use the radio from the rack;
In the intercom scenario: intercom text UI will disappear and reappear after you close the intercom panel UI. "CREW R/T" text will be white, but "DASH" text will be gray, and you won't be able to use the radio from the intercom / rack.
8. In the brief time while the text is white, you can use the racked radio, but that ability will end the second the text stops being white.

**Expected behavior:**
Exiting remote control of an AI character inside a vehicle should not render rack radios in other vehicles unusable for the player character and other remotely controlled AI characters.

**Workaround:**
- Exit the remote control while the AI character is outside the vehicle to avoid the bug in the first place.

**How to temporarily fix the bug:**
- Enter Zeus mode. Select the AI character with which you activated the bug and put him outside the vehicle. (Killing him inside or destroying / despawning the vehicle won't work and will make the bug unfixable.) You can then put him back inside by clicking and dragging him back into the vehicle.
- Or remote control the same AI character you activated the bug with, exit the vehicle, and leave the remote control.
- Upon again doing the steps to reproduce, the issue will reappear and will work identically.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Log Files:**
- https://pastebin.com/9WuGY0cu
- https://pastebin.com/H3q7v9P1 [I only tested this bug for like 3 last days]

**Additional context:**
- **I can confirm this bug is not only on my end because I asked my friend to reproduce this bug, and it behaved as described here.**
- The bug does not occur after exiting the mission and restarting it, but after doing the same thing, the bug will return.
- Occurrence chance for me (and my friend) when following the aforementioned instructions: 100%
- I didn't have a chance to test if this bug affects anything else besides not being able to use rack radios / intercom radios in vehicles (like, for example, actual intercom communication with other players)

**What I tested and didn't work:**
- Disconnecting from the intercom before exiting the remote control without leaving the vehicle.
- Switching the radio off before exiting the remote control without leaving the vehicle.
- Setting different options in the intercom panel UI (setting work or monitor to any options, push-to-talk, v/o, volume) before exiting the remote control without leaving the vehicle.
- Dying and respawning after the bug was activated
- Deleting unit and vehicle I used to activate the bug
- Killing the unit or destroying the vehicle I used to activate the bug (destroying the vehicle kind of worked a couple of times because the AI character exited the vehicle the moment it blew up)
- Using units and vehicles spawned before and after activating the bug.
- Restarting TS3 plugin
- Turning off TS3 and starting it again

**Comment by RM978** [comment]
This Issue still occurs as described.

- **Arma 3:** `2.14.150957`
- **CBA:** `3.16.0.231017` 
- **ACRE2:** `2.12.0.1056`
- **ACE3:** `3.16.0`
- **TS3:** `3.6.2`

I don't want to hasten you, but have you looked into this bug yet?

**Comment by jonpas** [comment]
Not yet, this issue will be updated when we do.

**Comment by mrschick** [comment]
Can reproduce, looks like `sys_gui/fnc_showVehicleInfo.sqf` is called with `false` to hide the GUI right after using a Rack. Happens regardless of whether or not the Zeus uses the remote voice.
Will look into it as part of some Zeus RC bugs I noticed.

**Comment by mrschick** [comment]
A workaround for the moment is making the AI leave the vehicle, that will allow the rackPFH to terminate and a new one to be generated for the player, making his Racks usable again.
