### ISSUE TITLE
[Docs] Link to BABEL in the guides broken

### ISSUE THREAD

**Issue by mwpowellhtx** [IDI-Systems/acre2#1286]
I think the [URL](http://acre.idi-systems.com/api/api_babel.html) has changed since the original writing.

**Comment by jonpas** [comment]
Which guides?

**Comment by mwpowellhtx** [comment]
Good question, [_making missions intro_](https://acre2.idi-systems.com/wiki/frameworks/mission-making-intro), opening paragraphs. _TL;DR_, did not QA hundred percent, that one jumped out as obsolete.
