### ISSUE TITLE
Text goes out of interface

### ISSUE THREAD

**Issue by alezm00** [IDI-Systems/acre2#1311]
**Mods (complete and add to the following information):**
All steam version
- **Arma 3:** `2.14 stable`
- **CBA:** `3.16.1 stable`
- **ACRE2:** `2.12.0 stable`

**Description:**
In some languages the text for vehicles racks and intercom goes out of the predefined space for the interface (screenshot for example)

**Steps to reproduce:**
- Set the Arma language to, in this case, `Italian`

**Screenshots:**
![WhatsApp Image 2023-12-26 at 22 24 12](https://github.com/IDI-Systems/acre2/assets/31077802/aa0682c1-5cef-40af-b6d5-0de7112afd62)
![WhatsApp Image 2023-12-26 at 22 24 11](https://github.com/IDI-Systems/acre2/assets/31077802/053a63d6-dfd1-4b93-b113-6083a8087e65)

**Comment by mrschick** [comment]
I noticed that too, should be already resolved in Italian by the shorter intercom channel names I added [here](https://github.com/bagigi-arma/acre2/commit/d01482204f33029eb1bef0b628bdc589418f2d31#diff-4ccc73a2d4fb4bf8e7afd2353d62dcc0b4508455bf11ec57755f38323527b298).

**Comment by jonpas** [comment]
Dynamic wrapping calculation is off, needs to be fixed, just didn't get around to it yet.
