### ISSUE TITLE
Acre2 Will Not Connect to TS3

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [IDI-Systems/acre2#1344]
I'll let the title speak for itself here.

The mod just won't connect to TS3 on Linux.

I use Protontricks and the Windows client of TS3.

The Client doesn't crash at all, but Acre2, which did this previously, just won't send its plugin to TS3.

Generally useless troubleshooting done:

Removed mod
Reinstalled mod
Verified game files
Reinstalled TS3 thanks to the Arma 3 Helper Script

I don't know what to do.

**Comment by De-Been-Tech-Solutions** [comment]
Fix for this issue:

On Linux, you must go to where your TS3 is installed thanks to the Arma 3 Helper Script, then delete it.

You must then re-install, then open it with said script, then run Arma 3 using the games launcher like normal with TS3 running in the background.

**Comment by gitshipdone** [comment]
> Fix for this issue:
> 
> On Linux, you must go to where your TS3 is installed thanks to the Arma 3 Helper Script, then delete it.
> 
> You must then re-install, then open it with said script, then run Arma 3 using the games launcher like normal with TS3 running in the background.

I installed via steam, ts3 is installed via their website (I did have it on flatpak but assumed id get into permission errors), I'm not understanding what this helper script is but the mod also isn't loading for me.
