### ISSUE TITLE
Default password for TS3 channel 

### ISSUE THREAD

**Issue by Marcin648** [IDI-Systems/acre2#1346]
**Is your enhancement related to a problem?**
On public TS3 servers used by multiple Arma 3 communities, non-Arma players often join ACRE channels, causing issues. Setting a password via CBA settings isn't a feasible solution, as the number of communities using this server is unknown. The TS3 admins are looking for a zero-configuration solution that requires no interaction with Arma servers.

**Solution you'd like:**
ACRE2 TS2 extension should attempt to use default password `acre` if no password is configured in CBA settings.
This approach is already used in _similar competing products_. ;)

**Comment by rautamiekka** [comment]
How is using the publicly viewable CBA settings unfeasible compared to a publicly viewable extremely simple pw ? Just cuz it'd be a zero-conf solution, it's just as good as having no pw (same as no security), AFAICT.

**Comment by Marcin648** [comment]
Yes! It's not about security here. Problem was players that unintentionally occupy the channel, because is a public available and without password. Those who do it on purpose still can do this, but they should be banned. But more often than it unintentionally.

_I am not directly affiliated with this TS3 server._

**Comment by jonpas** [comment]
Closed by #1347
