### ISSUE TITLE
Disable underwater communication

### ISSUE THREAD

**Issue by Soldia1138** [IDI-Systems/acre2#15]
Disable radios and direct speech under water.
As this is unrealistic we should simply disable it, therefore i consider it as an optimization. Perhaps a filter can be applied to direct speech.

Implementation of underwater radios is not part of this issue and should be considered as a long-term goal  (-> #14)

**Comment by jonpas** [comment]
`optimization` as meant as purely performance optimization, everything else is an `enhancement`. :)

Done in #66
