### ISSUE TITLE
Switch antenna data models from MMANA-GAL to 4nec2

### ISSUE THREAD

**Issue by Sniperhid** [IDI-Systems/acre2#201]
**Description:**
- At present the binary gain data for the anntenas is generated from MMANA-GAL, switching to 4nec2 would make things easier for others to produce these models and the data format is easier to work with and could provide better simulation information.

**Tasks:**
- [x] Update C++ signal processing to use the new format
- [x] Generate data for the currently used antennas
- [x] Create a tutorial.

**Comment by Soldia1138** [comment]
Actually we should define a raw format from which the binary is build. It shouldn't matter from which application or calculation the data comes from.

What we need are the following parameters:
* Frequency
* Theta + Phi for Elevation and Azimuth
* Gain (total)

with `G[f,theta,phi]`

**Comment by NouberNou** [comment]
There is already a format in the ABA file format. I just need to formalize it and document it.

I might add phase to the file.

**Comment by Soldia1138** [comment]
Need to document that. But antennas are ported and specific antennas were added.
