### ISSUE TITLE
Proper indentation and spacing in all config files

### ISSUE THREAD

**Issue by Soldia1138** [IDI-Systems/acre2#206]
- [x] Opening brace on same line
- [x] `QUOTE(DFUNC( ))` -> `QFUNC( )`
- [x] Correct spaces (_something = something_)
- [x] Correct indentation
- [x] `CLASS:` without space between class and semi-colon.
- [x] `QUOTE(PATHTOF( ))` -> `QPATHTOF( )`

**Comment by TheMagnetar** [comment]
The `QFUNC()` change I did it without noticing in the #209 alongside different macro conversions, including some changes to use `EFUNC()`, `QEFUNC()`, `GVAR()`, `EGVAR()` and `QEGVAR()`.

**Comment by Soldia1138** [comment]
Think this could be closed. > 99% should be fixed in master branch now
