### ISSUE TITLE
Feature Request: Modify the TS Mute Range

### ISSUE THREAD

**Issue by Mezilsa** [IDI-Systems/acre2#222]
Good evening,

would it be possible to make the TS mute range editable for a mission creator?

Sincerly
Mezilsa

**Comment by jonpas** [comment]
What would be the use case? The mute range is there only to improve performance, you can't hear anyone in direct that far anyways, but it does not impact radio communications.

**Comment by Mezilsa** [comment]
The use case would be that you can't estimate the distance to a unmuted player (which would be actual less than 300 meters). If the range would be modular or just realy big it wouldn't be as interesting to try to do this.

**Comment by Soldia1138** [comment]
Added in #228
