### ISSUE TITLE
No support for HOTAS warthog

### ISSUE THREAD

**Issue by dansta** [IDI-Systems/acre2#226]
**Arma 3 Version:** stable
**CBA Version:** stable
**ACRE2 Version:** stable

**Mods:**
```
- @CBA_A3
- @acre2
- @ace3
```

**Description:**
Cannot bind ACRE2 actions to joypads or joysticks/throttles.

I have a HOTAS warthog, and as a replica of a real joystick it has a communications 4-way switch on the throttle. For some reason you cannot bind this in ACRE2 and it would be immensely helpful as I'd have to find the keyboard buttons each time I wanted to talk, which is bad in case you're airborne etc. The controller is natively recognized by Arma3 and you can bind it to other voice channels as for example the group, side and direct chat.

This seems to in effect for all mods we currently use even the ACE-related ones. So the assumption is that it's actually not enabled for mods to bind joystick/joypad controls and it therefore is an arma3 vanilla issue. However, I'm reporting it here and hopefully it can be flow upstream as in other open source development.

Also if you read the configs for ACRE2 it does not mention external controllers. Support seems to exist only for ascii keyboards.

**Steps to reproduce:**
1. Start the game with mods.
2. Start any mission where you are a player of any kind.
3. Enter options and switch to mod bind menu. 
4. Select ACRE2 option and bind it to a joystick or joypad button.

If reproduced, it should not succeed in binding the control.

**Where did the issue occur?**
All known menus.

**Placed Modules:**
None

**RPT log file:**
I'm not sure if this is necessary. Please advise.

**Comment by Soldia1138** [comment]
As the framework for all the addon keybinding is actually coming from, it would be the best if you post your Issue on CBA's tracker: 
https://github.com/CBATeam/CBA_A3/issues

Might be related to: https://github.com/CBATeam/CBA_A3/issues/581

Will close the issue here but thank you for the issue report.

**Comment by jonpas** [comment]
It is not possible to bind any joystick or other peripheral keys, it is an engine limitation and there is nothing we or CBA team can do about.

Your best luck is using software to bind joystick buttons to keyboard input.

**Comment by brainslush** [comment]
The hotas comes with an excelent software for adjusting the inputs/outputs. Use that one

**Comment by dansta** [comment]
The HOTAS does come with software. It being excellent is a subjective opinion. It has numerous drawbacks I've noticed. The only way for me to solve this right now is by wrapping the joystick with a virtual driver through TARGET software and reprogramming the switches to do keypresses and that complicates the environment for every other game that uses the same controller. Also it would be a workaround that targets a specific subaudience only since TARGET is not generic wrapper software. Arma per default has a lot of keybinds which means some keys may have to give way to voip/acre communication, complicating other areas. The same goes for any mod that has custom actions with keybinds. And no, profile switching or loading/unloading virtual drivers is not a good solution as I've found that to be bugridden as well. Often wrappers are also untrusted third party .exe-files you run which may or may not contain malware, and may or may not be against battle-eye rules. They also will have to get accepted via windows UAC which means they're explicitly trusted not to be bad software, even though their origin is often an unknown developer.

Creating a ticket on BI Phabricator seems to be the proper way to do it, but looking at the ticket stack you can clearly discern that their reporting system is being nearly a 100% neglected by BI and it would ultimately serve no purpose. Arma 4 will be on sale before they address my issue, and it's no different from the forerunner ticket system. It took them on average 2-3 years to solve my tickets.

Either way, this ticket is closed. This community cannot fix the problem and it's not their obligation. I must confess, my ticket was a pot shot that maybe ACRE2-devs had better contact with devs than I do and could escalate the issue easier. Or that maybe devs once in a while looked at this ticket list.

In the meanwhile, I'll keep answering "Bohemia's brain fart" whenever anyone says I can't fly straight when I talk and fly at the same time.

**Comment by jonpas** [comment]
You can only use TARGET for Arma and then just unload the profile when you are done playing. It's what I do and it works pretty well.

BI is aware of the issue, it has been reported many many times. Until they provide API to capture peripheral input there is nothing we can do.
