### ISSUE TITLE
No Biep sound when starting use the Radio

### ISSUE THREAD

**Issue by Frostie2811** [IDI-Systems/acre2#236]
Arma 3 Version: 1.66 (stable)
CBA Version: 3.x.x (stable)
ACRE2 Version: 2.4.0 (stable)

Mods:

    @CBA_A3
    @acre2
    @ACE3 3.8.3

**Description:**
some guys of us didnt hear the biep sound when they start to use the radio. We were on the server on the same time but for me it worked

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- ACRE 
- ACE

**Comment by TheMagnetar** [comment]
This can be similar to #82. It would be really helpful If you can upload both RPT and logs/acre_dll.log of the affected players.

**Comment by Sniperhid** [comment]
Could you please attach the RPTs of both players and give more detail as to what radios, where you both were ingame etc?

**Comment by Frostie2811** [comment]
Ok we played again today with 20+ players. 7 Players had the problem i will posting the actually RPTs of the 7 guys also the acre_dll.log.

ACRE dlls:

https://justpaste.it/13vi5
https://justpaste.it/13vi3
https://justpaste.it/13vi7
https://justpaste.it/13vif
https://justpaste.it/13vin
https://justpaste.it/13vil
https://justpaste.it/13viu


RPTs:

https://justpaste.it/13vic
https://justpaste.it/13vid
https://justpaste.it/13vih
https://justpaste.it/13vip
https://justpaste.it/13vj4
https://justpaste.it/13vig
https://jpst.it/Ubb-

i think it is maybe the same problem like #82. One of the guys that worked yesterday tried it later too and had also the problem wirh no biep sound today it worked fine for him. We were all ingame. Sorry for my bad english :P if someone wants it more detailed and speaks german im open for a direct chat like teamspeak or something else.

**Comment by TheMagnetar** [comment]
Found these lines:

```
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_other_on.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_other_off.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\beep.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\beep-low.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_new_on.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_new_off.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\sem52knob.b64'. Extension not listed in allowedLoadFileExtensions
20:10:31 Could not load '\idi\acre\addons\sys_sounds\sounds\click.b64'. Extension not listed in allowedLoadFileExtensions
```

Please enable those extensions and it may solve the problem. After looking at them this is not like #82. These are the files for the radio sounds and they are being blocked.

**Edit:** Wiki will be edited accordingly.

**Comment by Frostie2811** [comment]
Where should it be enabled ?

**Comment by TheMagnetar** [comment]
They are in [server.cfg ](https://community.bistudio.com/wiki/server.cfg), it is important for [dedicated servers](https://community.bistudio.com/wiki/Arma_3_Dedicated_Server)

**Comment by Frostie2811** [comment]
okay i will check it and will give u my feedback tommorow

**Comment by Frostie2811** [comment]
tested it today and those files were not enabled, after they were enabled it worked well. The Funny thing is only that before they were enabled they already worked for some persons. But i would also say its solved :P

**Comment by jonpas** [comment]
Generally they have to enabled to work. Glad it is resolved, we will update the wiki in some time with that information for the future.
