### ISSUE TITLE
Acre was unable to parse the map!

### ISSUE THREAD

**Issue by Wesley-TB** [IDI-Systems/acre2#247]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `v3.2.0.1702224` (stable)
**ACRE2 Version:** `2.4.0.942` (stable)

**Mods:**
```
- CUP Core
- CUP Terrains
- ACE
- ACEX
- BSOC Brasil
- CBA_A3
- acre2
```

**Description:**
I'm having trouble using the acre on my map, see the image below

http://i.imgur.com/YpiHJke.jpg

====steps needed to reproduce the issue.=======

Select BSOC Brasil on map list, go to anywhere of map, place any playable unit and play. The message will appear as soon as you finish loading

**Where did the issue occur?**

- Editor, single mission and multiplayer

**Placed Modules:**

No modules added

**RPT log file:**

https://gist.github.com/ViruzDeath/0b78acb35995eec062e654ae2b6481ce - ACRE RPT
https://gist.github.com/ViruzDeath/01f5bdc85cb62037c5b711ab57815442 - ARMA 3 RPT

**Comment by jonpas** [comment]
EDIT: I was wrong, it is because you have no prefix for the PBO. Therefore the path is wrong, Arma probably chews through it as it has PBO references directly. But you really should have a [PBOPREFIX](https://community.bistudio.com/wiki/PBOPREFIX) either way.

**Comment by Wesley-TB** [comment]
Ok, i maked the prefix with "Addon Builder" and the error persists! Can you help me find another solution?

**Comment by jonpas** [comment]
I am not sure what's up, I will check what happens when building with Addon Builder for me.

**Comment by Wesley-TB** [comment]
Jonpas, I solved the problem and forgiveness my stupidity!

**Comment by jonpas** [comment]
Great to hear!

Feel free to write down what the problem was, as it may help others in the future.

**Comment by Wesley-TB** [comment]
The problem was pboprefix! I did some more tests and managed to set the right path. Thanks for all the attention and help jonpas!

**Comment by jonpas** [comment]
Cheers! 🎉
