### ISSUE TITLE
Isla Duala Client/Server Crash

### ISSUE THREAD

**Issue by SchwererKonigstiger** [IDI-Systems/acre2#250]
**Arma 3 Version:** `stable` 
**CBA Version:** `stable`
**ACRE2 Version:** `stable` 

**Mods:**
```
- CBA_A3
- acre2
- ACE3
- Isla Duala A3
- CUP Complete
- etc, more details below
```

**Description:**
Isla Duala A3 is not loadable with ACRE2 enabled.
I have tested this with both my full modpack enabled, and disabled. The result is the same, client + server silently crashes. RPT logs for clients have been attached, I will attach a fresh RPT for the server as well.
Server does not properly log an RPT for this crash, the log file becomes corrupt after crashing.

**Steps to reproduce:**
- Launch/Select an Isla Duala mission on dedicated server.
- Join
- Slot in, and hit accept
- Server will crash, all connected clients will crash

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None, utilized a blank mission with 1 soldier to test

**RPT log file:**
Links provided below. This is from 1 client running the modpack. If required, I can supply RPTs running just ACRE2+CBA+CUP Terrains + Isla Duala
DLL Log
https://gist.github.com/SchwererKonigstiger/5ea1bf83d1adcaf44280f297799446fc
RPT
https://gist.github.com/SchwererKonigstiger/802b58ec7d121a0cc0d25e52b11a1812

**Comment by rebelvg** [comment]
Just tested it, can't confirm. Running latest isla duala and cup tp with acre 942 and a lot of other stuff.

**Comment by rebelvg** [comment]
RPT says Isla Duala 1.97, I'm not sure it's the correct Duala. Author released a3 version, it's latest version is 3.8 atm and it works fine.

**Comment by Bosenator** [comment]
Can't confirm either. We had an OP tonight on this very map with ACRE 2 - none of the 34 players reported this issue.

**Comment by SchwererKonigstiger** [comment]
Will redownload and check, seems odd that the map is openable/editable in editor just fine.
The same set of files was working just a few months back.

**Comment by jonpas** [comment]
Forgot to comment here, I also tested it yesterday in local hosted multiplayer (which also crashes for @SchwererKonigstiger next to dedicated) and it was completely fine.

**Comment by TheMagnetar** [comment]
I have also tested it right now on a dedicated. I could not reproduce it either.

**Comment by SchwererKonigstiger** [comment]
You seem to have been correct. Corrupted file was not being read properly. Odd that it loaded without ACRE though. 

Closing.

**Comment by jonpas** [comment]
Arma can read things ACRE can, such as if PBOPREFIX is not correct Arma will still read it, but we have to rely on config paths.
