### ISSUE TITLE
Preset for "PRC77" is not retrievable via acre_api_fnc_getPresetData

### ISSUE THREAD

**Issue by Dorbedo** [IDI-Systems/acre2#260]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.2.1` (stable)
**ACRE2 Version:** `2.4.0` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- the preset for "PRC77" is not retrievable via acre_api_fnc_getPresetData, while other radios are
- acre_sys_data_radioPresets contains no preset for PRC77

**Steps to reproduce:**
- `["ACRE_PRC77", "default"] call acre_api_fnc_getPresetData`

**Comment by Sniperhid** [comment]
The 77 doesn't use presets as it doesn't store channels. It only uses the selected frequency.

I think it might be nifty for us to create a single channel preset for the 77 and use that so that the default frequency can be changed.
