### ISSUE TITLE
difficulty settings are not found in eden

### ISSUE THREAD

**Issue by kripto202** [IDI-Systems/acre2#262]
**Arma 3 Version: 1.68
**CBA Version: stable
**ACRE2 Version: workshop stable

**Mods:**
```
- CBA_A3
- acre2
```

The difficulty settings module isn't found in 3DEN.

**Comment by Sniperhid** [comment]
This is intended as they are now CBA settings, you need to open the CBA settings menu whilst in the Eden editor and set the difficultly settings for ACRE2 that you would like.

**Comment by kripto202** [comment]
It doesn't make any sense, why have it in game settings when you want to make sure everyone to have the same settings. Say we go with how this is set, person A can have all default settings and person B found the settings. Person B can easily turn the terrain loss coefficient to 0 and have no loss. I still find that having that module very important.

**Comment by PabstMirror** [comment]
The difficulty settings are set to "global" in cba. So everyone will have the same settings and normal clients won't be able to change it.

Confusion is probably that CBA allows you to change the server settings when local hosting.

**Comment by PabstMirror** [comment]
For mission makers in 3den
goto Settings -> Game Options (addons) 
Be on mission tab
Set difficulty and check the force box.

This should offer the same functionality that the modules did.

**Comment by Sniperhid** [comment]
Thanks @pabstmirror - What he said is correct CBA settings are not necessarily traditional game settings but in this case (ACRE difficulty) are influenced by either the mission or server (i.e
 community).
