### ISSUE TITLE
Radio Transmission terminates on any ALT Radio Key release

### ISSUE THREAD

**Issue by eren-kemer** [IDI-Systems/acre2#266]
**Arma 3 Version:** `1.68 x64` (stable)
**CBA Version:** ` 3.2.1.170227` (stable)
**ACRE2 Version:** `2.4.0.942` (stable)

**Mods:**
```
ACRE2
CBA
```

**Description:**
When you click and release any ALT Radio modifier Key, while talking over radio using CAPSLOCK, radio transmission terminates(as if you released CAPSLOCK).

**Steps to reproduce:**
- Hold CAPSLOCK to transmit
- click and release SHIFT, ALT,CTRL, ALT GR or CTRL RIGHT

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Comment by jonpas** [comment]
Can you please make sure this happens with just CBA and ACRE2 as outlined in the issue report template?

**Comment by eren-kemer** [comment]
confirmed happening with ACRE2 and CBA only as well

**Comment by TheMagnetar** [comment]
Alt+CapsLock is also bound as PTT. So i think that the system realises it is starting a transmission with another radio.

**Comment by eren-kemer** [comment]
Yup. Just tested it.
you can replace ALT with CTRL, ALT GR, RIGHT CTRL as well. Same behaviour.

**Comment by jonpas** [comment]
I don't think there is much we can do about that, one combinations transmits on one radio, the other on another or something like that. It's just how the keybind system works.

**Comment by TheMagnetar** [comment]
@eren-kemer And I bet this also happens with SHIFT as it is also bound to PTT.

**Comment by eren-kemer** [comment]
@TheMagnetar yes,as I edited. 
I don't think  this should happen with capslock being pressed already? @jonpas

**Comment by eren-kemer** [comment]
Maybe release of the alt radio key is interpreted as closing the(any) transmission?

**Comment by jonpas** [comment]
I can't reproduce this. Holding down Caps Lock to transmit and clicking any of the buttons you mentioned doesn't interfere with the transmission in any way. Tried with default keybinds as well.

**Comment by eren-kemer** [comment]
Weird.. Can somebody else reproduce the issue?

**Comment by Dorbedo** [comment]
Can't reproduce either.
Could this be an Hardware-Issue? Can you test it with another Keybord?

**Comment by eren-kemer** [comment]
Will test later today and report back.

**Comment by eren-kemer** [comment]
Seems like the problem is with my keyboard. Others don't have the problem either.
I have unbinded the ALT radio keys to not face the problem anymore.

**Comment by jonpas** [comment]
Sorry to hear, time to grab a better keyboard. 😃
