### ISSUE TITLE
Access violation crash in antenna gain map

### ISSUE THREAD

**Issue by TheBamse** [IDI-Systems/acre2#274]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACRE2 Version:** `2.4.1.947` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
Arma3 CTD when radio traffic is being sent when playing with x64.
We were able to reproduce the error and it happens when someone is transmitting over the radio (tested with 343 and 152) and you are the receiver and you combine that with taking damage. We tried shooting and the crash occurred, we tried grenading and the error occurred and so on.

**Steps to reproduce:**
We did a four man test running latest perfomance build v07 (on Dwardens request) with, in the end, only CBA and ACRE2 running, still being able to reproduce the error. We did however test is with a plethora of mod combinations and result was the same. We've tried it with first release of 1.68, then the hotfixed version and most performance builds up to and including v07. Error occurs on all tried versions of 1.68.
The map is Altis. 4 players placed and a game master module with all unofficial mods allowed, no more, no less. The mission was started on a dedicated server running CBA and ACRE2.
We tried this "incrementally", so multiple ppl took turn transmitting but as soon as person 1 got shot he/she crashed. Next person in line got shot, crashed and so on. It did however take a few times for the crash to trigger so one person had to respawn 10 times for it to happen, another crashed right away, and the third 4 respawns etc.
We were not able to reproduce the error if you were the transmitter and getting shot. It's only the receiver that crashes.

Last sunday we experienced the same issue with our full mod set but our Zeus who were using x86 (by mistake) did not crash. All players were running x64 and all of us crashed several times.

We tried using alternate mallocs and -hugePage in all kinds of combinations and that did not affect things.

Even if it takes a few tries we can 100% reproduce this error and cannot use ACRE2 if we want to play.

**Where did the issue occur?**
Dedicated, x64. Vanilla and perf build v07 tested.

**Placed Modules:**
Game Master set to #adminLogged and All unofficial mods allowed.

**RPT log file:**
([RPT 1](https://pastebin.com/EZatzHby))
([RPT 2](https://pastebin.com/TB6bLWtQ))
([RPT 3](https://pastebin.com/01H5GngK))
([Extension log](https://pastebin.com/X7XrLwV5))
([Windows event log 1](https://pastebin.com/Dgmm3JbN))
([Windows event log 2](https://pastebin.com/3ptSrnSq))
([Windows event log 3](https://pastebin.com/G96a4HzF))

rpt's, bidmp and mdmp sent to Dwarden as well upon his request.

**Comment by jonpas** [comment]
Note: acre_x64.dll is blamed in the minidump, it is highly likely something in x64 of the engine is not being handled correctly as we don't do anything special around that. 

We experience crashes on x64 even without any damage taken.

**Comment by TheBamse** [comment]
Copy that, I just wanted to include all the info that I had on hand not knowing what benefits all of you with the know-how (in comparison to me that knows jack shit :D)

What I did forget to mention in the report is that if we just run around shooting each other without talking we do not crash. If we just run around transmitting to each other we do not crash. The CTD occurs right when you are listening to a transmission and you take damage.
I'm not saying that is the only combination possible but it was the one way we found during our ~1h30min testing session.

Let me know if there is something more you want us to try, we are more than willing to test and help in the way we can :)

**Comment by Cuel** [comment]
Does dying or not matter?

**Comment by jonpas** [comment]
That repro will definitely help. :)

**Comment by TheBamse** [comment]
Hmm, good Q. From what I can remember we crashed on both occasions, taking non-lethal amounts of damage and lethal. But, we'll test again tonight to be 100% sure!

**Comment by jonpas** [comment]
I have managed to reproduce the issue on x64 with ease and also found where it's coming from, still looking as to why exactly it happens though.

@TheBamse feel free to join our Slack (slackin link on this repo's main page) so we can quickly communicate and if you want you can help test possible fixes.

**Comment by TheBamse** [comment]
Sorry for not responding earlier, I've had my hands full since reporting to say the least.
I'll join slack tonight when I get home from work!

**Comment by TheBamse** [comment]
Another test was made with the log enabled pbo and dll, v947.

We were only 3 guys today and one person did not crash at all with the same test procedures as above (same unedited mission), two of us did however. For the first time we had some straight CTD's without a single error message, Arma3 just disappeared and no mdmp/bidmp was generated and rpt didn't include the crash stuff. Tbh, not sure it's related to this or something new :/
Everyone was running perfbuild v10 (1.68.141149).

A lot of the logs were to big to upload on pastebin, so links are to Google Drive.

My logs:
[rpt, straight CTD](https://drive.google.com/file/d/0B2WLNcfe_WswX1ZWWUhNcWJ1Mmc/view?usp=sharing)
[rpt, "normal" crash](https://drive.google.com/file/d/0B2WLNcfe_WswNDZ6WmpCOTVJNFU/view?usp=sharing)
[acre_dll.og](https://drive.google.com/file/d/0B2WLNcfe_WswVktuYy1NaENHOFE/view?usp=sharing)

Buddys' logs:
[rpt, straight CTD](https://drive.google.com/file/d/0B2WLNcfe_WswODdWOG9ib25zSGM/view?usp=sharing)
[rpt, "normal" crash](https://drive.google.com/file/d/0B2WLNcfe_WswaXh6ME1jR0JtaW8/view?usp=sharing)
[acre_dll.og](https://drive.google.com/file/d/0B2WLNcfe_WswX1VqOVc3MUZKbDA/view?usp=sharing)

Server rpt
[No server crash](https://drive.google.com/file/d/0B2WLNcfe_WswaVFYem9lLTRiWGc/view?usp=sharing)

**Comment by jonpas** [comment]
The log I added shows nothing special sadly, all the data passes through correctly. Minidumps would be nice if you could attach them (or send them to me via Slack).

**Comment by BlackHawkPL** [comment]
In some cases you are subtracting from an unsigned 0 at [antenna.cpp line 79](https://github.com/IDI-Systems/acre2/blob/x64crashFixFloat948/extensions/src/ACRE2Arma/signal/antenna/antenna.cpp#L79), then using that incorrect value to access an array.

**Comment by jonpas** [comment]
Yes we know, however that does not seem to be the root cause. We want to investigate further and rather release a proper fix. If you are looking for a bandaid fix, check our Slack.
