### ISSUE TITLE
Use new alternate callExtension syntax

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#276]
New syntax since 1.67 (1.68 stable) [`extension callExtension [function, arguments]`](https://community.bistudio.com/wiki/callExtension) improves performance by not needing to separate the string in the extension (minimal) and using `format` in SQF (bigger, but still small). Although mild, this will prove rather a big gain due to the number of extension calls we do.

Additionally, return of the new `callExtension` syntax can be used with [`parseSimpleArray`](https://community.bistudio.com/wiki/parseSimpleArray) for large performance improvements when returning multiple values.

**Comment by jonpas** [comment]
It has been tested that `parseSimpleArray` nests big improvement, but alternate syntax for `callExtension` not so much (not using `format`).

**Comment by TheMagnetar** [comment]
Is this still a thing?

**Comment by jonpas** [comment]
Not really, parseSimpleArray might be faster but it's harder to work with. Let's leave it open and I might take a look some day.

**Comment by jonpas** [comment]
Closed by #933. Remaining extension calls are only occasional or only on load.
