### ISSUE TITLE
SEM52SL Antenna

### ISSUE THREAD

**Issue by Sniperhid** [IDI-Systems/acre2#29]
We need to create a binarized antenna for the SEM52SL. As a placeholder it uses a 120cm BNC.

It should use either a 40cm or 90cm BNC.

**Comment by NouberNou** [comment]
I should document how to do this, and then make a python version of the old ass (6 years at this point) PHP scripts I use to pack data.

I really wish we had our own antenna radiation field generator, but... yea it is pretty much the hardest shit to do.

**Comment by NouberNou** [comment]
http://www.qsl.net/4nec2/

We need to migrate our antenna simulations to using this application for generation. It is much more capable than mmana-gal.
