### ISSUE TITLE
C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by 0dr** [IDI-Systems/acre2#291]
**Arma 3 Version:**
Perf v11 64x

**Description:**
At seemingly random points of play I and sometimes others of the group too (at the same time), receive an error message
"access violation  c00000005".
The game continues to run and won't exit until the "ok" button is pressed.
Only thing that gets effected is the acre2 radio, one can no longer receive radio transmissions,local voice and sending radio still works and can be heard by others.

the dmp says 
"FAILURE_ID_HASH_STRING:  um:invalid_pointer_read_c0000005_acre_x64.dll!rvextension"
*more dmps could be available soon.  if needed

While it is quite similar to "https://github.com/IDI-Systems/acre2/issues/274" we had the bug even when no damage was received.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
https://pastebin.com/kHwrs3uL
https://www.dropbox.com/s/7aacrghnigkdjd0/arma3_x64_2017-04-06_16-42-28.mdmp?dl=0

**Comment by jonpas** [comment]
It is indeed the same crash as #274, you can hop on our Slack to get a build of the extension with presumably fixed crash for testing. If weekend testing shows it is indeed fixed, we will release a hotfix soon.

Closing this as duplicate.
