### ISSUE TITLE
Selected Client Connectivity Problems

### ISSUE THREAD

**Issue by Pironesis** [IDI-Systems/acre2#300]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACRE2 Version:** `2.4.1.947` (stable)

**Mods:**
```
- CBA_A3
- acre2
-RHS
-CUP Terrains
-Alive
```

**Description:**
- As some context, i manage addons for my community and we recently ran a large test on a gamenight testing switching from TFAR to ACRE. We had upwards of 40 players and were running ACRE 2.4.1.974
 
It was a bit of a bumpy night, the biggest issue we had was a small set of players that whilst loading a mission would consistently crash out with no errors. No matter what mission the same small subset of players would consistently crash out when we had approx 40 people on the server all loading to the briefing. This was replicated in 3 different missions and on 2 of our servers both running the same modsets. 
 
We tried letting these people go into a completely empty server, load up the mission and they were able to get into the briefing with just them. Then they launched the mission and the other 30 or so players JIP'd in, over the next half an hour of mission play time most of the people with issues proceeded to crash out with no errors, nothing in their RPT's either. Only 2 people i believe of the small group affected didn't crash out, of all the players having this issue there was a mix of 32 and 64 bit users.
 
The only data that seems to correlate is high player numbers already on the server, though i know this shouldn't be an issue as communities like Shacktac and UO run ACRE fine with more players than we had. I don't believe it was anything to do with the server, it was running ACRE fine on 64bit server exec, and i was using a userconfig to load default server settings via CBA. 

Raising an issue on here at the request of Jonpas.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- ACRE log and RPT's for Victim Client: https://gist.github.com/Twelvecaliber/98da8f1bcebf6b2c77dbf656b22fd7c4

I am working on getting server RPT's they seem to have gone missing trying to retrieve an archive. I can provide client RPT's for a user that had no problems for comparison if requested.

**Comment by Cuel** [comment]
#274 ?
There's a build available in acre slack to fix this, it worked well for us

**Comment by TheMagnetar** [comment]
What is strange is that  you report crashes on x32 builds. However the attached rpt  is from x64. Can you get a RPT from a crash on x32?
It would be great if you can report if  you experience any crashes using the latest dev available from the slack. As @Cuel mentioned, the fix seems to be successful.

**Edit**: Oh, and remove all the other mods that are not related to ACRE2.

**Comment by Pironesis** [comment]
I can try to get an RPT from a 32bit client, though only a few of our members are using 32bit systems. As for the latest dev build, where can one find that to download?

**Comment by Cuel** [comment]
@Twelvecaliber  http://slackin.idi-systems.com:3000/

**Comment by Pironesis** [comment]
Apologies for the long ass delay. This can now be closed. Upon testing with 953 players whom previously had issues loading into a game, were now able to do so. 

As a side note, is there any known script systems that are known to cause issues with ACRE. For example we tested a mission that used a fair amount of DAC, and when players would trigger the un-cacheing of AI it would briefly cause outages in ACRE, radios would briefly stop working.

**Comment by TheMagnetar** [comment]
Let me have a look. I use DAC as well. Only CBA + ACRE + DAC (+ ACE3).
