### ISSUE TITLE
Random-ish Game Crashes

### ISSUE THREAD

**Issue by aarengibson** [IDI-Systems/acre2#307]
Arma 3 Version: 
Launcher version: 1.5.141155
Game version: 1.68.141205
Branch: main / beta branch not specified

CBA: Latest Steam Version
ACRE2 Version: Latest Steam Version

Mods:
- CBA_A3 from Steam
- ACRE2 from Steam

Description:
I tested on my dedicated server with 2 other people running ArmA with just CBA and this mod, 

When I have 2 of the same radios in my inventory, game crashes.

Sometimes while randomly speaking on the radio or when one of my friends speak, I crash. The other two players also experience the same issue

All of us have the steam version of the mod and when on TS, it says ACRE is successfully connected to ArmA. Is there anything I need to install on the TS server?

Where did the issue occur?
Dedicated Server

Placed Modules:
- Tried it with no modules, and then with all of them at once.

RPT log file:
https://pastebin.com/wcRFN22T - Client

Server didn't produce a log file. not sure how to fix that (Using TADST and ArmA3Server from Steam)

**Comment by jonpas** [comment]
Looks like duplicate of #274, will be fixed with a hotfix later today.

If this is not the same crash, please just reopen the issue after confirming it still happens with the new versions. And also attach the mini-dump (`.mdmp`) file.

**Comment by aarengibson** [comment]
Hi, sorry, where can I find the minidump files?

**Comment by jonpas** [comment]
Next to the RPT files.
