### ISSUE TITLE
Do not exit on merge failure

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#309]
Basically fix #296, back-merge conflicts will likely happen with cherry-picks for hotfixes in the future again.

**Comment by NouberNou** [comment]
I am not sure I fully understand what you are asking here?

**Comment by jonpas** [comment]
`jenkins.py` would exit when merge failed, but build was fine, and wouldn't upload the build mod.

I fixed this in 09fc5c34751e32e65697dfb8129185c6311c1dd1 and af9e95363a6802214478fba22d463bb648f1c90d.
