### ISSUE TITLE
Cannot remove radio from gear in Virtual Arsenal

### ISSUE THREAD

**Issue by ThymoNL** [IDI-Systems/acre2#331]
**Arma 3 Version:** `1.68` (profiling)
**CBA Version:** `3.2.1` (stable)
**ACRE2 Version:** `2.4.2` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- Upon adding a radio to the inventory in the Virtual Arsenal the ID gets appended to the radio (e.g. ACRE_PRC148_ID_1) as expected. However the Virtual Arsenal still thinks that ACRE_PRC148 is in the inventory and it fails to remove the radio or register the correct amount currently in the inventory.

**Steps to reproduce:**
- Open the Virtual Arsenal.
- Add any radio to inventory
- Attempt removing the radio again

**Where did the issue occur?**
- Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
- [arma3_x64_2017-05-01_13-15-28.rpt](https://gist.github.com/Thymo-/a0301889ae15e9454f3dbf47210885bc)
- [acre_dll.log](https://gist.github.com/Thymo-/cb3f2ce6e7809808be5589e933aeacdd)

**Comment by jonpas** [comment]
I don't think we can do anything about that, it is what Virtual Arsenal is.
