### ISSUE TITLE
acre_api_fnc_isInitialized doesn't wait long enough

### ISSUE THREAD

**Issue by freghar** [IDI-Systems/acre2#354]
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)
**ACRE2 Version:** `2.4.2` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- `acre_api_fnc_isInitialized` returns true before radios are actually truly initialized, specifically the list returned by `acre_api_fnc_getCurrentRadioList` is empty `[]` or contains generic radio item classes alongside unique `_ID_*` ones.

**Steps to reproduce:**
- create a simple mission by placing a soldier down (ie. `B_Soldier_F`)
- in global mission init or in `init.sqf` use this:
```
waitUntil { [] call acre_api_fnc_isInitialized };
diag_log format ["first call: %1", [] call acre_api_fnc_getCurrentRadioList];
sleep 2;
diag_log format ["second call: %1", [] call acre_api_fnc_getCurrentRadioList];
```
- open the RPT log, observe the following:
```
...
21:48:48 "first call: []"
...
21:48:55 "second call: [""ACRE_PRC343_ID_1""]"
...
```

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)
  - tested all of them, Dedicated usually mixes unique and non-unique radio IDs, possibly due to `isInitialized` returning slightly later on clients

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/YrM9Fvej

**Comment by TheMagnetar** [comment]
I cannot reproduce it on a self-hosted server (It happens in single player).  For me, only a unit + init.sqf with the lines you provided returns: with 

> first call: [""ACRE_PRC343_ID_1"",""acre_prc343_id_1""]
> second call: [""ACRE_PRC343_ID_1""]

Can you provide your test mission? Are you using any editing mods (e.g. 3den Enhanced)?

**Comment by freghar** [comment]
The issue isn't only about the array being empty, but about it containing incorrect data (like the lines you posted), which is the reproducer. There should not be any difference between "first call" and "second call", as the radios should be fully initialized when the `isInitialized` function returns - the sleep should make no difference.

I can't seem to be able to attach zip or sqm here (for some reason), but your example shows that it's reproducible on a self-hosted server as well. For a more "realistic" example, just give the unit more radios using "Edit loadout",
```
11:55:44 "first call: [""ACRE_PRC343_ID_2"",""ACRE_PRC343_ID_1"",""ACRE_PRC148_ID_1"",""ACRE_PRC152_ID_1"",""acre_prc343_id_2""]"
11:55:46 "second call: [""ACRE_PRC343_ID_2"",""ACRE_PRC343_ID_1"",""ACRE_PRC148_ID_1"",""ACRE_PRC152_ID_1""]"
```

**Comment by Sniperhid** [comment]
I was able to reproduce the issue is that the `acre_player` variable hadn't been initialised yet.

A temporary fix is to simply add a waitUntil on the acre_player being not null.
```sqf
waitUntil {!isNull acre_player}
waitUntil{[] call acre_api_fnc_isInitialized };
```
