### ISSUE TITLE
ACE integration options do not appear ( External Radios / Intercom / Vehicle Racks )

### ISSUE THREAD

**Issue by AJCStriker** [IDI-Systems/acre2#356]
**Arma 3 Version:** `1.7` stable
**CBA Version:** Unknown - Latest on Steam Workshop (20MAY2017)
**ACRE2 Version:** Unknown - Latest on Steam Workshop (20MAY2017)

**Mods:**
```
- CBA_A3
- ACE
- ACRE2
```

**Description:**
Apologies if this is the wrong place to ask this question but I am trying to reconcile the instructions with the documents to the game. In particular the following three documentation pages do not appear to work in game in so far as I can tell:

- http://acre2.idi-systems.com/wiki/user/external-radios
- http://acre2.idi-systems.com/wiki/user/vehicle-intercom
- http://acre2.idi-systems.com/wiki/user/vehicle-racks

Is there additional configuration required to enable these ACE dependant features of ACRE or are they not yet part of the mod? We are able to open the radios and assign PTT keys via the ACE menu however the additional ACRE interactions described above cannot be accessed.

Thanks for your assistance.

**Steps to reproduce:**
- Load ACE and ACRE
- Attempt to interact with Radio via ACE
- Options stated within documentation are not present

**Where did the issue occur?**
- Dedicated Multiplayer

**Placed Modules:**
ACRE Basic Radio Channel Setup Module ONLY

**RPT log file:**
N/A

**Comment by jonpas** [comment]
Those features are not yet in stable build (which is on Steam Workshop), only on development build meant for testing (which can be acquired on our Slack - found on front page of this repository).
