### ISSUE TITLE
INT Audio not hearable for radio owner

### ISSUE THREAD

**Issue by Soldia1138** [IDI-Systems/acre2#358]
If using the internal speaker of 148, only other players can hear it, but not the owner of the radio. However it is possible if the GUI is opened.

**Comment by TheMagnetar** [comment]
Same for 152?

**Comment by Soldia1138** [comment]
Haven't tested it on other radios (PRC152 / SEM52). This is more a reminder for myself. Issue is pretty old and I experienced it a couple of time mid-mission. Always managed to forget it afterwards.

But yeah, I bet it's broken for other radios as well

**Comment by jonpas** [comment]
IIRC only 148 is affected.

**Comment by Soldia1138** [comment]
Will test this evening

**Comment by Soldia1138** [comment]
Can confirm, only 148

**Comment by Soldia1138** [comment]
One interesting thing thou. If the signal calculation is triggered manually (`[unit1, "acre_prc148_id_2", acre_player, "acre_prc148_id_1"] call acre_sys_modes_fnc_sc_speaking`), it works afterwards for the first transmission. Second and following transmissions are not hearable again.

**Comment by Soldia1138** [comment]
Correction...all radios are affected...
