### ISSUE TITLE
Improve Zeus support

### ISSUE THREAD

**Issue by abbioro** [IDI-Systems/acre2#376]
Inspired by comments in this thread: https://forums.bistudio.com/forums/topic/193813-advanced-combat-radio-environment-2-acre2/?page=20#comment-3185498

- Add the ability to hear players proximity voice when nearby in free camera mode. Currently if Zeus is in free camera mode he can only hear things that are close to his virtual entity or body. He should be able to hear things nearby his floating camera. I believe ACE3 does something to make it work with spectators, might be worth looking into.

- Add the ability to listen in on certain radio channels to know what your players are up to. I think this is currently possible only when Zeus is not a virtual entity.

**Comment by abbioro** [comment]
My problem is mainly that it seems very frustrating to use ACRE 2 with Zeus. I cannot hear what my players are saying.

**Comment by kymckay** [comment]
+1 for this issue, especially the free camera part

**Comment by kymckay** [comment]
I'd also add a suggestion:

There should be a setting or something to allow players using zeus to speak to each other in the same way that spectators do. The reason I say setting is because some scenarios might have zeus players on opposing sides or w/e.

**Comment by jonpas** [comment]
First point is a duplicate of #369 I believe.

**Comment by kymckay** [comment]
Negative on duplicate, that ticket is basically asking for a toggle between `player` and `ace_player`.

I've been fairly regularly zeus-ing for a long time now with ACRE and can probably summarise the ideal solution:

- When in zeus *camera* (not while RC-ing) you ideally should be able to hear directional voice *both*:
  - Near to the camera
  - Near to your unit (`player`)
- There should be a toggle hotkey (which works in the camera or while RC-ing) to switch your own voice between:
  - Current unit (`ace_player` equivalent)
  - Zeus "channel" (aka, zeus players talking together like spectators would)
- With some method of control over the Zeus "channel" (to cover cases where zeus units are hostile to one another or w/e)

This kind of implementation would cover all bases. Allows multiple zeus units to talk while also allowing them to roleplay the currently controlled unit. If it's not possible to implement hearing directional voice from two locations at once like that, then the next best option is probably to toggle between the two as part of the same hotkey.

**Comment by kymckay** [comment]
As for zeus listening in on radio channels, that's probably a more advanced quality of life feature request that deserved it's own ticket. Whereas the above is more functionality that would make zeus more compatible with ACRE.

**Comment by jonpas** [comment]
Agreed with everything you said.

**Comment by PabstMirror** [comment]
We add a tiny little button to the bottom left corrner of zeus that toggles acre's spectator mode
![image](https://user-images.githubusercontent.com/9376747/27344423-d61d7f48-55ab-11e7-9bdc-e7ad7f35b5b3.png)
Lots of good uses for this, mainly that zeus can get feedback from dead people on the mission

**Comment by abbioro** [comment]
Thanks @SilentSpike for putting it into better words than I could.

The main benefit of having Zeus being able to listen in on radio channels for me would be to not only know what your players are up to but also support the "Commander" use case where Zeus is roleplaying a commander for the players. Ideally it would mean that Zeus could be off doing something else when the players contact him over radio (from possibly an arbitrary distance away).

But agree that this could be a more advanced feature, being able to simply hear positional voice when near players with the camera is already a great improvement.

**Comment by kymckay** [comment]
No problem. Thanks for making the ticket, it's bugged me for so long and I never got around to making a ticket for it 😆 Had plenty of time to think through what would be ideal

**Comment by abbioro** [comment]
@PabstMirror is this button implemented somewhere right now?

**Comment by PabstMirror** [comment]
https://github.com/BourbonWarfare/POTATO/tree/master/addons/zeusMonitor
Really just 
```
class RscDisplayCurator {
    class Controls {
        class GVAR(acreSpectateButton): RscButton {
            idc = 777550;
            x = "safezoneX";
            y = "safezoneY + safeZoneH - 14 * pixelH";
            w = "80 * pixelW";
            h = "12 * pixelH";
            sizeEx = "12 * pixelH";
            text = "ACRE Spectator";
            action = QUOTE(_this call FUNC(toggleAcreSepcator));
```
```
[!ACRE_IS_SPECTATOR] call acre_api_fnc_setSpectator;
```

**Comment by abbioro** [comment]
Thanks

**Comment by abbioro** [comment]
For now, my group is using this rather ugly hack as a workaround:

```sqf
zeus_virtual_entity enableSimulationGlobal false;
zeus_virtual_entity hideObjectGlobal true;

// move zeus_virtual_entity to camera position continuously
if (player == zeus_virtual_entity) then {
	[] spawn { 
		while {true} do { 
			sleep 1; 
			zeus_virtual_entity setPos (getPos curatorCamera);
		}; 
	};
};
```

Essentially keeps the virtual zeus entity in "sync" with the curator camera by constantly teleporting it. Disabling the simulation and hiding it means it can float in the air and won't clip with anything. I can hear what my players are saying over radio, I can move my camera close to hear them, I can use any radio by briefly remote controlling a unit (which lets you use their radio after exiting remote control), the radio is always in range if I move my camera near players. I can even move my camera up close and talk to them with direct chat.

But yeah, it's ugly.

EDIT: ~~By now I figure this would probably be a lot easier to do with just `attachTo`.~~ Didn't work.

**Comment by brainslush** [comment]
All these new features should be options to switch on and off. We like the current system quite well but the reason is mainly that we don't use virtual Zeus and most of the time the Zeus has the role of a high command officer as well so he automatically has radios in his inventory or is close to a vehicle rack.
Also we like that the Zeus doesn't hear what the players are saying because we are fond of the idea that Zeus isn't all knowing.

**Comment by Rekkless88** [comment]
Here is a work around fellas. It isn't perfect but it is better than nothing.

I'm sure all you guys now use ACHILLES mod for your Zeus. What we do is place a playable player, just a regular soldier, give him the radios necessary to listen in.

Then use the "HIDE ZEUS" function in ACHILLES this will make your player invisible to players and AI. I can't comment on however if it makes you invincible or not.

You can then run around with the players and listen in to their conversations in total stealth. you can even still get into vehicles and operate the radio as normal. Also keep in mind the players can hear you, so be careful where you operate your radio.

It isn't a perfect solution like what OP is requesting or like what TFAR offers, but it is much better than no hearing at all.

**Comment by austinjames314** [comment]
> It isn't a perfect solution like what OP is requesting or like what TFAR offers, but it is much better than no hearing at all.

Just to put a line under this, the lack of features to accommodate zeus players is pretty much the single biggest sticking point preventing ACRE2 from being adopted, in my experience. In a given milsim clan, the guys that play as zeus tend to have more influence about mod selection, typically being more senior members. They don't want to lose the ability to be able to hear what's going on that TFAR gives them.

**Comment by jonpas** [comment]
Tell them they should stop cheating and knowing what player's plans are. 😆 
_Joking if it isn't clear._

**Comment by keith0123** [comment]
just checking in here we recently switched to acre from tfar and i'm seeing this problem as well. have they added this feature yet?

**Comment by TheMagnetar** [comment]
No. Not yet. Our current focus is on vehicle radios and on overhauling the intercom system.
