### ISSUE TITLE
Drones have Infantry Phone

### ISSUE THREAD

**Issue by Soldia1138** [IDI-Systems/acre2#379]
As it can be seen in this picture, drones (at least the darter) got the infantry phone. 😄 

https://images-ext-2.discordapp.net/external/jqlrr88kZwfrwVfR9sY6BNUFJBkCFu567YsyVMcxdV8/https/i.imgur.com/8sBIdicr.jpg

**Comment by TheMagnetar** [comment]
What is wrong? Why poor drones can't have one?
