### ISSUE TITLE
Mission Modules

### ISSUE THREAD

**Issue by Pironesis** [IDI-Systems/acre2#382]
Just a brief request for some more editor modules, particularly for babel. Obviously there are functions in place for controlling things like languages and which units can speak particular languages. However it isn't the most user friendly system in the world, and sometimes has JIP issues. (What in ArmA ever is? :P ) 

Would it be possible to have modules for creating new languages, assigning which units can speak these languages, these are the immediate ones that come to mind, but i am sure there are other functions that could be made into modules, if it is possible.

**Comment by jonpas** [comment]
Modules have JIP issues, we are moving away from them and will rather have Eden attributes in the future.
