### ISSUE TITLE
Interface for AN/PRC-148 not displaying properly

### ISSUE THREAD

**Issue by rebel12340** [IDI-Systems/acre2#387]
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**ACRE2 Version:** `2.4.2` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
The interface for the AN/PRC-148 is not displaying text properly. None of the text is readable on any of the menus.
Picture of the problem: https://image.prntscr.com/image/P5Fhbj6rSSO-gRsEhxOKxw.png

**Steps to reproduce:**
1. Add an AN/PRC-148 to your inventory.
2. Open up the radio ("Ctrl+Alt+Caps Lock" by default).
3. See that main display for the radio is not displaying text properly.
4. Navigate to other menus on the radio and notice that not of them display properly, either.

**Where did the issue occur?**
Tested and present in multiplayer (Dedicated and self-hosted) as well as in the singleplayer editor. 

**Placed Modules:**
None.

**RPT log file:**
https://pastebin.com/GNxk3ctn

**Comment by Sniperhid** [comment]
This is due to changes to a font that BI provided in Arma 3 when they added Chinese localisation.

This could be fixed on BI's end but that remains to be seen if this will happen.

**Comment by jonpas** [comment]
It is supposed to be fixed with next Arma update.
