### ISSUE TITLE
Switch channel keybind does not work with certain radios

### ISSUE THREAD

**Issue by Gilatar** [IDI-Systems/acre2#388]
**Arma 3 Version:** `1.72.142223` (stable)
**CBA Version:** `3.4.0.170627` (stable)
**ACRE2 Version:** `2.4.2.954` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- The Previous Channel and Next Channel (Active Radio) keybinds do not work on all radios. It works with the AN/PRC-343, 148 and the SEM 52, but will only allow switching between the first 5 channels with the AN/PRC-152 and will not allow any channel switching with the AN/PRC-77 and 117F.

**Steps to reproduce:**
- Equip an AN/PRC-152, 77 or 177F.
- Using the keybinds, you can only switch between the first five channels when the AN/PRC-152 is active.
- Using the keybinds, you can not switch between any channels when the AN/PRC-77 and 177F is active.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Placed Modules:**
- None

**RPT log file:**
- [Pastebin](https://pastebin.com/t6Xz9r15)

**Comment by Sniperhid** [comment]
This is intended behaviour. It works for handheld radios but not for radios that can only be in your backpack and so you need to open them to change channels.
