### ISSUE TITLE
SDV should have intercom in all seats

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#406]

**Comment by TheMagnetar** [comment]
I am not sure... cargo positions are not crew members.

**Comment by jonpas** [comment]
They are in SDV, it's only 4 slots, no cargo, they are all special. 😆 

It's mostly because there is no other way to communicate underwater than radio or intercom. And radio is a bit pointless, I am 99% sure real life small submarines also have intercom on all seats.
