### ISSUE TITLE
Named channel switching and server-forced settings not working

### ISSUE THREAD

**Issue by Fourjays** [IDI-Systems/acre2#408]
**Arma 3 Version:** `1.76` (stable / rc / dev)
**CBA Version:** `3.4.1.170912` (stable / dev + commit hash)
**ACRE2 Version:** `2.5.0.968` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- Configuration options for the new automatic channel switching feature are behaving inconsistently.
- Custom names are never being used, no matter the method - only a channel named "ACRE" works.
- Forcing options via the server configuration does not appear to work at all.
- Forcing options via the mission settings will ensure everyone gets moved, but only to "ACRE".
- Setting options via "client" options makes no difference.
- If settings aren't forced by the mission, checking the automatic switching checkbox clientside makes no difference. However, typing anything into the channel name box will switch the client to the "ACRE" channel.
- Moving back to a prior channel works without issue, even if a player moves themselves to the ACRE channel manually.
- Settings shown in-game do not show the server-set channel name, and do not show the channel name and switching checkbox as "overwrite clients" despite being forced.
- Our existing server config has settings different to those in our regular mission templates, yet correctly overrides them. With the latest ACRE, the server settings are not getting applied in any situation. Only mission settings seem to have an effect.
- Unsure if these issues are the same or seperate. I think the server settings issue is preventing a clearer analysis of what's going on with channel switching.

**Steps to reproduce:**
- Create 4 channels in Teamspeak: Test1, Test2, Test3, ACRE.
- Set client to Test1, mission to Test2, server to Test3.
- Create one mission that forces settings, another that doesn't.
- Check behaviour of channel switching. Always lands in ACRE _if_ the player gets moved at all.
- Check behaviour of other settings. Server configuration seems to be _always_ ignored.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- Player 1 RPT: https://pastebin.com/E8PXx7uW
- Player 2 RPT: https://pastebin.com/5XDZiUkU
- Player 1 ACRE Log: https://pastebin.com/DKbJyekh
- Player 2 ACRE Log: https://pastebin.com/eGmSLAs8
- Server RPT: https://pastebin.com/SThPSQK3
- CBA/ACRE Config: https://pastebin.com/p3nkxRWY
- In-Game Server Settings: http://steamcommunity.com/sharedfiles/filedetails/?id=1144010506
- In-Game Mission Settings: http://steamcommunity.com/sharedfiles/filedetails/?id=1144010402
- In-Game Client Settings: http://steamcommunity.com/sharedfiles/filedetails/?id=1144010285
- Teamspeak 3 Channel Structure: https://www.dropbox.com/s/ubf8fc1kbsw1lsk/tschannels.png?dl=0

**Comment by jonpas** [comment]
> Channel names must contain “ACRE” to be detected as a dedicated channel.

That goes for custom names as well, a limitation for now. Will be improved in the future.
~~Will reply to other stuff later, looks like some profile corruption or something possibly.~~

**Comment by jonpas** [comment]
How do you apply CBA settings server-side, userconfig or a PBO? Server configuration will be ignored unless it forces mission configuration.

**Comment by Fourjays** [comment]
Server settings are applied via userconfig/cba file. I've tried both `force setting_name` and `force force setting_name` and confirmed it is taking settings from the mission file only. Also checked with a template that has "overwrite" checked on each option and one that doesn't. I think the settings file is still read, as the in game settings screen for "server" shows the correct values - they're just not being applied instead of those under "mission".

**Comment by Fourjays** [comment]
Is there anything else I need to ensure server-side settings get applied or is it not working as intended? I think that not working is the actual issue here.

**Comment by jonpas** [comment]
> 21:22:31 [ACRE] (api) INFO: Difficulty changed. Interference: true - Duplex: false - Terrain Loss: 0.5 - Omni-directional: 0 - AI Hearing: true

Those are definitely getting applied correctly.

> 21:32:01 [CBA] (settings) WARNING: Value true and priority 0 are the same as previously for setting acre_sys_core_ts3ChannelSwitch. x\cba\addons\settings\fnc_set.sqf:47
> 21:32:01 [CBA] (settings) WARNING: Value "Test1" and priority 0 are the same as previously for setting acre_sys_core_ts3ChannelName. x\cba\addons\settings\fnc_set.sqf:47

There is a bunch of those messages, I am not sure how you managed to get those. Will ask commy2 and get back to you.

**Comment by Fourjays** [comment]
Those settings in the RPT you quoted come from the mission file - the server ones specified in the config are different (terrain loss is set to 0, full-duplex is on, antenna direction turned off).

On the prior version the server settings override whatever is specified in the mission itself. This no longer seems to be the case.

**Comment by jonpas** [comment]
Looking at your Server Settings screenshot, I see "Overwrite Mission" isn't checked, it has to be to overwrite whatever is set in mission. Your userconfig does have `force force` though, so I am not sure why this doesn't get applied. I suggest you post this over at the CBA GitHub, doesn't look like an ACRE2 issue.

We are running a PBO with `cba_userconfig.sqf` in it, and it gets applied correctly there, never used server-side userconfig though.

> On the prior version the server settings override whatever is specified in the mission itself. This no longer seems to be the case.

That supports my above thinking, priority system changed in CBA 3.4.0 to satisfy community requests. But it doesn't explain why `force force` wouldn't work in server's userconfig.

**Comment by Fourjays** [comment]
I'll try the PBO method and see if that works before reporting it over at CBA.

**Comment by tbeswick96** [comment]
We use serverside userconfig without any issues. Assuming you have filepatching enabled on the server?

**Comment by jonpas** [comment]
He does, as seen in RPT.

**Comment by Fourjays** [comment]
I've got to the bottom of the server settings not getting forced - in my haste to figure out the channel switching, my test server setup had the settings file in the old location of  `userconfig/cba/settings.sqf` instead of the new one of `userconfig/cba_settings.sqf`. Fixed that and it all works (other than requiring ACRE in the channel name, but you're working on that).

**Comment by jonpas** [comment]
Yep, that should be improved with next update. Glad you solved it!
