### ISSUE TITLE
ACRE2 Robotic Voice

### ISSUE THREAD

**Issue by ownedarg** [IDI-Systems/acre2#413]
**Arma 3 Version:** `1.76.143187` (stable)
**CBA Version:** `3.4.1.170912` (stable)
**ACRE2 Version:** `2.5.0.968` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- I hear other players with a robotic voice, making communication quite difficult. Nearly impossible.

**Steps to reproduce:**
- Connect to a server with ACRE2 modules placed in the mission and talk to other person.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Placed Modules:**
- Both ACRE2 default modules.

**RPT log file:**
- https://pastebin.com/MupgiD2r

**Comment by jonpas** [comment]
I see script errors from ACRE2 configuration (from #412). Try on an empty mission without "Name Channls" modules set.

**Comment by ownedarg** [comment]
I set the option 'No babel' on the Basic Setup Module, and know I hear a DEEP voice i don't know if it's random but, still unable to communicate properly.

**Comment by jonpas** [comment]
Can you check with a different headset for example? Check settings in TeamSpeak, check drivers.

I really have little to no idea what could be doing this, do you have problems outside of ACRE2 at any time? Robotic voices could mean babel is enabled.

**Comment by ownedarg** [comment]
All player are experiencing this issue. The teamSpeak Channel is using Opus Voice codec, i tried with other codecs and same result.

**Comment by jonpas** [comment]
There are a lot of `[ACRE] (sys_io) INFO: Pipe error: Read Loop CreateFileA WinErrCode: 231`
Are you starting both Arma 3 (Steam) and TeamSpeak 3 as admin, or both as regular user?

Can you upload your server RPT and server config (remove passwords of course)?

**Comment by ownedarg** [comment]
Sorry for the delay here is what you requested:

Server RPT: https://pastebin.com/rBCuzqDR
server config.cfg: https://pastebin.com/DGEDjCAx

Executing both TS3 and Arma3_x64 as admin.

I tried model interference on/off on cba settings but no go, same with TeamSpeak channel name and Automatic Switch.

EDIT: The 'robotic' voice we hear is very babel-like. As when you are talking to someone who you don't share the language with.

**Comment by ownedarg** [comment]
# SOLVED!

We eliminated 'Basic Mission Setup' Module and now we can hear each other again.

Thank you for your willingness to help.

**Comment by ownedarg** [comment]
# Solved!

We tried resetting the 'basic mission setup' module and tinkered with Babel setting.

No babel: robot voices
Per side w/ common: robot voices
Per side: **works ok**

if you delete the module: **works ok**

Hope this has been helpful to you.

**Comment by ownedarg** [comment]
Closed it on accident. Left it open in case you want to add something.

Thank you!

**Comment by jonpas** [comment]
Then it was indeed babel setup messing it up! Looks like same issue as #412, will close this as duplicate, you can track progress in the other issue.

**Comment by jonpas** [comment]
Is actually separate issue, same as reported by @Cuel on Slack, reopening.
