### ISSUE TITLE
Virtual Arsenal assigns radio IDs

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#426]
We should not run ID assignment when in Virtual Arsenal.

Not sure if we can catch when you "Try" the loadout through it though.

**Comment by Cuel** [comment]
A CBA arsenal display load / unload EH enough?

**Comment by jonpas** [comment]
There are `arsenalOpened` and `arsenalClosed` EHs, but we don't want to unassign IDs on each close, we just don't want to load them (or even better, save them or have them in export).

I am not sure if Eden Arsenal has the same issue either. Needs further research to see where exactly we may want to handle it.
