### ISSUE TITLE
152 Transmission Cut Out

### ISSUE THREAD

**Issue by Pironesis** [IDI-Systems/acre2#428]
Arma 3 Version: 1.76 (stable)
CBA Version: 3.4.1 (stable)
ACRE2 Version:2.5.0.969 (dev )

**Mods:**

- CBA_A3
- acre2
-Ace 3

**Description:**
- When setting the 152 to play in only left or right ear, no transmissions are heard by the player. As soon as it is switched back to both ears they are heard again. 

**Steps to reproduce:**
- Have someone transmit on 152.
-Set 152 to right ear whilst other player is transmitting.
-Observer transmission cut off.

**Where did the issue occur?**
- Dedicated

**Comment by Tittoffer** [comment]
Was the radio `Set to active` while you changed ear?

**Comment by Pironesis** [comment]
It happened in both cases, active or not.

**Comment by Pironesis** [comment]
Now started encountering this with other radios. Had it last night with a 343 when setting it to right ear only. Radio beeps died and i could not hear people talking on the radio. Using 981.

**Comment by TheMagnetar** [comment]
OK. I will check. Is it only  happening when changing the setting when the player is receiving a transmission or does it happen always?

**Comment by Pironesis** [comment]
It seems to be consistent, whenever you change to only left or right ear incoming transmissions die.

**Comment by TheMagnetar** [comment]
I could not reproduce this. Whenever I change to left or right ear, i can always hear them... what sort of speakers are you using? Is anybody else experiencingredients this effect?

**Comment by Soldia1138** [comment]
How are your TS Settings regarding Surround Settings?

Do you use a virtual 7.1 USB Headset?

**Comment by Pironesis** [comment]
Hmm, i have had sporadic reports from other users in my community with the issue. My TS is using mono to stereo settings in the playback menu. However my headset does use virtual 7.1 surround sound. Do we think that could be an issue?

**Comment by Soldia1138** [comment]
Yes, absolutely. We had this in the past. Reason is that the virtual 7.1 surround sound isn't fully compatible with the 3D System from TS. You should be able to reproduce the following: 
- Two players (you and another one)
- You standing still
- The other one's running circles around you talking continously, always facing towards you

**Intended** behavior: Realistic 3D Sound, with you being able to locate the other player without even looking
**Probable** behavior: A certain area, where the other player isn't hearable at all. 


You can, however play around with the following TS Settings (under "playback"):
![image](https://user-images.githubusercontent.com/10269712/36098151-22ac183a-0ffe-11e8-9050-e33a4494cadf.png)

**Comment by TheMagnetar** [comment]
Any update on this?

**Comment by Pironesis** [comment]
Hi, sorry for the lack of an update. I have tried with changing the playback options in TS. But to no result, might just have to change from playing arma in 7.1 which is sad, but not the end of the world.

**Comment by Drofseh** [comment]
I always play ARMA in 7.1 virtual surround and haven't had this problem so there is likely more to it than that.

**Comment by TheMagnetar** [comment]
@Drofseh not really. It depends a lot on the virtual emulation. Some do it better than others. @Twelvecaliber did the change to 5.1 solve the issues?

**Comment by Pironesis** [comment]
Unfortunately the software doesn't support virtual 5.1 only 7.1.

**Comment by TheMagnetar** [comment]
Any update?

**Comment by Soldia1138** [comment]
As there seems to be no update, I'll close this. Reopen whenever there are new issues
