### ISSUE TITLE
Volume control for vehicle intercom (feature request)

### ISSUE THREAD

**Issue by A-killer-Wombat** [IDI-Systems/acre2#429]
What it says on the tin really. There have been many times where I've wanted to lower the volume of the crew or pax intercom in real-time (similar to how you can adjust the volume of different radios).

It would also be useful to have the option to select left or right ear only for the intercom audio similar to radios.

**Comment by jonpas** [comment]
Is going to happen once we get proper UI for intercoms, already planned.

Leaving open to prevent future duplicate requests.

**Comment by A-killer-Wombat** [comment]
Thought it was likely to already be planned. Thanks for replying so quickly.
