### ISSUE TITLE
ACRE Muting Teamspeak

### ISSUE THREAD

**Issue by Dankrid** [IDI-Systems/acre2#432]
**Arma 3 Version:** `1.76` stable 
**CBA Version:** `3.4.1` stable
**ACRE2 Version:** `2.5.0` stable

**Mods:**
```
- CBA_A3
- acre2
-ace
-acex
-bundeswehr and ace compat
-CUP CORE, MAPS AND CWA
-celle 2
-MBG buildings
-RHS [US, RUSSIA, SAF, GREF, ALL ACE COMPATS]

**Description:**
- Any time that I connect to a server and ACRE connects to Teamspeak, all sound in teamspeak is muted. This includes other people and all notifications. It's not just that I can't hear it either, teamspeak doesn't make any noise as shown in the volume mixer.

**Steps to reproduce:**
- See above

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- Unknown, it's not any specific mission

**RPT log file:**
-https://pastebin.com/zemZGUwp [ARMA]
-https://pastebin.com/bUJ98qUY [ACRE]

**Comment by TheMagnetar** [comment]
If I understand it correctly this happens to you when you enter a game session. ACRE  will mute all players that are not in-game automatically. This is a design decision. You can still hear other players and communicate with them right?

**Comment by Dankrid** [comment]
This is not the case. I cannot hear anything from teamspeak at all. It completes destroys all output from teamspeak

**Comment by Dankrid** [comment]
I have a new computer as of yesterday. ACRE's working fine on this one so it must have been a local issue. I can no longer provide info on this problem if it comes up for anyone else

**Comment by TheMagnetar** [comment]
Perfect, thanks for the report. Closing the issue.
