### ISSUE TITLE
"Racks" interaction point for vehicle radios is superfluous

### ISSUE THREAD

**Issue by Drofseh** [IDI-Systems/acre2#468]
**Arma 3 Version:** `1.78` (stable)
**CBA Version:** `3.5.0` (stable)
**ACRE2 Version:** `2.5.1.981` (dev)

**Mods:**

- CBA_A3
- ACE3
- acre2

**Description:**
The `Racks` interaction point for vehicles radios is an unneeded step that provides no concrete benefit and hinders quick access to the radio interaction points.
https://gyazo.com/5d3712900b184a1b713bf45b71dbeca7

I suggest removing it and moving the individual radios closer to the centre position.
https://gyazo.com/885d390be3ddf2861c7f36b14d694364

**Comment by jonpas** [comment]
There are 2 racks in that specific vehicle. In some vehicles you can have 4 and more, that gets cluttered very very fast. And that is the reason they are sub-interactions. It also mimics "Radios" interaction point.

**Comment by Drofseh** [comment]
Which vehicles have four radios?
In https://github.com/IDI-Systems/acre2/blob/development-build/addons/sys_rack/CfgVehicles.hpp no vehicle has more than two.

**Comment by Soldia1138** [comment]
Only because there is no example in the default, it doesn’t mean there is none. 
E.g. it is useful if you want to realize a communications central, either stationary or mobile. 
We only provide a framework and it should be as flexible as possible

**Comment by Drofseh** [comment]
Fair enough. I still think that an extra step to get to the radios is silly, especially considering the only other interactions available are also communications related, but I'll close this issue.

**Comment by jonpas** [comment]
Those base actions might even get other functionality in the future.
