### ISSUE TITLE
Radio tx power interface problems

### ISSUE THREAD

**Issue by KarlMoebius** [IDI-Systems/acre2#474]
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACRE2 Version:** `2.5.1` (stable)

**Mods:**
```
- CBA_A3
- ace3
- acre2
```

**Description:**
- PRC117 Tx power level choice, up arrow decreases power, down arrow increases power, which feels backwards.
- PRC152 Tx power level, no matter the user made choice (low, med, hi), the choice structure terminates in "user" setting, and asks to set tx power. (I.e. instead of exiting medium and returning to menu, all choices end with manual tx power input)

**Steps to reproduce:**
- virtual arsenal
- add 152 & 117 to inventory
- navigate to Tx power selection
- try to set Tx power in radios

**Where did the issue occur?**
- Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file and extension log file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3). Extension log file can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Comment by MaHuJa** [comment]
The 117 part of the issue may be the acre representation being authentic to the real thing? 
(Reputable source, like somebody who operated the real thing, needed.)

Basically, they have a list of transmission strengths in increasing order, and you're scrolling down that list.

**Comment by KarlMoebius** [comment]
What feels backwards is in every UI that uses a list, down scrolls "down" by decreasing the number, and up scrolls "up" by increasing the number (an example would be a car radio, selecting the frequency). Here "down" increases the number, and "up" decreases the number, and I didn't know if that was a feature or a flaw but logged it just in case.

**Comment by jonpas** [comment]
@Sniperhid @Soldia1138 know how this works IRL?

**Comment by TheMagnetar** [comment]
This is being fixed @jonpas

**Comment by TheMagnetar** [comment]
The 117F power selection is as expected, with the higher power output at the bottom of the list. The power selection issue, as well as the related menu issues, are fixed in PR #507
