### ISSUE TITLE
No squelch sound

### ISSUE THREAD

**Issue by Opendome** [IDI-Systems/acre2#486]
**Arma 3 Version:** `Stable` (stable / rc / dev)
**CBA Version:** `3.6.1.180131` (stable / dev + commit hash)
**ACRE2 Version:** `2.5.1.980` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
This might not be a issue at all but with the PRC-152s I cant get incoming squelch to work? I have 'b64' whitelisted

allowedLoadFileExtensions[] = {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi","b64"}; //only allow files with those extensions to be loaded via loadFile command (since Arma 3 build 1.19.124216)
allowedPreprocessFileExtensions[] = {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi","b64"};

in server.cfg and the squelch toggle button doesnt seem to do anything?

**Comment by jonpas** [comment]
So you hear the messages normally, just not start/stop voice indicators?

**Comment by Opendome** [comment]
Just tested it out with all the radios and none of them squelch? Sorry about that

**Comment by jonpas** [comment]
Is it just for you or for everyone on the server?

**Comment by Opendome** [comment]
For everyone it seems

**Comment by jonpas** [comment]
Please add server and client RPT.

**Comment by jonpas** [comment]
@Opendome status?

**Comment by phumberdroz** [comment]
We have the same issues with 2 clients i will try to organise the RPTs.

**Comment by jonpas** [comment]
Closing due to no updates and inability to replicate. Please reopen or create a new issue with more information.
