### ISSUE TITLE
Please add these options for ACRE

### ISSUE THREAD

**Issue by jus61** [IDI-Systems/acre2#510]
- TFAR_fnc_getTeamSpeakServerName
- TFAR_fnc_getTeamSpeakChannelName
- TFAR_fnc_isTeamSpeakPluginEnabled

https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions

**Comment by jonpas** [comment]
Valid points, but not priority, accepting contributions of course!
