### ISSUE TITLE
Teamspeak notifications muted

### ISSUE THREAD

**Issue by Jarvvski** [IDI-Systems/acre2#513]
I believe this is more of a question rather than a bug report

Is the muting of teamspeak ‘notification’  sounds also intentional? I know player muting is there for those not in game

If so, is there a way to split the two? I’d prefer to keep notifications on if at all possible

**Comment by jonpas** [comment]
It is intentional, yes. I think we could split them, but I don't think anyone from core developers is going to get around to it, so contributions are welcome!

**Comment by Jarvvski** [comment]
Interesting

I'm new to Arma dev, but not to dev/git in general.
Any parts of the code base you can point me to for quick ref on where it's handling muting etc? Or any references in general?

**Comment by jonpas** [comment]
It is somewhere in the C++ land, the TeamSpeak plugin or Arma-TS extension. You can check how global volume settings are transmitted from Arma to TS and then applied there, should be doable via a similar path. Or even better, "unmute clients" option, that's just a toggle that is then checked. I am not sure about the TS API, maybe someone else from @IDI-Systems/acre-developers knows more, but I am guessing it's just a function call which you'd wrap into a conditional statement (and also call it on setting change).

**Comment by Jarvvski** [comment]
Thanks, I’ll have a look at this and see if I can contribute

**Comment by Jarvvski** [comment]
Been super busy, still haven't had time to look at this. Still very much wanted

**Comment by Coryf88** [comment]
This mutes the Teamspeak notifications:
https://github.com/IDI-Systems/acre2/blob/c877d3e7c97e1ecfd83e0640672a76cfc1ad6972/extensions/src/ACRE2Core/SoundEngine.cpp#L77

However, it's also used to mute everything else for custom mixing of sound output in:
https://github.com/IDI-Systems/acre2/blob/c877d3e7c97e1ecfd83e0640672a76cfc1ad6972/extensions/src/ACRE2Core/SoundEngine.cpp#L78

**Comment by jonpas** [comment]
No further activity, and this is somewhat by design anyways.
