### ISSUE TITLE
Next/Prev channel keybinds on 152 restricted to channels 1-5

### ISSUE THREAD

**Issue by franstam** [IDI-Systems/acre2#515]
**Arma 3 Version:** `1.80.144071` (stable / rc / dev)
**CBA Version:** `3.6.1` (stable / dev + commit hash)
**ACRE2 Version:** `2.5.1.980` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- ace3
```

**Description:**
- When using the channel next and channel previous keyboard binds in controls (default ctrl-up and ctrl-down) for the AN/PRC-152 radio, you can only change channels from 1-5. channels 6-99 need to be done via opening the radio and clicking the PRE + - buttons.

**Steps to reproduce:**
- Open Editor, put down any unit with AN/PRC-152 radio
- open the 152 radio on screen.
- click the PRE + OR - key to verify able to switch channels from 1-99.
- switch to channel 97 for example (any channel from 6-99)
- close 152 radio interface
- press ctrl-up or ctrl-down to switch channels with radio not open
- notice radio jumps to channel 5 before being locked to channels 1-5 only

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- NONE

**RPT log file:**
rpt: https://gist.github.com/franstam/b8a8c3a845ac8caca393f5e4872e9b6a
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file and extension log file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3). Extension log file can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Comment by Soldia1138** [comment]
This is the intended behavior. The reason is that if in a pouch, only the upper channel knob is reachable. And that knob only serves channels 1-5

**Comment by franstam** [comment]
oh, thanks for the prompt reply.

i tested that the other radios are working for whole range in their block: 343/148/SEM 52

**Comment by jonpas** [comment]
That's interesting, didn't know either. :D

**Comment by jonpas** [comment]
@franstam Sorry for making you make the issue, I was not aware that is so either! 😆

**Comment by franstam** [comment]
No problem, but could i make a request?
If its by design in a pouch to be only 1-5, could it be made such that when the radio is open and accessible, the channel next and channel prev keys actually allow serving all channels 1-99?

that would be awesome thanks.

**Comment by jonpas** [comment]
That could work.
