### ISSUE TITLE
No voice and radio on server

### ISSUE THREAD

**Issue by NicoChp** [IDI-Systems/acre2#520]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.1.18` (stable)
**ACRE2 Version:** `2.5.1.185` (dev)

**Mods:**
```
- CBA_A3
- acre2
- ace 3
- acex
- all rhs

**Description:**
When on dedicated server, we have no voice and radio are not working (no icon on bottom right corner), but in local it's working. All addons are up to date on server and running the sames as the clients.

**Where did the issue occur?**
- Dedicated server

**Placed Modules:**
- None, using framework

**Comment by NicoChp** [comment]
Of course, here it is

[arma3server_x64_2018-04-26_12-07-37.zip](https://github.com/IDI-Systems/acre2/files/1950923/arma3server_x64_2018-04-26_12-07-37.zip)

**Comment by Cuel** [comment]
Does it work at all? Or randomly for just some clients? If randomly I think we've had the same issue.

**Comment by TheMagnetar** [comment]
In the RPT there are additional mods loaded. Project Infinite, CUP, etc

Please try to reproduce the issue and upload the rpt files for the mods given in the description

**Comment by NicoChp** [comment]
Ok I found the problem. With the last update of ACE you have to delete the ace_server in userconfig to not be in conflict with cba_settings ...

**Comment by TheMagnetar** [comment]
perfect. Closing the issue.

**Comment by NicoChp** [comment]
Hi guys, just want to re-open the ticket. Exactly the same problem, but this time I didn't touch to my cba_settings.sqf, located in userconfig, filepatching activated on the server. No conflict with the ace_serverconfig because it has been removed.

It's working in solo, but not on the server ...

[arma3server_x64_2018-08-28_02-05-46.zip](https://github.com/IDI-Systems/acre2/files/2326017/arma3server_x64_2018-08-28_02-05-46.zip)

**Comment by TheMagnetar** [comment]
Can you try with only CBA + ACRE (+ ACE). You have a bunch of mods loaded and it is difficult for us to see if there is a mod conflict (which is most probably the case).

I would also suggest to trace the changes you have done to your modset and disable each one of them in order to see what caused the change (filepatching, additional mods, ...). I say this because it was working as expected for some time then suddenly it stopped, and that points to a conflict at your end (ACRE2 did not change).

**Comment by NicoChp** [comment]
I just tried with only ACE + ACE + CBA and it's working ... Will take a look at the addons ...

**Comment by NicoChp** [comment]
Ok so, I removed the addins for the radios animations, and it fixed 2 problems. The infinite loading on the map screen, and apparently the bug with ACRE. Will test again to confirm it is solved.

**Comment by TheMagnetar** [comment]
Feel free to post what caused the conflict. Closing the issue
