### ISSUE TITLE
Error in sys_components\fnc_findAntenna

### ISSUE THREAD

**Issue by tbeswick96** [IDI-Systems/acre2#523]
**Arma 3 Version:** `1.82`
**CBA Version:** `3.7.0 RC`
**ACRE2 Version:** `2.5.1.985` (custom build of 985 build 66 with speakers and antenna elevation merged as well)

**Mods:**
```
- CBA_A3
- acre2
- ACE 3
- CUP (all)
- Alive
- 3cb
- uksf mods (can see pbos in rpt)
```

**Description:**
- RPT spam of error in `sys_components\fnc_findAntenna` when a transmission is received on a racked radio with speaker enabled
```
20:25:04 Error in expression <NG"})) then {
if ((!(isNil {_attributes getVariable  "worldObject"}))) then {
_c>
20:25:04   Error position: <getVariable  "worldObject"}))) then {
_c>
20:25:04   Error getvariable: Type Array, expected Namespace,Object,Group,Display (dialog),Control,Team member,Task,Location
20:25:04 File idi\acre\addons\sys_components\fnc_findAntenna.sqf, line 28
```

**Steps to reproduce:**
- Not sure, let me know if needed

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Full rpt https://gist.github.com/tbeswick96/6dd221217a21514c6c7c2031cda1a3a8.
- Isolated error message rpt https://gist.github.com/tbeswick96/cade2a71f0b56d7b86f43b2ee8f27bd9

**Comment by jonpas** [comment]
Is this still the case?

**Comment by tbeswick96** [comment]
I do still see this error, but have not updated my modpack's acre version. I'll update to dev when I can and report back

**Comment by jonpas** [comment]
Any news?

**Comment by tbeswick96** [comment]
Fraid not, not played the game for a few weeks personally so not been able to test

**Comment by jonpas** [comment]
I just experienced this this weekend. My game crashed (DX11 error), I had a 343 on me and was connected to a 117F in a helicopter rack.

I reconnected, both radios continued to work fine, however every time a transmission came through on the racked 117F, I got above script error. It continued to work well (maybe too well?) and only appeared on that specific rack.

Unusing and using it again didn't help the issue. Using another 117F worked fine, but I didn't try another racked 117F.

**Comment by jonpas** [comment]
Happened today again, in an MELB (helicopter), racked 117F. @TheMagnetar @Soldia1138 any ideas? Where does `worldObject` come from in the first place?

**Comment by tbeswick96** [comment]
I get this spammed into my logs when someone is talking on a radio and I'm in a vehicle with racks, pretty much every time I play

**Comment by tbeswick96** [comment]
I can't see any other references to `worldObject` in acre at all (only the `HASH_HASKEY` and `HASH_GET`), is it some vanilla thing?
