### ISSUE TITLE
ACE Fast Rope makes radio unusable

### ISSUE THREAD

**Issue by CPTMiller** [IDI-Systems/acre2#541]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `latest` (stable)
**ACRE2 Version:** `2.5.1.989` (dev)

**Mods:**
- ACE
- CBA_A3
- acre2
- RHS

**Description:**
- After testing ACE Fast Rope during a session, we stumbled upon the problem with not being able to communicate with each other on the radio. It had created a new channel called 01-$CCH-Name, with module saying the same on display.
Only way for us communicate was to pickup another radio and drop the malfunction one.

**Steps to reproduce:**
- Spawn down any helicopter with FRIES capable, and put this on.
- Get into helicopter
- Fast rope

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- N/A

**Images**
https://i.imgur.com/iYkIgTL.jpg

**RPT log file:**
- N/A

**Comment by jonpas** [comment]
This is funny!

**Comment by TheMagnetar** [comment]
So, without FRIES it works, with FRIES it does not?! Can you attach the RPT?

**Comment by TheMagnetar** [comment]
Also, what radio was affected since you say you dropped it? Rack radio or personal radio?

**Comment by CPTMiller** [comment]
Heres the RPT, but I did not find anything resembling the reason.

Due to not being able to upload on github, I provided a google drive link instead.
https://drive.google.com/file/d/1NxEQ_4jzXQS-Eh9bKHyrURXpsEw8PoaW/view?usp=sharing

This happened to all radios we use. PRC 343, PRC 152 and PRC 117F

**Comment by TheMagnetar** [comment]
What is really strange... it does not affect racks but personal radios...

**Comment by TheMagnetar** [comment]
This error happens when assigning a non-existent preset.

**Comment by TheMagnetar** [comment]
@CPTMiller OK. Something I find dangerous:

```
[ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (SGT Scottacre_prc343_id_21) idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:192
[ACRE] (sys_server) WARNING: Id object relation created independently of unique ID creation process (acre_prc343_id_2)! idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:246
[ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (SGT Blackwellacre_prc343_id_2) idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:192
[ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (SGT Blackwellacre_prc117f_id_2) idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:192
[ACRE] (sys_server) WARNING: Id object relation created independently of unique ID creation process (acre_prc117f_id_5)! idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:246
[ACRE] (sys_server) WARNING: Id object relation created independently of unique ID creation process (acre_prc343_id_13)! idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:246
```
There are quite a lot of them. Are you using a gear script?  I also noticed that ctab is loaded. Can you reproduce the issue without any gear script and  only with CBA + ACE + ACRE?

**Comment by CPTMiller** [comment]
I can try atleast :) But were using ACE Arsenal, so maybe this is the same problem happening with TFAR, where you get the same unique ID if getting radios from Arsenal?

**Comment by TheMagnetar** [comment]
I could get into a PC with A3 and I could not reproduce the issue. Here are the steps I followed on a dedicated server:

1) Assign an PRC-152 and PRC-117F
2) Spawn a UH-60 (RHS) using Zeus
3) Assign Fries using the ACE Module
4) Get In. 
5) Radios still have the right preset applied.

**Comment by CPTMiller** [comment]
Yea but did you fast rope? It was after we were on the ground this started to happen.

**Comment by TheMagnetar** [comment]
ahhh. OK. Will try.

**Comment by TheMagnetar** [comment]
@CPTMiller I still could not reproduce the issue.

**Comment by CPTMiller** [comment]
Okay. I will continue my experimentation. You can consider this issue closed for now.

**Comment by TheMagnetar** [comment]
Try to reproduce it with an empty mission and zeus. I am still interested in why you had no preset applied to personal radios

**Comment by CPTMiller** [comment]
https://github.com/acemod/ACE3/pull/6387

**Comment by PabstMirror** [comment]
I don't really think that PR will really help with this issue.

All that would have happened was ace would be creating multiple new helicopters (helpers).
They would have racks init.
But the player never got in those helpers, so I don't think it should have effected radios at all.

**Comment by CPTMiller** [comment]
I dont know. It was just all wierd. We will be doing some more tests, to see if we can get the same issue with just cba, ace and acre.
