### ISSUE TITLE
Radio bug when loading loadouts.

### ISSUE THREAD

**Issue by shol9570** [IDI-Systems/acre2#546]
**Arma 3 Version:** `1.82` (stable / rc / dev)
**CBA Version:** `3.7.1` (stable / dev + commit hash)
**ACRE2 Version:** `2.5.1.980` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- ace3
```

**Description:**
- Can listen radio, but can't transmit radio.
- It always happens when load loadouts that include radio on arsenal.
- But sometimes it does not happen after restart game even load loadouts that include radio on arsenal.

**Steps to reproduce:**
- save loadout with radio.
- public your loadout to others.
- let others load your loadout.
- and it happens.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None.

**RPT log file:**
- None. (cause it not happend for me)

**Comment by Soldia1138** [comment]
Can you provide your loadout script and loadout file?

**Comment by shol9570** [comment]
I don't have that loadout now (cause loaded others' loadout). But I'll when it happens again. (today also happend in Altis)

**Comment by TheMagnetar** [comment]
when saving your loadout with setUnitLoadout and read it whith  getUnitLoadout or any form of saving/storing a loadout, make sure you  are not saving any radios with unique ID, like 'acre_prc343_id_1' or "acre_prc152_id_1". It won't work because the unique radio ID is assigned to you and not to anybody else.

**Comment by shol9570** [comment]
@TheMagnetar OK. I'll try not to save with unique ID (or with any radio). thank you for your comment

**Comment by TheMagnetar** [comment]
you can save it with a non-unique radio ID or make an script that substitutes the unique ID with a  non unique one: For example, something that changes 'acre_prc152_id_4' with "ACRE_PRC152"

**Comment by jonpas** [comment]
This should be handled automatically in Vanilla Arsenal and ACE3 Arsenal loadouts. However only since ACRE2 version 2.5.1.

**Comment by tbeswick96** [comment]
@shol9570 This snippet will sanitise a getUnitLoadout format loadout of radio IDs
https://pastebin.com/UJ9c6zJc

**Comment by TheMagnetar** [comment]
I will close this bug since it is more a problem of how unique IDs  are treated. If you still think that this is a  bug, I will reopen.
