### ISSUE TITLE
Cannot find ACRE2 on Steam Workshop any longer

### ISSUE THREAD

**Issue by mwpowellhtx** [IDI-Systems/acre2#549]
Was it removed recently for some reason? What happened to it? I had only just received the 2.6 update, but now I cannot find it in the workshop any longer.

**Comment by PabstMirror** [comment]
Shows up in the list of mods here: https://steamcommunity.com/profiles/76561198323575101/myworkshopfiles/

but when clicking on it says 
`The item is either marked as hidden or you do not have permission to view it.`

Might just be steam acting funny, or visibility was changed.

**Comment by Sniperhid** [comment]
Issue fixed - Thanks for letting us know.

Steam hid it because we hadn't yet accepted the latest version of the steam workshop license agreement after publishing the update (an automated process for us).

**Comment by jonpas** [comment]
Thanks for the quick bump and quick fix @Sniperhid.
