### ISSUE TITLE
thingx objects don't support racks

### ISSUE THREAD

**Issue by AndreasBrostrom** [IDI-Systems/acre2#553]
**Arma 3 Version:** `1.83.144870` dev
**CBA Version:** `3.7.1` stable
**ACRE2 Version:** `v2.6.1.992` stable

**Mods:**
```
- CBA_A3
- ace3
- acex
- acre2
```

**Description:**
- `thingx` objects don't support racks.
- (Unless not a bug) Support for the feature on some `thingx` objects (Laptops and other reasonable electronics)

**Steps to reproduce:**
- add `[this, ["ACRE_VRC103", "My Special External Radio", "ERadio", false, ["external"], [], "ACRE_PRC117F", [], []]] call acre_api_fnc_addRackToVehicle;` to a chair, crate or laptop.

**Where did the issue occur?**
- Editor (Singleplayer)
- Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- https://gist.github.com/ColdEvul/9488270f0c22723b85d2b0b87391dc27

**Comment by AndreasBrostrom** [comment]
Running this in the debug console works and add the functionality:
```
[cursorTarget, {}] call acre_api_fnc_initVehicleRacks;
[cursorTarget, ["ACRE_VRC103", "My Special External Radio", "ERadio", false, ["external"], [], "ACRE_PRC117F", [], []],false, {true}] call acre_api_fnc_addRackToVehicle;
```

This does not work on init.

**Comment by Bosenator** [comment]
Per our group findings, it has to be run by a player - debug console is seemingly doing that. Works if you add to a players init remotely on to the object. Hypothetically, you could add to initPlayerLocal and do a one-time only check on top per mission. Haven't tested that yet, but we will be trying that later.

**Comment by jonpas** [comment]
Correct, racks have to be initialized by a player. @TheMagnetar can provide more information.

**Comment by AndreasBrostrom** [comment]
I threw this together not sure if it works yet but figured i could share it:

```
params [
    ["_vehicle", objNull, [objNull]],
    ["_radio","ACRE_PRC117F", [""]]
];

_vehicle addAction [
    "Setup HQ Radio System", 
    {
        params ["_target", "_caller", "_actionId", "_arguments"];
        [_target, {}] call acre_api_fnc_initVehicleRacks;
        [_target, ["ACRE_VRC103", "HQ Radio", "ERadio", false, ["external"], [], _arguments select 0, [], []],false, {true}] call acre_api_fnc_addRackToVehicle;
        _target setVariable [QEGVAR(object,hq),true];
    },
    [_radio],1.5,true,true, "",
    "(isNil {_target getVariable 'cscripts_object_hq'});",
    10,false,"",""
];
```

**Comment by jonpas** [comment]
Can this be closed?

**Comment by AndreasBrostrom** [comment]
will check stand by

**Comment by AndreasBrostrom** [comment]
Still the case

**Comment by jonpas** [comment]
What we could do is provide later initialization on first player that connects. So queue it up on the server, send to first client.

@TheMagnetar thoughts?

**Comment by 7cavZlobinN** [comment]
What would be a current workaround for initializing racks on an object until this is fixed?

**Comment by jonpas** [comment]
This went off the original issue direction. Racks initialization could use some work or at least documentation, but that is for another issue.
