### ISSUE TITLE
Add function to set speaker mode on compatible radios

### ISSUE THREAD

**Issue by Sweedn** [IDI-Systems/acre2#555]
Hello, could we have the possibilty to : 
- Set radios in speaker mode without any player action
- Add the possibilty to "lock" radio in speaker mode, interesting in TvT scenarios
- Perfect for designing mission when there isn't headset yet or too expensive for soldiers to afford (WW2 era or low-tech armies)

**Comment by TheMagnetar** [comment]
Making an API function for configuring the speaker mode makes sense, on the other hand, locking a radio in speaker mode makes very little sense to me at the moment.

**Comment by xetra11** [comment]
Yea speakermode would be pretty cool!

**Comment by Ginganinja82** [comment]
This would be awesome !, even just in the init to set the speaker on load ? Idea is to have a "general [AI]" in base to broadcast what's going on in the field when new players join.. could be a nice feature for immersion ?

**Comment by TheMagnetar** [comment]
I do not think that what you propose is possible

**Comment by Jason-Terry** [comment]
I know this is only 23 days old, but isn't this feature working on the 152 and the 148?

If so, I wouldn't mind taking a stab at extending it to the 177f and 77, with some small direction I could also work on this and make a PR.

**Comment by TheMagnetar** [comment]
There is no speaker directly on the 77 or the 117f. They would need to be implemented either as a component or through racks

**Comment by Jason-Terry** [comment]
> There is no speaker directly on the 77 or the 117f. They would need to be implemented either as a component or through racks

I see. I know the AN/PRC-117 we used the in USMC had a speak attachement that you could use in replacement of the handset.

So we would need to implement a simple component, that can be linked to the 177f, and it just needs to replace the origin point of the 177f sounds?

I am going to dig around at some of the components already in game, see if I can't gather how they work as.

**Comment by milivojm** [comment]
https://wiki.clearbackblast.com/guides:acrespeakers

148 and 152 have speakers but they don't work well as speakers. We've just tested it and people can hear transmission like it's in their head, not like speaker audio coming from the receiver. Don't know if to open a new issue or just let it all here.

**Comment by jonpas** [comment]
Done in #1038.
