### ISSUE TITLE
ACRE UI Hints obscuring Zeus

### ISSUE THREAD

**Issue by DMZDaishi** [IDI-Systems/acre2#557]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACRE2 Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- Zeus/ARES
```

**Description:**
When Zeusing and using ACRE, the UI elements that report opening pipes and closing pipes either linger far too long (30 seconds for the 'ACRE has recovered from closed pipe' to disappear) or don't disappear at all 'WARNING: ACRE not connected to Teamspeak!'. 

As Zeuses, we do not need this black box obscuring our view and preventing screenshots and as players, we should at least have an option to to toggle these UI elements off entirely, or set a shorter delay for them disappearing.

Having ACRE off while Zeusing is useful as it allows us to hear our players without necessarily being near them, and toggling ACRE on and off prevents one from recording effectively or taking screenshots if you like to avoid these ugly boxes.

**Solution:**
- Give players the option to remove the UI elements introduced by ACRE via ACRE config menu
OR
- Have the popups obey the showHUD false; command that hides _all_ other UI elements.
OR
- Give players the option to manually set the time to fade for these popups via the ACRE config menu or console commands.

Since these are all opt-in solutions, new players won't be affected.

 
**Steps to reproduce:**
- Be Zeus. Use ACRE and turn the plugin off via hotkey. Observe the warning lingering forever. Turn plugin back on and observe recovered from closed pipe message linger for 30 seconds.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None relevant.

**RPT log file:**
- None relevant.

**Comment by CNTODachi** [comment]
Yeah this is a big issue for myself also.

It can ruin great screenshot opportunities and it is not really needed at all. 

Should be an option to toggle this off.

**Comment by jonpas** [comment]
It is an ordinary Arma hint. Rework of the "notification system" UI is in the works.

**Comment by DMZDaishi** [comment]
Any chance we'll see that rework in the next month? If not, with a little tinkering and pseudocode I got here:

https://pastebin.com/JVTd5JvT

Basing it on a boolean that we can set in either console or in settings by creating a checkbox.

How difficult would it be for you to implement this short term and how can I help?

**Comment by jonpas** [comment]
Rework might happen, but not as part of a release (dev-build maybe, if you're using that).
Am I correct in assuming this is only a problem when you are in Zeus-only (meaning there isn't a unit you spawn into, but you go directly into Zeus)? Or is it when you want to talk to possible other Zeuses and don't have ACRE enabled on purpose?

If it's the latter (or similar) I think you could help us by preparing a pull request to add your muting UI as a proper CBA setting. I can see that still being used even with the rework (as you wouldn't want any kind of markers notifying you something you know anyways).

In the meantime you can just run `hintSilent "";` in a PFH as well.

**Comment by jonpas** [comment]
Should be a lot better with 2.6.2, however we are planning to improve it further (fancy icons etc.).
