### ISSUE TITLE
Voice direction is derived from camera, not unit orientation

### ISSUE THREAD

**Issue by freghar** [IDI-Systems/acre2#558]
**Arma 3 Version:** `1.82` (stable)
**CBA Version:** `3.7.0` (stable)
**ACRE2 Version:** `2.6.1` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
When in Curator (or any other external camera), the position for direct chat stays with the player unit, but orientation is derived from the external camera. This is because of

```sqf
// ref bug: http://feedback.arma3.com/view.php?id=15580
private _projectPos1 = ATLtoASL positionCameraToWorld [0,0,0];

private _projectPos2 = ATLtoASL positionCameraToWorld [0,0,1];

ACRE_LISTENER_DIR = _projectPos2 vectorDiff _projectPos1;

if (!ACRE_IS_SPECTATOR) then {
    ACRE_LISTENER_POS = eyePos acre_player;
} else {
    ACRE_LISTENER_POS = _projectPos1;
};
...

CALL_RPC("updateSelf", ACRE_LISTENER_POS + ACRE_LISTENER_DIR + _additionalValues);
```
in `sys_core/fnc_updateSelf.sqf`.

The correct approach would probably be to calculate `ACRE_LISTENER_DIR` from the orientation of `acre_player` for the first condition part and use the current `vectorDiff` for the second part. Maybe something like `vectorDir acre_player`.

I'll submit a PR if I manage to find somebody to test this on. Feel free to provide feedback regardless. Thanks.

**Steps to reproduce:**
- Join a MP game as a regular soldier unit with a Curator instance assigned
- Open up Curator
- Let another player near your player unit speak in direct chat
- Rotate Curator camera and observe voice direction changing

**Where did the issue occur?**
- Dedicated

**Comment by TheMagnetar** [comment]
You can submit the PR as well...

**Comment by kymckay** [comment]
Relates to #376

**Comment by freghar** [comment]
Okay, so this is not as simple as it seems since Arma 3 doesn't simulate `vectorUp` for soldiers and thus the `vectorDir` is different to the old value when the player is looking up/down. In practice, this is not an issue (tested, switching the algorithm via keypress, couldn't tell the difference) for one reason or another.

The problem might be with left/right tilting - not generally an issue for a soldier unit (leaning doesn't tilt the camera) except some situations (weapon deployment), but can be a factor for vehicles (open M2 position on a humvee), for which simply taking `vectorUp` of the vehicle should suffice.

I'll do some more testing, but am not sure if the end result wouldn't be worse than the current state.

**Comment by TheMagnetar** [comment]
@freghar any updates?

**Comment by freghar** [comment]
Sorry, I didn't really investigate that much further.

The basic idea of using a camera position probably isn't as crazy as it first sounded; Arma has many modes / positions in which a player "view point" can be and not all of them are necessarily tied to the unit position/tilt.

So using the camera might be actually preferable, ... assuming fixing the glaring exception of a Curator camera (I think there's another thread for it).
