### ISSUE TITLE
Vehicle adds new PRC-343 upon entering, repeatedly

### ISSUE THREAD

**Issue by Otter8tor** [IDI-Systems/acre2#559]
**Arma 3 Version: 1.82.144710
**CBA Version: 3.7.1.180604
**ACRE2 Version: 2.6.1.992
CBA_A3
ACRE2
ACE
IFA3_AO_Lite (Iron Front)

Description:
-Upon entering an Iron Front tank, the player's inventory is given a new an/prc-343. This occurs every time the player enters the vehicle. 

This does not occur when using vehicles from other mods such as Faces of War's M4A2 tanks. 

This may be due to a config or setting I am not aware of, however I could not find anything mentioning this sort of occurrence.

Tested with: LIB_M4A3_76 and LIB_M4A3_75

Where did the issue occur?
- Singleplayer / Editor (Singleplayer)

Placed Modules:
- None

RPT log file:
https://pastebin.com/mu3Vj0QG

**Comment by TheMagnetar** [comment]
Thanks for the report. This is a problem with the IFA3 mod  and it is not caused by ACRE2.

The only way I have been able to solve it is through an CBA "vehicle" event and remove the radio. I honestly do not know what IFA3 does, as it is exclusively a problem with that mod. I can provide you with the  Code if you are  interested, but we cannot fix it in ACRE itself.

**Comment by Otter8tor** [comment]
Thank you, I suspected it would be an issue with the IFA3 mod, but I wanted to be sure. The code would be much appreciated.

**Comment by TheMagnetar** [comment]
Here you are. I bet it  can  be improved, but I just hacked it  before a mission start...

```sqf
["vehicle", {
    params ["_player", "_newVehicle"];
 
    if (_newVehicle == _player) then {
       {
            if (_x select [0, 14] isEqualTo "acre_prc343_id") then {
                 _player removeItem _x;
            };
        } forEach ([] call acre_api_fnc_getCurrentRadioList);
    } else {
        [{
            params ["_player"];
            {
                if (_x select [0, 14] isEqualTo "acre_prc343_id") then {
                    _player removeItem _x;
                };
            } forEach ([] call acre_api_fnc_getCurrentRadioList);
        }, _player, 2] call CBA_fnc_waitAndExecute;
    };
}, true] call CBA_fnc_addPlayerEventHandler;
```

**Comment by Drofseh** [comment]
Just put this in your mission's `init.sqf` file.

`LIB_GLOBAL_ENABLE_RADIO_IN_VEHICLE = false;`
