### ISSUE TITLE
Compatibility issue with RHS intercom on bench fire pos in UH60

### ISSUE THREAD

**Issue by AndreasBrostrom** [IDI-Systems/acre2#562]
**Arma 3 Version:** `1.82.144710` stable
**CBA Version:** `3.7.1.180604`stable
**ACRE2 Version:** `2.6.1.992` stable

**Mods:**
```
- CBA_A3
- acre2
- ACE3
- ACEX
- RHS
```

**Description:**
- When attempting to connect to the intercom (PAX, Crew) when on any of the the door bench position of a UH60 you are not given the option.
- Everyone else except for the door bench positions have the option.

**Steps to reproduce:**
- Place down a RHS UH60
- Place your self in one of the for door benches connect to the PAX or CREW intercom.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by TheMagnetar** [comment]
Unfortunately this is an issue with the mod itself and can only be solved through a compatibility patch. Contributions are welcome and we can provide a place to upload these compatibility patches (like in ACE) but we will not be supporting them officially.

Understand please, that we cannot support every mod and every vehicle with the current man-power, but as mentioned before, you are more than welcome to help us with this issue.
