### ISSUE TITLE
Updated client side TS not connected to ACRE

### ISSUE THREAD

**Issue by mwpowellhtx** [IDI-Systems/acre2#567]
Updated to latest version of TS today v3.2.0, getting ACRE not connected.

Does server side also need to be updated to the same version of TS? Or is this a deeper TS / API related issue? Does not appear as though the SDK itself has updated, so the issue may be client/server version mismatch?

Thanks!

**Comment by TheMagnetar** [comment]
Most probably a TS/API issue

**Comment by mwpowellhtx** [comment]
@Pictureclass Oh! I too had the same issue; wouldn't connect under scenario 1, did connect under scenario 2. I'm glad it wasn't just me.

**Comment by mwpowellhtx** [comment]
@TheMagnetar Are these things not tested? Something apparently fell through the cracks.

**Comment by Cuel** [comment]
Our server is updated and it works fine from what I can tell at least.

**Comment by mwpowellhtx** [comment]
@BaerMitUmlaut That was CI sarcasm, correct?

**Comment by Pictureclass** [comment]
The logs from yesterday. ACRE Initalisation around Line 2200
[Arma3_x64_2018-08-13_20-19-38.txt](https://github.com/IDI-Systems/acre2/files/2287989/Arma3_x64_2018-08-13_20-19-38.txt)

ACRE Log
[acre2.log](https://github.com/IDI-Systems/acre2/files/2287997/acre2.log)
File create in early 2016 ;) 

Server is still on 3.2.0. I will update the server and try to get more informations with 20+ Players without informing them :D

**Comment by TheMagnetar** [comment]
@mwpowellhtx You have to consider that we have no influence on TS development. Upgrading to 3.2.0 causes both ACRE and TFAR plug-ins to misbehave without apparent SDK/API changes, so we cannot really test anything but the final TS product.

While we would like that nothing like this happens, it is unfortunately out of our control.

**Comment by C0kkie** [comment]
What i dont understand why are other voice plugins working like for gta?

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/44501952-a5cfc480-a6d2-11e8-8910-d504ada6921b.png)
**Nice**
[src](https://forum.teamspeak.com/threads/136729-3-2-x-doesn-t-work-with-Task_force_radio?p=460402#post460402)

**Comment by thorwe** [comment]
Client 3.2.2 is in the beta channel and should fix this issue.

**Comment by Soldia1138** [comment]
@thorwe Thanks for the info. We'll look into that asap

**Comment by z3r03nna** [comment]
Is this fixed with the released TS Client 3.2.2 ?

**Comment by dawid2193487** [comment]
seems to be fixed for me with latest stable TS3 but other people I know still got issues

**Comment by thorwe** [comment]
Beta 3.2.3 fixes another crash in playback. That one's not triggered by calling ts3 functions from within audio callback, but there was an increased chance due to the resulting different timing with the audio code slowed down a bit by additional computations in plugins. Hopefully none other slipped through and it fixes the remaining issues.

**Comment by Soldia1138** [comment]
Seems like all issues have been fixed in 3.2.3
