### ISSUE TITLE
Using Basic Mission Setup module to set default radios won't make any difference

### ISSUE THREAD

**Issue by baranelitez** [IDI-Systems/acre2#574]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.8.0` (stable / dev + commit hash)
**ACRE2 Version:** `2.6.1.992` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- ACE
- RHS
```

**Description:**
- Using Basic Mission Setup module to set default radios won't make any difference. The units all spawn with 343's regardless of their rank or type of unit (rhs or vanilla). Trying to put other radios into their inventories and launching the game won't make difference either. They still spawn with 343's.

**Steps to reproduce:**
- Add any unit in editor.
- Add Basic Mission Setup module into the game
- Change the value of "Default Radio 1" from ACRE_PRC343  to ACRE_PRC152
- Notice how units still spawn with 343's.

**Where did the issue occur?**
- Self-Hosted Multiplayer 

**Placed Modules:**
- Basic Mission Setup

**Comment by TheMagnetar** [comment]
The modules were deprecated some versions ago and with 2.6 you should not see them in the editor.

 In addition we cannot speak for rhs units since they are not compatible with cba.

Maybe we can provide a setting for changing the basic radio. I think this will make a lot of sense. 

Nevertheless we would also appreciate you fill the template correctly so that we know what are your acre and cba versions

**Comment by baranelitez** [comment]
I've updated the template. Not sure about the ACRE version though. It states nowhere in game, in launcher or in the workshop.

It's the latest version from the workshop though. And workshop states the latest change to this date (26 June 2018) was "2.6.1.992". Yet I'm still seeing the modules within the editor.

I would appreciate if there's a setting for changing the basic radio. Thank you for your interest and assistance.

**Comment by jonpas** [comment]
Modules should be hidden on any new mission. If you already had it placed in a mission, it will appear visible. We will not fully remove them to not break backwards compatibility, but they will stay hidden. If they are indeed not hidden on a fresh mission, then that's a bug, let us know please.

https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_setItemRadioReplacement.sqf#L12
This API function should let you change the default radio, just call it early in the mission. `initPlayerLocal.sqf` should do the trick perfectly.

We could make it a CBA setting, but that would lower the use-case for mission frameworks.

**Comment by baranelitez** [comment]
thanks for the API function @jonpas . 

It was an old mission but it didn't have acre2 before. 

Let me explain this way: I created this mission, had no idea of an addon called ACRE2, had some other modules such as CBA, ACE and RHS. Months later I added ACRE2 and the module was immediately visible in the editor. 

The issue was posted the day I acquired ACRE2, so no trace of a previous ACRE2 version in the mission.

**Comment by jonpas** [comment]
Oh wait a second! That module is not one of the deprecated ones! That functionality should still work, we will look into it.

I would still suggest API function over it, and we might actually deprecate that module, because of modules running later in initialization, there is some hacky stuff going on.

**Comment by jonpas** [comment]
This module will be deprecated and replaced with API functions or CBA Settings. Part of it already done in #1015 (now #1283).

**Comment by jonpas** [comment]
This now works correctly with #1283. Remaining 2 modules won't get deprecated for now, as they would require replacement API, for which there is little gain compared to modules at this time.

If the module is not placed, any `"ItemRadio"` will get replaced with "Radio Item Replacement" (`acre_sys_radio_defaultRadio`) item.

If the module is placed, but all "Default Radio" attributes are empty, any `"ItemRadio"` will get replaced with "Radio Item Replacement" (`acre_sys_radio_defaultRadio`) item.

If the module is placed and any "Default Radio" attributes are filled out, all unit's radios will be removed and the ones specified in the module will be added.

**Comment by mrschick** [comment]
Apparently when the module is placed but all the "Default Radio" attributes are empty, every radio that matches `acre_sys_radio_defaultRadio` will be removed from the player when initializing.

Need to tests it some more, but I don't think that's expected behaviour?

**Comment by jonpas** [comment]
> If the module is placed, but all "Default Radio" attributes are empty, any `"ItemRadio"` will get replaced with "Radio Item Replacement" (`acre_sys_radio_defaultRadio`) item.

This is how it should work if past me was correct.

**Comment by mrschick** [comment]
But in this case the module is placed and all "Default Radio" attributes are empty, but every radio of class equal to that of "Radio Item Replacement" is removed from the player's Eden-defined loadout.
