### ISSUE TITLE
ACRE 2 will not transmit

### ISSUE THREAD

**Issue by Supdawge** [IDI-Systems/acre2#580]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable / dev + commit hash)
**ACRE2 Version:** `2.6.1.992` (stable / dev + commit hash)

**Mods:**
CUP_Terrains_Maps
CUP_Terrains_Core
CUP_Units
CUP_Weapons
CUP_Vehicles
CBA_A3
RHS_AFRF
RHS_USAF
RHS_GREF
RHS_SAF
ACE
ACEX
Achilles
Camofaces

**Description:**
When i'm in-game I can hear other talking to me directly and I can hear them communicate through the Radio, as for me I can only speak to them directly but can't transmit to them through a radio the box at my bottom right corner will come up when I press Caps-Lock but it will fade away and won't play the radio sound.

**Steps to reproduce:**
- I don't know how to re-produce it.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- 'None'

**RPT log file:**
[acre_dll.log](https://github.com/IDI-Systems/acre2/files/2364381/acre_dll.log)

**Comment by Soldia1138** [comment]
This is a common problem with Arma / TS rights. Please press your TS PTT key (for direct speed) _while_ pressing CAPS LOCK. If you monitor TS on a 2nd Screen, you'll see the blue dot.

Then try a combination of starting Arma and TS as non-admin / admin

**Comment by Supdawge** [comment]
Hey, when I press TS PTT and Default Radio Key they still do not transmit anything, and I've tried the Admin / non-admin multiple times.

**Comment by Soldia1138** [comment]
Does the "Blue Dot" in TS light up when you press the Radio Key?

**Comment by Supdawge** [comment]
Hey, thank you for responding, I went to the game with ACRE and everything I held Caps Lock and in TeamSpeak I have the blue dot and yes I have PTT without delay, so yeah the Blue Dot comes as if I was transmitting but then the transmit icon becomes gold for a split second and fades away also doesn't play any sound.

**Comment by Supdawge** [comment]
Hey, when ever I now hit Transmit I hear a radio sound does that mean it's working now?

**Comment by Soldia1138** [comment]
All radio sounds are played through TS. So it's at least a good sign. 

Did you change anything?

**Comment by TheMagnetar** [comment]
@Supdawge Any updates?

**Comment by Supdawge** [comment]
Yes it is fixed
