### ISSUE TITLE
Add a scalable factor for AI revealing

### ISSUE THREAD

**Issue by freghar** [IDI-Systems/acre2#606]
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0.181012` (stable)
**ACRE2 Version:** `2.6.2.996` (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
With the current setting, an AI unit will instantly identify you on open ground
 * ~91m away when speaking at default volume (3/5)
 * ~52m away when speaking one level lower (2/5)
 * ~12m away when using the lowest volume (1/5)

From experience, this is way too much compared to what players can hear (ie. 1-2m on the quietest setting).

As such, it would be great to have some kind of factor that could be set via CBA settings to scale this down, ie. for stealth-based scenarios. Currently, there is only the on/off toggle.

**Comment by xetra11** [comment]
Good Idea!
