### ISSUE TITLE
Radio Rack disabledPositions array prevents Rx/Tx even when in a position connected to a linked Intercom

### ISSUE THREAD

**Issue by Drofseh** [IDI-Systems/acre2#611]
**Arma 3 Version:** `1.84.144923` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE Version:** `3.12.3` (stable)
**ACRE2 Version:** `2.6.2` (stable)

**Mods:**
```
- CBA_A3
- ace3
- aceX
- acre2
- CUP Weapons/Units/Vehicle (Dev)
```

**Description:**
- When using a custom vehicle radio rack config to disallow radio use when turned out, the turned out player loses the ability to Rx/Tx on that radio even if they can still talk on the intercom that it is connected to.
- Expected function would be that if the player can still talk on the connected intercom then they should be able to Rx/Tx on the radio that feeds through that intercom.

**Steps to reproduce:**
- Create a rack/intercom config with these settings:
```
    class AcreIntercoms {
        class Intercom_1 {
            displayName = "Crew Intercom";
            shortName = "Crew";
            allowedPositions[] = {"driver", "gunner", "commander"};
            disabledPositions[] = {};
            limitedPositions[] = {{"cargo", "all"}};
            masterPositions[] = {"commander"};
            numLimitedPositions = 1;
            connectedByDefault = 1;
        };
    };

    class AcreRacks {
        class Rack_1 {
            displayName = "Radio Set";
            shortName = "Radio";
            componentname = "ACRE_VRC103";
            allowedPositions[] = {"commander"};
            disabledPositions[] = {{"turnedout", "all"}};
            defaultComponents[] = {};
            mountedRadio = "ACRE_PRC117F";
            isRadioRemovable = 0;
            intercom[] = {"Intercom_1"};
        };
    };
```
- Note that `Rack_1` is accessible through `Intercom_1`.
The commander is the only position allowed full control.
Control is disabled when turned out.
- Pack it.
- Place the vehicle down in the editor.
- Get into the commanders seat.
- Check you are connected to `Intercom_1` (Crew) (should automatically connect).
- Connect to `Rack_1` (Radio) using Ace interaction.
- Turn out.
All connection to `Rack_1` is disabled (interface and Rx/Tx).
Expected behaviour is that only the radio interface should be disabled but Rx/Tx should work since the player is still connected to `Intercom_1`.

**Where did the issue occur?**
- Tested in Singleplayer Editor, but test environment shouldn't effect result.

**Placed Modules:**
- None

**Comment by TheMagnetar** [comment]
Thanks. I will have a look at it asap.

**Comment by TheMagnetar** [comment]
@Drofseh I cannot reproduce it the latest dev-build, which has a fix concerning turnedOut positions. Can you confirm it?

**Comment by TheMagnetar** [comment]
Weird because I have the radios as expected...

**Comment by Drofseh** [comment]
Well that's not good.
What vehicle are you testing the config on?

**Comment by TheMagnetar** [comment]
Vanilla tank. I will test with whatever vehicle you have...

**Comment by Drofseh** [comment]
I'm working on CUP's tracked vehicles right now. These are the ones that I've done so far in the dev branch.
- 2S6M
- AAV
- BMP-1/2/3
- Bradley
- Bulldog
- Challenger II
- FV510
- Leopard 2
- M1 Abrams

I've spot checked the BMP-1, the AAV, and the M1 Abrams for this issue and all of them have the same problem.
Here's a recording of my experience in the AAV Unarmed/Command: https://www.youtube.com/watch?v=YiRd6XV8aho

**Comment by TheMagnetar** [comment]
Fix is quite easy for the moment. Just put the intercom  in lowercase

```
class AcreRacks {
        class Rack_1 {
            displayName = "Radio Set";
            shortName = "Radio";
            componentname = "ACRE_VRC103";
            allowedPositions[] = {"commander"};
            disabledPositions[] = {{"turnedout", "all"}};
            defaultComponents[] = {};
            mountedRadio = "ACRE_PRC117F";
            isRadioRemovable = 0;
            intercom[] = {"intercom_1"};
        };
    };
```

**Comment by Drofseh** [comment]
Alright, I'll give that a try and report back after the next CUP dev build.

**Comment by TheMagnetar** [comment]
I am closing this for now. We will reopen it if needed.
