### ISSUE TITLE
Acre bikey doesnt pass verify signatures on dedicated server!

### ISSUE THREAD

**Issue by Megahurt** [IDI-Systems/acre2#613]
**Arma 3 Version  (stable)
**CBA Version:** `3.9.0.10 
**ACRE2 2.6.2.996    Version   11/29/2018

**Description:**
We run a dedicated arma3 server wit verify signatures 2 enabled. We cannot get it to allow players to get on with acre as it says acre pbos are not accepted. Ive copied the acre_2.6.2.9669.bikey  to the keys folder like any other mod.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated Server

**Comment by jonpas** [comment]
Do you run release candidate by any chance? Signatures are broken there for all mods.

This must be something on your side.

**Comment by Megahurt** [comment]
My bad.. All is ok. Sorry. I had the keys in the wrong folder and the error
message denied acre alphabetically and ran out of list space for errors
only showing acre. Thanks for your prompt reply

**Comment by jonpas** [comment]
:+1:
