### ISSUE TITLE
Client-sided radio issue.

### ISSUE THREAD

**Issue by DannyTWC** [IDI-Systems/acre2#617]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACRE2 Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
```
@3cb_baf_equipment;@3cb_baf_equipment_acre;@3cb_baf_vehicles;@3cb_baf_weapons;@3cb_baf_weapons_ace;@ace3;@ace3_optionals;@acex_a3;@anizay;@cba_a3;@ctab;@cup_ace_compatibility;@cup_terrains_core;@cup_terrains_maps;@cup_units;@cup_vehicles;@cup_vehicles_ace_compat;@cup_weapons;@em;@mad_resh;@mbg_buildings3;@rhs_afrf3;@rhs_compatibility;@rhs_gref;@rhs_usf3;@rosche;@ruha;@twc_al_jahra;@twc_config_compatibility;@twc_config_public;@twc_framework;@ukcw;@blastcore;@jsrs-soundmod;@twc_bloodlust;@twc_compatibility;@acre2;
```

**Description:**
- When ingame and using ACRE2, all radios are set to both ears as standard of course. However, if I set any radio to left ear, it's still broadcasting through both. And when setting one to right ear, there's no sound at all.

**Steps to reproduce:**
- Described above.

**Where did the issue occur?**
/ Self-Hosted Multiplayer 

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/vk0SPW25 (RPT File)
- https://pastebin.com/XFDLcDf0 (ACRE_dll File)

**Comment by Soldia1138** [comment]
May you show us your TS Playback Options Menu? (TS -> Options -> Playback)

**Comment by DannyTWC** [comment]
Here ya go.

https://gyazo.com/1011674a490ae5543371f80ee39ad4da

**Comment by Soldia1138** [comment]
If you got the surround feature of your headphones enabled, could you switch that off? TS is known for having issues with that. 

To be clearer why I think of a TS / Setup issue:
The Left/Center/Right Ear feature is accomplished by simple shifting the audio source in the 3D to one side. 
You may check that by joining a MP session with another player. While you stand still, let him run circles around you while talking constantly. If that doesn’t sound like it would in reality (I.e. if you got directions where you hear nothing), it’s most likely a setup issue.

**Comment by DannyTWC** [comment]
The surround feature is off, i doubt that's the problem. I'll give that a try anyhow and keep you updated =)

**Comment by DannyTWC** [comment]
After some testing, that doesn't seem to be the problem

**Comment by Soldia1138** [comment]
Alright. Next steps:

1. Start a game with only CBA/ACE/ACRE
2. Enable the debugConsole ingame and watch (`["acre_prc343_id_1", "getSpatial"] call acre_sys_data_fnc_dataEvent` // radioId may be different but should be ok, if you're alone on the server // Should be -1 for left, 0 for center and 1 for right)
3. If you got speakers or another headphone, you could try that
4. Would be perfect if you can record a video of the behavior

**Comment by DannyTWC** [comment]
I will come back to you tomorrow with a video of said behavior.

**Comment by DannyTWC** [comment]
Upon looking into doing said test, how do you want me to do it? I can't host multiplayer servers and I don't have my own TeamSpeak server.

**Comment by TrainDoctor** [comment]
> 
> 
> Upon looking into doing said test, how do you want me to do it? I can't host multiplayer servers and I don't have my own TeamSpeak server.

Simply go into the editor and place a unit. Click on the unit and play in single-player. Execute the code he specified within the debug run code area and report your results.
[Here's what the console looks like,](https://community.bistudio.com/wikidata/images/thumb/8/83/A3_console_editor.jpg/800px-A3_console_editor.jpg) just in case.
The image is a little old but it's a good reference. 
(Also, ACE/CBA adds some additional debug areas to the left of the main debug menu.
If you need to do this on a teamspeak server I believe this would have been specified.
Best of luck.

**Comment by HenrikFosse** [comment]
Was this resolved? currently having this issue

**Comment by TrainDoctor** [comment]
> 
> 
> Was this resolved? currently having this issue

Does not appear to have been. The user has not followed up on the issue. If you could go through the steps requested of the author seen above it would be very helpful in resolving the issue.

**Comment by HenrikFosse** [comment]
Tested the debug in editor, nothing out of the ordinary (Results came back -1. 0. 1), description of the issue is spot on so i dont see a reason to record it.  Chose left side = sound on both ears, choose both = sound on both, choose right = No sound. Noticed i have almost same model headset as OP, a Steelseries Artic Pro Wireless (whereas he had the Artic 7 Version)

**Comment by TrainDoctor** [comment]
I have a feeling this is likely a hardware issue, or firmware for the headsets. Likely forced spatial sound.

**Comment by TheMagnetar** [comment]
Closing for now
