### ISSUE TITLE
AI Detection Not Working On Dedicated Servers

### ISSUE THREAD

**Issue by ojemineh** [IDI-Systems/acre2#623]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.90` (stable)
**ACRE2 Version:** `2.6.2` (stable)

**Mods:**

- CBA_A3
- acre2
- ACE3

**Description:**
If you have "acre_sys_core_revealToAI" enabled, ai can reveal players, if they are speaking in the "catchment area", depending on the sound-factor the player chooses (TAB). In local hosted missions (or for ZEUS on dedicated), where ai is local to the host, everything is working fine. but, if you are running the mission on a dedicated server, ai is not able to reveal players, because the eventhandler "acre_sys_core_onRevealUnit" is not registered on dedicated servers.

if you are looking into the code (acre2/addons/sys_core/XEH_postInit.sqf), you see at line 99 the eventhandler, wich is raised by the global event in "acre2/addons/sys_core/fnc_enableRevealAI.sqf" (line 64). BUT, in XEH_postInit (line 3) you'll see, that dedicated servers are "kicked out" of the script, therefore the eventhandler never gets registered on dedicated servers.

**Steps to reproduce:**
create a simple mission (one player unit and one enemy outside the line of sight) and run it on a dedicated server. teleporting the player behind a wall (or something), near to the enemy unit and speak in direct speech (like you are doing in normal missions to your team-mates). check, if the ai is turning to you and/or get his knowledge (enemy knowsAbout player) about the player. you will reconize, that the player is NOT revealed to the ai.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- not needed?!

**Comment by ojemineh** [comment]
to solve the problem temporarily, put the following code in the initServer.sqf of your mission:

```
if (isDedicated) then {
	["acre_sys_core_onRevealUnit", { _this call acre_sys_core_fnc_onRevealUnit }] call CBA_fnc_addEventHandler;
};
```

**Comment by TheMagnetar** [comment]
I think it may not be wrong but I will check anyway.

**Comment by ojemineh** [comment]
acre2/addons/sys_core/fnc_enableRevealAI.sqf has to run on clients - true. but, if you want to achieve the goal that acre2/addons/sys_core/fnc_onRevealUnit.sqf is executed on dedicated servers (to affect units that are local to that machine), you have to register the event on dedicated too.

if you do not want to change the acre2/addons/sys_core/XEH_postInit.sqf, you can simple edit the extended postinit in acre2/addons/sys_core/CfgEventHandlers.hpp (line 13).

original:
```
class Extended_PostInit_EventHandlers {
    class ADDON    {
        init = QUOTE(call COMPILE_FILE(XEH_postInit));
    };
};
```

change to:
```
class Extended_PostInit_EventHandlers {
    class ADDON    {
       clientInit= QUOTE(call COMPILE_FILE(XEH_postInit));
       serverInit=QUOTE(call COMPILE_FILE(XEH_postInitServer));
    };
};
```

create new file XEH_postInitServer.sqf
```
#include "script_component.hpp"
if ((Not isMultiplayer) || (Not isServer) || (is3DEN)) exitWith {};
[QGVAR(onRevealUnit), { _this call FUNC(onRevealUnit) }] call CALLSTACK(CBA_fnc_addEventHandler);
```

done ;-)

**Comment by TheMagnetar** [comment]
Huh? It was addressed already in a PR. I just simply forgot to update the comment xD. Plus your solution does not acount for headless clients

**Comment by ojemineh** [comment]
right - i forgot the HC, my fault.
anyways... my intention was to point on the dedicated-server issue. 
i'm sure you will fix that! you guys are doing a great job!

**Comment by TheMagnetar** [comment]
See the attached PR ;) thanks for pointing it out
