### ISSUE TITLE
Custom vehicle radio disables on turnout.

### ISSUE THREAD

**Issue by Neciota** [IDI-Systems/acre2#627]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1` (stable)
**ACRE2 Version:** `2.6.2.996` (stable)

**Mods:**
```
- CBA_A3
- acre2
- ACE3
- ACEX
- CUP Vehicles/Weapons/Units
- CUP Terrains Maps/Core
- Spearpoint
- TWC Config V2
```

**Description:**
I've configured an AN/PRC-77 instead of the regular 117 on a tracked vehicle, but when I turn out the radio disappears. This does not happen on the same vehicle without altered ACRE code (retaining the entry from the base class), but the bug persists if I use the same code with a 117 instead of the 77 I want. Code for the entry is: https://pastebin.com/jeHEeTjQ
Youtube example: https://www.youtube.com/watch?v=gVhDqGpcHDo&feature=youtu.be

**Steps to reproduce:**
- Override the base class entry for an ACRE rack on a vehicle.
- Load up A3, place vehicle in editor.
- Use the radio.
- Turn out.
- Vehicle radio will no longer be accessible.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- [RPT](https://pastebin.com/SgWnHQHp)
[ACRE log](https://pastebin.com/C1EN21mT)

**Comment by TheMagnetar** [comment]
That you use that 117 in the vrc 64 it is normal that it breaks everything  since it is not compatible.

**Comment by TheMagnetar** [comment]
Is this the whole RPT? If a radio gets deleted it should show a message telling that it has been garbage collected.

**Comment by Neciota** [comment]
The 117 I did not use in te VRC64, but in the VRC103. It is indeed the entire rpt.

**Comment by Neciota** [comment]
I had another look; if you turn out while not having the radio in use, the radio stays visible in the top left rack view, but you cannot access it via the ACE interaction menu.

This problem is also an issue with the CUP Challenger 2, that has customized radio racks.

**Comment by Neciota** [comment]
I have found the issue; the radio is unusable when turned out if the assigned intercom isn't present. On the CUP Challenger 2, this manifests on the Bravo radio set because it's missing the assigned intercom to it. On my custom entry it manifests because I entered "Intercom_1"instead of "intercom_1".

**Comment by TheMagnetar** [comment]
Thanks for this. It is already fixed in dev build
