### ISSUE TITLE
ACRE2 'gunner' copilot rack access

### ISSUE THREAD

**Issue by byjokese** [IDI-Systems/acre2#633]
**Arma 3 Version:** `Latest stable` (stable / rc / dev)
**CBA Version:** `Latest stable ` (stable / dev + commit hash)
**ACRE2 Version:** `Latest Stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- RHS USAF
```

The copilot, should have access to vehicle radio, normally the one using the radio is not the pilot for obious reasons :P. 
Any way I can add that ability to the copilot?

**Comment by jonpas** [comment]
I noticed that myself at our joint op Magnetar. I guess we set it to Pilot only for Air class by default?

**Comment by jonpas** [comment]
I see the issue [here](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_rack/CfgVehicles.hpp#L140).

Problem is attack helicopters usually have `gunner` as copilot, not actual `copilot`. But it's very rare that they have both, turrets are usually straight-up `turret`. So I reckon we should add `gunner` to that.

**Comment by byjokese** [comment]
This will also fix the humvee? So Copilot in humvee will have radio access?

**Comment by byjokese** [comment]
Do humvee have "copilot" or is "passenger 2". Because, would be grea to have rack access on "copilot" in humvee

**Comment by TheMagnetar** [comment]
It depends on the mod

**Comment by byjokese** [comment]
Okey thanks.

**Comment by byjokese** [comment]
Well I belive RHS is not willing to change their mod (http://feedback.rhsmods.org/view.php?id=4813), so will try to create my self a patch for adding stack access to passenger number 2.

**Comment by Drofseh** [comment]
Land vehicles don't have copilots anyways right?

Could have a commander role instead though.

**Comment by jonpas** [comment]
@byjokese 
> You can provide compat patches and they can be shipped with acre2. However we cannot maintain them, and the approach will be the same as with ace3

Same as [ACE3 `optionals`](https://github.com/acemod/ACE3/tree/master/optionals).

**Comment by jonpas** [comment]
Let's leave open for #634.
