### ISSUE TITLE
Default and Alt Radio Keys switching radios

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#635]
Currently default keybinds are:
- Default Radio Key: `Caps Lock`
- Alt Radio Key 1: `Shift + Caps Lock`
- Alt Radio Key 2: `Ctrl + Caps Lock`
- Alt Radio Key 3: `Alt + Caps Lock`

"Default Radio Key" button alone works great, however once you pair it with a bound "Alt Radio Key N" it causes switching of radios as soon as you transmit on them, so "Default Radio Key" and all "Alt Radio Key N"s get switched constantly.

I think we should either make "Default Radio Key" not switch the radio to that or propose a change of default keybinds to only use "Alt Radio Key" and possibly provide default keybinds for multiple radios from the start.

I personally use the following keybind setup to solve all my squad lead issues:
- Default Radio Key: `/`
- Alt Radio Key 1: `Caps Lock`
- Alt Radio Key 2: `T`
- Alt Radio Key 3: `Z` (the one next to T, not the one next to X :laughing:)

I think we should keep both functionalities still available (I bet someone finds that switching actually useful?). Naming of those keybinds doesn't help the clarity at all either.

Further ideas welcome.

**Comment by Drofseh** [comment]
I dislike the default radio key and we advise everyone in our unit to unbind it.
It causes a lot of confusion for people who have forgotten which radio they used last and results in a lot of wrong net transmissions.

I use these:
* Default Radio Key: `nil`
* Alt Radio Key 1: `Caps Lock`
* Alt Radio Key 2: `Ctrl+Caps`
* Alt Radio Key 3: `Alt+Caps`

**Comment by jonpas** [comment]
I just had an idea that would clarify a lot and make for better defaults. Leave all functionalities as is, but rename keybinds and set them the following default way:
- Last Used Radio Key: `unbound` (and move below other 3)
- Radio Key 1: `Caps Lock`
- Radio Key 2: `Ctrl + Caps Lock`
- Radio Key 3: `Alt + Caps Lock`

Caps Lock and modifier default for all to not conflict with other keybinds by default.

Thoughts?

**Comment by Drofseh** [comment]
`Last Used Radio Key` name with `Default Radio Key` functionality might not be great.
I think most people consider `used` to mean `transmitted on`, even if they technically used the radio when they switched to it to change the channel or freq, or adjusted the volume, or changed the stereo setting.

Maybe call it something like `Selected Radio` since any interaction functionally selects that radio as the current radio for `Default Radio Key`

**Comment by bovine3dom** [comment]
I'd personally leave last used radio unbound (isn't `/` bound to text chat?). It'd be nice if the radioes were numbered in ACE interaction. Currently I just guess.

I have the following binds:

Radio 1: Caps
Radio 2: Ctrl-Caps
Radio 3: Ctrl-Tab

**Comment by jonpas** [comment]
@Drofseh Agreed on the naming. :+1: 

@bovine3dom Sorry, I used `/` as "unbound". :laughing: So yes, that would be unbound, should have used `nil` - fixed now!

As for numbering, they are already numbered in ACE Interaction, the part of it where you can change which one it is, it's called "Multi-PTT". I wouldn't advise adding more text to base interaction as that will get too long.

**Comment by bovine3dom** [comment]
Ah, I totally misread that. I assumed that was for setting up multiple radioes that you could broadcast on by pressing a single key.

Could it be renamed to "Radio Key" to match the keybinds, and have the number displayed in front of the radio?

E.g, 
```
1: AN/PRC-152
Chn: 1

2: AN/PRC-152
Chn: 2
```

I'd also like it to display which ear it was assigned to if not both, e.g

```
1: AN/PRC-152 (L)
Chn: 1

2: AN/PRC-152
Chn: 2
```

but maybe I'm just asking for too much because I like my UIs to be awful :)

**Comment by jonpas** [comment]
It's possible, but I like to keep same UI for personal radios and racked radios (and those are already 2-liners). You can see both of those information if you just expand the interaction menu, so as soon as you hover over it, it tells you stereo setup and radio key.

We could rename it yeah.

**Comment by bovine3dom** [comment]
https://github.com/IDI-Systems/acre2/pull/636 I reckon it looks fine :)

**Comment by Max255PL** [comment]
Yep, same here, stopped used `Defualt radio key` long time ago and instructed rest of our guys to change it aswell. 
Tho we're using something like this:
Radio 1: Caps Lock
Radio 2: ~
Radio 3: Shift + ~

**Comment by jonpas** [comment]
@Max255PL Thanks, I do think it's best we stick to Caps Lock and modifiers with it as default, just to be sure nothing is in conflict for a pure beginner, rebinding is easy afterwards, understanding what the heck current keybinds do is not.

**Comment by Max255PL** [comment]
Agreed, definitely safer to avoid conflicts. 
My thinking was to avoid using same key with modifiers for similiar things, one finger slip away from using wrong radio.

**Comment by Drofseh** [comment]
Shift should be avoided as a modifier as well, since it will cause most people to sprint when moving.

**Comment by tbeswick96** [comment]
> Shift should be avoided as a modifier as well, since it will cause most people to sprint when moving.

and to start-up an aircraft

**Comment by jonpas** [comment]
Actually realized the default keybinds are:
- Default Radio Key: `Caps Lock`
- Alt Radio Key 1: `Shift + Caps Lock`
- Alt Radio Key 2: `Ctrl + Caps Lock`
- Alt Radio Key 3: `Alt + Caps Lock`

Which doesn't change anything, just found it interesting.
