### ISSUE TITLE
Babel Volume Indicator, Current Ear Pin and Cell Phones

### ISSUE THREAD

**Issue by sagjangi** [IDI-Systems/acre2#640]
Babel Volume Indicator
-Player's current direct speech volume displayed below/with/near the ammo/stance indicator.
-Whisper, Soft, Normal, Yell and Scream.

Current Ear Pin
-Display which ear the radio is pinned to in the channel indicator at the bottom right of the screen when the PTT is pressed.

Cell Phones
-In game object that allows you to access a list of all players in the game that also have a cell phone object in their inventory.
-Other player must accept the incoming call.
-Conference calls?
-Weapons must be holstered to use cell phone.
-Satcom cell phone variant that only has access to a list of players on the same side.
-Static landline object and/or phone booth.
-ACE3 cell phone item has same functionality as ACRE2 phone item.

**Comment by jonpas** [comment]
Always-visible Volume Indicator:
- You can just press `TAB` to see your volume, I don't see much sense in having it always there taking up HUD space.

Current Ear Pin in Transmit/Receive Notification:
- There is space, simple `L/R/B` or arrows could work.
- PRs welcome!

Cell Phones:
- That's a big one.
- PRs welcome!

**Comment by sagjangi** [comment]
> Always-visible Volume Indicator:

> You can just press TAB to see your volume, I don't see much sense in having it always there taking up HUD space.

It's a small thing but it comes up every TvT, people realizing they should have adjusted their volume while in the spectator screen. Maybe make it optional to turn on for groups that would like that input in their HUD.

**Comment by jonpas** [comment]
Spatial setting is now displayed on pop-up since #722. Cell phones are not going to happen.
