### ISSUE TITLE
SEM 70: Problems with changing frequencies

### ISSUE THREAD

**Issue by Timi007** [IDI-Systems/acre2#645]
**Arma 3 Version:** `1.90.145381` (stable)
**CBA Version:** `3.9.1.181229` (stable)
**ACRE2 Version:** `2.6.2.997-141a109d` (dev)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- This issue occurs on a dedicated server with at least 2 players (!) on the server (with and without JIP).
- *Expected behaviour:* If the frequency on the SEM 70 is changed and the PTT button pressed then the radio will transmit through the newly set frequency. Also the newly set frequency will be shown on the display of the SEM 70.
- *Issue:* If the frequency is changed and the PTT button pressed then the radio will transmit through the last (not newly) set frequency. That frequency will also be shown on the display. But adding e.g. 3 MHz results in the change of the newly set frequency, not the displayed one.

**Steps to reproduce:**
- Go on a dedicated server with someone.
- Load a mission (e.g. Testmission)
- Get a SEM 70
- Set the frequency to e.g. 35.000 MHz
- Press the PTT button
- The display at the bottom right and on the SEM 70 shows 30.000 MHz 
- Press one of the frequency knobs
- The frequency will be changed from 35.000 MHz although 30.000 MHz was shown

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Files:**
- [Logfiles.zip](https://github.com/IDI-Systems/acre2/files/2932208/Logfiles.zip)
- [Testmission.zip](https://github.com/IDI-Systems/acre2/files/2932210/Testmission.zip)

**Comment by Timi007** [comment]
This issue still exists in ACRE version: `2.7.1.1016-ff31f44a` (stable)

**Comment by Timi007** [comment]
From [Slack](https://idi-systems.slack.com/archives/C0M39JG23/p1564342713022200): The issue was fixed in Dev Build 1008 (1.94 Arma).

**Comment by TheMagnetar** [comment]
I think it was never fixed.

**Comment by jonpas** [comment]
@Timi007 is this still an issue?

**Comment by Timi007** [comment]
@jonpas I tested it just now and yes this issue still exists in `2.7.3.1024-167bda9c`.

**Comment by Pictureclass** [comment]
thanks jonpas <3
