### ISSUE TITLE
acre2 corruption

### ISSUE THREAD

**Issue by Tibbs22** [IDI-Systems/acre2#660]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACRE2 Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
when I download the mod on the workshop it says corrupted and also if I download the mod from the website and select it like that it still will be corrupted. This started because I was trying to reinstall it because when I loaded in-game with acre2 I couldn't hear Teamspeak at all, not even the notifications.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated

**Comment by TheMagnetar** [comment]
Any antivirus?

**Comment by TheMagnetar** [comment]
Update?

**Comment by jonpas** [comment]
Reopen if you are prepared to give us more information.
