### ISSUE TITLE
ACRE Fails to load GM map

### ISSUE THREAD

**Issue by TomTucka** [IDI-Systems/acre2#661]
**Arma 3 Version:** `1.92`
**CBA Version:** `3.10.1x` 
**ACRE2 Version:** `2.6.2` 

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- Running the new Creator DLC with ACRE produces an error on both versions of the new map. 

(Screenshot below)

https://i.gyazo.com/bb81d618901bbe34f59040548154cf1f.jpg

**Steps to reproduce:**
- Open Eden Editor
- Place any unit down
- Run mission

**Where did the issue occur?**
- Eden Editor

**Placed Modules:**
- None

**RPT log file:**
- [pasetbin](https://pastebin.com/MUZeP9cX)

**Comment by Soldia1138** [comment]
This is due to the encryption (.ebo instead of .pbo) of the map. This means we have to create an additional compat addon which we are currently working on.

**Comment by TomTucka** [comment]
@Soldia1138 Awesome, Just thought I'd report it 😄

**Comment by TheMagnetar** [comment]
Fixed in #662
