### ISSUE TITLE
Use tags for TS metadata

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#665]
I'm not sure if this is not possible due to a limitation of TS3, haven't looked into that.

Right now you have to disable TFAR when using ACRE, and vice versa. TFAR is already using a tag system for the metadata. `<TFAR>datas</TFAR>`. Would it be possible for ACRE to use `<ACRE>datas</ACRE>`

This would allow both plugins to be active at the same time.

**Comment by jonpas** [comment]
I don't see why not, but there is probably a reason why it wasn't done before. @NouberNou ?
