### ISSUE TITLE
PTT keybind issues with Tilde key, build 1001

### ISSUE THREAD

**Issue by Max255PL** [IDI-Systems/acre2#669]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.1` (stable)
**ACRE2 Version:** `2.6.2.1001` (dev)

**Description:**
The PTT1/2/3 key when assigned to Tilde key alone (no modifiers) errors out with this message:
```
16:56:38 Error in expression <s;
_params pushBack _x;

_blockInput = ([_params call _code] param [0, false] is>
16:56:38   Error position: <[_params call _code] param [0, false] is>
16:56:38   Error Generic error in expression
16:56:38 File x\cba\addons\events\fnc_keyHandlerDown.sqf, line 75
```
and results with either:
A) when pressing and releasing immidiately it keeps the transmission live until the next press
B) it starts transmission with a ~1s delay OR immidiately on a quick second press

No change to the error message in both cases. I noticed A first, then after messing with keys and radios it changed to B and stayed that way.

Same controls worked on the same modset/server/etc. but with build 998.

**Comment by TheMagnetar** [comment]
This also happens without having anything assigned to that key.

**Comment by commy2** [comment]
Assigned keydown function reports assignment operator. This is a common problem with SQF:
```sqf
_a = call {_b = 1};
```
Make sure all functions you ever write don't end with an assignment operator. Put `nil` at the end if necessary.

**Comment by jonpas** [comment]
@commy2 all keybinds used in this case return `true` as the last thing in the function.

**Comment by dedmen** [comment]
https://github.com/IDI-Systems/acre2/blob/3ac18b001cf3b8a706bb8920b51470301eb1ce99/addons/sys_zeus/fnc_handleZeusSpeakPress.sqf#L34
returns nothing.


https://github.com/IDI-Systems/acre2/blob/3ac18b001cf3b8a706bb8920b51470301eb1ce99/addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf#L30
doesn't return true/false on return.
