### ISSUE TITLE
Zeus - Unable to hear players on ships

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#673]
**Arma 3 Version:** `1.92` (stable / rc / dev)
**CBA Version:** `3.11.1` (stable / dev + commit hash)
**ACRE2 Version:** `dev 1001` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- Zeus is unable to hear players when close to a naval ship (both vanilla NATO static ships tested). The players can be heard properly once Zeus is hovering about 6 meters or so above the ship.

**Steps to reproduce:**
- Have players on a ship
- Enter Zeus interface
- Go beside players (no audio)
- Go above players (audio)

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Comment by jonpas** [comment]
Definitely some funky stuff with the camera height.

Does it work fine with high buildings?

**Comment by BrettMayson** [comment]
I've never noticed any issues outside of ships, but I haven't specifically looked.
