### ISSUE TITLE
No voice after 100+ clients connected to ACRE

### ISSUE THREAD

**Issue by ghost** [IDI-Systems/acre2#683]
**Arma 3 Version:** `1.92.145639` (stable)
**CBA Version:** `3.11.2` (stable)
**ACRE2 Version:** `2.6.3.1003` (stable)

**Mods:**
```
CUP Core / CBA / ACE / ACRE2
FOW / IFA3 / CSA3
CSA3-FOW-IFA3 weapons compat / IFA3-FOW compat / CSA ACE compat / FOW ACRE compat / IFA ACRE compat / IFA3 ACE3 compat
Splendid smoke / suppress / ACE ragdolling
ADV ACE CPR / ADV ACE Splint
Enhanced Movement/  WMO / knock on vehicles
G.O.S Dariyah / Messerschmitt Bf-109 / TWC 2 inch mortar / 2nd NZ ID uniforms / more uniforms
```

**Description:**
At 100 players connected to ACRE within the same TeamSpeak 3 channel, all voice communications would go silent. No one would be able to hear each other. Lowering the TS3 channel's codec quality did not fix the issue. As soon as there was 99 clients or less within the channel everyone could talk again.

Unfortunately, due to the nature of the issue, I cannot reproduce with less mods.

**Steps to reproduce:**
Have 100 players connected to ACRE in the same TS3 channel.

**Where did the issue occur?**
Dedicated

**Placed Modules:**
Zeus - #adminLogged

**RPT log file:**
Will get the server RPT ASAP.

**Comment by TheMagnetar** [comment]
Please provide the RPT. It might well be your TS was not able to handle the amount of players, specially if you have TS running in the same machine as Arma 3. In that case consider decreasing the audio codec quality prior the event or make TS run in a separate machine.

ACRE2 has been tested  with games with over 120 players without issues.

**Comment by ghost** [comment]
TS3 and game server were running on seperate machines. Codec quality was also decreased and this did not help.

**Comment by TheMagnetar** [comment]
Anything new?

**Comment by jokoho48** [comment]
i know this issue and it does not have anything todo with ACRE. this is a issue with how the teamspeak is setup. under Virtual Server settings, there is a setting that mutes all users in a channel when more than 100 users are in a channel. increase that value and the issue will be fixed.
under More => Misc => Min clients in channel befor silence.
Default is 100

**Comment by ghost** [comment]
> i know this issue and it does not have anything todo with ACRE. this is a issue with how the teamspeak is setup. under Virtual Server settings, there is a setting that mutes all users in a channel when more than 100 users are in a channel. increase that value and the issue will be fixed.
> under More => Misc => Min clients in channel befor silence.
> Default is 100

I love you. I was confused as I believed this was a conflict issue, rather than just with ACRE.

**Comment by TheMagnetar** [comment]
Closing
