### ISSUE TITLE
Can't hear yourself through speakers on Radios

### ISSUE THREAD

**Issue by nameless** [IDI-Systems/acre2#685]
**Arma 3 Version:** `1.92` (stable / rc / dev)
**CBA Version:** `3.11.2` (stable / dev + commit hash)
**ACRE2 Version:** ` 2.6.3.1003` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- ACE
```

**Description:**
- When you enable speaker mode for any of the radios and you put it on the ground and try transmitting on that same frequency with a different radio, you cannot hear yourself from the radio that is on the ground that has speaker mode on.  

**Steps to reproduce:**
- Turn on speaker mode for any of the radios and drop it
- Pick up another radio and set channel to the same one that is dropped
- Start transmitting and you cant hear yourself from the radio that is on the ground

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Comment by Fynnoverse** [comment]
Just get me this clear.
You want TS3 to replay your Microphone. 
Because this is how its wrks or not, the ACRE2 Plugin tells TS3 how to "listen" on the others user, so how would it be in a simple way possible ??? you cannot hear yourself in TS3 ecept for the Mic-Test in the Config. 
Yeah it should be Physically possible, but dude rly?

**Comment by NouberNou** [comment]
Most of this functionality is in the engine, but it was causing some very hard to track down crashes when it was first tested, so it kinda got shoved onto the back burner... years and years ago.

**Comment by Fynnoverse** [comment]
Yeah thats what i mean with "simple way".
Sure its possible but i see this more like a feature request and not a bug.
My opinion ^^

**Comment by jonpas** [comment]
Yeah, this isn't a bug. It is one of those things we would really want to do. I'll close this, because it's specific about something that's actually much larger (hearing yourself generally), we have it in our minds always.
