### ISSUE TITLE
Misaligned GUI on 21:9

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#687]
**Arma 3 Version:** `1.92` (stable / rc / dev)
**CBA Version:** `3.11.1` (stable / dev + commit hash)
**ACRE2 Version:** `2.6.3.1001` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- The Intercom UI is not aligned on 21:9.

https://www.youtube.com/watch?v=6fqOJSvGUGs

**Comment by TheMagnetar** [comment]
This is solved in #675

**Comment by BrettMayson** [comment]
:+1: My search didn't hit that

**Comment by TheMagnetar** [comment]
Closed. PR merged. If that is still the case, we can reopen it

**Comment by jonpas** [comment]
Duplicate of #670.
