### ISSUE TITLE
Teamspeak plugin API version problem

### ISSUE THREAD

**Issue by byjokese** [IDI-Systems/acre2#691]
**Arma 3 Version:** Latest on currect date.
**CBA Version:** `3.11.2.190515` 
**ACRE2 Version:** `2.6.3.1003`

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- TS3 ERROR: Plugin failed to load: Api version is not compatible: 21 (minumium: 23, current: 23). This error is shown in addons, inside teamspeak option.
Teamspeak version: 3.3.0 [Beta] (last to commit date).

**Steps to reproduce:**
- No Steps needed.

**Where did the issue occur?**
- Dedicated, does not apply.

**Placed Modules:**
- Mission Setup, does not apply.

**RPT log file:**
- No arma error.

**Comment by jonpas** [comment]
ACRE2 does not support API version 23 yet. Hotfix is in the works.
