### ISSUE TITLE
setRadioVolume and getRadioVolume are included but are not defined.

### ISSUE THREAD

**Issue by gkovalechyn** [IDI-Systems/acre2#692]
**Arma 3 Version:** `1.92` stable
**CBA Version:** `3.11.2` stable
**ACRE2 Version:** `Latest`, should be the same as  IDI-Systems/acre2@ffc3cdce8151ca0acf27ada69091f50614480e54

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
The release build of ACRE2 does not have `acre_api_fnc_getRadioVolume` and `acre_api_fnc_setRadioVolume` defined in `CfgFunctions.hpp` even though they are included in the pbo. But they are defined in `CfgFunctions` in the master branch.

**Steps to reproduce:**
- Try to call either `acre_api_fnc_setRadioVolume` or `acre_api_fnc_getRadioVolume`.
- You can also see if the functions are defined in the function viewer.

**Where did the issue occur?**
- Editor (Singleplayer) 
- Editor (Multiplayer)

**Placed Modules:**
None

**Image showing the functions are included but not defined:**
![image](https://user-images.githubusercontent.com/1435142/59515480-92762b80-8e95-11e9-930a-7c83057bc37b.png)

**Comment by jonpas** [comment]
Already done in #632.
