### ISSUE TITLE
SEM52SL buttons and overlays are misaligned

### ISSUE THREAD

**Issue by rebelvg** [IDI-Systems/acre2#71]
**Arma 3 Version:** `1.64` (stable)
**CBA Version:** `3.1.0` (stable)
**ACRE2 Version:** `2.3.0.912` (dev)

**Mods:**
- `@CBA_A3`
- `@acre2`

**Description:**
- SEM52SL buttons and overlays are misaligned. I'm running 16:10 so maybe that's an issue.
  Other radios work properly.
  http://i.imgur.com/nEXy6UF.jpg
  http://i.imgur.com/GMHrgNv.jpg
  http://i.imgur.com/en0qfwk.jpg
  http://i.imgur.com/OQ4OUCG.jpg

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- N/A.

**Comment by jonpas** [comment]
Fixed by #73
