### ISSUE TITLE
Zeus toggle for talking source

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#712]
Toggle for talking from camera of Zeus would be nice instead or in addition to current PTT button, which is problematic if your TS already has PTT and you don't want to bind 2 buttons in TeamSpeak (or alternatively hold 2 buttons to talk).

Alternatively we could possibly do it like for radios, automatically enable TeamSpeak PTT when holding down "talk from camera" PTT.

**Comment by TheMagnetar** [comment]
The implementation can be similar to what I did for intercoms

**Comment by BrettMayson** [comment]
Perhaps rename the rpc functions from `*IntercomSpeaking` to something more generic that can work for both?

**Comment by jonpas** [comment]
You would want a separate function, as you wouldn't want intercom filters applied, but pass clean voice through it.
