### ISSUE TITLE
Ropes

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#727]
Ropes are fun, so there should be some in acre2 cause acre2 is also fun.

A way to change the appearance of the ropes has not yet come along, but this is a minor issue.

Infantry phones and taking someone's handset should use ropes to visually indicate that they are on the phone and can't talk right now. It should obviously have a global CBA setting to disable it on a server because some places are less fun and would choose to miss out on the joy of the ropes.

**Comment by TheMagnetar** [comment]
Yes. I had this planned. Same as GSA
