### ISSUE TITLE
Move Livonia (Enoch) fakeWRP to main ACRE2

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#728]
Currently as optional mod as DLC is not yet released. For 2.7.1 we can put it into main ACRE2 as DLC data will always be loaded even if not owned (unlike Global Mobilization).

**Comment by jonpas** [comment]
Possibly not, looks like some things will only be set if Contact is running (optional download), ref.: https://github.com/CBATeam/CBA_A3/pull/1181

Will set as separate Workshop package if that's the case.

**Comment by veteran29** [comment]
Map data should be available no mater if you've loaded Contact DLC or not. (stuff like changes to map display etc. are in optional addon)

But I guess we'll see today.

**Comment by TheMagnetar** [comment]
In my opinion this should remain optional. Not everybody owns the DLC.

**Comment by jonpas** [comment]
Doesn't matter if they own it or not, config is there with base game apparently.

People have to download it as it is now (optional) either way.

**Comment by ElTyranos** [comment]
Yes, same as Tanoa.
