### ISSUE TITLE
Default radio volume setting

### ISSUE THREAD

**Issue by Quailsnap** [IDI-Systems/acre2#730]
ACRE2's default radio volumes at 100% are a little loud for me, so I commonly turn my AN/PRC-343 and/or 152 to ~60%-80% on mission start. I know I'm not the only one that does this, either, as some people like having the extra overhead to turn up to in case things suddenly get loud. 

TFAR has had this option for a while. It's very convenient and not at all immersion-breaking to assume I would always lower the knob to 60%-80%, and we already have busywork-prevention features like automatic antennae adjustment.

**Comment by jonpas** [comment]
I like this! Also find myself turning radios to 80% volume most of the time.

**Comment by Quailsnap** [comment]
Awesome! It's probably the only feature missing from ACRE (vs. TFAR) other than.. what? 'Additional' radio nets? I would pull this (hopefully simple) feature myself, but I'm knee-deep in a revamp for some of my own projects.

**Comment by jonpas** [comment]
> 'Additional' radio nets?

Not happening on radios we currently feature, as they do not have that ability in reality. If and when we get some radios that do support multi-push-to-talk operation or dual standby and similar features, then yes they will be featured.
