### ISSUE TITLE
After Update Vehicle Racks disappear

### ISSUE THREAD

**Issue by Justice-Molton** [IDI-Systems/acre2#732]
After the Update, the vehicle Racks at the RHS UH60M and at the 3CB BAF Vehicle Merlin disappear.
Anyone else having this problem?

**Comment by TheMagnetar** [comment]
I would kindly ask to use the bug template. Besides that, try using the racks using the UI intercom, they will not be displayed by default using the ACE3 interaction any more

If you cannot use them through the UI Intercom, then file a proper bug report with an RPT.

**Comment by Justice-Molton** [comment]
Sorry,
whos able to read...my bad please delete this post.
