### ISSUE TITLE
Air vehicle racks / radios vanished or are broken with the latest release

### ISSUE THREAD

**Issue by mwpowellhtx** [IDI-Systems/acre2#735]
Was this an API change? i.e. Air assets need to be initialized via a different SQF API?

**Comment by TheMagnetar** [comment]
No, just use the intercom UI.

**Comment by Justice-Molton** [comment]
is there anywhere documentation about it? my unit is getting confused. Do they need to carry a Radio to get a Rack working?

**Comment by Max255PL** [comment]
Yes, this change wasn't explained in the release material so people will get confused (as did I back in dev).

You don't need to carry radios but instead use the Intercom UI (by default Ctrl+Shift+Tab) and use the upper 2 knobs to define what radio you have active in the vehicle.

PS:
I still feel like the aircraft radios shouldn't be connected to intercom in config by default.

**Comment by mwpowellhtx** [comment]
I'm not sure I understand. When we ACE interact since the update, **THERE IS NO RACK** and so **THERE IS NO RADIO** and **THERE IS NO INTERCOM UI** that I am aware of.

**Comment by mwpowellhtx** [comment]
BTW, Ground Vehicles seem just fine. They still have the ACE interact *Rack*.

**Comment by TheMagnetar** [comment]
Please read above. There is no rack in ace interaction. And avoid using caps I can read just fine without having them. And there is an intercom UI.

**Comment by TheMagnetar** [comment]
If you feel that there is a bug, fill the issue template as indicated with a proper rpt. 

Ground vehicles. Only those racks that are not connected to the intercom have rack interaction in ace menu. And this applies to all vehicles, not only ground.

**Comment by mwpowellhtx** [comment]
> Only those racks that are not connected to the intercom have rack interaction in ace menu.

What does this even mean, if you please?

Air assets lost this with the latest update. Do we need to attach a rack now?

**Comment by TheMagnetar** [comment]
I am talking about this:
- https://acre2.idi-systems.com/wiki/user/vehicle-racks#vehicle-intercom
- https://acre2.idi-systems.com/wiki/user/vehicle-intercom#full-functional-crew-station-ffcs

**Comment by mwpowellhtx** [comment]
Appreciate the feedback, and after using the key bind, interesting UI for it. Takes some getting used to, but still interesting. Tango.
