### ISSUE TITLE
2 issues not fixed yet? no beep sound sometimes & only the crew can hear the infantry phone ringing?

### ISSUE THREAD

**Issue by battleshipfree** [IDI-Systems/acre2#740]
**Arma 3 Version: stable
**CBA Version: stable
**ACRE2 Version: stable 

Still, there is no beep sound sometimes when transmitting on radio, and only the crew who is using it can hear the infantry phone ringing, weird.
By the way, my clan is new to ACRE, thus experiencing some bugs.

**Comment by battleshipfree** [comment]
oops, i'm new to github...

**Comment by TheMagnetar** [comment]
The lacking beep sounds you are experiencing might be related to your server not loading b64 files. Infantry phone ringing  uses playSound3D and that is global.
Try next time to

1) Post rpt
2) try to reproduce the issues with only cba + acre (+ ace3).

**Comment by battleshipfree** [comment]
> 
> 
> The lacking beep sounds you are experiencing might be related to your server not loading b64 files. Infantry phone ringing uses playSound3D and that is global.
> Try next time to
> 
>     1. Post rpt
> 
>     2. try to reproduce the issues with only cba + acre (+ ace3).

**Comment by battleshipfree** [comment]
sorry to ask but can you please explain explicitly what b64 and playSound3D are? Im quite new to these staffs.

**Comment by TheMagnetar** [comment]
1) playsound3D is a command script: https://community.bistudio.com/wiki/playSound3D
2) b64 are the extensions of ACRE sound files that get played through TeamSpeak

**Comment by battleshipfree** [comment]
alright, gotta check it out with my clan members, thx

**Comment by battleshipfree** [comment]
is this Wav2B64.exe the b64 files you've mentioned above?

**Comment by TheMagnetar** [comment]
no, they are in a pbo
