### ISSUE TITLE
Proximity Chat bugs, Radios not working at all.

### ISSUE THREAD

**Issue by Rekkless88** [IDI-Systems/acre2#741]
Ok so this is a response to my Post on the BI Forums:
https://forums.bohemia.net/forums/topic/193813-advanced-combat-radio-environment-2-acre2/?page=31

https://www.youtube.com/watch?v=ECZzcfNJWk0

Basically the issues are:
- When some players login they can not hear other players and must quit back to the lobby and rejoin in order to hear everyone via proximity chat
- Radios don't work at all, so  far we have left all radio settings on default.
- ACRE 2 worked seamless and perfectly fine everytime in version 2.6
- It might be an issue with our Mission framework as Antistasi works fine, however Antistasi doesn't use all our mods. It DOES however use FMIS MOD but not the other FMIS mods.

I will post up the server RPT file and our mission frame work, later today I'll try and get a copy of my RPT up here too.

**Arma 3 Version:** `Contact Stable 1.94` (stable / rc / dev)
**CBA Version:** `Latest` (stable / dev + commit hash)
**ACRE2 Version:** `2.7` (stable / dev + commit hash)

**Mods:
- CBA_A3
- acre2
- ace
- ace x
- RHS x 4
- Cup terrains maps and core
- NI Arms
- Zombies and Deomons,
- RDS Civ pack
- MCC 4 and Achilles
- Flying Monkeys in Space Mod, Extra, Maps, Weapons, Uniforms - these are our in house private use mods, you can find them on the workshop for purposes of testing.
- a few other mods, nothing out of the ordinary that should affect ACRE 2.

Steam workshop collection:
https://steamcommunity.com/sharedfiles/filedetails/?id=861183699

- ACRE related mods: 
Radio Animations for Advanced Combat Radio Enviroment 2
https://steamcommunity.com/sharedfiles/filedetails/?id=1481341874

- Electronic Warfare - no missions we tested ran its modules and problems persisted.
https://steamcommunity.com/sharedfiles/filedetails/?id=1568688945

**Steps to reproduce:**
- Make a mission with our framework and use above mods
- Here is a simple mission where the problem persists. You can download the mission framework below from a mega link.
https://steamcommunity.com/sharedfiles/filedetails/?id=1815844003

**Where did the issue occur?**
- Dedicated server

**Placed Modules:**
- ACRE 2 radio channels and basic mission setup modules, Some Vanilla curator modules, Our Module set is part of the framework.

**RPT log file:**

- SERVER AND PERSONAL RPT FILE:
https://gist.github.com/Rekkless88/c266787b406027ff1f610b788b2847c8

- Server and my Personal ACRE_dll.log
https://gist.github.com/Rekkless88/8983211b05d587e337f5284918fbce12

Download our mission Framework:
FMIS MISSION FRAME WORK VERSION 14.1
https://mega.nz/#!Q1UmlQzB!5QRB8XZ4Mx6EYwCsIFet00NXAYc_bQuOyLSpxVlN3Ac

**Comment by TheMagnetar** [comment]
If antistasi works fine, it is not an issue with acre, but with your modset. Acre animations was known to have caused issues in the past. 

What I recommend is enabling one mod at a time and see if the issue persists

**Comment by TheMagnetar** [comment]
Oh. Electronic warfare. Someone in slack reported it broke acre.

**Comment by TheMagnetar** [comment]
Understand that we cannot test always all mod combinations: we can reproduce bugs only with the following modset: cba + acre (+ ace3)

**Comment by Rekkless88** [comment]
Magnetar like I said, there were no issues with anything in version 2.6, everyone, everytime could log in using our modset and framework and everything would work. To say ACRE is fine when it is quite literally the only adjusted variable in the equation seems unfair. I have updated the RPT file with my personal RPT. Perhaps something in there can narrow down what the problem is.

Personally I think it is the framework, but I honestly do not know what to look for as I did not write it.

I also will remove Electronic Warfare and the ACRE animations. However like I said they were never and issue before. Also we fixed the ACRE animations, I found someone who wrote a small fix for them. But I will remove them.

**Comment by TheMagnetar** [comment]
Again, we cannot keep track of all mods. Ich acre works fine with ace and cba that's all we can do. We cannot support each framework or each mod out there. Understand that please.

**Comment by Rekkless88** [comment]
I'm trying to work with you guys to find out what the issue is, I spent a good 90 minutes putting that post together, uploading the RPT files, uploading a video of the symptoms, uploading the mission to the steam workshop and our mission framework all to give you everything you could need to help me try and figure out why this issue is happening again. (it used to be an issue back in 2.3, 2.4.

I kind of feel like I'm getting blown off. I've provided you with everything you guys have asked for and I'm willing to work with you to try and solve this issue. Again because 2.6 worked fine, something has changed in the mod to cause this. Unfortunately I'm not a modder, I can't go through all the code and have it make sense, I'm looking for help here.

The mission framework is what we put in our missions, it has nothing to do with mods.

**Comment by Rekkless88** [comment]
The Magnetar - Ok so I've done a bunch of testing just now.

We modified the mission and mods, We removed the Electronic Warfare and ACRE 2 Animations and Completely removed our mission frame work - scripting, mission settings etc. So that the mission we were playing was literally just a mission.sqm.

And ACRE worked perfectly fine.

So I reuploaded the mission WITH our mission framework but still Electronic Warfare and ACRE 2 Animations were not loaded.

Problem persisted.

So I've come to the conclusion that it is NOT a mod issue but in fact an issue with our mission framework, in our initialization scripts etc.

So this doesn't help me a huge amount as again I'm not much of scripter. So could you do me a favor and download our mission framework and tell me if you see anything in there that could be causing the proximity chat issue and radio issue.

[FMIS Framework v14.1.zip](https://github.com/IDI-Systems/acre2/files/3436709/FMIS.Framework.v14.1.zip)

**Comment by TheMagnetar** [comment]
besides acre there are other issues:

```
12:04:30 Error in expression <]] call ace_common_fnc_canInteractWith} >
12:04:30   Error position: <>
12:04:30   Error Missing )
```

Try removing the ACRE modules as well.

**Comment by Rekkless88** [comment]
I will, but as I posted earlier, When we removed all our scripting but left the mission otherwise unchanged (ACRE Modules still present) the mission worked fine.

I however will still remove the modules to prevent that error from showing up and to further remove any other variables.

**Comment by Rekkless88** [comment]
Holy SMOKES Magnetar you were right - It was the ACRE 2 Modules that were causing all the problems. I'm going to revert a few changes I've made to double check, but I just removed the ACRE 2 modules and the mission with our framework worked perfectly fine.

**Comment by jonpas** [comment]
ACRE2 modules (all but 1) are deprecated since 2.5.0 and should so be listed in your RPT ever since. They have now been removed and only backwards compatibility classes have been kept (to still allow at least loading of the mission).
