### ISSUE TITLE
Zeus radioData script error

### ISSUE THREAD

**Issue by SirKoolKid** [IDI-Systems/acre2#742]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**ACRE2 Version:** `2.7.0` (stable)

**Mods:**
```
- CBA_A3
- acre2
- Achillies
- ACE3
```

**Description:**
- If someone in your channel or you speak over the radio a error will appear. The screenshot of the error is linked

**Steps to reproduce:**
- Simply have anyone or yourself talk on the radio while in the zeus interface and the error will appear

**Where did the issue occur?**
- Multiplayer Zeus Eden with more than one person inside the Zeus interface

**Placed Modules:**
- Zeus module and respawn module

**RPT log file:**
-![image](https://user-images.githubusercontent.com/53355587/61984472-858b4280-afd2-11e9-951c-6dd739a1e718.png)

[acre_dll.log](https://github.com/IDI-Systems/acre2/files/3438534/acre_dll.log)

**Comment by jonpas** [comment]
Fill out the issue template fully and test with only CBA, ACRE (and ACE).

**Comment by SirKoolKid** [comment]
ok will get back to you

**Comment by SirKoolKid** [comment]
Ok the mods I am using is
Achilles
Ace
CBA
ACRE

**Comment by SirKoolKid** [comment]
I am unable to find my RPT log file

**Comment by SirKoolKid** [comment]
Also we are using the eden editor with my player being able to enter the zeus interface

**Comment by SirKoolKid** [comment]
Ok jonpas I have redone my template to the best of my ability. It also seems that another person over on the workshop is experiencing the same problem as me.

**Comment by SirKoolKid** [comment]
I also included the RPT log file

**Comment by jonpas** [comment]
Same error reported on Slack by multiple people. We are looking into it!

**Comment by SirKoolKid** [comment]
Thank you very much! :)
