### ISSUE TITLE
ZeusListenViaCamera does not affect listening through Zeus camera

### ISSUE THREAD

**Issue by BojanOnTheInternet** [IDI-Systems/acre2#743]
**Arma 3 Version:** `1.94 stable` (stable / rc / dev)
**CBA Version:** `3.12.0` (stable / dev + commit hash)
**ACRE2 Version:** `2.7.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
- a bunch of the other usual stuff
```

**Description:**
- Setting does not affect listener position, always forced to listen through camera
- Setting title and effect is confusing, should consider changing one or the other

While playing as a player with Zeus access, it seems the ZeusListenViaCamera setting does not fully work. The intended functionality, according to Brett, is to toggle whether or not both the emitter and listener position is either the player, or the Zeus camera. In the current implementation, **the setting only toggles the ability to speak through the camera - not listen.**

There may be some missing checks here.
https://github.com/IDI-Systems/acre2/blob/master/addons/sys_core/fnc_processDirectSpeaker.sqf#L51

In addition, I find the setting, or perhaps the entire UX, a bit confusing. If the setting is on, I can only listen through the camera, but I can speak either through my player or through the camera. If the setting is off, I can neither listen nor speak through the camera. It almost seems to make more sense to either split this into two settings, `ZeusListenViaCamera` and `ZeusSpeakViaCamera`, or have communications go either through the camera or through the player. At the very least, the setting description could be changed to make it clear that this affects speaking through the camera as well - perhaps it could be entitled `Communicate through camera` to imply both listening and speaking are affected by this.

Lastly, it would prove very useful, at least to my community, if you could bind a key to toggle between speaking/listening through the camera, and through your player. Often you want to communicate with another Zeus when building something, but may want to jump in and listen to friendlies for a moment.

@synixebrett

**Comment by Max255PL** [comment]
Experienced the same thing, very annoying tbh.
