### ISSUE TITLE
Radio voice bug 

### ISSUE THREAD

**Issue by maxx2223** [IDI-Systems/acre2#744]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ACRE2 Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
Players have a bug, at some point the player speaks into a walkie-talkie and they hear him, but he stops hearing other players, other players hear everyone perfectly. If a player with a problem buys a new radio, the problem disappears and everyone starts to hear it perfectly. Appears in random time with any players.

**Steps to reproduce:**
The bug happens randomly.
**Where did the issue occur?**
- Dedicated

**Comment by TheMagnetar** [comment]
Can you provide an rpt?

**Comment by maxx2223** [comment]
Server rpt?

**Comment by TheMagnetar** [comment]
Both

**Comment by TheMagnetar** [comment]
Any updates?
