### ISSUE TITLE
Intercom UI alignment modified

### ISSUE THREAD

**Issue by BizBomb42** [IDI-Systems/acre2#747]
**Arma 3 Version:** `1.94.145903` (stable)
**CBA Version:** `3.12.0` (stable)
**ACRE2 Version:** `2.7.0.1010` (stable)

**Mods:**
```
- CBA_A3
- acre2
- ace (Version 3.12.6 - stable)
- ACE Compat - RHS United States Armed Forces (Version 3.12.6)
- RHSUSAF (Version 0.4.8)
```

**Description:**
- The Intercom UI seen when occupying a vehicle with intercoms equipped has been re-positioned near the middle of the screen (previously positioned in the top-left corner underneath the Vehicle Info UI).
- ACE and RHSUSAF mods used for intercom UI visibility.

![intercom-ui](https://user-images.githubusercontent.com/36508144/62236457-21cf9380-b39d-11e9-929f-3503686fcd32.png)

**Steps to reproduce:**
- Load Arma into the 3den Editor on the Altis terrain.
- Place an M2A3 (class RHS_M2A3_wd) on the terrain with the crew.
- Start a multiplayer game through the 3den Editor, and select a playable character in the vehicle.
- After loading into the player unit, the intercom UI is positioned around the middle of the screen (see attached screenshot) where it was previously positioned in the top-left corner underneath the Vehicle Info UI.

**Where did the issue occur?**
- Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- [Client RPT and ACRE Log](https://gist.github.com/BizBomb42/292ef42245ca32d19ca21fd7d58cfe49)

**Comment by jonpas** [comment]
Known, thank you.

**Comment by BizBomb42** [comment]
You're welcome. I didn't see another issue describing this so I wanted to make sure you were aware. I saw the same issue with my mod UI grid because I modeled it after the `grid_ACRE_vehicleInfo` definition utilizing the `profileNamespace` variables.

**Comment by jonpas** [comment]
I wonder if ACE MicroDAGR and other tools have a similar issue (same system)?

**Comment by BizBomb42** [comment]
Appears the MicroDAGR is still in the proper location after a quick test.

![microdagr-centered](https://user-images.githubusercontent.com/36508144/62238300-b25ba300-b3a0-11e9-8d64-cc9b8d5cc03e.png)
![microdagr-minimized](https://user-images.githubusercontent.com/36508144/62238301-b2f43980-b3a0-11e9-98fe-7bbfa077a631.png)

**Comment by jonpas** [comment]
I have a hint, BI changed Vehicle Info UI element.

**Comment by mgmegive** [comment]
In looking at [lines 126-127](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_gui/CfgRscTitles.hpp#L126-L127) of CfgRscTitles.hpp, and inspecting the variables in the debug console, it appears as though `IGUI_grid_ACRE_vehicleInfo_X` and `IGUI_grid_ACRE_vehicleInfo_Y` aren't being set properly. 
___
Watching:
```
profileNamespace getVariable ['IGUI_grid_ACRE_vehicleInfo_X', profileNamespace getVariable ['IGUI_GRID_VEHICLE_X', safezoneX + 0.5 * (((safezoneW / safezoneH) min 1.2) / 40)]]
```
Returns `0`
___
While watching the second argument of the getVariable:
```
profileNamespace getVariable ['IGUI_GRID_VEHICLE_X', safezoneX + 0.5 * (((safezoneW / safezoneH) min 1.2) / 40)]
```
returns `-0.697121` for my resolution.
___
When I set the values manually via:
```
profileNamespace setVariable ["IGUI_grid_ACRE_vehicleInfo_X", -0.697121]
```
it corrects the position.

**Comment by jonpas** [comment]
I can't reproduce, mine didn't move at all.

**Comment by mgmegive** [comment]
Odd. I wonder if there is something we have stored in our profileNamespace that is causing the `IGUI_grid_ACRE_vehicleInfo_X` to be set to 0.

**Comment by jonpas** [comment]
I also can't seem to move it in the layout editor though, must be related.

**Comment by BrettMayson** [comment]
I can reproduce, mine has also moved.

Using a 21:9 2560x1080 display

**Comment by jonpas** [comment]
Can reproduce on another profile.

**Comment by jonpas** [comment]
```
mharis001  Removing the profileNamespace getVariables from the CfgUIGrids fixes it (default parsed position is correct). I am not sure why though.

mharis001  Okay, I think I know why.. This is happening because of BI switching to BIS_fnc_parseNumberSafe in 1.94. profileNamespace is not in the "MATH_OPS" array it checks tokens in the string against. So it thinks the string is "unsafe" and returns 0.
```

Thanks @mharis001.

~~Need to verify if antenna indicator still works as intended.~~ Of course it does, it doesn't use `CfgUiGrids`.

**Comment by jonpas** [comment]
For reference, in my group, we found out only editor causes this issue. It appears editor saves the layout for some reason, like going to layout editor and saving there, which is the second way of breaking it.
