### ISSUE TITLE
Previous/Next Intercom Network disconnects current

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#750]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**ACRE2 Version:** `2.7.0` (stable)

**Mods:**
```
- CBA_A3
- acre2
- ace
```

**Description:**
Using "Previous Intercom Network" and "Next Intercom Network" switches the intercom correctly but also disconnects the one that was currently selected (before switching).

Expected behaviour would be to switch the primary one so you can open Intercom UI with keybind directly to that, without going through ACE3 Interaction Menu.

**Steps to reproduce:**
- Connect to both Crew and Pax intercom and use one of the "Previous/Next Intercom Network" keybinds.
- Observe getting disconnected.

**Where did the issue occur?**
- All

**Placed Modules:**
- None

**RPT log file:**
- N/A

**Comment by TheMagnetar** [comment]
This is working as intended. There are two types of keybinds

- Previous/  Next  intercom: Connects only to the next/previous intercom, disconnecting the others
- **Add** Previous/Next  intercom:  Adds the next or previous intercom to the list of connected intercoms.
