### ISSUE TITLE
152 range is 13km

### ISSUE THREAD

**Issue by Cytreen** [IDI-Systems/acre2#765]
Current release version on steam is allowing us to use acre2 radios prc152 at 13km on altis using the rice model. I know its experimental but we have also replicated this same distance test using LOS Multi-path with terrain degradation at 90%.. The prc 117 also has the same range and cuts off only about 20m further than the 152 currently.

![Untitled](https://user-images.githubusercontent.com/18506687/62591097-1811c880-b894-11e9-9aee-2b0a10208c62.png)

**Comment by jonpas** [comment]
Related to #763.

- Fill out the issue template fully please
- Does that happen only with ACRE2 2.7.0? (cause could also be Arma 3 update)

**Comment by Cytreen** [comment]
Yes, its the current version on Steam Workshop 2.7.0 released 7/24 on steam workshop.

**Comment by TheMagnetar** [comment]
OK,  i have done some testing on my end and I get the expected results. Can you please check the following settings?

- Propagation mode: LOS Multipath
- Terrain Loss Coefficient at least at 0.9
- Execute the following command in the  console: acre_sys_signal_showSignalHint = true

Report your findings with different propagation modes.

**Comment by TheMagnetar** [comment]
Radio ranges are OK. Closing. Feel free to reopen it if you deem it necessary!
