### ISSUE TITLE
The new radio knobs work but

### ISSUE THREAD

**Issue by mwpowellhtx** [IDI-Systems/acre2#804]
Latest versions of mods as far as I know.

As far as I could determine, when someone uses the new knobs and sets up the on-board LR radio for vehicles, no one else can ever use that radio ever again. They leave the vehicle, someone else enters, the knobs can be adjusted just fine, but the radio never appears in their radio set, cannot cycle through and configure that radio ever again.

**Comment by TheMagnetar** [comment]
Fill in the issue template and specify the version you are using and provide the RPT.

**Comment by mwpowellhtx** [comment]
Literally the [latest version](https://github.com/IDI-Systems/acre2/releases/tag/v2.7.0.1010), with the Intercom UI.

**Comment by TheMagnetar** [comment]
It is solved in the development build

**Comment by jonpas** [comment]
> Latest versions of mods as far as I know.

Which part of "filling out the template" don't you understand. Template is there for a reason, if you don't specify the versions we don't know if it's even still relevant. "As far as I know" is exactly as much as we know, we don't. Fill out the issue template in the future, incorrect issue reports will be closed.
