### ISSUE TITLE
Add (linux) server config howto

### ISSUE THREAD

**Issue by hbeni** [IDI-Systems/acre2#806]
**Situation**
Hello, i currently spent over an hour to figure out how to change the server wide configuration of this plugin. All i could find was that this goes via @cba_a3 userconfigs.
However i was not able to find any information o what or where i need to enter, and what config keys are available and what values can go in.

**Details**
Specific example: I try to force-enable the new arcade mode server wide.

**Suggestion**
Add a section to the wiki, explaining where the config goes and what options are available.
The documentation should be such exhaustive, as a linux aware admin can configure ACRE server side settings with just the console (bash or sh).

**Comment by jonpas** [comment]
We use [CBA Settings](https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System). Read that page and you should have all the information. :)

**Comment by hbeni** [comment]
Thank you, that was quick and a good hint.

With this i was able to get a list of value elements currently set at client and server (import/export feature).

I added the following lines to my server file``arma3/userconfig/cba_settings.sqf``:
```
// ACRE2
acre_sys_core_automaticAntennaDirection = true;
force acre_sys_core_ignoreAntennaDirection = true;
force acre_sys_signal_signalModel = 0;   //0=arcade
```
This applied/overwrote the client settings like intended.

However still: how should one know to enter ``0`` for "arcade" without first having to tweak the client and then exporting the settings? It would be good if this would be documented somewhere.

at least it would be good to include the link you gave me above in the wiki under a "server config" entry, together with some easy to understand words on how to get the needed values.

**Comment by jonpas** [comment]
> However still: how should one know to enter 0 for "arcade" without first having to tweak the client and then exporting the settings? It would be good if this would be documented somewhere.

By exporting indeed, that's the meant way to have it in a static file.

However, you can also simply set it on the server as described on the wiki page. Join server, login as admin, open CBA Settings and switch to Server tab, then change relevant settings there and they will be stored on the server.

If you are versed in SQF you can search code like [this](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_signal/initSettings.sqf#L9).

> at least it would be good to include the link you gave me above in the wiki under a "server config" entry, together with some easy to understand words on how to get the needed values.

Link to CBA Settings is a good idea. All explanation on the settings themselves should be in CBA - and I think it's explained well.

**Edit:** None of this is specific to Linux.

**Comment by hbeni** [comment]
>  Link to CBA Settings is a good idea. All explanation on the settings themselves should be in CBA - and I think it's explained well.

May i suggest merging the following change then?
-> https://github.com/hbeni/acre2/commit/a3cba773ee1f97fedb041152a83ad0acce42787a
-> PR https://github.com/IDI-Systems/acre2/pull/808

**Comment by jonpas** [comment]
This was done in #808.
