### ISSUE TITLE
Four different colours for voice volume

### ISSUE THREAD

**Issue by ghost** [IDI-Systems/acre2#812]
**Issue:**
When instructing someone on how to use ACRE, or when asking people to lower their talk volume, it would be helpful to reference specific colours of speaking volume. This is mainly referring to the two orange colours that can easily be mistaken.

This obviously isn't a massive issue, but more of an ease of use suggestion.

**Current setup:**
1/5 - no colour
2/5 - dark yellow
3/5 - light orange
4/5 - orange
5/5 - red

**Requested setup:**
1/5 - no colour
2/5 - yellow (not as dark)
3/5 - green
4/5 - orange
5/5 - red

**Outcome:**
"Change your volume to whisper"
"When speaking at green level you can be heard for a maximum of around 100m"
i.e. no confusion when talking about a voice level.

**Comment by jonpas** [comment]
@TMZulu expressed interest in contributing further customization options for Volume Control.

We discussed it and decided best would be to provide some presets (yellow-to-red, standard loudness scale of blue-to-red, some color-blind options), as we don't want the volume UI to look out of place with fully custom color configurations. Open for discussion of course.

@mharis001 redesigned the Volume Control UI including the current colors, I would value his input as well.

**Comment by TMZulu** [comment]
Im fine with adding in the option. Currently they would need to be presets for simplicity and ease of use. I would, however, like some ideas/discussion on what colors presets/ranges as people interested in. Once we got the end points, ill need to fill in the middle and there is room for input there as well.

**Comment by mharis001** [comment]
I agree on the use of a couple predefined presets instead of full customization. Should be a fairly simple thing to add as well, I experimented with the scales suggested here and these should all be color colorblind safe.

**Comment by TMZulu** [comment]
Guess haris is taking care of it

**Comment by TheMagnetar** [comment]
Closing, PR is in master
