### ISSUE TITLE
arma acre not conecting to ts

### ISSUE THREAD

**Issue by zeastful** [IDI-Systems/acre2#816]
**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.x.x` [e.g. 2.0.0 stable, commit hash]

**Description:**

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the extension log file, which can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Additional context:**

**Screenshots:**

**Comment by jonpas** [comment]
Template is there to be filled out, re-open once you do...

**Comment by jonpas** [comment]
_We also don't support Arma 1, or Arma 2 for that matter._
