### ISSUE TITLE
ACRE fails to initialise - Can't hear anyone (but everyone else can hear you on direct)

### ISSUE THREAD

**Issue by Sniperhid** [IDI-Systems/acre2#82]
This is an issue in the current versions that has a low probability of occurring (~1 in 15). The temporary solution is to restart the game/teamspeak.

In my tinkering it seems that the client variable `ACRE_MAP_LOADED` remains `false` and that setting it to `true` tends to fix the effected client.

**Comment by jonpas** [comment]
Meant to be fixed with #91, but wasn't fully.

**Comment by Sniperhid** [comment]
#91 - Fixed a lot of cases of this happening for ARK, but there's still a few edge cases where this can occur.

**Comment by Sniperhid** [comment]
#198 added some more logging to help diagnose the issue. If you do encounter this in build 940 or later please provide us with acre.log

**Comment by Sniperhid** [comment]
Some logs courtesey of @Cyruz143
[rpt.txt](https://github.com/IDI-Systems/acre2/files/777081/rpt.txt)
[acre_dll.txt](https://github.com/IDI-Systems/acre2/files/777082/acre_dll.txt)

Log Highlights:

`12:03:41 [ACRE] (sys_core) INFO: Loading Map: \ibr\IslaDuala3\isladuala3.wrp`

```
2017-02-11 12:03:35,106-{INFO }- ACRE Loaded
2017-02-11 12:03:35,111-{INFO }- Generating PBO List
2017-02-11 12:03:41,702-{INFO }- PBO Index complete
GAME REBOOT (to fix issue) - successfully works as per below
2017-02-11 12:09:45,665-{INFO }- ACRE Loaded
2017-02-11 12:09:45,670-{INFO }- Generating PBO List
2017-02-11 12:09:52,266-{INFO }- PBO Index complete
2017-02-11 12:09:52,268-{INFO }- Attempting to load map from PBO...
2017-02-11 12:09:53,271-{INFO }- Map Loaded, Error Status: 0
```

Now this indicates that the `load_map` operation (load in signal.hpp) is not executed in acre.dll. It does however return an id as threaded calls should (otherwise a script error would be in the rpt). Perhaps there is some sort of mutex issue where the command is never processed. This seems to make sense as in my prior testing future threaded calls to the extension (load_map) don't seem to be processed. Would be useful to know if this also occurs in all cases and still need to find a reliable method to reproduce the issue.

**Comment by Cuel** [comment]
Another case

```
2017-02-19 12:56:46,765-{INFO }- ACRE Loaded
2017-02-19 13:00:44,361-{INFO }- Generating PBO List
2017-02-19 13:00:59,128-{INFO }- PBO Index complete
(reboot, worked after)
2017-02-19 13:32:45,485-{INFO }- ACRE Loaded
2017-02-19 13:32:45,497-{INFO }- Generating PBO List
2017-02-19 13:33:00,790-{INFO }- PBO Index complete
2017-02-19 13:33:00,792-{INFO }- Attempting to load map from PBO...
2017-02-19 13:33:03,813-{INFO }- Map Loaded, Error Status: 0
2017-02-19 13:33:03,813-{INFO }- Adding signal processing to map...
2017-02-19 13:33:03,814-{INFO }- Finished adding signal processor to map.
```

**Comment by Sniperhid** [comment]
@Cuel - Do you have the accompanying RPT as well?

**Comment by Sniperhid** [comment]
Alright so after retrieving another set of logs it seems the same issue is occurring. 

My suspicion is that the `threaded_dispatcher` that is used is simply not running as no further commands are processed. I suspect that the `_ready` var is permanently `false`. This would be explained by a rare race condition in which the monitor thread kicks into life after the init command finishes. The init command sets `_ready` to `true` but it is my understanding the monitor thread sets it to `false` when the thread starts. To me this makes a lot of sense. To fix it is simple a matter of removing this line in the monitor function? -> https://github.com/IDI-Systems/acre2/blob/master/extensions/src/ACRE2Arma/common/dispatch.hpp#L135

It is actually pretty simple to confirm if this is the issue, simply retrieve the value of the below command to determine the state of the `_ready` variable, this needs to be done on an effected client as it is a client specific issue:
`"acre" callExtension "ready:"`
The value will be either `"0"` or `"-1"`, note if the command for callExtension on the acre.dll is incorrect it also returns `"-1"` so care must be taken to ensure the command is precisely as above.

**Comment by Cuel** [comment]
Yeah I know I forgot something. If you still need it I'll post it once I get home @Sniperhid

**Comment by Sniperhid** [comment]
I suspect it's the same thing happening, so probably not necessary.

**Comment by dramabeats** [comment]
I tried running that debugging command in the debug console but I didn't see any output.

Would it be possible for you to upload a modified version of the relevant file for our group to try? I get this problem everytime I connect to our server

**Comment by jonpas** [comment]
We will release a dev-build with a possible fix for it.

**Comment by Sparfell** [comment]
I tried to use ""acre" callExtension "ready:"" when it happened to me last night and it returned -1. I had to reboot the game in order to fix the issue.

RPT : 
http://pastebin.com/yh5LsVwL

RPT after reboot : 
http://pastebin.com/D0mFM549

acre_dll.log : 
http://pastebin.com/15Z23qia

**Comment by Sniperhid** [comment]
Thanks for the information @Sparfell - PR #240 should fix this issue. Expect the fix in the next dev-build.
