### ISSUE TITLE
LOS Multipath line of sight range is too far

### ISSUE THREAD

**Issue by BlackAlpha** [IDI-Systems/acre2#820]
**Mods:**
- **Arma 3:** `1.94.145977 (Stable)` 
- **CBA:** `3.12.1 (Steam)`
- **ACRE2:** `v2.7.1.1016 (Steam)`

**Description:**
AN/PRC-343 line of sight range is 2000-2500 meters with LOS Simple. The line of sight range is 5000+ meters with LOS Multipath. In both cases the Terrain Loss Coefficient is set to 1. I've managed to reproduce this various times in actual missions and a test mission (see below).

**Steps to reproduce:**
- Download test mission: https://www.dropbox.com/s/9b4a4grvkromdqs/acretest1.Altis.pbo?dl=0
- Run on dedicated server.
- The mission allows you to teleport to various distances with a clear line of sight to the person up on the hill.
- Try talking to each other from as far away as possible.

**Expected behavior:**
I believe the AN/PRC-343 line of sight range in real life is closer to 500-800 meters.

**Where did the issue occur?**
Dedicated

**Log Files:**
- Server RPT: https://pastebin.com/5nD9ndm3
- Client RPT: https://pastebin.com/BC2RrUdW
- ACRE Log: https://pastebin.com/tgsxR0tW

**Additional context:**
ACRE settings used:
Model Interference: On
Full Duplex Radios: Off
Ignore Antenna Direction: On
Automatic Antenna Direction: Off

**Comment by TheMagnetar** [comment]
Thanks for your detailed bug report. We will have a loot at it asap.

**Comment by arismagicgr** [comment]
I do have the same issue as @BlackAlpha although to be honest, I can not present all these info he did. I can just say that I have almost the same settings with the difference that I have "Ignore Antenna Direction: off". If there is a way to acquire all the info you need, please give me some guidance and I will do my best to follow.

**Comment by JamesTheClarke** [comment]
Our community utilises the same settings as @BlackAlpha with the exception of Model Interference and our results are more or less the same. As long as there is nothing breaking LOS the 353 range is very far indeed. Easy testing site is the Altis desert for example.

I agree with the OP that the 343 should be heavily distorted at around 800m even with LOS being maintained.

**Comment by TheMagnetar** [comment]
At the moment (since 2.7.0) there are some subtle problems on how multipath is being calculated. LOS Simple and ITM should give more accurate results for the time being.

**Comment by JamesTheClarke** [comment]
@TheMagnetar we use LOS Simple because on Multipath we could barely create interference on the 343 net even in mountainous terrain.

With LOS Simple on flat (or slightly uneven) terrain, the transmission range of a 343 is between 2.2 and 2.5 clicks depending on the area. Hill areas tend to cut it down to 1000-1500m and mountains actually cut the 343 off entirely if they break LOS even within 200m (which is a good thing).

But flat and hilly terrain calculation needs some work as currently the 343s are very powerful indeed.

A temporary 343 "fix" is to switch to Arcade but there you run into the problem that 152 are too powerful making larger radios obsolete.

**Comment by jonpas** [comment]
Closed #827 as duplicate, because this issue is older and more to the point.

Also renamed to fit what the actual issue is.

**Comment by jonpas** [comment]
Just went to test older versions with @TyroneMF and confirmed it broke from 2.6.4 to 2.7.0.

**Comment by NouberNou** [comment]
See fix in above PR.
