### ISSUE TITLE
Vehicle Intercom issues (Redd'n'Tank)

### ISSUE THREAD

**Issue by c0nnex** [IDI-Systems/acre2#821]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94.145977 stable`
- **CBA:** `3.12.1.190812 Latest Steam Workshop`
- **ACRE2:** `2.71.1016 Steamworkshop`
- **Redd'n'Tank Vehicles:** `4558f1fda9db318833905cde2c91505d5af5997c Steamworkshop`

**Description:**
We have similar Issues to #792  with Redd'n'Tank Vehicles.
E.g. the Fuchs 1A4 Infantry [e.g. 2.0.0 stable, commit hash]

When loaded with 6-7 people it's totally random who hears whom in intercom. 
Only constant is, driver always hears everyone, everything else is completely random.

(Works fine with TFAR btw)
Sideproblem:
A,B sit in vehicle
C,D,E,F are outside and just outside hearing range
if A and C talk at the same time (no radio) the Intercom of A will be choppy for B and not understandable

**Where did the issue occur?**
- Dedicated 

**Log Files:**
Arma3 Rpt: is literally empty (only the comon stuff)
Acre log:
2019-08-30 23:43:19,782-{INFO }- ACRE Loaded
2019-08-30 23:43:19,784-{INFO }- Generating PBO List
2019-08-30 23:43:24,170-{INFO }- PBO Index complete
2019-08-30 23:52:34,704-{INFO }- Attempting to load map from PBO...
2019-08-30 23:52:35,354-{INFO }- Map Loaded, Error Status: 0
2019-08-30 23:52:35,354-{INFO }- Adding signal processing to map...
2019-08-30 23:52:35,354-{INFO }- Finished adding signal processor to map.

**Comment by z3r03nna** [comment]
Same problem here with RHS vehicles.

**Comment by TheMagnetar** [comment]
Does the same happen with vanilla vehicles? In addition, please do post the RPT.

**Comment by jonpas** [comment]
No more information since forever, reopen if more information can be provided.
