### ISSUE TITLE
Zeus can't hear while underwater

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#826]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.94`
- **CBA:** `3.x.x`
- **ACRE2:** `2.7.1`

**Description:**
Zeus is not able to hear player while their unit is underwater

**Steps to reproduce:**
- Create a virtual curator entity at [0,0,0] on a map with water at that location
- Open Zeus interface
- Unable to hear players

**Expected behavior:**
Able to hear players

**Where did the issue occur?**
- Dedicated

**Additional context:**
This was working correctly for me on all the dev builds leading up to 2.7.1, PRs should be checked for a change that would've caused this

**Comment by TheMagnetar** [comment]
This is because zeus does not by pass occlusion

**Comment by BrettMayson** [comment]
It used to, in 2.7.0 it did. Related to #803 then

**Comment by TheMagnetar** [comment]
No. It never did bypass it.

**Comment by BrettMayson** [comment]
It did. That was being caused by a different bug however that I fixed, and now this bug has revealed itself.
