### ISSUE TITLE
AN/PRC-148 and 152 ranges too large

### ISSUE THREAD

**Issue by UnRealxInferno** [IDI-Systems/acre2#827]
**Is your enhancement related to a problem?**
I'm not sure whether this is correct as it might just be my lack of radio knowledge, but the AN PRC 152 seems to be able to transmit across an entire mountain range (20KM) on the map Lythium.

I can stand at the bottom right of the map and my friend can stand 20KM away (At the top left) with the same radio at the other side of the map, with dozens of mountains blocking LOS and 1000M difference in altitude and the signal quality is still 90%? 

I'm not sure if this is intentional as it really does seem like the radios can transmit flawlessly up to around 21KM and then it drops off entirely to 0%

(All done on default ACRE settings)

**Solution you'd like:**
Reduce effective range on the radios with LOS Multipath enabled?

**Alternatives you've considered:**
None currently, maybe allow terrain coefficient to be turned up above 1.0?

**Additional context:**
I can provide video clips if necessary.

**Comment by UnRealxInferno** [comment]
I'd also like to note that we seem to have the issue mentioned in #820 The PRC 343 seems to be effective way past 8KM regardless of terrain.

**Comment by Drofseh** [comment]
It looks like you meant to leave a bug report instead of an enhancement request.
It would probably be helpful if you filled out the template for that instead.

**Comment by UnRealxInferno** [comment]
> It looks like you meant to leave a bug report instead of an enhancement request.
> It would probably be helpful if you filled out the template for that instead.

My bad, wasn't sure if it was actually a bug or if i'd just missed some config options?

**Mods:**

Arma 3: Latest Stable version
CBA: Latest Stable version
ACRE2: Latest Stable version

**Description:**
I'm not sure whether this is correct as it might just be my lack of radio knowledge, but the AN PRC 152 seems to be able to transmit across an entire mountain range (20KM) on the map Lythium.

I can stand at the bottom right of the map and my friend can stand 20KM away (At the top left) with the same radio at the other side of the map, with dozens of mountains blocking LOS and 1000M difference in altitude and the signal quality is still 90%?

I'm not sure if this is intentional as it really does seem like the radios can transmit flawlessly up to around 21KM and then it drops off entirely to 0%

(All done on default ACRE settings)

**Steps to reproduce:**
Load up Lythium terrain, stand at opposite ends of the terrain with a test partner, attempt radio contact on default settings

NOT tested yet in other maps but I can check if necessary


**Expected behavior:**
Audio should be cut off FAR before 20KM, not to mention the mountainous terrain should prevent radio contact at this kind of distance with these radios?

**Where did the issue occur?**

Dedicated

**Additional context:**
Seems as if the only time radios cut off are in extreme valleys, but only in certain spots, there is no spectrum of audio quality, either 100% or 0%, the lowest quality we could achieve at 20KM~ was 89%, Audio drops to 0% on debug when in aforementioned valleys

Video footage can be provided, I haven't attached RPTs as I cannot see anything out of the ordinary in terms of errors, and they're somewhat awkward to download from our server host, but I can provide if needed


(Apologies for the wrong label, I can remake the thread if necessary)

**Comment by jonpas** [comment]
No need to remake the report, thank you!

**Comment by BlackAlpha** [comment]
I can confirm that the 152 line of sight range is 20+ km. It's at least 10+ km with large hills in the way. That is with LOS Multipath and Terrain Loss Coefficient of 1.

From what I could find, it should be around 6 km with line of sight (not 100% sure, though).

**Comment by Nemoman123** [comment]
I have this problem as well the 148 and 152 can broadcast across the entirety of Altis rendering PRC-117Fs obsolete. PRC-343s did this as well until I changed the signal propagation model to Longley-Rice ITM. However, 148s and 152s still can broadcast across the entire map. Is there a way to attenuate the transmission power a setting to decrease it either in the radio itself or by use of init.sqf, a code module, or functions somewhere? To change the settings for entire classes of radios.

**Comment by TheMagnetar** [comment]
I  would very much like to see all your  RPTs. @UnRealxInferno @Nemoman123.

**Comment by UnRealxInferno** [comment]
> I would very much like to see all your RPTs. @UnRealxInferno @Nemoman123.

Gonna get this for you guys tomorrow, been away so I apologise for the delays

**Comment by bux** [comment]
We're experiencing the same with default settings.

**Comment by BrettMayson** [comment]
@bux I'm guessing dedicated server, do you use Windows or Linux for it?

**Comment by bux** [comment]
@synixebrett Dedi on Windows. Do you think this is a platform issue?

**Comment by BrettMayson** [comment]
I did, since I've only encountered it with Linux; but guess not

**Comment by NouberNou** [comment]
> From what I could find, it should be around 6 km with line of sight (not 100% sure, though).

The max range could be anywhere from a few kilometers to hundreds of kilometers depending on the antenna and frequency. For reference IRL I've built radios that have a maximum output of <2W and talk from space (LEO) to ground stations with omni-patch antennas on the Tx side (though usually multi-meter dishes on the ground side, but still that's still only +20dBi to +30dBi). That's ~500km sometimes.

Course again mileage may vary based on terrain, but yea, the "max" range is deceiving and multi-path fading and diffraction are going to be your practical points of limitation in a terrestrial system.

**Comment by bux** [comment]
@NouberNou The issue is a new one (since from one of the last 1 or 2 updates, can't exactly tell which one). Based on distance and/or terrain you would experience sincere interferences. The same setting now yields near perfect reception.

It's very obvious with an AN PRC 343 being able to reach past 10km (on "LOS Simple" or "LOS Multipath", the range is better modeled on "Longley Rice").

**Comment by BlackAlpha** [comment]
> > From what I could find, it should be around 6 km with line of sight (not 100% sure, though).
> 
> The max range could be anywhere from a few kilometers to hundreds of kilometers depending on the antenna and frequency. For reference IRL I've built radios that have a maximum output of <2W and talk from space (LEO) to ground stations with omni-patch antennas on the Tx side (though usually multi-meter dishes on the ground side, but still that's still only +20dBi to +30dBi). That's ~500km sometimes.
> 
> Course again mileage may vary based on terrain, but yea, the "max" range is deceiving and multi-path fading and diffraction are going to be your practical points of limitation in a terrestrial system.

True, but I was talking about the default radio. So, no additional antenna or other equipment. Since my last post, I found a document from the 148 manufacturer and two military documents that list the max range as 5-6 km.

**Comment by jonpas** [comment]
I will close this issue as #820 is the same, issues will be linked for information.
