### ISSUE TITLE
Massive Desync when using ACRE2 on dedicated server.

### ISSUE THREAD

**Issue by Jason-Terry** [IDI-Systems/acre2#837]
**Mods (complete and add to the following information):**
- **Arma 3:** `Latest Stable`
- **CBA:** `3.x.x` 3.12.2 (Steam)
- **ACRE2:** `2.x.x` Latest (Steam)
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
Desync on default Altis missions with only ACRE2, CBA, ACE3, and VCOMAI
We attempted to remove ALL mods to track the issue, removed VCOMAI, desync persisted, then ACRE2 was the last to go.

Experiencing no issues with server FPS, client FPS, or ping.

Desync was gone. We loaded into the same missions about 40 times to find this, very frustrating.

**Steps to reproduce:**
- Go to ...
- Load Arma 3 with ACRE2, ACE, CBA.
- Load any default mission (On dedicated server)
- Connect with multiple clients.
- Experience desync, teleporting, and lag.

- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated

**Log Files:**
- https://gist.github.com/Jason-Terry/a802b9513a6a5d63d01233870277e7b9
- https://gist.github.com/Jason-Terry/63cada151aa90a9015b813ad826d0bec

**Comment by Sniperhid** [comment]
ACRE2 does like other mods add more communication between clients and the server. Plenty of others are able to use ACRE2 without massive desync. Server bandwidth settings can play a massive role in influencing desync -> https://community.bistudio.com/wiki/basic.cfg

There's a lot of potential factors here - player count, your server hardware and their connections to the server all play a massive role here. With the Arma engine even one player with massive packet loss can start to cause issues for everyone else.

More info is required - How many players are we talking here? (each player also adds more strain) and what are your server bandwidth options (see basic.cfg above) and how much bandwidth does it have available? etc. Please provide as much information as possible.

Your RPTs also have more mods loaded than just `ACRE2, CBA, ACE3, and VCOMAI`. Even alive starts printing messages which makes me think it also was a non default mission you loaded? (more objects in a mission also lead to more strain)

**Comment by Jason-Terry** [comment]
It's pretty late here now, I will get all this info for you tomarrow.

As stated, that RPT is from when the issue was first getting so bad we started testing. I can provide more tomorrow as well.

My guess is this is a latency issue between TS and the Server.

We only had 12 clients connected (all under 100 ping)
Server hardware is 
i74970k
32gb ram (speed unkown right now)
SSD's for disk space.

AS stated, when we got to the final two mods to remove, it was VCOMAI, and ACRE2, and I prayed to god removing vcom fixed it, and it did not.

Sorry, I am just so tired. I will update tomorrow.

**Comment by TheMagnetar** [comment]
update @Jason-Terry ?

**Comment by Jason-Terry** [comment]
I was unable to confirm the issue with ACRE2.

We reinstalled our server and started testing up the chain MOD by MOD, trying to recreate the issue. We are back to using the whole mod-pack (ACRE2 included thank god) and have not experienced the issue yet at all.

**Comment by TheMagnetar** [comment]
Closing then. If something like this happens, feel free to reopen
