### ISSUE TITLE
Radios not working after respawn

### ISSUE THREAD

**Issue by UnRealxInferno** [IDI-Systems/acre2#852]
**Mods (complete and add to the following information):**
- **Arma 3:** `Latest` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `Latest` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `Latest` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
While playing KP liberation, after dying and respawning, radios will stop working in one of several ways:

- Can transmit but cannot hear inbound
-Can hear but cannot transmit outbound
-Radio doesn't work at all

Settings have already been checked and this issue occurs regardless of difference

**Steps to reproduce:**
- Load up KP Liberation with a small group
-have people respawn
-Test radios

**Expected behavior:**
Radios will not work when they should

**Where did the issue occur?**
- Dedicated 

**Log Files:**
-Will acquire tonight

**Additional context:**
According to mission file creator, this is an issue with multiple radios having the same ID after respawn (?)

**Comment by TheMagnetar** [comment]
This is most probably an error in the respawn script of the mission. Is the gear saved somehow?

**Comment by UnRealxInferno** [comment]
> This is most probably an error in the respawn script of the mission. Is the gear saved somehow?

I believe so, but even if we reload our gear, the radios still don't work? I'm not sure how the radio IDs are assigned but they don't seem to update (if that makes sense)

**Comment by TheMagnetar** [comment]
Any update @UnRealxInferno. When restoring the gear, make sure to remove the trailing *_id_xxx in the radio item to avoid duplicates.

**Comment by c0nnex** [comment]
We have the same issue with KP Liberation. It was working fine until last A3/Acre2 update (We cannot tell exactly since both where applied the same time for us). 
It looks like that always the first person to receive a radio in a session has problems to hear others. (Specially people that join an already runing session)
For people having the problem A3 needs to be restarted.

**Comment by TheMagnetar** [comment]
Read the post above @c0nnex . An RPT (client & server) would also be helpful

**Comment by MrEpiphanyYT** [comment]
I seem to be having this issue, now when in the arsenal I do see the ID you are talking about. Me and my friend are currently on server testing, now if we both grab a normal 343 with no id it doesn't work, when going back to the arsenal you can see it assigned it an ID. Now I'm not 100% how these IDs work so I'm a bit lost here. What do I do to fix this issue of people not being able to hear others?  Also, I couldn't find anywhere that specifically tells the server to respawn with their gear. Can you direct me to location where this could be so I could disable this. I want to get rid of this issue ASAP as this is causing major issues to our gameplay and will soon force us to switch radio mods.

**Comment by TheMagnetar** [comment]
Providing an RPT is the way to go for both client and server.

**Comment by SanchezMilsim** [comment]
We have this problem in all missions, with more than 20 players. Custom missions and missions without respawn. I feel our problem is the same. We have this problem usually after 3 hours of begin mission. Im going to open a new ticket.

**Comment by godgutten** [comment]
Same here this happens for me and my squad all the time after 1 to 2 hours of playing 

The only way we get it to be fixed is that people either reloads TS, ARMA3 or reloads the acre2 addon in TS

**Comment by jonpas** [comment]
Duplicate of #264. If issue continues after 2.7.3 release, please comment on #264.
