### ISSUE TITLE
Allow higher volume level than current maximum

### ISSUE THREAD

**Issue by WALancer** [IDI-Systems/acre2#853]
**Is your enhancement related to a problem?**
It is not currently a problem. I would like to see a change in how loud a radio in ACRE can be.

**Solution you'd like:**
For example, I would like to see all radios start on volume level 5 out of 10 and that would be the same as how loud the current default setting is currently in ACRE. I would like to see the ability to put a radio on volume level 10 and it be ear piercing like it is in real life. No one cranks up their radio in real life to the max volume because hearing loss is usually involved, I would like to see that replicated in ACRE.

**Comment by TheMagnetar** [comment]
Is the intercom volume level enough for you or would you prefer to boost it as well?

**Comment by Quailsnap** [comment]
Note that the nature of ACRE2 (and TFAR) is that they can only work with the voice given to them by the player, through Teamspeak. If the default was 50% (ie: if our current 100% became the new 50%), ACRE2 would have to start **boosting** the signal past that, and boosting can result in a notable decrease in audio quality.

I'm not 100% sure, but _so far_ both systems have mostly refrained from boosting voices.
