### ISSUE TITLE
Compatibility with Contact DLC Radio Backpacks

### ISSUE THREAD

**Issue by TheNightstalk3r** [IDI-Systems/acre2#854]
Currently, the Contact DLC Radio backpacks are not compatible with the LRRs ACRE2.0 offers (either because of a setting or their tiny inventory space - I blame BI). It would be a great addition to the game to have these antenna-rich backpacks function with ACRE for those who want radio backpacks in the camouflage within the standard ArmAverse and its DLCs.

**Comment by BrettMayson** [comment]
```hpp
class CfgVehicles {
	class Bag_Base;
	class B_RadioBag_01_base_F: Bag_Base {
		maximumLoad = 150; // 120 for 117F
	};
};
```
I've been using this to allow for a 117F and a small amount of extra gear

**Comment by jonpas** [comment]
We probably shouldn't change maximum load in ACRE as that is a global change. What os the default value anyways? Sounds like those backpacks should have much more space to begin with.

Amd we can't change radio weights as that will change carrying capacity for everything else. 

I think best course of action here os separate mod that increases maximum load of those backpacks as Brett provided.

**Comment by BrettMayson** [comment]
An optional perhaps? Not sure what the best course would be for the steam workshop however

**Comment by BrettMayson** [comment]
A more interesting approach would be to create a new item `Integrated 117F`. It would have 0 mass. We could add it to all radio backpacks. This would get around the "All radios are items" issue without rewriting anything existing. The only issue would be the less than ideal method to prevent it from being moved out of the backpack. Still would be an interesting experiment.

**Comment by TheNightstalk3r** [comment]
Would there not be an option to make this Integrated 117F only compatible with those backpacks? It's not ideal for mod support, but it's something corresponding mod makers could do something with.

**Comment by jonpas** [comment]
`Integrated 117F` just sounds like a start of a great confusion to me. You should be able to put in a normal 117F.

I think changed mass in a separate mod is the best option. I am not sure that's something we would want in ACRE2, we'll discuss it internally.

**Comment by jonpas** [comment]
If anyone wants to add backpacks that inherit from Contact DLC ones but have more space to allow a radio to fit, we can put them into ACRE2 as optional and also distribute it that way. However, we have no plans of doing this ourselves and distribution might be easier/faster if done on your own, so I am closing this request.
