### ISSUE TITLE
Keying noise not played

### ISSUE THREAD

**Issue by erentar** [IDI-Systems/acre2#858]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.12.2.1909` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.7.1.1016` [e.g. 2.0.0 stable, commit hash]
Reproducable with CBA and ACRE only ✔️

**Description:**
Keying noises not played and not heard when transmitting player keys the radio

**Steps to reproduce:**
* Start mission
* Key radio
* Not hear the keying sound 

**Expected behavior:**
The keying sound to play.

**Where did the issue occur?**

| Dedicated✔️ | ~~Self-Hosted Multiplayer~~ | Singleplayer✔️ | Editor (Singleplayer)✔️ | Editor (Multiplayer)✔️ | ~~Virtual Arsenal~~ |
| --- | --- | --- | --- | --- | --- |

(striked ones are not tested)

**Log Files:**
- [rpt log](http://gist.github.com/erentar/419489f09b6257817e95417f80e74c03)
- [acre2.dll.log](http://gist.github.com/erentar/97a0a6960b6ad7ad77bf1b52a1a83516)

**Footage:**
https://youtu.be/SJdQIldwCHs

**Comment by TheMagnetar** [comment]
Right, make sure that b64 files are whitelisted on the server. This covers 99.99% of the cases similar to yours :)

**Comment by erentar** [comment]
> Right, make sure that b64 files are whitelisted on the server. This covers 99.99% of the cases similar to yours :)

How can i do that for sp or local mp?

**Comment by erentar** [comment]
Nevermind, that fixed it, thanks very much!
