### ISSUE TITLE
Cannot access FFCS connected radios in ACE Self Interact if unit has no radio in their inventory

### ISSUE THREAD

**Issue by CawsForConcern** [IDI-Systems/acre2#859]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.92`
- **CBA:** `3.12.2`
- **ACRE2:** `2.7.1.1016`

**Description:**
If you do not have at least one radio in your inventory, you will not able to use ACE Self-Interact to interact with FFCS connected vehicle radios.

With any radio in your inventory, you will have access to the vehicle's FFCS radio:
![image](https://user-images.githubusercontent.com/6044186/68519643-2383df80-0247-11ea-9835-a5502afd71d3.png)

If you have no radios, you won't get the 'Radios' sub-menu at all.
![image](https://user-images.githubusercontent.com/6044186/68519654-30083800-0247-11ea-93c1-02ff4b4a072f.png)

**Steps to reproduce:**
1. Spawn any vanilla armored vehicle with FFCS connected vehicle radios.
2. Discard any radios from your inventory (343s, 152s, etc)
3.  Open the FFCS, and set your `Work` to `A`
4. ACE Self Interact to try and interact with the FFCS vehicle radio
5. You will not have access to the FFCS vehicle radio. See pictures above.
6. Acquire any radio (343, 152, etc).
7. ACE Self Interact to try and interact with the FFCS connected vehicle radio. You will now be able to interact with the FFCS connected vehicle radio.

**Expected behavior:**
- You should be able to interact with the FFCS connected vehicle radios even if you do not have any other radios in your inventory.

**Where did the issue occur?**
- Occurs in Local, Local MP, and dedicated server MP

**Log Files:**
- Does not generate any errors in .rpt file.

**Additional context:**
- Was tearing my hair out figuring why players on server could not access racks.

**Screenshots:**
- Please see above.

**Comment by TheMagnetar** [comment]
Nice report!
