### ISSUE TITLE
zero divisor in fnc_updateIntercomUse when Zeus moves player out of vehicle and deletes it

### ISSUE THREAD

**Issue by McDiod** [IDI-Systems/acre2#860]
**Mods:**
- **Arma 3:** `1.96.146070` 
- **CBA:** `3.12.2`
- **ACRE2:** `2.7.1.1016`

**Description:**
Script error:
```
20:20:41 Error in expression <[]];

{
private _name = (_intercomNames select _forEachIndex) select 0;
private >
20:20:41   Error position: <select _forEachIndex) select 0;
private >
20:20:41   Error Zero divisor
20:20:41 File idi\acre\addons\sys_intercom\fnc_updateIntercomUse.sqf..., line 25
```

**Steps to reproduce:**
- have a vehicle with intercom
- have a playable unit inside said vehicle
- move playable unit out of vehicle with Zeus' G key
- delete vehicle

**Where did the issue occur?**
- Dedicated Multiplayer

**Comment by jonpas** [comment]
This was fixed in 2.7.2 by #865.
