### ISSUE TITLE
Freeze on start with Tobii EyeTracker

### ISSUE THREAD

**Issue by Twillidan** [IDI-Systems/acre2#861]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114 stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.12.2.190909` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.7.1.1016` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
With only CBA and ACRE 2 loaded, and the Tobii service (eye tracking hardware/software) I can't start ARMA 3, I just get stuck on a black screen.
Seems that no matter how long I leave it at this black screen ARMA won't start, and I have to kill the process. ARMA crash reported shows the following as the last enrty.
11:32:40 CallExtension loaded: acre (D:\Games\SteamLibrary\steamapps\common\Arma 3\!Workshop\@ACRE2\acre_x64.dll) [2.7.1.1016]

From the ACRE logs I only see the following on each start up.
2019-11-14 11:51:38,807-{INFO }- ACRE Loaded
2019-11-14 11:51:38,809-{INFO }- Generating PBO List

I tried reinstalling arma 3 and the mods and I'm still having the same issue.

**Steps to reproduce:**
- Install arma3
- Install drivers for Tobii eye tracking.
- Subscribe to CBA and ACRE in the steam workshop
- Start the arma 3 launcher.
- Select to load CBA and ACRE 2
- Click start with mods
- Wait for the initializing box to finish it's work
- Get to the black screen that is typical before the first splash screen
- Get stuck at this black screen until the process is killed.

**Expected behavior:**
Expected to get to splash screen and then in to main menu.

**Where did the issue occur?**
- Starting ARMA 3

**Log Files:**
-https://gist.github.com/Deathwatch187/e4f57d2f67dd1a1bde78bb3d8f06efbd(https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- https://gist.github.com/Deathwatch187/5fd9ea5c0bae13777092c174eacc9666

**Additional context:**
ACRE was able to install the TS plugin without issue
TeamSpeak version 3.3.2
A connected Tobii device is NOT needed, no such device was connected when I was testing this.

**Screenshots:**
N/A

**Comment by dfr1238** [comment]
my friend have same issues too.hope can get hotfix soon
TeamSpeak version 3.3.2

**Comment by TheMagnetar** [comment]
Can you please check if you load Tobii. All crashes with ACRE are most of the times related to loading in addition that dll.

**Comment by Twillidan** [comment]
Thank you, that seems to have done it, after making sure to kill the Tobii service, the game now loads even with my full mod list.

However I don't think the bug label should be removed from this issue report, as I for one still very much view this as an issue that would need fixing. So unless i have just missed that this is already a reported issue, please consider re-adding the bug label and have this put in the backlog of things to fix.

I have updated the issue name and description to more accurately reflect this issue.

I do not know how similar/dissimilar TFR is in how it operates compared to ACRE, but I had no issues running TFR with Tobii service running.

**Comment by jonpas** [comment]
It is being reported more and more recently, so we can keep this issue around. It would be nice if someone can get a hold of Tobii and also report it on their side.

**Comment by mgmegive** [comment]
As a workaround. If you aren't using Tobii and want don't want to task kill it every time you want to run Arma with ACRE, you can prevent it from initializing on startup by doing the following:
- Launch "services.msc"
- Scroll down to "Tobii Service"
- Right Click >> Properties
- Startup Type Dropdown >> Set to "Disabled"
- Done, Tobii Eye tracking shouldn't start with windows anymore.

I would have fully disabled hardware and uninstalled drivers but the Tobii drivers also control the touchpad on my Alienware Laptop.

**Comment by Ficzzho** [comment]
Any updates on if this is going to get fixed or?
