### ISSUE TITLE
Disable / Enable for the server

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#862]
**Is your feature request related to a problem?**
Sometimes when doing training or testing we don't want to use ACRE.

**Solution you'd like:**
`#acre-disable` and `#acre-enable` that tell the addon to just chill.

This is slightly better than telling people to disable ACRE and then someone inevitably not, followed by them typing "why can't I hear anyone" in the game chat.

**Comment by jonpas** [comment]
If any contributor wants to tackle this, should be pretty easy.

**Comment by jonpas** [comment]
No chat commands in ACRE, but if any API needs to be added to do this easily, that would be accepted.
