### ISSUE TITLE
Radio rack open access lost when a position with only Rx/Tx access connects

### ISSUE THREAD

**Issue by Drofseh** [IDI-Systems/acre2#873]
**Mods:**
- **Arma 3:** `1.96.146114`
- **CBA:** `3.13.0`
- **ACRE2:** `2.7.2.1022`
- **ACE3:** `3.12.6`
- **IFA3:** `Preview v38`
- **IFA3 ACE Compat:**
- **IFA3 ACRE2 Compat:** `1.2.1`

**Description:**
If a radio rack is assigned `allowedPositions` but is also accessible through an `intercom` for Rx/Tx then when an intercom connected player sets their RxTx to that radio in the intercom UI the `allowedPositions` can no longer open the radio UI to change frequency and other settings.

**Steps to reproduce:**
1) Use this config:
```
class Your_Tank: Tank_F {
    class AcreIntercoms {
        class Intercom_1 {
            displayName = "Crew Intercom";
            shortName = "IntCm";
            allowedPositions[] = {"crew"};
            disabledPositions[] = {};
            limitedPositions[] = {};
            masterPositions[] = {"commander"};
            numLimitedPositions = 0;
            connectedByDefault = 1;
        };
    };
    class AcreRacks {
        class Rack_1 {
            displayName = "Radio Set";
            shortName = "Radio";
            componentname = "ACRE_VRC64";
            allowedPositions[] = {{"turret", {1}}};
            disabledPositions[] = {{"turnedout", "all"}};
            defaultComponents[] = {};
            mountedRadio = "ACRE_PRC77";
            isRadioRemovable = 0;
            intercom[] = {"intercom_1"};
        };
    };
};
```
2) get in the Turret 1 position
3) set radio to RxTx in intercom UI
4) test opening and closing radio
5) get in any other vehicle crew seat with radio access through intercom only
6) set radio to RxTx in intercom UI
7) return to the Turret 1 position
8) radio UI can no longer be opened
9) return to the other seat
10) disconnect from RxTx for the radio
11) return to the Turret 1 position
12) radio UI access is restored

**Expected behavior:**
Seats in `allowedPositions` should aways be able to open the radio UI and change radio settings even if others are connected for RxTx

**Where did the issue occur?**
- Editor (Singleplayer), presumably others but I will test later.

**Log Files:**
- Link to [RPT ](https://pastebin.com/EMD7HSJK) file.

**Comment by jonpas** [comment]
I can't reproduce this with #910 using `B_APC_Tracked_01_rcws_F`.

**Comment by Drofseh** [comment]
Hopefully someone fixed it along the way then.
Here is a vid of me reproducing it in the current release though.
https://youtu.be/J1_T0I_HYEM

**Comment by jonpas** [comment]
Can you try reproducing in current release with the vehicle I noted above?

It should be a similar configuration.

**Comment by Drofseh** [comment]
Config is too different.
`allowedPositions` includes all crew members for `B_APC_Tracked_01_rcws_F` and no one else has access to the radio through intercom besides those same crew members.
Issue only happens when second position is not in `allowedPositions`.

I've updated the issue to make repro step 5 more explicit on that.

**Comment by jonpas** [comment]
Unsure how to solve this easily, will take a closer look for next release.
