### ISSUE TITLE
Voice not muffed or lowerd when unconscious

### ISSUE THREAD

**Issue by AndreasBrostrom** [IDI-Systems/acre2#882]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96 ` Stable
- **CBA:** `3.13.0.191116` Stable 
- **ACRE2:** `2.x.x` Stable 
- **ACE3** `3.13.0` Stable

**Description:**
Acre radio and local talk don't get lowered or muffed when player is unconscious.

**Steps to reproduce:**
- Get unconscious
- Have some guys around you talking also have some other sound in the background for reference. 

**Expected behavior:**
Sound to be lowerd or muffed.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- None of intrest

**Additional context:**
- None

**Screenshots:**
- Imagen blackness and muffled gunfire. While some medic is talking clearly via radio and to surrounding.

**Comment by Soldia1138** [comment]
This should be called from ACE, shouldn’t it? Maybe it’s an issue with medical rewrite? @jonpas

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/common/functions/fnc_setVolume.sqf#L36

This function doesn't seem to be called in the new medical though.

Opened an issue at ACE3 https://github.com/acemod/ACE3/issues/7528.

**Comment by jonpas** [comment]
Getting fixed in ACE3: https://github.com/acemod/ACE3/pull/7529
