### ISSUE TITLE
acre_api_fnc_setCustomSignalFunc can´t be undone

### ISSUE THREAD

**Issue by Zumiii** [IDI-Systems/acre2#890]
- Mods:
ace
ACRE2
CBA_A3

- Arma 3: 1.96.146114
- CBA: 3.14.0.200207
- ACRE2: 2.7.2

**Description:**
When using the acre_api_setcustomSignalFunc, the Variable doesn´t seem to be set properly. Once set, the Variable acre_sys_signal_customSignalFunc  cant be undefined.
When trying to set:
`acre_sys_signal_customSignalFunc = nil;`
via Script, the Code:
`(isNil "acre_sys_signal_customSignalFunc")`
still returns false

**Steps to reproduce:**
- Set your custom signalfunc
- Execute [{}] call acre_api_setcustomSignalFunc; locally
- Check for (isNil "acre_sys_signal_customSignalFunc")

**Expected behavior:**
acre_sys_signal_customSignalFunc should be nilled

**Where did the issue occur?**
- Dedicated && Self-Hosted Multiplayer && Singleplayer && Editor (Singleplayer) && Editor (Multiplayer)

**Additional context:**
Trying to Script a jammer Function, which works fine, but it doesnt let me reset the GVAR

**Comment by jonpas** [comment]
This is wrong:
```
[{}] call acre_api_setcustomSignalFunc
```
should be:
```
[{}] call acre_api_fnc_setCustomSignalFunc
```

**Comment by Zumiii** [comment]
I actually typed it wrong here, but in the script it is correct. I also tryed to undefine the variable:
acre_sys_signal_customSignalFunc = nil;
It didn´t matter, it still used the custom signalfunc. I will look at it again tomorrow and write if i find something out. I will also dig a bit deeper into the acre code.

**Comment by jonpas** [comment]
https://github.com/IDI-Systems/acre2/blob/c660621831d4a4ac4647a80d65492de4f7fe2a56/addons/sys_signal/fnc_getSignal.sqf#L21

This is the only place it is used, and I don't why that wouldn't work. Maybe the API function could be broken, but setting the variable directly should still revert it.

**Comment by Zumiii** [comment]
I knew that function. I even can´t get it to work by typing:
```
if !(isNil "acre_sys_signal_customSignalFunc") then {
	acre_sys_signal_customSignalFunc = nil;
};
```
The API is being called locally right?

Using:
`[{}] call acre_api_fnc_setCustomSignalFunc;`
Does nothing

**Comment by Zumiii** [comment]
> EGVAR(sys_signal,customSignalFunc)

according to 

> #define EGVAR(var1,var2) TRIPLES(PREFIX,var1,var2) 

means

> idi_acre_sys_signal_customSignalFunc

?

**Comment by jonpas** [comment]
No, [`PREFIX` is `acre`](https://github.com/IDI-Systems/acre2/blob/master/addons/main/script_mod.hpp#L4).

**Comment by Zumiii** [comment]
Ok, well, in this case i dont know what i am doing wrong ^^

**Comment by dedmen** [comment]
Log the contents of `acre_sys_signal_customSignalFunc ` via debug console while its not nil, see whats inside.

**Comment by Zumiii** [comment]
```
15:12:01 Error in expression <_log format ["Returned Signalpower: %1" _mWnew];
private _rxAntennas = [_receive>
15:12:01   Error position: <_mWnew];
private _rxAntennas = [_receive>
15:12:01   Error Missing ]
15:12:01 File zumi\jammer\fn_customSignalFnc.sqf [zumi_fnc_customSignalFnc]..., line 12
15:12:01 Error in expression <_log format ["Returned Signalpower: %1" _mWnew];
private _rxAntennas = [_receive>
15:12:01   Error position: <_mWnew];
private _rxAntennas = [_receive>
15:12:01   Error Missing ]
15:12:01 File zumi\jammer\fn_customSignalFnc.sqf [zumi_fnc_customSignalFnc]..., line 12
```
The problem seems to be inside my function that calculates the signal strength.
I am right now debugging that function, will post as soon as i know more.

**Comment by Zumiii** [comment]
Even with no errors showing up anymore, i cannot reset the signalFunc to its default.

**Comment by jonpas** [comment]
Can you link or post your function? I will test it.

**Comment by Zumiii** [comment]
preInit:
```
["acre_startedSpeaking", {
		params [["_player", player], ["_onRadio", false], ["_radioID", ""]];
		if (!_onRadio) exitWith {};
		zumi_jammers = zumi_jammers select {(_x getvariable ["zumi_jamming", false])};
		if ((count zumi_jammers) < 1) then {
			if !(isNull (_player getVariable ["zumi_currentJammer", objNull])) then {
				_player setVariable ["zumi_currentJammer", objNull];
			};
			if !(isNil "acre_sys_signal_customSignalFunc") then {
				acre_sys_signal_customSignalFunc = nil;
			};
		} else {
			private _closestJammer = [zumi_jammers, {-(_player distance2d _x)}, objNull] call CBA_fnc_selectBest;
			private _currentJammer = _player getVariable ["zumi_currentJammer", objNull];
			if (_currentJammer != _closestJammer) then {
				_player setVariable ["zumi_currentJammer", _closestJammer];
			};
			if (isNil "acre_sys_signal_customSignalFunc") then {
				acre_sys_signal_customSignalFunc = zumi_fnc_customSignalFnc;
			};
		};
	}] call CBA_fnc_addEventHandler;
```

zumi_fnc_customSignalFnc:

```
if (!hasInterface) exitWith {};

params ["_f", "_mW", "_receiverClass", "_transmitterClass"];

private _count = missionNamespace getVariable [_transmitterClass + "_running_count", 0];
if (_count == 0) then {

	_mWnew = [acre_player, _mW, _f] call zumi_fnc_calculate_power;
	private _rxAntennas = [_receiverClass] call acre_sys_components_fnc_findAntenna;
	private _txAntennas = [_transmitterClass] call acre_sys_components_fnc_findAntenna;
	{
		private _txAntenna = _x;
		{
			private _rxAntenna = _x;
			_count = _count + 1;
			private _id = format ["%1_%2_%3_%4", _transmitterClass, (_txAntenna select 0), _receiverClass, (_rxAntenna select 0)];
			[
				"process_signal",
				[
					_id,
					(_txAntenna select 2),
					(_txAntenna select 3),
					(_txAntenna select 0),
					(_rxAntenna select 2),
					(_rxAntenna select 3),
					(_rxAntenna select 0),
					_f,
					_mWnew, //Signalstärke
					acre_sys_signal_terrainScaling,
					diag_tickTime,
					ACRE_SIGNAL_DEBUGGING,
					acre_sys_signal_omnidirectionalRadios
				],
				true,
				acre_sys_signal_fnc_handleSignalReturn,
				[_transmitterClass, _receiverClass]
			] call acre_sys_core_fnc_callExt;
		} forEach _rxAntennas;
	} forEach _txAntennas;
	missionNamespace setVariable [_transmitterClass + "_running_count", _count];
};

private _maxSignal = missionNamespace getVariable [_transmitterClass + "_best_signal", -992];
private _Px = missionNamespace getVariable [_transmitterClass + "_best_px", 0];


if (ACRE_SIGNAL_DEBUGGING > 0) then {
	private _signalTrace = missionNamespace getVariable [_transmitterClass + "_signal_trace", []];
	_signalTrace pushBack _maxSignal;
	missionNamespace setVariable [_transmitterClass + "_signal_trace", _signalTrace];
};

[_Px, _maxSignal];
```

zumi_fnc_calculate_power:
```
params ["_player", "_power", "_frequency"];

private _currentJammer = _player getVariable ["zumi_currentJammer", objNull];

if (isnull _currentJammer) exitWith {_power};

private _radio = ([] call acre_api_fnc_getCurrentRadio);

if (_radio isequalTo "") exitWith {_power};

private _channel = [_radio] call acre_api_fnc_getRadioChannel;
if (_channel < 0) exitWith {
 _power;
};

private _txData = [_radio, "getCurrentChannelData"] call acre_sys_data_fnc_dataEvent;
private _frequenzTX = _txData getVariable ["frequencyTX", 0];
private _rxData = [_radio, "getCurrentChannelData"] call acre_sys_data_fnc_dataEvent;
private _frequenzRX = _txData getVariable ["frequencyRX", 0];


private _frequenz_jammed = false;
{
 if ((_frequenzTX >= (_x select 0)) && (_frequenzTX <= (_x select 1))) then {
   _frequenz_jammed = true;
 };
 if ((_frequenzRX >= (_x select 0)) && (_frequenzRX <= (_x select 1))) then {
   _frequenz_jammed = true;
 };
 if (_frequenz_jammed) exitWith {};
} count zumi_frequenzen;

if !(_frequenz_jammed) exitWith {
 _power;
};

private _distance2d = _player distance2D _currentJammer;

if (_distance2d <= 50) exitWith {
 0;
};

linearConversion [50, 100, _distance2d, 0, 1, true];
```

**Comment by Zumiii** [comment]
For adding a Jammer type:
```
player setVariable ["zumi_jamming", true, true];
_jip_str = ["zumi_jammer", [player , true]] call CBA_fnc_globalEventJIP;
[_jip_str, player ] call CBA_fnc_removeGlobalEventJIP;
```
For removing it:
```
player setVariable ["zumi_jamming", false, true];
_jip_str = ["zumi_jammer", [player, false]] call CBA_fnc_globalEventJIP;
[_jip_str, player] call CBA_fnc_removeGlobalEventJIP;
```

**Comment by Zumiii** [comment]
It will activate/update as soon as you use a radio.

**Comment by Zumiii** [comment]
Oh and defines:

```
zumi_jammers = [];
publicVariable "zumi_jammers";
zumi_frequenzen = [
			[30,90], //VHF SEM 52SL/70/80/90
			[2400,2402.55], //UHF 343
			[0,1000] //Frei programmierbare 148/152/117
		];
publicVariable "zumi_frequenzen";
```

**Comment by dedmen** [comment]
> Log the contents of acre_sys_signal_customSignalFunc via debug console while its not nil, see whats inside.

Maybe also provide RPT.

**Comment by Zumiii** [comment]
RPT shows nothing connected to ACRE or my fnc

**Comment by Drofseh** [comment]
Post it anyways

**Comment by dedmen** [comment]
> RPT shows nothing connected to ACRE

That means you didn't load ACRE, kinda obvious that ACRE doesn't work if you didn't even load it.

**Comment by Zumiii** [comment]
[rpt.txt](https://github.com/IDI-Systems/acre2/files/4391004/rpt.txt)

**Comment by Zumiii** [comment]
> That means you didn't load ACRE, kinda obvious that ACRE doesn't work if you didn't even load it.

No errors, as far as i can tell

**Comment by Drofseh** [comment]
`Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!`

**Comment by dedmen** [comment]
Thats exactly why I asked for the RPT, because I suspected you lied in your modlist.
Btw you can just attach files, instead of posting such a big block of text as a message.
Also after 2 days now you still didn't check what I told you to check.

I think I know what might be causing this, but please first check what I told you twice... thrice now, and then test again with only the mods that you actually specified in your bug report post.

**Comment by NouberNou** [comment]
@dedmen No need to be hostile. Calm down.

**Comment by Zumiii** [comment]
> Log the contents of `acre_sys_signal_customSignalFunc ` via debug console while its not nil, see whats inside.

I will do that as soon as i am home with only the 3 addons loaded. As far as i can tell right now, the function works fine, the signal is being calculated correctly (according to debugging with hint format  ) and the player is set to "jammed" when he should be. But undefining the GVAR for the customSignalFunc doesn't seem to work. How could that be connected to any of those additional mods?

**Comment by Zumiii** [comment]
[Arma3_x64_2020-03-27_09-28-02.rpt.txt](https://github.com/IDI-Systems/acre2/files/4392462/Arma3_x64_2020-03-27_09-28-02.rpt.txt)

(Self hosted)
Works as intended, still does not reset the GVAR.

**Comment by Zumiii** [comment]
[rpt.txt](https://github.com/IDI-Systems/acre2/files/4392607/rpt.txt)

**Comment by dedmen** [comment]
> How could that be connected to any of those additional mods?

Hm So the sympthom is
> But undefining the GVAR for the customSignalFunc doesn't seem to work.

What if.. some mod.. lets say maybe RHS (which you have loaded despite not listing it in your report) which has ACRE signal jammers which probably uses customSignalFunc, repeatedly sets customSignalFunc to its own because thats what it needs for its own jammer function.
Oh right, it will never be nil, because RHS will repeatedly set it.

Which is why I asked for you to log the contents of the function, which you still haven't done.
Because then we can see what actual function it is being set to, and that makes it much easier to figure out what is setting it.
If it is some unknown script, with `rhs_` variables inside it.. Then we could just guess that its from RHS, and it would be hard to guess wrong at that point.


I just can't see any way how this is acre's fault, so I'm trying to find out what user error you made.

**Comment by Soldia1138** [comment]
@dedmen While you're correct on the original report, the posted rpt from today are without any additional mods. So that can be the baseline for further investigation

**Comment by Zumiii** [comment]
> What if.. some mod.. lets say maybe RHS (which you have loaded despite not listing it in your report) which has ACRE signal jammers which probably uses customSignalFunc, repeatedly sets customSignalFunc to its own because thats what it needs for its own jammer function.
> Oh right, it will never be nil, because RHS will repeatedly set it.

In the given RPT i do not load RHS, only the three mentioned Addons

**Comment by Zumiii** [comment]
The Problem is, once a custom Signal Function is used, it cannot be undone for some Reason.
Besides, even with RHS loaded, the GVAR is "Nil"

**Comment by Soldia1138** [comment]
Minimal approach:

Delete all of your functions regarding the custom signal function out of the mission, start it.

Debug Console, watch:
```
acre_sys_signal_customSignalFunc
```
and
```
isNil "acre_sys_signal_customSignalFunc"
```

Then execute (global, local, whereever you want that function to be applied):
```
[{hint "Hello"}] call acre_api_fnc_setCustomSignalFunc
```

Does the watch-lines change?

```
[{}] call acre_api_fnc_setCustomSignalFunc
```

Does it work?

It works for me at least. Setting and resetting.

**Comment by dedmen** [comment]
> The Problem is, once a custom Signal Function is used, it cannot be undone for some Reason.
Besides, even with RHS loaded, the GVAR is "Nil"

You finally actually checked the contents of the function like I asked?
So the signal function is still there, and isNil returns false. But the variable is "Nil"? 
Can you explain? Did I missunderstand that? How is it nil?
Your test with isNil showed its not nil so what do you mean by "Nil"?

**Comment by Zumiii** [comment]
What i tried to say there is, that RHS does only have an effect on TFAR but not on ACRE.
So, with no own function used and RHS loaded, acre_sys_signal_customSignalFunc  is still undefined.
As soon as i use my function, the customsignalfunc cannot be undefined by script nor by command.

**Comment by Zumiii** [comment]
> Minimal approach:
> 
> Delete all of your functions regarding the custom signal function out of the mission, start it.
> 
> Debug Console, watch:
> 
> ```
> acre_sys_signal_customSignalFunc
> ```
> 
> and
> 
> ```
> isNil "acre_sys_signal_customSignalFunc"
> ```
> 
> Then execute (global, local, whereever you want that function to be applied):
> 
> ```
> [{hint "Hello"}] call acre_api_fnc_setCustomSignalFunc
> ```
> 
> Does the watch-lines change?
> 
> ```
> [{}] call acre_api_fnc_setCustomSignalFunc
> ```
> 
> Does it work?
> 
> It works for me at least. Setting and resetting.

This works for me too

**Comment by Zumiii** [comment]
It seems to make a difference not having it precompiled in the cfgFunctions

**Comment by Zumiii** [comment]
[] call compile preProcessFileLineNumbers "zumi\jammer\fn_customSignalFnc.sqf";

logs show error in Line 45:

14:35:05 Error in expression <} forEach _txAntennas;
missionNamespace setVariable [_transmitterClass + "_runni>
14:35:05   Error position: <setVariable [_transmitterClass + "_runni>
14:35:05   Error Reserved variable in expression
14:35:05 File C:\Users\x\Documents\Arma 3 - Other Profiles\Zumi\missions\acre_debug.Altis\zumi\jammer\fn_customSignalFnc.sqf..., line 45

**Comment by dedmen** [comment]
> This works for me too

But thats what the repro steps in the report say doesn't work.

> 14:35:05 Error Reserved variable in expression

that means either name of a script command, or empty string, cannot really be either as you append a suffix.
I assume _transmitterClass is nil in there.

> It seems to make a difference not having it precompiled in the cfgFunctions

it doesn't matter where a function is compiled, result is the same. And that also shouldn't influence your removing of the function.. unless.. Acre tries to execute your signal func, errors out and exits, and thus never calls `acre_startedSpeaking` thereby not calling your eventhandler that would remove the signal func.

**Comment by Zumiii** [comment]
I might give up on this. I can´t get it working. Thx for Support though. Acre Jammer would have been the icing on the cake.

**Comment by Zumiii** [comment]
Hang on i think i know what i did wrong. I fucked up the script. I fixed some things, gonna test, will report! I can reset the GVAR now!

**Comment by jonpas** [comment]
If the example given by @Soldia1138 works, then it must be something inside your  function that is preventing the reset. Either it constantly sets it back or errors somewhere on the way and never reaches the unset point. If you tried manually unsetting it while it was running, first case is probably the issue.

**Comment by Zumiii** [comment]
First Tests in Singleplayer Environment have been **successful**, waiting for our Servers to update and will update after I checked it out in Multiplayer!

**Comment by Zumiii** [comment]
It works. It jamms the receiving and broadcasting Antenna within the wanted radius. However, it does not weaken the miliwatt.

**Comment by Zumiii** [comment]
Works like a charm. Thanks for patience.

**Comment by jonpas** [comment]
Glad you solved it!
