### ISSUE TITLE
Pipe Error 

### ISSUE THREAD

**Issue by joezappie** [IDI-Systems/acre2#893]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.96.146114 stable
- **ACRE2:** 2.7.2.1022 stable

- **TeamSpeak Client:** 3.5.1
- **TeamSpeak Server:** 3.12.0

**Description:**
One of my friends is having an issue where when the mission starts up he briefly gets an "Acre Connected" message and then it gives him a generic "Pipe Error" message. We cannot hear him in game, but he can hear us so his ACRE definitely isn't connected. We have 7 other people who the mod works for so the server is setup correctly. This is a client side issue.

I've tried having him run as admin for both TS and Arma, hes reinstalled Arma and TS a few times now, hes switched from Windows 7 to Windows 10, hes disabled his firewall, hes restart TS while in game, hes restarted ARMA while connected to TS.

He does get the message when booting Arma for the first time after installing the mod that the ACRE plugin has been copied to his team speak. He can see the plugin in the addons tab in Teamspeak and it is enabled.

This used to work for him but we stopped playing Arma for about 8 months. Nothing has changed for him, same computer and hardware, same apartment, same internet. Our group has used this mod for about 2 years and this is the first time we've had an issue like this.

I did also reinstall my TS server on a different physical server, but that didn't help. Like I said I've got 7 other people who can all connect and use ACRE just fine, so I think its safe to rule out a server issue.

Are there any other logs that might have some information? Is there any router settings he should look at or port forward? We can hear him fine in Team Speak but once the mission starts he can hear us but we cant hear him.

**Steps to reproduce:**
Unknown

**Expected behavior:**
Acre to connect and for everyone to be able to hear the person in game

**Where did the issue occur?**
Dedicated multiplayer

**Log Files:**

RPT: 
Working on getting this from him.

acre_dll.log: 
2020-03-28 22:39:02,617-{INFO }- ACRE Loaded
2020-03-28 22:39:02,619-{INFO }- Generating PBO List
2020-03-28 22:39:30,168-{INFO }- PBO Index complete
2020-03-28 22:40:56,616-{INFO }- Attempting to load map from PBO...
2020-03-28 22:40:58,261-{INFO }- Map Loaded, Error Status: 0
2020-03-28 22:40:58,263-{INFO }- Adding signal processing to map...
2020-03-28 22:40:58,263-{INFO }- Finished adding signal processor to map.

TS Client Log:
https://pastebin.com/g2UB6Pwr

**Additional Comments**
Reading through the first couple of pages on the steam workshop comments there are several other people with this exact same issue: Mak, An Inconspicuous Landmine and Kal. Doesn't seem like they've received any tips on possible fixes.

**Screenshots:**
I will get a screenshot of the Pipe Error message.

**Comment by jonpas** [comment]
RPT will be required.

Also make sure no anti-virus program is blocking those extensions. They could easily be blocked as soon as they start getting used, which would cause a disconnect exactly as described.

> Doesn't seem like they've received any tips on possible fixes.

We only monitor this GitHub page for issues and our Slack for questions.

**Comment by joezappie** [comment]
Hi jonpas, thanks for the suggestion. He actually just bought a new SSD and reinstalled windows (instead of just upgrading from 7 to 10) and now its working. Since he cannot get me an RPT to post since its now fixed, I will close this issue.

**Comment by jonpas** [comment]
Could be permission errors, anti-virus blocking or simple HDD failure at that point.

Glad its resolved.
