### ISSUE TITLE
Every player hearing babel like voices instead of normal voices

### ISSUE THREAD

**Issue by PrivateMcMuffin** [IDI-Systems/acre2#900]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.96.146114` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.14.0` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `stable` [e.g. 2.0.0 stable, commit hash]

**Description:**
On mission start, every player that spawns hears each other as if they are speaking with a babel language. This has happened to me before: https://github.com/IDI-Systems/acre2/issues/564
I reset up my dedicated arma3 Linux server two weeks ago, and figured I'd give this mod a shot since it's been a year since I had this issue. After reinstall of the server, and CBA and ACRE2, I loaded into a stock Arma 3 mission to see if the radios worked. They didn't. every player on the same side, in the same group, experience this. The funny thing is, after reading: https://github.com/IDI-Systems/acre2/issues/41, I changed the settings in the module to "per side" and it seemed to work after  that. However after restarting my server today, it all of a sudden no longer works. I wiped my server, reinstalled everything, loaded into mission with just fresh installs of Arma3, CBA, and ACRE2, and loaded into stock missions, even missions where I tinkered with the settings, and I still can't get the babel voices to go away. After asking around, and going on the steam workshop page and scrolling through the comments, this seems to be effecting a lot of people. Last year when this happened, nobody could recreate this problem, however, I could not get the mod to function properly at all.

**Steps to reproduce:**
- Fresh install of Arma3 dedicated linux server, CBA, ACRE2, and stock Arma3 missions.
- Launch everything as admin
- Load into a stock Arma3 mission on the server
-Attempt to talk to another player

**Expected behavior:**
Every player connected to the server can't understand other players as if the deep roboticy babel voice is applied to everybody.

**Where did the issue occur?**
- Dedicated Linux Server to all(10) players

**Log Files:**
I've gone ahead and set up an duplex output.
https://pastebin.com/vrV5dypG

**Additional context:**
I don't expect anybody to be able to go and recreate this issue if their acre2 already works fine. I have used it for the last two weeks every day and it has worked fine for me. One day it just stops working and I can't seem to figure out why.

**Comment by jonpas** [comment]
RPT is kind of required. You have to redirect output on Linux.

**Comment by PrivateMcMuffin** [comment]
Right, yea I figured I'd have to go and set that up eventually. Last time the RPT was useless, so I figured I could skim out. I went and set up the outputs.
This is the RPT from the server launching with just CBA and ACRE2. Nothing stood out to me except line 673-675. Other then that, nothing crazy.
https://pastebin.com/vrV5dypG
Is there anything else that could help? I've been able to use ACRE2 for the last two weeks.

**Comment by jonpas** [comment]
Can you test with a very small singleplayer mission? Preferably just slots and that's it.

Also upload client RPT, may have more clues.

**Comment by PrivateMcMuffin** [comment]
Right, I loaded with a stock mission with just 2 slots, and the same thing happened. The call extension line is attempting to load an ACRE2 DLL on Linux which I've always known to not be ideal, but it works fine for so many people on Linux. I'll load up the small mission with two people and grab the client RPT's.

After searching on BI's Wiki for Call Extension not found, I found this Line:
Linux specific
While on Windows the extension name is case-insensitive, on Linux the extension name is case-sensitive and should match the name of the .so file exactly (minus ".so" part). Currently only 32-bit extensions are supported on Linux.

I got the server RPT: https://pastebin.com/uE8A4y3w
client RPT: https://pastebin.com/K4SPQMSu
I skimmed through it, nothing jumped out to me. the server RPT states the same lines.

**Comment by jonpas** [comment]
> The call extension line is attempting to load an ACRE2 DLL on Linux

ACRE2 doesn't do anything on the server, that's just a bug already fixed for 2.7.3, it should never even try to load on the server.

```
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_other_on.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_other_off.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\beep.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\beep-low.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_new_on.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\mic_click_new_off.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\semknob.b64'. Extension not listed in allowedLoadFileExtensions
19:08:41 Could not load '\idi\acre\addons\sys_sounds\sounds\click.b64'. Extension not listed in allowedLoadFileExtensions
```

Here lies one problem. easily fixable: https://acre2.idi-systems.com/wiki/user/installation#troubleshooting
> Radio beeps not audible on dedicated server

I don't see anything else. Your TeamSpeak settings could be a problem, insufficient bandwidth reducing the quality to babel-like unrecognizable quality.

**Comment by PrivateMcMuffin** [comment]
I'll go through and run that fix for the radio beeps. I wasn't concerned about the beeps in the first place though. Maybe restart the entirety of the server, including the Teamspeak server, and try to tweak with the module some more.

**Comment by PrivateMcMuffin** [comment]
**SOLVED**
I'd recommend mentioning this in the troubleshooting section for ACRE2 as it is a simple problem that I feel can be simply overlooked by a lot of people. 
I've been running the teamspeak for about two weeks but yesterday it auto-restarted. When it did that, the settings have it auto-default to OPUS Music instead of OPUS voice. I usually check that before anything else, but we had a music bot that changes the channel to OPUS Music aswell. simple fix that I overlooked. 
Thank you for being patient and working with me on this though. The fast replies are much appreciated.

**Comment by jonpas** [comment]
Glad you got it solved. Sadly fast replies are not always possible. :)

If you'd like, you can easily open a pull request for the troubleshooting addition. Every wiki page has an "Edit" button that leads to the source page.
