### ISSUE TITLE
ACRE2 interference with CBA Item Context Menu Framework

### ISSUE THREAD

**Issue by G3rrus** [IDI-Systems/acre2#901]
**Mods: CBA, ACRE2**
- **Arma 3: 1.96 stable**
- **CBA: 3.15.0 stable**
- **ACRE2: 2.7.2 stable**

**Description:**
ACREs system to be able to double click to open radios in the inventory seems to interfere with CBAs new "Item Context Menu Framework".

https://github.com/CBATeam/CBA_A3/blob/master/addons/ui/fnc_addItemContextMenuOption.sqf

**Steps to reproduce:**
- Go to editor and place player/playable unit.
- Click play
- Execute example given in CBA_fnc_addItemContextMenuOption (Debug console)
```
["#All", "ALL", ">DEBUG ACTION<", nil, nil, {true}, {
	params ["_unit", "_container", "_item", "_slot", "_params"];
	systemChat str [name _unit, typeOf _container, _item, _slot, _params];
	true
}, false, [0,1,2]] call CBA_fnc_addItemContextMenuOption;
```
- Double Click on various items

**Expected behavior:**
While the >DEBUG ACTION< should show up on things like the uniform/vest/backpack and guns themselves, it will not show up on items in uniforms/backpacks/vests. (although it should)

**Where did the issue occur?**
I tried it in:
- Self-Hosted Multiplayer
- Singleplayer
- Editor (Singleplayer)
- Editor (Multiplayer)

**Comment by jonpas** [comment]
Thanks, this conflicts: https://github.com/IDI-Systems/acre2/blob/c748d10ac11afe0aac9e71a28ef5df81795bf2f6/addons/sys_gui/fnc_inventoryMonitorPFH.sqf

Best if we simply move that over to the new CBA system, I see no reason not to.

**Comment by PabstMirror** [comment]
not sure, but I think switching from `ctrlSetEventHandler` -> `ctrlAddEventHandler` might be enough?

**Comment by jonpas** [comment]
Both are used right now, does `Add` support all required events?

I don't see too much of a point when we can just use the CBA system though. Could even add more actions to it instead of the ACE3 menu (or in addition).
