### ISSUE TITLE
Add an API for cut off / mute radios

### ISSUE THREAD

**Issue by Elgin675** [IDI-Systems/acre2#908]
It could be interesting to implement an api that would allow to mute the radios and / or adjust their volume.

This would allow, for example, because that's what I was trying to do, to cut off radio transmissions in specific cases, typically in an area considered "jammed" by the mission maker, or to prevent unconscious players from listening to other players' communications.

**Comment by jonpas** [comment]
What you are really asking here for is a framework for jamming. We could technically use [Custom Signal Processing](https://acre2.idi-systems.com/wiki/frameworks/custom-signal-processing) to provide some nicer API for disabling/enabling, however I bet we already have better ways to do that, just not exposed.

As far as I understood, you want to mute radios when person is unconscious in ACE Medical, and that really has nothing to do with jamming.

**Comment by Elgin675** [comment]
Thank you for your answer @jonpas !
Indeed, perhaps I should have made two separate requests, instead of just confusing one.

That said, you have understood exactly what I would like :
- the possibility of mute radios while unconscious,
- the possibility of "jamming" radios (with parasitic noises, such as white noise / pink noise, etc.)

Thank you very much, and sorry for the confusion ;) !

**Comment by jonpas** [comment]
> the possibility of mute radios while unconscious,

Done in #1159 and acemod/ACE3#8659.

> the possibility of "jamming" radios (with parasitic noises, such as white noise / pink noise, etc.)

#1087 makes custom signal processing easier, so you could add your own jamming. Filters such as white noise etc. would require interaction with the audio system, for which there are other issues open.
