### ISSUE TITLE
Zeus local speech cut-off on "disable spectator" mode

### ISSUE THREAD

**Issue by BorderKeeper** [IDI-Systems/acre2#911]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.98
- **CBA:** 3.15.0
- **ACRE2:** 2.7.2.1022

**Description:**
Previously with "disabled spectator" you could hear people around your body talking and you could talk to them as if you weren't in zeus at all. This is still the case, but only if you are roughly 100 meters around the body with the zeus camera.

**Steps to reproduce:**
- Launch a multiplayer game
- Get into Zeus whilst a player near you is talking
- Move >100m away and notice a sudden disappearance of his voice at a certain range

**Expected behavior:**
- Disable Spectator mode: You can talk to people around you and hear them no matter where you are at the cost of not being able to hear audio from zeus camera or people in spectator.
- Enable Spectator mode: You can only hear people around your zeus camera and people in spectator. Can only talk to people in spectator. (This mode seems to work fine)

**Where did the issue occur?**
- Dedicated

**Log Files:**
- [extension acre log from that day](https://pastebin.com/sgrBJ3yb)

**Video:**
[![Youtube](https://img.youtube.com/vi/ejjyvDzrMCQ/0.jpg)](https://www.youtube.com/watch?v=ejjyvDzrMCQ)

**Comment by jonpas** [comment]
Seems the same as #870 to me.

**Comment by BorderKeeper** [comment]
> Seems the same as #870 to me.

I checked that one and I believe it proposes hearing both players around you and people in Zeus cam.

Also to add colleagues in my discord pointed out that this might be an achilles bug due to it not being maintained anymore.

**Comment by jonpas** [comment]
What you are experiencing is inded same bug as #870, just worded differently. It is a bug, as it should work in the way that you can hear both players around your unit and around your Zeus camera.

I will close this report so we can only leave one open. It will be linked.

**Comment by BorderKeeper** [comment]
Thanks jonpas. Altough I am confident this has worked in the past version
of acre from two weeks ago. Maybe we were on a very old version.

Good luck with bug smashing, JL.

**Comment by jonpas** [comment]
There was no update since 25th November. It did indeed break in that update.

It's fixed for next update anyways. :)
