### ISSUE TITLE
Feature: "Take Shared Radio" Hotkey

### ISSUE THREAD

**Issue by Quailsnap** [IDI-Systems/acre2#937]
Been playing more operations lately that depend on ACRE2's "SHARE RADIO" feature, currently only accessible through use of the ACE3 Interaction menu on the part of both sharer and shared-to. It is very fluid as the sharer, but if someone is frequently trying to access the shared radio on a moving, conscious person, it is oftentimes a bother. 

The actual scenario usually involves a Platoon or Company leader with a designated RTO nearby.

Possible solutions:
- an additional ACE node in the share menu to "ALWAYS GRAB" that will automatically add the radio to that person's inventory when they are in a certain distance of the sharer
- a hotkey to take a shared radio off of someone. overlap it with the hotkeys (if any exist?) for vehicle infantry phones, since shared radios are for non-vehicles (actual infantry) only. I would personally probably make it the same as my shoulder-tap bind (shift+t) but that's obviously not for everyone
- an additional ACE node on someone's person when they are sharing their radio. I don't personally like this one, but it would probably be approximately upper torso, which is currently mostly unoccupied

**Comment by jonpas** [comment]
I like this.

First one sounds expensive, would have to continously scan near objects. Other 2 are doable.

**Comment by Quailsnap** [comment]
Mostly a fan of the second one, but the first one can be done -- the calculations for ACE interaction nodes are only run when the menu is open, right?

So nest "GRAB NEAREST SHARED RADIO" under the ACRE Radio's tree, and if someone opens the "Radios" node, check nearestEntities... for a publicly broadcasted variable that simply states whether they have a shared radio available or not?

**Comment by TheMagnetar** [comment]
First one cannot be done.  It would  break handheld radios where only the one using it can send/receive.

**Comment by Drofseh** [comment]
I'd prefer an ace interaction instead of an additional hotkey.
