### ISSUE TITLE
[ACRE] (sys_gsa) ERROR: Empty unique radio ID

### ISSUE THREAD

**Issue by LOOP3PARA** [IDI-Systems/acre2#939]
**Mods:
@CBA_A3;@CUP_Terrains_Core;@Virolahti;@HEBONTES;@ADV;@ace3;@acex;@ALiVE;@ACRE2;@CUPUnits;@CUPVehicles;@CUPWeapons;@CFP;@3cb_baf_units;@3cb_baf_equipment;@3cb_baf_weapons;@3cb_baf_vehicles;@RKSLWatchkeeper;@RKSL;@RKSLWildcat;@Boeing;@Bdf;@backpackonchest;@DUI;@EM;@Ctab;@JSHK;@Suppress;@CF_BAI;@Vcomai;@LAMBS;@LAMBS_Suppression;@LAMBS_RPG;@Zab;@UK_Insignia_pack;@LimitedGunMovement;

_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

DONE.

**Description:**
When using the GSA the RPT file is floodet with this 3 errors :

[ACRE] (sys_gsa) ERROR: Empty unique radio ID

ThingX 8768dd00# 1697033: wrench_f.p3d was falling under terrain! Position corrected to ground [8892.33, 184.02, 11935.23]. Disable simulation to keep object under terrain.

Ref to nonnetwork object 87ab2b00# 1696916: wrench_f.p3d

**Steps to reproduce:**
- Go to mission
- Use the GSA
- Close server and tjek rpt file

**Expected behavior:**
Not my server chrasing

**Where did the issue occur?**
- Dedicated server with about 18 Players 

**Log Files:**
https://drive.google.com/open?id=1XvE5wXKbZwtukedjIWHNt0ZZrTiIm1aE

**Additional context:**
Mission was on tanora

**Screenshots:**
N/A

**Comment by Drofseh** [comment]
`Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!`

**Comment by LOOP3PARA** [comment]
We didt

**Comment by CammyL16** [comment]
yeh this issue popped up on a mission of ours on sunday which the rpt file is from and just to make sure we recreated the scenario with just said mods CBA, ACRE2 and ACE and the same issue happened, this was similar to the bug a bit ago with the terrain stuff going a bit nuts , with this one though it made it so a few members who tried to rejoin to spectate via Ace spectator slot got a CTD
