### ISSUE TITLE
Disallow radio use while an ACE captive

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#948]
**Is your feature request related to a problem?**
Players can use radios while an ACE captive

**Solution you'd like:**
A setting to disallow radio use while an ACE captive.

**Alternatives you've considered:**
Taking away their radio, this leaves them with no radio when they are freed.

**Comment by bux** [comment]
Ref: https://github.com/acemod/ACE3/pull/4334

**Comment by BrettMayson** [comment]
Ah nice, 2016 :(

**Comment by jonpas** [comment]
#600 fixed `isDisabled` use since then. I don't think there is anything left to do in ACRE2 specifically, since ACE3 already has the required functions that handle other radio mod things.

**Comment by jonpas** [comment]
Properly fixed in https://github.com/acemod/ACE3/pull/8388.
