### ISSUE TITLE
Add variable with connected Teamspeak IP/Name

### ISSUE THREAD

**Issue by bux** [IDI-Systems/acre2#955]
**Is your feature request related to a problem?**
I would like to check if people have connected to the correct Teamspeak server.

**Solution you'd like:**
A variable I can check containing the IP and or Teamspeak server name a player has connected to

**Alternatives you've considered:**
Writing a custom extension doing that

**Additional context:**
This would be very helpful for public server to remind players to connect to one Teamspeak server and make people play together rather in their own groups.

**Comment by dedmen** [comment]
TFAR has servername/serveruid/channelname/channelid
I don't like IP. usually you don't actually need a actual IP. And.. privacy/safety. 
What if user is not on your server, but some other server, you could spy out the IP and stuff..
Unlikely that many people would do that but still..

**Comment by ThymoNL** [comment]
Similar to #510

**Comment by bux** [comment]
2 years 😢

**Comment by TheMagnetar** [comment]
Contributions are welcome:D

**Comment by bux** [comment]
C# ok? 😄
