### ISSUE TITLE
Channel scratchpad does not load current channel name

### ISSUE THREAD

**Issue by ThymoNL** [IDI-Systems/acre2#958]
**Description:**
Radio scratchpad is kept between channels switches.

**Steps to reproduce:**
- Edit a channel name
- Select different channel to edit
- Edit name
- Observe last channel name being in scratchpad

**Expected behavior:**
Scratchpad loads current channel name

**Additional context:**
Affects PRC117f and 152. Will check 148.

**Comment by ThymoNL** [comment]
I'll take this one

**Comment by jonpas** [comment]
Great! :D

**Comment by ThymoNL** [comment]
Obviously 148 is unaffected because it doesn't have a scratchpad, duh. :P

**Comment by ThymoNL** [comment]
I must be going crazy because I can no longer reproduce this. Will reopen when this surfaces again.

**Comment by ThymoNL** [comment]
I knew I wasn't crazy! This was indeed an issue in the latest release but I couldn't reproduce it on master. That is because it was already fixed. 😅 
https://github.com/IDI-Systems/acre2/pull/946#issuecomment-623188454
