### ISSUE TITLE
Parse options from parameter files

### ISSUE THREAD

**Issue by ThymoNL** [IDI-Systems/acre2#959]
**Is your enhancement related to a problem?**
Arma 3 launcher doesn't support custom command line arguments so -skipAcrePluginCopy can't be added through standard launcher

**Solution you'd like:**
Look for -par parameters and parse options in those files to check for -skipAcrePluginCopy.
https://community.bistudio.com/wiki/Startup_Parameters_Config_File

**Alternatives you've considered:**
Launching outside of the launcher breaks normal workflow.

**Additional context:**
When I'm working from my own ACRE build I have all dev related launch options in a parameter file so that I only have to enable a checkbox and unload my mods to work from it. -skipAcrePluginCopy was not detected when it was in a parameter file.

**Definition of Done:**
- ACRE can find and read parameter file format from post arma2 build 86060
- Old `class Arg` .par format won't be supported.
- Options are appended to the output of getcommandline so they appear as if they were on the process commandline.

**Comment by ThymoNL** [comment]
Dibs.

Already analyzed what needs done. Just needs finishing/testing but I keep forgetting.

**Comment by jonpas** [comment]
Why would ACRE need to do any of that? Arma already supports `-par` and parses those, can't those be read just the same?

**Comment by ThymoNL** [comment]
This is all in the extension. So we parse the command line ourselves. So when Arma see's the `-par` option it reads parameters from there. I don't know of any documented way that Arma exports these options and I'm assuming there aren't any.

**Comment by ThymoNL** [comment]
This is how it's currently done: https://github.com/IDI-Systems/acre2/blob/master/extensions/src/ACRE2Steam/CallExt_DllMain.cpp#L207

That uses the Windows API.

**Comment by veteran29** [comment]
Arma parses `-par` but these parameters are not appended to command line, they are just detected and parsed by arma internally afaik. At least when I tried to use `-par` with intercept plugins that had their own params it did not work.

**Comment by veteran29** [comment]
also you can add the `-skipAcrePluginCopy` in Steam launch options, then `commandLine` is exposed in launcher.
![image](https://user-images.githubusercontent.com/4293906/82349777-d0ab9180-99fa-11ea-9a9d-1e7c378be980.png)

**Comment by ThymoNL** [comment]
Oh sweet. Hadn't noticed it. Nevertheless, requires one more mouse click.
