### ISSUE TITLE
RadioStuttering

### ISSUE THREAD

**Issue by KajSchak** [IDI-Systems/acre2#960]
**Mods (complete and add to the following information):**
- **Arma 3:** latest stable version
- **CBA:** `latest stable version
- **ACRE2:** `2.7.3.1024
- **TeamSpeak:** 3.5.3
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
In our Milsim group we ran into stuttering or not working radios. We are playing heavily modified (we are not able to just test it with vanilla +CBA/ACRE) and with custom channel names, that get loaded in via initPlayerLocal.sqm and initServer.sqm. I hope I can still explain the problem well enoough that you can tell if it is an us, a terrain or an ACRE problem.

Since the latest update, we are running into stuttering issues when there are more then 50 players in a mission. Before the last update we had missions with 80+ players and it was stable. We haven't been able to pinpoint when the issue occurs, but maybe you already get an idea.

We had the issue when the server FPS droped to 5-10, but also when they were 25-40

Terrains: 
- Kidal and Virolathi.

Issue: 
- Voice/Radio stuttering
- stuttering over short local distances
- stuttering when talking inside a vehicle to the outside
- stuttering when talking on 152 over any range
- person that hears stuttering, can sometimes not be heard by others
- sometimes there is a complete loss of coms
- if people set their radio to "active" the issue disappear

**Steps to reproduce:**
- not so easy

**Expected behavior:**
No Stuttering

**Where did the issue occur?**
- Dedicated server

**Log Files:**
- no error messages

**Additional context:**
- I don't know how your code works and I am only making guesses. I am an audio engineer and from what I hear I think that something is breaking how ACRE meassures the distance between two objects, the location/place of the sound source and the dampening that gets applied at the locals player client. The

I will try to get a recording of the issue as soon as possible. For now I forgot to do it.

**Screenshots:**
-

**Comment by bux** [comment]
> (we are not able to just test it with vanilla +CBA/ACRE)

Then the only answer is: too many and broken mods

**Comment by Xavia1991** [comment]
we have the same problem with about 10-16 players already, I was told it has to do with TS bandwith and/or flooding options, but i increased both a lot and it did not help

I agree with the Info given under additional context, as a programmer that was my first guess too.

@KajSchak what do you mean by "if people set their radio to "active" the issue disappear"?

**Comment by Xavia1991** [comment]
@KajSchak Do you use Tactical Weapon Swap? We found it to be the source of the error.

**Comment by KajSchak** [comment]
Yes we do. What a shame.

**Comment by jonpas** [comment]
Nice find @otting, thanks.

I'll close this as most likely cause is that mod and not ACRE2. If this is wrong, feel free to comment again.
