### ISSUE TITLE
Additional Channel

### ISSUE THREAD

**Issue by JustAKuba** [IDI-Systems/acre2#962]
It would be nice to have some kind of additional channel. Like you need to talk to your group but be on the standby on the command channel, so you can set up command channel as secondary that you can hear, and your group that you can talk to.
 Best regards,
Jacob Rooster

**Comment by NouberNou** [comment]
You can add additional radios to soldiers set to different channels. Please check out the mission making guides here: https://acre2.idi-systems.com/wiki/frameworks/mission-making-intro

**Comment by jonpas** [comment]
As @NouberNou said, you can carry multiple radios.

No radio we currently have in ACRE2 is capable of dual-watch (or dual-band). WHen we'll have one, this will of course be possible.

**Comment by ThymoNL** [comment]
Assuming you are talking about the 'additional channel' function that TFAR has that will not happen with the currently implemented radios as their real life counterparts do not have multiple VFOs. If a radio gets added that does have it this can be implemented.

EDIT: Sniped by @jonpas

**Comment by JustAKuba** [comment]
We are milsim special forces group. AN/PRC-152 is not able to watch over one channel and have one active channel? If not, when can we await the new radio?

**Comment by ThymoNL** [comment]
If you can provide a model of such a (military) radio along with documentation on its operation and technical specifications I'm sure someone will be willing to get it into ACRE.

**Comment by JustAKuba** [comment]
Do you plan to create a radio AN/PRC-163 from Harris? It is dual-band. 
[https://www.youtube.com/watch?v=bFZ9sHDhHIg&t=9s](url)
[https://www.harris.com/solution/harris-an-prc-163-multi-channel-handheld-radio](url)
[https://www.harris.com/sites/default/files/an-prc-163-multi-channel-handheld-radio-datasheet.pdf](url)

It would be nice, because whole group love this addon, but JTACs and RTOs have problems with managing more channels, bcs when they have more radios and no space for medical and other accessories.
