### ISSUE TITLE
AN/PRC-163

### ISSUE THREAD

**Issue by JustAKuba** [IDI-Systems/acre2#966]
As special forces group which wants to use this addon because it realistic interface, nice component solutions and other fine things, we are truly missing the capability to communicate a monitor more channels at once with one SR radio and one LR radio.

**Solution you'd like:**
In milsim way, it would be best to add some radios of the capability of dual-channel or dual-watch.

**Alternatives you've considered:**
1. add this capability to already existing radio(for ex. AN/PRC-152/117F, but those don't have the capability in real life)
2. Add new, modern radio. The one I know about and like it is Falcon IV AN/PRC-163 Multi-Channel. It is new, modern marines hand-held radio with lots of capabilities, and it actually has the required things. I will add additional information into the next post in the thread.

Best regards,
Jacob Rooster

**Comment by JustAKuba** [comment]
The information about AN/PRC-163:

- [https://www.youtube.com/watch?v=sDllsWsxhm0](url)
- [https://www.harris.com/solution/harris-falcon-iii-rf-7800v-hh-handheld-vhf-tactical-radio](url)
- [https://www.harris.com/sites/default/files/an-prc-163-multi-channel-handheld-radio-datasheet.pdf](url)

**Comment by jonpas** [comment]
Provide a legitimate model and we can start thinking about it. Until then it's all wishes. Same as you were told in your first issue.

I still don't understand why you have such a need for that, you can carry 2 radios. If they are too heavy, make a patch PBO to reduce their weight.

**Comment by JustAKuba** [comment]
Don't know what you mean by legitimate model. If the picture is meant, it is here.
[https://www.harris.com/sites/default/files/images/solution/anprc-163-stc-multi-channel-handheld-radio-1.jpg](url)
All functions, that can be made in ArmA are already in 152, but the dual-channel. If this is not a legitimate model, please describe it to me, that I can provide it to you. Also, the screen is the same as in the AN/PRC-152 but you can see two channels, not one. All additional information like documentation and video are in my other post in the thread.

I think it would also good for you to add some modern army radio. Even in Czech is 152 used even by Air Rescue, the specs are already using more advanced IT technologies. Modern equipment will make your addon more popular.

**Comment by Soldia1138** [comment]
A full 3D Model with all necessary rendering states (buttons, switches) plus at least a good description of the Operating System (a Manual would be even better) and of course the antenna simulation model itself.

In ACRE it's not just another ui image to add a new radio. There are a few descriptions and guidelines in our documentation what is necessary to create a new radio.

**Comment by JustAKuba** [comment]
Ok, understood, we are working on it.

**Comment by JustAKuba** [comment]
So, I have couple of developers from my group, and they are willing to create the radio, so if we create a p3d model with working buttons, with texture, antenna and other things that you have on that page, will you make it into working state? Our guys don't want to spend their time and then figure out that nothing is going to happen.
@jonpas

**Comment by TheMagnetar** [comment]
Do we have a manual? Donwe have antenna specs?

**Comment by BrettMayson** [comment]
basic datasheet
https://www.harris.com/sites/default/files/an-prc-163-multi-channel-handheld-radio-datasheet.pdf

**Comment by TheMagnetar** [comment]
Not enough! Menus etc

**Comment by BrettMayson** [comment]
Didn't see it linked above, just providing a reference.

It's a fairly new radio, very unlikely to find anything more than that online

**Comment by JustAKuba** [comment]
Menus are the same as in the actual AN/PRC-152, at least for arma. Irl there are ISR video and other similar things that cant be in arma. All antennas are listed in the datasheet, they can be found by their names. Waveforms are also in the datasheet.

**Comment by JustAKuba** [comment]
We contacted Harris and got a reply that more information than they released are classified government information, so all the things we can get are from video and other similar things. As told in the video the UI of an/prc-163 is same and familiar from the Falcon III series.  From the build of the radio, we can say that the display of the radio is bigger, and contains more information, for example, the second channel, and all information to both channels.

**Comment by Soldia1138** [comment]
tbh that was obviously NOT the smartest move on earth.

So please, if you want that radio, make a fork, create that radio with everything in it and make PR or live with that fork. An alternative is to make a separate mod for this radio.
We won't create features by just being shouted.

**Comment by NouberNou** [comment]
We are currently not adding new radios to ACRE2 unless the work is developed independently.
