### ISSUE TITLE
ACE interaction error when using external vehicle rack radio

### ISSUE THREAD

**Issue by TikaKino** [IDI-Systems/acre2#974]
**Mods:**
- **Arma 3:** `1.98.146373`
- **CBA:** `3.15.1`
- **ACRE2:** `2.7.3.1024`
- **ACE3:** `3.13.2`

**Description:**
When using an externally accessible radio created with acre_api_fnc_addRackToVehicle, attempting to ace-interact with the vehicle carrying the rack causes an error.

**Steps to reproduce:**
Place the following in a vehicle's init:
[this, ["ACRE_VRC103", "TF Comms", "TF", false, ["external"], [], "ACRE_PRC117F", [], []], true] call acre_api_fnc_addRackToVehicle;
Play the mission from the editor, ace-interact with the vehicle and use the created rack.
Then attempt to ace-interact with the vehicle again; it throws an error to screen.
The ace interaction still works; stop using the rack radio, and the error will stop occuring.
Problem does not occur when creating an internal radio (replace "external" with "inside" above and enter the vehicle to use the radio, no error).

Error:
13:05:29 Error in expression <r = ACE_player;

if !((_origActionData select 10) isEqualTo {}) then {

_origAc>
13:05:29   Error position: <select 10) isEqualTo {}) then {

_origAc>
13:05:29   Error Generic error in expression
13:05:29 File z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf..., line 28

**Expected behavior:**
Exactly as above minus the error to screen.

**Where did the issue occur?**
- Editor (Singleplayer and Multiplayer)

**Log Files:**
https://gist.github.com/TikaKino/3cc276935dafec34dea2253847bfa257#file-arma3_x64_2020-06-05_12-57-25-rpt
https://gist.github.com/TikaKino/3cc276935dafec34dea2253847bfa257#file-acre_dll-log

**Example Mission:**
[t_radios.Malden.zip](https://github.com/IDI-Systems/acre2/files/4736021/t_radios.Malden.zip)

**Comment by jonpas** [comment]
Is this still an issue? @TikaKino

**Comment by TikaKino** [comment]
Yes, still getting the same error under the same circumstances with the stated minimal set of mods.
Arma 3 2.02.147359
CBA_A3 3.15.3
ACE3 3.13.6
ACRE2 2.8.0.1037
