### ISSUE TITLE
Volume slider doesn't change anything

### ISSUE THREAD

**Issue by jameslkingsley** [IDI-Systems/acre2#98]
From what a lot of people have reported within our community, the volume slider appears to not change anything. If you go to whisper, you can still be heard the same distance as shout for example.

Is this a known issue or is it something we're doing on our end that breaks it?

**Comment by Sniperhid** [comment]
iirc in your framework your changing the selectable voice curve model to one that makes the volume slider have no effect

`ACRE_CURVE_MODEL_ORIGINAL` breaks this.

http://acre.idi-systems.com/api/api_general.html#acre_api_fnc_setCurveModel

**Comment by jonpas** [comment]
To quote the page:

> ACRE_CURVE_MODEL_ORIGINAL     - The **volume range is static** and based off a custom curve.

**Comment by jameslkingsley** [comment]
I'm a silly pleb, but to be fair I wasn't the one to change it. Thanks for the info, it's fixed now.
