### ISSUE TITLE
False Format

### ISSUE THREAD

**Issue by Sk3y** [IDI-Systems/acre2#981]
acre2/addons/sys_data/fnc_serverHandleJip.sqf

Line 23: Beginning with %2 not %1.
Result: 21:24:29 [ACRE] (sys_data) INFO: Data Sync for acre_player: 2:725 [491054.96] - KB

Missing: ","? -> [%3,%4]

**Comment by jonpas** [comment]
Why not press the "Edit" button and submit a pull request while at it? :)

**Comment by Sk3y** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/1360205/85933686-5237ee80-b8da-11ea-821d-f16dafca46c5.png)
Because not click able :)
