### ISSUE TITLE
No radio sounds (b64 whitelisted) 

### ISSUE THREAD

**Issue by tyl3r99** [IDI-Systems/acre2#983]
**Mods (ACE, MLO, CBA, enhanced movement, shacktack, jsrs, cup weapons, rhs usaf and afrf, achillies, project opfor):**
- **Arma 3:** `Latest stable version as of 28th june 20` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `cba_3.15.1.200418` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.7.4.1027` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
I get the yellow box that shows when transmitting however no radio beeps or skwawking.
ACRE does connect to teamspeak and moves me into our operations channel just fine. 
I do not get any in game error messages i.e. pipe closed
I looked in my RPT and this is getting spammed. 

if (_name != "ACRE_TR") exitWith {};
(parseSimpleArray _data) params ["_id", ">
 9:26:49   Error position: <parseSimpleArray _data) params ["_id", ">
 9:26:49   Error Generic error in expression
------
9:25:45 Warning: 47324 ms spent in callExtension calling name: "ACRE2Steam", function: "2VER2.7.4.1027"
------
9:26:25 Wrong location draw style - "ACRE_RequiredDrawStyle"
------
9:26:43 [ACRE] (sys_core) WARNING: SquadLead has no TS3 ID 

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated
 (b64 was whitelisted in the extensions in the server.cfg)

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the extension log file, which can be found at `<Arma 3 directory>\logs\acre_dll.log`.

Acre.dll log 
[acre_dll.log](https://github.com/IDI-Systems/acre2/files/4841933/acre_dll.log)
**Additional context:**

**Screenshots:**

**Comment by PabstMirror** [comment]
It would be helpful to see full rpt

**Comment by tyl3r99** [comment]
[Arma3_x64_2020-06-28_09-24-43.zip](https://github.com/IDI-Systems/acre2/files/4842327/Arma3_x64_2020-06-28_09-24-43.zip)

**Comment by tyl3r99** [comment]
[Arma3_x64_2020-06-28_22-38-45.zip](https://github.com/IDI-Systems/acre2/files/4843041/Arma3_x64_2020-06-28_22-38-45.zip)
This time im getting an on screen error message 

if (_name != "ACRE_TR") exitWith {};
(parseSimpleArray _data) params ["_id", "> 

something like that

**Comment by PabstMirror** [comment]
Was there underwater radio use?
or were there vehicles or units with multiple radios tuned to the same net?

**Comment by tyl3r99** [comment]
> Was there underwater radio use?
> or were there vehicles or units with multiple radios tuned to the same net?

Thank you for the reply!
Nope no underwater usage 
I am currently testing just with me on the server. 

I did do a test with 4 people on the server and 2 could hear the radio noises but me and another player could not. 

We all start on the same channel yep with radios prc152, I've also tested 117f and 148 and issue still occurs.

**Comment by tyl3r99** [comment]
Regarding issue 984 we was also on the simple mode as mentioned in that. 

Have you any ideas on the sound issue? Thanks for your time by the way

**Comment by jonpas** [comment]
@tyl3r99 please try the latest dev-build (available on our Slack): http://dev.idi-systems.com/dev/acre2_2.7.4.1032.zip

**Comment by jonpas** [comment]
Fixed by #984.
