### ISSUE TITLE
ACRE was unable to parse the map ( Global Mobilization Weferlingen Winter)

### ISSUE THREAD

**Issue by BishopsArch** [IDI-Systems/acre2#995]
ACRE was unable to parse the map [\gm\gm_worlds\gm_weferlingen_winter\gm_weferlingen_winter.wrp]

I have no technical knowledge of how this system works nor what the problem is, I figured I'd just notify.

**Comment by jonpas** [comment]
You must load the optional `@acre_sys_gm` that provides map compatibility.
